version: '3.8'

services:
  mhw-db:
    container_name: mhw-db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    networks:
      mhw:
        aliases:
          - mhw-db
  mhw-zoo1:
    image: zookeeper:3.7.2
    restart: always
    container_name: mhw-zoo1
    hostname: mhw-zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=mhw-zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
    networks:
      mhw:
        aliases:
          - mhw-zoo1
  mhw-solr:
    image: solr:9.5.0
    container_name: mhw-solr
    hostname: mhw-solr
    restart: always
    ports:
      - "8983:8983"
    environment:
      SOLR_JAVA_MEM: -Xms1024m -Xmx1024m
      ZK_HOST: mhw-zoo1:2181
      SOLR_HOST: mhw-solr
    depends_on:
      - mhw-zoo1
    networks:
      mhw:
        aliases:
          - mhw-solr
networks:
  mhw:
    name: mhw