BEGIN;

INSERT INTO monster_reward_condition_text VALUES(1,'de','Track');
INSERT INTO monster_reward_condition_text VALUES(2,'de','Body Carve');
INSERT INTO monster_reward_condition_text VALUES(3,'de','Carve / Capture');
INSERT INTO monster_reward_condition_text VALUES(4,'de','Break Horn');
INSERT INTO monster_reward_condition_text VALUES(5,'de','Break Horns');
INSERT INTO monster_reward_condition_text VALUES(6,'de','Wound Head');
INSERT INTO monster_reward_condition_text VALUES(7,'de','Wound Horn');
INSERT INTO monster_reward_condition_text VALUES(8,'de','Wound Horns');
INSERT INTO monster_reward_condition_text VALUES(9,'de','Wound Beak');
INSERT INTO monster_reward_condition_text VALUES(10,'de','Wound Antennae');
INSERT INTO monster_reward_condition_text VALUES(11,'de','Wound Neck Pouch');
INSERT INTO monster_reward_condition_text VALUES(12,'de','Wound 1 Horn');
INSERT INTO monster_reward_condition_text VALUES(13,'de','Wound Jaw');
INSERT INTO monster_reward_condition_text VALUES(14,'de','Wound Body');
INSERT INTO monster_reward_condition_text VALUES(15,'de','Wound Wings');
INSERT INTO monster_reward_condition_text VALUES(16,'de','Wound Left Wing');
INSERT INTO monster_reward_condition_text VALUES(17,'de','Wound Right Wing');
INSERT INTO monster_reward_condition_text VALUES(18,'de','Break Left Wing Mantle');
INSERT INTO monster_reward_condition_text VALUES(19,'de','Break Right Wing Mantle');
INSERT INTO monster_reward_condition_text VALUES(20,'de','Wound Back');
INSERT INTO monster_reward_condition_text VALUES(21,'de','Wound Fin');
INSERT INTO monster_reward_condition_text VALUES(22,'de','Wound Claws');
INSERT INTO monster_reward_condition_text VALUES(23,'de','Wound Forearms');
INSERT INTO monster_reward_condition_text VALUES(24,'de','Wound Forelegs');
INSERT INTO monster_reward_condition_text VALUES(25,'de','Wound Left Foreleg');
INSERT INTO monster_reward_condition_text VALUES(26,'de','Wound Right Foreleg');
INSERT INTO monster_reward_condition_text VALUES(27,'de','Wound Belly');
INSERT INTO monster_reward_condition_text VALUES(28,'de','Wound Chest');
INSERT INTO monster_reward_condition_text VALUES(29,'de','Wound Chest Shell');
INSERT INTO monster_reward_condition_text VALUES(30,'de','Wound Hindlegs');
INSERT INTO monster_reward_condition_text VALUES(31,'de','Wound Left Hindleg');
INSERT INTO monster_reward_condition_text VALUES(32,'de','Wound Right Hindleg');
INSERT INTO monster_reward_condition_text VALUES(33,'de','Break Left Leg Mantle');
INSERT INTO monster_reward_condition_text VALUES(34,'de','Break Right Leg Mantle');
INSERT INTO monster_reward_condition_text VALUES(35,'de','Wound Legs');
INSERT INTO monster_reward_condition_text VALUES(36,'de','Wound Tail');
INSERT INTO monster_reward_condition_text VALUES(37,'de','Shiny Drop');
INSERT INTO monster_reward_condition_text VALUES(38,'de','Tail Carve');
INSERT INTO monster_reward_condition_text VALUES(39,'de','Head Shell Carve');
INSERT INTO monster_reward_condition_text VALUES(40,'de','Horn Carve');
INSERT INTO monster_reward_condition_text VALUES(41,'de','Gold Plating Carved');
INSERT INTO monster_reward_condition_text VALUES(42,'de','Red Crystal Mining / Shiny');
INSERT INTO monster_reward_condition_text VALUES(43,'de','Back Mining');
INSERT INTO monster_reward_condition_text VALUES(44,'de','Siege Reward (Fury)');
INSERT INTO monster_reward_condition_text VALUES(45,'de','Siege Progress');
INSERT INTO monster_reward_condition_text VALUES(46,'de','Palico Bonus');
INSERT INTO monster_reward_condition_text VALUES(47,'de','Plunderblade');
INSERT INTO monster_reward_condition_text VALUES(48,'de','Bandit Mantle');
INSERT INTO monster_reward_condition_text VALUES(49,'de','Hunt (Bronze)');
INSERT INTO monster_reward_condition_text VALUES(50,'de','Investigation (Silver)');
INSERT INTO monster_reward_condition_text VALUES(51,'de','Investigation (Gold)');
INSERT INTO monster_reward_condition_text VALUES(52,'de','Investigation (Purple)');
INSERT INTO monster_reward_condition_text VALUES(53,'de','Guiding Lands (Low)');
INSERT INTO monster_reward_condition_text VALUES(54,'de','Guiding Lands (Mid)');
INSERT INTO monster_reward_condition_text VALUES(55,'de','Guiding Lands (High)');
INSERT INTO monster_reward_condition_text VALUES(56,'de','Guiding Lands (Tempered)');
INSERT INTO monster_reward_condition_text VALUES(57,'de','Appraisal (Bronze)');
INSERT INTO monster_reward_condition_text VALUES(58,'de','Appraisal (Silver)');
INSERT INTO monster_reward_condition_text VALUES(59,'de','Appraisal (Gold)');
INSERT INTO monster_reward_condition_text VALUES(60,'de','Appraisal (Blue)');
INSERT INTO monster_reward_condition_text VALUES(1,'en','Track');
INSERT INTO monster_reward_condition_text VALUES(2,'en','Body Carve');
INSERT INTO monster_reward_condition_text VALUES(3,'en','Carve / Capture');
INSERT INTO monster_reward_condition_text VALUES(4,'en','Break Horn');
INSERT INTO monster_reward_condition_text VALUES(5,'en','Break Horns');
INSERT INTO monster_reward_condition_text VALUES(6,'en','Wound Head');
INSERT INTO monster_reward_condition_text VALUES(7,'en','Wound Horn');
INSERT INTO monster_reward_condition_text VALUES(8,'en','Wound Horns');
INSERT INTO monster_reward_condition_text VALUES(9,'en','Wound Beak');
INSERT INTO monster_reward_condition_text VALUES(10,'en','Wound Antennae');
INSERT INTO monster_reward_condition_text VALUES(11,'en','Wound Neck Pouch');
INSERT INTO monster_reward_condition_text VALUES(12,'en','Wound 1 Horn');
INSERT INTO monster_reward_condition_text VALUES(13,'en','Wound Jaw');
INSERT INTO monster_reward_condition_text VALUES(14,'en','Wound Body');
INSERT INTO monster_reward_condition_text VALUES(15,'en','Wound Wings');
INSERT INTO monster_reward_condition_text VALUES(16,'en','Wound Left Wing');
INSERT INTO monster_reward_condition_text VALUES(17,'en','Wound Right Wing');
INSERT INTO monster_reward_condition_text VALUES(18,'en','Break Left Wing Mantle');
INSERT INTO monster_reward_condition_text VALUES(19,'en','Break Right Wing Mantle');
INSERT INTO monster_reward_condition_text VALUES(20,'en','Wound Back');
INSERT INTO monster_reward_condition_text VALUES(21,'en','Wound Fin');
INSERT INTO monster_reward_condition_text VALUES(22,'en','Wound Claws');
INSERT INTO monster_reward_condition_text VALUES(23,'en','Wound Forearms');
INSERT INTO monster_reward_condition_text VALUES(24,'en','Wound Forelegs');
INSERT INTO monster_reward_condition_text VALUES(25,'en','Wound Left Foreleg');
INSERT INTO monster_reward_condition_text VALUES(26,'en','Wound Right Foreleg');
INSERT INTO monster_reward_condition_text VALUES(27,'en','Wound Belly');
INSERT INTO monster_reward_condition_text VALUES(28,'en','Wound Chest');
INSERT INTO monster_reward_condition_text VALUES(29,'en','Wound Chest Shell');
INSERT INTO monster_reward_condition_text VALUES(30,'en','Wound Hindlegs');
INSERT INTO monster_reward_condition_text VALUES(31,'en','Wound Left Hindleg');
INSERT INTO monster_reward_condition_text VALUES(32,'en','Wound Right Hindleg');
INSERT INTO monster_reward_condition_text VALUES(33,'en','Break Left Leg Mantle');
INSERT INTO monster_reward_condition_text VALUES(34,'en','Break Right Leg Mantle');
INSERT INTO monster_reward_condition_text VALUES(35,'en','Wound Legs');
INSERT INTO monster_reward_condition_text VALUES(36,'en','Wound Tail');
INSERT INTO monster_reward_condition_text VALUES(37,'en','Shiny Drop');
INSERT INTO monster_reward_condition_text VALUES(38,'en','Tail Carve');
INSERT INTO monster_reward_condition_text VALUES(39,'en','Head Shell Carve');
INSERT INTO monster_reward_condition_text VALUES(40,'en','Horn Carve');
INSERT INTO monster_reward_condition_text VALUES(41,'en','Gold Plating Carved');
INSERT INTO monster_reward_condition_text VALUES(42,'en','Red Crystal Mining / Shiny');
INSERT INTO monster_reward_condition_text VALUES(43,'en','Back Mining');
INSERT INTO monster_reward_condition_text VALUES(44,'en','Siege Reward (Fury)');
INSERT INTO monster_reward_condition_text VALUES(45,'en','Siege Progress');
INSERT INTO monster_reward_condition_text VALUES(46,'en','Palico Bonus');
INSERT INTO monster_reward_condition_text VALUES(47,'en','Plunderblade');
INSERT INTO monster_reward_condition_text VALUES(48,'en','Bandit Mantle');
INSERT INTO monster_reward_condition_text VALUES(49,'en','Hunt (Bronze)');
INSERT INTO monster_reward_condition_text VALUES(50,'en','Investigation (Silver)');
INSERT INTO monster_reward_condition_text VALUES(51,'en','Investigation (Gold)');
INSERT INTO monster_reward_condition_text VALUES(52,'en','Investigation (Purple)');
INSERT INTO monster_reward_condition_text VALUES(53,'en','Guiding Lands (Low)');
INSERT INTO monster_reward_condition_text VALUES(54,'en','Guiding Lands (Mid)');
INSERT INTO monster_reward_condition_text VALUES(55,'en','Guiding Lands (High)');
INSERT INTO monster_reward_condition_text VALUES(56,'en','Guiding Lands (Tempered)');
INSERT INTO monster_reward_condition_text VALUES(57,'en','Appraisal (Bronze)');
INSERT INTO monster_reward_condition_text VALUES(58,'en','Appraisal (Silver)');
INSERT INTO monster_reward_condition_text VALUES(59,'en','Appraisal (Gold)');
INSERT INTO monster_reward_condition_text VALUES(60,'en','Appraisal (Blue)');

COMMIT;