BEGIN;

INSERT INTO skilltree_text VALUES(1,'de','Giftwiderstand','Verringert den Schaden bei Vergiftungen.');
INSERT INTO skilltree_text VALUES(2,'de','Lähmungswiderstand','Reduziert die Dauer von Lähmungen.');
INSERT INTO skilltree_text VALUES(3,'de','Schlafwiderstand','Verringert die Dauer von Schlaf.');
INSERT INTO skilltree_text VALUES(4,'de','Betäubungswiderst.','Reduziert die Dauer von Betäubungen.');
INSERT INTO skilltree_text VALUES(5,'de','Mist-Widerstand','Reduziert Bewegungseinschränkungen, wenn du in Monstermist feststeckst.');
INSERT INTO skilltree_text VALUES(6,'de','Explosionswiderstand','Gewährt Schutz gegen Explosionspest.');
INSERT INTO skilltree_text VALUES(7,'de','Blutungswiderstand','Gewährt Schutz gegen Blutungen.');
INSERT INTO skilltree_text VALUES(8,'de','Eisenhaut','Gewährt Schutz gegen Verringerte Verteidigung.');
INSERT INTO skilltree_text VALUES(9,'de','Ohrstöpsel','Gewährt Schutz gegen das Brüllen großer Monster.');
INSERT INTO skilltree_text VALUES(10,'de','Windsicher','Gewährt Schutz gegen Winddruck.');
INSERT INTO skilltree_text VALUES(11,'de','Erschütterungswidst.','Gewährt Schutz gegen Erschütterungen.');
INSERT INTO skilltree_text VALUES(12,'de','Dungmeister','Monster, die per Schleuder von einer Dungkapsel getroffen werden, rennen mit einer höheren Wahrscheinlichkeit weg.');
INSERT INTO skilltree_text VALUES(13,'de','Miasmaexperte','Negiert oder reduziert Umgebungsschaden im Tal der Verwesung.');
INSERT INTO skilltree_text VALUES(14,'de','Hitzeschutz','Negiert Hitzeschaden.');
INSERT INTO skilltree_text VALUES(15,'de','Angriffsboost','Verbessert den Angriff – und bei höheren Stufen zusätzlich die Affinität.');
INSERT INTO skilltree_text VALUES(16,'de','Verteidigungsboost','Verbessert die Verteidigung. Erhöhe die Stufe, um auch die Widerstände zu verbessern.');
INSERT INTO skilltree_text VALUES(17,'de','Gesundheitsboost','Verbessert deine Gesundheit.');
INSERT INTO skilltree_text VALUES(18,'de','Erholung hoch','Erhöht die Menge der wiederhergestellten Gesundheit.');
INSERT INTO skilltree_text VALUES(19,'de','Erholungsgeschwindigk.','Erlaubt die schnellere Heilung von erholbarem Schaden (der rote Abschnitt des Gesundheitsbalkens).');
INSERT INTO skilltree_text VALUES(20,'de','Feuerwiderstand','Erhöht den Feuerwiderstand – und bei höheren Stufen zusätzlich die Verteidigung.');
INSERT INTO skilltree_text VALUES(21,'de','Wasserwiderstand','Erhöht den Wasserwiderstand. Auf höheren Stufen wird auch die Verteidigung verbessert.');
INSERT INTO skilltree_text VALUES(22,'de','Eiswiderstand','Erhöht den Eiswiderstand. Erhöhe die Stufe, um auch die Verteidigung zu verbessern.');
INSERT INTO skilltree_text VALUES(23,'de','Donnerwiderstand','Erhöht den Donnerwiderstand. Auf höheren Stufen wird auch die Verteidigung verbessert.');
INSERT INTO skilltree_text VALUES(24,'de','Drachenwiderstand','Erhöht den Drachenwiderstand – und bei höheren Stufen zusätzlich die Verteidigung.');
INSERT INTO skilltree_text VALUES(25,'de','Pestwiderstand','Gewährt Schutz gegen alle elementbasierten Pestarten.');
INSERT INTO skilltree_text VALUES(26,'de','Feuerangriff','Verbessert die Kraft von Feuerelement-Angriffen. Die Elementangriffskraft hat eine Obergrenze.');
INSERT INTO skilltree_text VALUES(27,'de','Wasserangriff','Verbessert die Kraft von Wasserelement-Angriffen. Die Elementangriffskraft hat eine Obergrenze.');
INSERT INTO skilltree_text VALUES(28,'de','Eisangriff','Verbessert die Kraft von Eiselement-Angriffen. Die Elementangriffskraft hat eine Obergrenze.');
INSERT INTO skilltree_text VALUES(29,'de','Donnerangriff','Verbessert die Kraft von Donnerelement-Angriffen. Die Elementangriffskraft hat eine Obergrenze.');
INSERT INTO skilltree_text VALUES(30,'de','Drachenangriff','Verbessert die Kraft von Drachenelement-Angriffen. Die Elementangriffskraft hat eine Obergrenze.');
INSERT INTO skilltree_text VALUES(31,'de','Giftangriff','Erhöht die Rate der Gift-Ansammlung. Die Elementansammlung hat eine Obergrenze.');
INSERT INTO skilltree_text VALUES(32,'de','Lähmungsangriff','Erhöht die Rate der Lähmung-Ansammlung. Die Elementansammlung hat eine Obergrenze.');
INSERT INTO skilltree_text VALUES(33,'de','Schlafangriff','Erhöht die Rate der Schlaf-Ansammlung. Die Elementansammlung hat eine Obergrenze.');
INSERT INTO skilltree_text VALUES(34,'de','Explosionsangriff','Erhöht die Rate der Explosion-Ansammlung. Die Elementansammlung hat eine Obergrenze.');
INSERT INTO skilltree_text VALUES(35,'de','Standardboost','Erhöht die Angriffskraft von Standardmunition und Standardpfeilen.');
INSERT INTO skilltree_text VALUES(36,'de','Perforierboost','Erhöht die Angriffskraft von Perforiermunition und Drachentöter.');
INSERT INTO skilltree_text VALUES(37,'de','Schrot/Kraftschuss','Erhöht die Angriffskraft von Schrotmunition, Kraftschuss-Pfeilen und Tausend Drachen.');
INSERT INTO skilltree_text VALUES(38,'de','Superwaffe','Schaltet das Verborgene Element deiner Waffe frei und erhöht die Ladekapazität des Bogengewehrs. (Die Ladekapazität hat ein Limit.)');
INSERT INTO skilltree_text VALUES(39,'de','Kritischer Blick','Erhöht die Affinität.');
INSERT INTO skilltree_text VALUES(40,'de','Kritischer Boost','Erhöht den Schaden durch kritische Treffer.');
INSERT INTO skilltree_text VALUES(41,'de','Schwächevorteil','Erhöht die Affinität von Angriffen, die den Schwachpunkt eines Monsters ausnutzen.');
INSERT INTO skilltree_text VALUES(42,'de','Fokus','Erhöht das Fülltempo von Waffen mit Balken und die Ladegeschwindigkeit von Waffen mit aufgeladenen Angriffen.');
INSERT INTO skilltree_text VALUES(43,'de','Kraftverlängerung','Langschwerter, Doppelklingen, Insektenglefen, Morph-Äxte und Energieklingen bleiben länger verstärkt.');
INSERT INTO skilltree_text VALUES(44,'de','Handwerk','Erweitert den Waffenschärfebalken, allerdings nicht bis jenseits des Maximums.');
INSERT INTO skilltree_text VALUES(45,'de','Kritisches Ziehen','Erhöht die Affinität beim Ausführen von Zug-Angriffen.');
INSERT INTO skilltree_text VALUES(46,'de','Teilezerstörer','Erleichtert das Brechen oder Abtrennen von Teilen großer Monster.');
INSERT INTO skilltree_text VALUES(47,'de','Lähmer','Erleichtert das Betäuben von Monstern.');
INSERT INTO skilltree_text VALUES(48,'de','Ausdauerdieb','Erhöht die Fähigkeit bestimmter Angriffe, Monster zu ermüden.');
INSERT INTO skilltree_text VALUES(49,'de','Rittmeister','Erleichtert das Aufsteigen auf Monster.');
INSERT INTO skilltree_text VALUES(50,'de','Luftherrschaft','Erhöht den Schaden durch gesprungene Angriffe.');
INSERT INTO skilltree_text VALUES(51,'de','Latente Kraft','Erhöht vorübergehend die Affinität und verringert den Ausdauerverbrauch unter bestimmten Bedingungen.');
INSERT INTO skilltree_text VALUES(52,'de','Aufhetzer','Erhöht Angriffskraft und Affinität, wenn große Monster wütend werden.');
INSERT INTO skilltree_text VALUES(53,'de','Höchstleistung','Verbessert den Angriff, wenn dein Gesundheitsbalken gefüllt ist.');
INSERT INTO skilltree_text VALUES(54,'de','Heldentat','Erhöht die Angriffskraft und die Verteidigung, wenn deine Gesundheit bei 35% oder weniger ist.');
INSERT INTO skilltree_text VALUES(55,'de','Kräftigen','Erhöht bis zu zweimal deine Verteidigung und deinen Angriff, wenn du in Ohnmacht fällst.');
INSERT INTO skilltree_text VALUES(56,'de','Groll','Erhöht den Angriff, wenn du erholbaren Schaden erlitten hast (der rote Abschnitt des Gesundheitsbalkens).');
INSERT INTO skilltree_text VALUES(57,'de','Wiederbelebung','Verbessert Ausweichen und reduziert den Ausdauerverbrauch bei anomalen Statuseffekten.');
INSERT INTO skilltree_text VALUES(58,'de','Horn-Maestro','Verlängert die Effektdauer von Jagdhornmelodien.');
INSERT INTO skilltree_text VALUES(59,'de','Kapazitätsboost','Erhöht die Munitionskapazität der Gewehrlanze und die Phiolenkapazität der Energieklinge.');
INSERT INTO skilltree_text VALUES(60,'de','Spezialmunitionboost','Verstärkt die Spezialmunition von Bogengewehren sowie den Drachentöter und Tausend Drachen.');
INSERT INTO skilltree_text VALUES(61,'de','Artillerie','Verstärkt Explosivangriffe: Wyvernfeuer, Patronen der Gewehrlanze, Detonation-Munition und Phiolenangriffe der Energieklinge.');
INSERT INTO skilltree_text VALUES(62,'de','Schwere Artillerie','Verbessert die Feuerkraft von Ballisten und Kanonen.');
INSERT INTO skilltree_text VALUES(63,'de','Marathon-Läufer','Verlangsamt den Ausdauerverbrauch von Aktionen, die andauernd Ausdauer erschöpfen (etwa Sprinten).');
INSERT INTO skilltree_text VALUES(64,'de','Konstitution','Verringert den Ausdauerverbrauch beim Ausweichen und ähnlichen Aktionen.');
INSERT INTO skilltree_text VALUES(65,'de','Schicksalssprung','Erlaubt es dir, großen Monstern per langem Hechtsprung auszuweichen, indem du auf sie zuspringst.');
INSERT INTO skilltree_text VALUES(66,'de','Ausdauererholung','Beschleunigt die Ausdauerregeneration.');
INSERT INTO skilltree_text VALUES(67,'de','Hungerwiderstand','Reduziert die Abnahme der maximalen Ausdauer. Wirkt nicht gegen kalte Umgebungen, die Ausdauer verringern.');
INSERT INTO skilltree_text VALUES(68,'de','Unverwundbarkeit','Du bist beim Ausweichen länger unverwundbar.');
INSERT INTO skilltree_text VALUES(69,'de','Ausweichdistanz','Erhöht die Ausweichdistanz.');
INSERT INTO skilltree_text VALUES(70,'de','Blocken','Reduziert Rückwürfe und den Ausdauerverbrauch beim Blocken.');
INSERT INTO skilltree_text VALUES(71,'de','SchnellesWegstecken','Beschleunigt das Wegstecken von Waffen.');
INSERT INTO skilltree_text VALUES(72,'de','Wirkbereich','Teilt einige Objekteffekte mit benachbarten Verbündeten.');
INSERT INTO skilltree_text VALUES(73,'de','Objektverlängerung','Verlängert die Dauer einiger Objekteffekte.');
INSERT INTO skilltree_text VALUES(74,'de','Freie Mahlzeit','Nahrungsmittel können mit einer bestimmten Wahrscheinlichkeit kostenlos verzehrt werden.');
INSERT INTO skilltree_text VALUES(75,'de','Schnellessen','Beschleunigt den Verzehr von Fleisch und den Verbrauch von Objekten.');
INSERT INTO skilltree_text VALUES(76,'de','Schnelles Schärfen','Beschleunigt das Schärfen von Waffen bei der Verwendung eines Wetzsteins.');
INSERT INTO skilltree_text VALUES(77,'de','Bombardier','Erhöht den Schaden durch explosive Objekte.');
INSERT INTO skilltree_text VALUES(78,'de','Mykologie','Erlaubt die Verdauung von Pilzen, die sonst ungenießbar wären, wodurch du deren Bonuseffekte erhältst.');
INSERT INTO skilltree_text VALUES(79,'de','Meisterfischer','Verbessert dein Angelgeschick.');
INSERT INTO skilltree_text VALUES(80,'de','Profikurier','Du bist beim Transportieren von Objekten schneller und lässt sie seltener fallen.');
INSERT INTO skilltree_text VALUES(81,'de','Meistersammler','Beschleunigt das Sammeln und verhindert Angriffe, wenn du dabei zurückgestoßen wirst.');
INSERT INTO skilltree_text VALUES(82,'de','Honigjäger','Erhöht die Menge an Honig, die du beim Sammeln erhältst.');
INSERT INTO skilltree_text VALUES(83,'de','Zerleger-Profi','Verhindert, dass du beim Zerlegen durch Angriffe zurückgeworfen wirst.');
INSERT INTO skilltree_text VALUES(84,'de','Göttlicher Segen','Verringert den von dir erlittenen Schaden mit einer bestimmten Wahrscheinlichkeit.');
INSERT INTO skilltree_text VALUES(85,'de','Palico-Versammlung','Stärkt Palicos.');
INSERT INTO skilltree_text VALUES(86,'de','Botaniker','Erhöht die Menge an Kräutern und anderen Verbrauchsobjekten, die du sammelst.');
INSERT INTO skilltree_text VALUES(87,'de','Geologe','Lässt dich häufiger an einem Sammelplatz sammeln.');
INSERT INTO skilltree_text VALUES(88,'de','Höchstmacht','Erhöht die Affinität, solange der Ausdauerbalken für eine bestimmte Zeit voll ist.');
INSERT INTO skilltree_text VALUES(89,'de','Schleuderkapazität','Erhöht die Ladekapazität für im Feld gesammelte Schleudermunition. Begrenzt die Munitionsmenge für bestimmten Schüssen.');
INSERT INTO skilltree_text VALUES(90,'de','Tarnung','Monster verlieren dich einfacher aus den Augen.');
INSERT INTO skilltree_text VALUES(91,'de','Unbeeindruckt','Verhindert das Zurückwerfen sowie andere Reaktionen auf geringen Schaden.');
INSERT INTO skilltree_text VALUES(92,'de','Spähkäfer-Reichweite','Erweitert die Erkennungsreichweite der Spähkäfer.');
INSERT INTO skilltree_text VALUES(93,'de','Schnellrobben','Erhöht deine Bewegungsgeschwindigkeit in der Hocke.');
INSERT INTO skilltree_text VALUES(94,'de','Sprungmeister','Verhindert, dass du im Sprung durch Angriffe zurückgeworfen wirst.');
INSERT INTO skilltree_text VALUES(95,'de','Überlebensexperte','Erhöht die wiederhergestellte Gesundheit beim Interagieren mit Dingen wie Sporenbäusche und Ausdauer-Insektenlarven.');
INSERT INTO skilltree_text VALUES(96,'de','Wasser-/Polarbeweglichkeit','Ermöglicht freiere Bewegung im Wasser. Auch Terraineffekte wie tiefer Schnee verlangsamen nicht mehr.');
INSERT INTO skilltree_text VALUES(97,'de','Kletterer','Verringert den Ausdauerverlust, wenn du an Wänden oder Efeu ausweichst oder dich an einem Gegner hängend bewegst.');
INSERT INTO skilltree_text VALUES(98,'de','Überraschungsangriff','Erhöht die Effektivität von Blitzangriffen und -objekten.');
INSERT INTO skilltree_text VALUES(99,'de','Gelehrter','Beschleunigt den Fortschritt von Forschungsstufen und besonderen Untersuchungen; siehe Quest-Ergebnisbildschirm.');
INSERT INTO skilltree_text VALUES(100,'de','Entomologe','Die Körper kleiner Insektenmonster werden seltener zerstört und können so öfter für Materialien zerlegt werden.');
INSERT INTO skilltree_text VALUES(101,'de','Miasma-Widerstand','Baut einen Widerstand gegen Miasma-Ansammlung auf.');
INSERT INTO skilltree_text VALUES(102,'de','Spürhund','Erhöht das Fülltempo des Spähkäferbalkens, wenn du Spuren und andere Überreste von Monstern findest.');
INSERT INTO skilltree_text VALUES(103,'de','Wildbeuterglück','Erhöht die Wahrscheinlichkeit, seltene Sammelpunkte zu finden.');
INSERT INTO skilltree_text VALUES(104,'de','Detektor','Zeigt seltene Sammelpunkte auf der Gebietskarte.');
INSERT INTO skilltree_text VALUES(105,'de','Werkzeugspezialist','Reduziert die Wartezeit, bis Spezialwerkzeuge erneut benutzt werden können.');
INSERT INTO skilltree_text VALUES(106,'de','Affinitätsschlittern','Schlittern steigert deine Affinität kurzzeitig.');
INSERT INTO skilltree_text VALUES(107,'de','Einschüchtern','Verringert die Wahrscheinlichkeit, dass dich kleine Monster angreifen, wenn sie dich sehen. (Kein Effekt auf bestimmte Monster.)');
INSERT INTO skilltree_text VALUES(108,'de','Schnelle Erholung','Regeneriert Gesundheit, solange du kontinuierlich ein Monster angreifst. Erholung hängt von der Waffe ab.');
INSERT INTO skilltree_text VALUES(109,'de','Super-Erholung','Ermöglicht es, durch Regenerierung mehr als den roten Abschnitt des Gesundheitsbalkens wiederherzustellen.');
INSERT INTO skilltree_text VALUES(110,'de','Giftdauer hoch','Verlängert die Dauer des Effekts deines Gifts auf Monster.');
INSERT INTO skilltree_text VALUES(111,'de','Adrenalin','Reduziert die Ausdauerabnahme vorübergehend, wenn die Gesundheit bei 40% oder weniger liegt.');
INSERT INTO skilltree_text VALUES(112,'de','Ausdauerlimit hoch','Erhöht die maximale Ausdauer.');
INSERT INTO skilltree_text VALUES(113,'de','Kritisches Element','Erhöht den Elementschaden (Feuer, Wasser, Donner, Eis, Drache) durch kritische Treffer.');
INSERT INTO skilltree_text VALUES(114,'de','Inneres Auge/Ballistik','Verhindert das Abprallen von Angriffen. Verkürzt die Distanz, bevor Munition und Pfeile maximale Kraft erreichen.');
INSERT INTO skilltree_text VALUES(115,'de','Prügler','Erhöht Angriff bei Schärfeverlust. Verstärkt Nahkampfangriffe von Distanzwaffen und die Chance, Ziele zu betäuben.');
INSERT INTO skilltree_text VALUES(116,'de','Nicht-Element-Boost','Verstärkt ausgerüstete nichtelementbasierte Waffen.');
INSERT INTO skilltree_text VALUES(117,'de','Fangmeister','Erhöhte Chance auf zusätzliche Fangbelohnungen. (Keine Auswirkung bei späterem Beitritt.)');
INSERT INTO skilltree_text VALUES(118,'de','Blocken hoch','Ermöglicht die Abwehr von normalerweise nicht zu blockenden Angriffen.');
INSERT INTO skilltree_text VALUES(119,'de','Stehvermögen','Verhindert, dass du von einem einzigen Angriff ohnmächtig wirst, solange du eine bestimmte Menge Gesundheit hast.');
INSERT INTO skilltree_text VALUES(120,'de','Meisterschliff','Verhindert, dass deine Waffe durch das Erzielen von kritischen Treffern an Schärfe verliert.');
INSERT INTO skilltree_text VALUES(121,'de','Negiert Winddruck','Negiert jeden Winddruck.');
INSERT INTO skilltree_text VALUES(122,'de','Scharfschwert/Extraschuss','Halbiert Schärfeverlust. Ermöglicht gelegentlich Schüsse ohne Munitionsoder Beschichtungsverbrauch.');
INSERT INTO skilltree_text VALUES(123,'de','Kritischer Status','Erhöht den Schaden von anomalen Statuseffekten (Lähmung, Gift, Schlaf, Explosion) durch kritische Treffer.');
INSERT INTO skilltree_text VALUES(124,'de','Glückserhöher','Erhöhte Chance auf zusätzliche Questbelohnungen. (Keine Auswirkung bei späterem Beitritt.)');
INSERT INTO skilltree_text VALUES(125,'de','Zerlegemeister','Ermöglicht dir, einen Kadaver einmal zusätzlich zu zerlegen. (Keine Auswirkung, wenn du der Quest später beitrittst.)');
INSERT INTO skilltree_text VALUES(126,'de','Glück','Eine gute Chance auf zusätzliche Questbelohnungen. (Keine Auswirkung bei späterem Beitritt.)');
INSERT INTO skilltree_text VALUES(127,'de','Sehnenkraft','Erhöht die maximale Aufladestufe des Bogens um eins.');
INSERT INTO skilltree_text VALUES(128,'de','Bestrafender Zug','Erweitert Zug-Angriffe um einen Betäubungseffekt und erhöht die Angriffskraft leicht.');
INSERT INTO skilltree_text VALUES(129,'de','Schutzpolitur','Die Waffenschärfe sinkt für eine bestimmte Zeit nach dem Schärfen nicht.');
INSERT INTO skilltree_text VALUES(130,'de','Grillspießmeister','Verbessert deine Fähigkeit, Fleisch zuzubereiten.');
INSERT INTO skilltree_text VALUES(131,'de','Explosionsbeschicht.','Ermöglicht das Auftragen von Explosionsbeschichtungen.');
INSERT INTO skilltree_text VALUES(132,'de','Ältestensiegel-Boost','Verbessert das Ältestensiegel von Waffen und Drachenmunition.');
INSERT INTO skilltree_text VALUES(133,'de','Lähmungsbeschicht.','Ermöglicht das Auftragen von Lähmungsbeschichtungen.');
INSERT INTO skilltree_text VALUES(134,'de','Giftbeschichtung','Ermöglicht das Auftragen von Giftbeschichtungen.');
INSERT INTO skilltree_text VALUES(135,'de','Schlafbeschichtung','Ermöglicht das Auftragen von Schlafbeschichtungen.');
INSERT INTO skilltree_text VALUES(136,'de','Element-Luftherrschaft','Erhöht den Element-Schaden durch gesprungene Angriffe.');
INSERT INTO skilltree_text VALUES(137,'de','WahrScharfschwrt/Extrsch','Reduziert Schärfeverlust stark. Chance auf Schüsse ohne Munitionsoder Beschichtungsverbrauch.');
INSERT INTO skilltree_text VALUES(138,'de','Offensive Abwehr','Erhöht nach dem Ausführen einer perfekt getimten Abwehr vorübergehend die Angriffskraft.');
INSERT INTO skilltree_text VALUES(139,'de','Verschmelzung','Verbessert nach der Erholung von Pest und anomalen Status-Effekten vorübergehend Angriffe.');
INSERT INTO skilltree_text VALUES(140,'de','Eiskunst','Bildet eine Frostaura bei weggesteckter Waffe, erhöht so Angriff; mit jedem Schuss / Nahkampftreffer schwächer.');
INSERT INTO skilltree_text VALUES(141,'de','Elementbeschleunigung','Kontinuierliche Angriffe aktivieren die Superwaffe-Fähigkeit Stufe 2 und erhöhen den Elementschaden.');
INSERT INTO skilltree_text VALUES(142,'de','WahrElementbeschleunigng','Kontinuierliche Angriffe aktivieren Superwaffe-Fähigkeit Stufe 3 und erhöhen Elementschaden.');
INSERT INTO skilltree_text VALUES(143,'de','Gaia-Schleier','Mantel gewährt Windsicher St. 3, Ohrstöpsel St. 3, Erschütterungswiderstand St. 3 und Unbeeindruckt.');
INSERT INTO skilltree_text VALUES(144,'de','Wahrer Gaia-Schleier','Mantel gewährt max. Windsicher, Ohrstöpsel St. 5, Erschütterungswiderstand St. 3 und Unbeeindruckt.');
INSERT INTO skilltree_text VALUES(145,'de','Drachenader-Erweckung','Element, anormaler Status und Affinität hoch bei gezogener Waffe. Erlittener Schaden kann wiederhergestellt werden.');
INSERT INTO skilltree_text VALUES(146,'de','Wahre-Drachenader-Erweckung','Verbesserte Angriffe mit gezogener Waffe. Nimmt beim Angriff Schaden, kann durch weitere Angriffe wiederhergestellt werden.');
INSERT INTO skilltree_text VALUES(147,'de','Freie-Mahlzeit-Geheimnis','Erhöht die Maximalstufe der Fähigkeit Freie Mahlzeit.');
INSERT INTO skilltree_text VALUES(148,'de','Höchstmacht-Geheimnis','Erhöht die Maximalstufe der Fähigkeit Höchstmacht.');
INSERT INTO skilltree_text VALUES(149,'de','Bombardier-Geheimnis','Erhöht die Maximalstufe der Fähigkeit Bombardier.');
INSERT INTO skilltree_text VALUES(150,'de','Lähmer-Geheimnis','Erhöht die Maximalstufe der Fähigkeit Lähmer.');
INSERT INTO skilltree_text VALUES(151,'de','Aufhetzer-Geheimnis','Erhöht die Maximalstufe der Fähigkeit Aufhetzer.');
INSERT INTO skilltree_text VALUES(152,'de','Artillerie-Geheimnis','Erhöht die Maximalstufe der Fähigkeit Artillerie.');
INSERT INTO skilltree_text VALUES(153,'de','Ausdauerdieb-Geheimnis','Erhöht die Maximalstufe der Fähigkeit Ausdauerdieb.');
INSERT INTO skilltree_text VALUES(154,'de','Werkzeugspezialist-Geheimnis','Erhöht die Maximalstufe der Fähigkeit Werkzeugspezialist.');
INSERT INTO skilltree_text VALUES(155,'de','Latente-Kraft-Geheimnis','Erhöht die Maximalstufe der Fähigkeit Latente Kraft.');
INSERT INTO skilltree_text VALUES(156,'de','GöttlicherSegenGeheimnis','Erhöht die Maximalstufe der Fähigkeit Göttlicher Segen.');
INSERT INTO skilltree_text VALUES(157,'de','Schleudermunition-Geheimnis','Erhöht die Maximalstufe der Fähigkeit Schleuderkapazität.');
INSERT INTO skilltree_text VALUES(158,'de','Heldentat-Geheimnis','Erhöht die Maximalstufe der Fähigkeit Heldentat.');
INSERT INTO skilltree_text VALUES(159,'de','WahrerKritschrStatus','Erhöht den Schaden von anomalen Statuseffekten (Lähmung, Gift, Schlaf, Explosion) durch kritische Treffer stark.');
INSERT INTO skilltree_text VALUES(160,'de','WahresKritschElement','Erhöht den Elementschaden (Feuer, Wasser, Donner, Eis, Drache) durch kritische Treffer stark.');
INSERT INTO skilltree_text VALUES(161,'de','Lunar-Geschenk','Verbessert die Chance, besondere Lunar-Fest-Belohnungen zu erhalten. (Kein Effekt bei Beitritt nach Questbeginn.)');
INSERT INTO skilltree_text VALUES(162,'de','Lunar-Segen','Verbessert die Chance stark, besondere Lunar-Fest-Belohnungen zu erhalten. (Kein Effekt bei Beitritt nach Questbeginn.)');
INSERT INTO skilltree_text VALUES(163,'de','Astral-Geschenk','Verbessert die Chance, besondere Astral-Fest-Belohnungen zu erhalten. (Kein Effekt bei Beitritt nach Questbeginn.)');
INSERT INTO skilltree_text VALUES(164,'de','Astral-Segen','Verbessert die Chance stark, besondere Astral-Fest-Belohnungen zu erhalten. (Kein Effekt bei Beitritt nach Questbeginn.)');
INSERT INTO skilltree_text VALUES(165,'de','Flor-Geschenk','Verbessert die Chance, besondere Flor-Fest-Belohnungen zu erhalten. (Kein Effekt bei Beitritt nach Questbeginn.)');
INSERT INTO skilltree_text VALUES(166,'de','Flor-Dankbarkeit','Verbessert die Chance stark, besondere Flor-Fest-Belohnungen zu erhalten. (Kein Effekt bei Beitritt nach Questbeginn.)');
INSERT INTO skilltree_text VALUES(167,'de','Elementwandlung','Die Elementkraft einer ausgerüsteten Waffe wird stärker, wenn sich der Elementwiderstand der Rüstung verbessert.');
INSERT INTO skilltree_text VALUES(168,'de','Alle Elementwiderstände','Alle Elementwiderstände +20%.');
INSERT INTO skilltree_text VALUES(169,'de','Clutch Claw Boost','Clutch claw weapon attacks wound monsters easier, and have a better chance of dropping slinger ammo.');
INSERT INTO skilltree_text VALUES(170,'de','Inheritance','Removes the skill level cap for the skill secrets.');
INSERT INTO skilltree_text VALUES(171,'de','Transcendance','Grants True Razor Sharp/Spare Shot. Health/Stamina +100 at the start of a quest or after fainting. (Effect doesn''t stack.)');
INSERT INTO skilltree_text VALUES(172,'de','Fun Fright''s Gift','Increases odds of getting special Fun Fright rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(173,'de','Fun Fright''s Gratitude','Greatly increases odds of getting special Fun Fright rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(174,'de','Sizzling Gift','Increases odds of getting special Sizzling Spice rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(175,'de','Sizzling Gratitude','Greatly increases odds of getting special Sizzling Spice rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(176,'de','Coldproof','Nullifies the effects of cold weather.');
INSERT INTO skilltree_text VALUES(177,'de','Provoker','Increases the attention drawn when attacking a monster.');
INSERT INTO skilltree_text VALUES(178,'de','Safe Landing','Allows you to quickly recover from heavy attacks that blow you back when you have your weapon unsheathed.');
INSERT INTO skilltree_text VALUES(1,'en','Poison Resistance','Reduces damage while poisoned.');
INSERT INTO skilltree_text VALUES(2,'en','Paralysis Resistance','Reduces the duration of paralysis.');
INSERT INTO skilltree_text VALUES(3,'en','Sleep Resistance','Reduces the duration of sleep.');
INSERT INTO skilltree_text VALUES(4,'en','Stun Resistance','Reduces stun duration.');
INSERT INTO skilltree_text VALUES(5,'en','Muck Resistance','Reduces impairments to mobility while stuck in monster muck.');
INSERT INTO skilltree_text VALUES(6,'en','Blast Resistance','Grants protection against blastblight.');
INSERT INTO skilltree_text VALUES(7,'en','Bleeding Resistance','Grants protection against bleeding.');
INSERT INTO skilltree_text VALUES(8,'en','Iron Skin','Grants protection against Defense Down.');
INSERT INTO skilltree_text VALUES(9,'en','Earplugs','Grants protection from large monsters'' roars.');
INSERT INTO skilltree_text VALUES(10,'en','Windproof','Grants protection against wind pressure.');
INSERT INTO skilltree_text VALUES(11,'en','Tremor Resistance','Grants protection against ground tremors.');
INSERT INTO skilltree_text VALUES(12,'en','Dungmaster','Makes monsters hit with slinger dung pods more likely to run.');
INSERT INTO skilltree_text VALUES(13,'en','Effluvial Expert','Nullifies or reduces environmental damage in the Rotten Vale.');
INSERT INTO skilltree_text VALUES(14,'en','Heat Guard','Nullifies damage from heat.');
INSERT INTO skilltree_text VALUES(15,'en','Attack Boost','Increases attack power. Also improves affinity at higher levels.');
INSERT INTO skilltree_text VALUES(16,'en','Defense Boost','Increases defense. Level up to improve resistances as well.');
INSERT INTO skilltree_text VALUES(17,'en','Health Boost','Increases health.');
INSERT INTO skilltree_text VALUES(18,'en','Recovery Up','Increases the amount recovered when restoring health.');
INSERT INTO skilltree_text VALUES(19,'en','Recovery Speed','Speeds healing of recoverable damage (the red portion of the health gauge).');
INSERT INTO skilltree_text VALUES(20,'en','Fire Resistance','Increases fire resistance. Also improves defense at higher levels.');
INSERT INTO skilltree_text VALUES(21,'en','Water Resistance','Increases water resistance. Also improves defense at higher levels.');
INSERT INTO skilltree_text VALUES(22,'en','Ice Resistance','Increases ice resistance. Also improves defense at higher levels.');
INSERT INTO skilltree_text VALUES(23,'en','Thunder Resistance','Increases thunder resistance. Also improves defense at higher levels.');
INSERT INTO skilltree_text VALUES(24,'en','Dragon Resistance','Increases dragon resistance. Also improves defense at higher levels.');
INSERT INTO skilltree_text VALUES(25,'en','Blight Resistance','Grants protection against all elemental blights.');
INSERT INTO skilltree_text VALUES(26,'en','Fire Attack','Increases fire element attack power. (Elemental attack power has a maximum limit.)');
INSERT INTO skilltree_text VALUES(27,'en','Water Attack','Increases water element attack power. (Elemental attack power has a maximum limit.)');
INSERT INTO skilltree_text VALUES(28,'en','Ice Attack','Increases ice element attack power. (Elemental attack power has a maximum limit.)');
INSERT INTO skilltree_text VALUES(29,'en','Thunder Attack','Increases thunder element attack power. (Elemental attack power has a maximum limit.)');
INSERT INTO skilltree_text VALUES(30,'en','Dragon Attack','Increases dragon element attack power. (Elemental attack power has a maximum limit.)');
INSERT INTO skilltree_text VALUES(31,'en','Poison Attack','Increases the rate of poison buildup. (Elemental buildup has a maximum limit.)');
INSERT INTO skilltree_text VALUES(32,'en','Paralysis Attack','Increases the rate of paralysis buildup. (Elemental buildup has a maximum limit.)');
INSERT INTO skilltree_text VALUES(33,'en','Sleep Attack','Increases the rate of sleep buildup. (Elemental buildup has a maximum limit.)');
INSERT INTO skilltree_text VALUES(34,'en','Blast Attack','Increases the rate of blast buildup. (Elemental buildup has a maximum limit.)');
INSERT INTO skilltree_text VALUES(35,'en','Normal Shots','Increases the attack power of normal ammo and normal arrows.');
INSERT INTO skilltree_text VALUES(36,'en','Piercing Shots','Increases the attack power of piercing ammo and Dragon Piercer.');
INSERT INTO skilltree_text VALUES(37,'en','Spread/Power Shots','Increases the attack power of spread ammo, power shot arrows, and Thousand Dragons.');
INSERT INTO skilltree_text VALUES(38,'en','Free Elem/Ammo Up','Unlocks your weapon''s hidden element. Also increases bowgun loading capacity. (There is a cap to loading capacity.)');
INSERT INTO skilltree_text VALUES(39,'en','Critical Eye','Increases affinity.');
INSERT INTO skilltree_text VALUES(40,'en','Critical Boost','Increases the damage of critical hits.');
INSERT INTO skilltree_text VALUES(41,'en','Weakness Exploit','Increases the affinity of attacks that exploit a monster weak spot.');
INSERT INTO skilltree_text VALUES(42,'en','Focus','Increases the fill rate for weapons with gauges and the charge rate for weapons with charge attacks.');
INSERT INTO skilltree_text VALUES(43,'en','Power Prolonger','Allows long swords, dual blades, insect glaives, switch axes, and charge blades to stay powered up longer.');
INSERT INTO skilltree_text VALUES(44,'en','Handicraft','Extends the weapon sharpness gauge. However, it will not increase the gauge past its maximum.');
INSERT INTO skilltree_text VALUES(45,'en','Critical Draw','Increases affinity when performing draw attacks.');
INSERT INTO skilltree_text VALUES(46,'en','Partbreaker','Makes it easier to break or sever parts of large monsters.');
INSERT INTO skilltree_text VALUES(47,'en','Slugger','Makes it easier to stun monsters.');
INSERT INTO skilltree_text VALUES(48,'en','Stamina Thief','Increases certain attacks'' ability to exhaust monsters.');
INSERT INTO skilltree_text VALUES(49,'en','Master Mounter','Makes it easier to mount monsters.');
INSERT INTO skilltree_text VALUES(50,'en','Airborne','Increases the damage caused by jumping attacks.');
INSERT INTO skilltree_text VALUES(51,'en','Latent Power','Temporarily increases affinity and reduces stamina depletion when certain conditions are met.');
INSERT INTO skilltree_text VALUES(52,'en','Agitator','Increases attack power and affinity when large monsters become enraged.');
INSERT INTO skilltree_text VALUES(53,'en','Peak Performance','Increases attack when your health is full.');
INSERT INTO skilltree_text VALUES(54,'en','Heroics','Increases attack power and defense when health drops to 35% or lower.');
INSERT INTO skilltree_text VALUES(55,'en','Fortify','Temporarily increases your attack and defense every time you faint up to 2 times.');
INSERT INTO skilltree_text VALUES(56,'en','Resentment','Increases attack when you have recoverable damage (the red portion of your health gauge).');
INSERT INTO skilltree_text VALUES(57,'en','Resuscitate','Improves evasion and reduces stamina depletion when afflicted with abnormal status effects.');
INSERT INTO skilltree_text VALUES(58,'en','Horn Maestro','Increases the effect duration of hunting horn melodies.');
INSERT INTO skilltree_text VALUES(59,'en','Capacity Boost','Increases the gunlance''s shell capacity and charge blade''s phial capacity.');
INSERT INTO skilltree_text VALUES(60,'en','Special Ammo Boost','Increases the power of bowgun special ammo, Dragon Piercer, and Thousand Dragons.');
INSERT INTO skilltree_text VALUES(61,'en','Artillery','Strengthens explosive attacks like gunlance shells, Wyvern''s Fire, charge blade phial attacks, and sticky ammo.');
INSERT INTO skilltree_text VALUES(62,'en','Heavy Artillery','Increases the firepower of ballistae and cannons.');
INSERT INTO skilltree_text VALUES(63,'en','Marathon Runner','Slows down stamina depletion for actions which continuously drain stamina (such as dashing).');
INSERT INTO skilltree_text VALUES(64,'en','Constitution','Reduces stamina depletion when performing stamina-draining moves such as evading, etc.');
INSERT INTO skilltree_text VALUES(65,'en','Leap of Faith','Allows you to do a dive-evade when facing towards large monsters, and extends the dive-evade distance.');
INSERT INTO skilltree_text VALUES(66,'en','Stamina Surge','Speeds up stamina recovery.');
INSERT INTO skilltree_text VALUES(67,'en','Hunger Resistance','Reduces maximum stamina depletion over time. However, does not work against cold environments that reduce stamina.');
INSERT INTO skilltree_text VALUES(68,'en','Evade Window','Extends the invulnerability period when evading.');
INSERT INTO skilltree_text VALUES(69,'en','Evade Extender','Increases evade distance.');
INSERT INTO skilltree_text VALUES(70,'en','Guard','Reduces knockbacks and stamina depletion when guarding.');
INSERT INTO skilltree_text VALUES(71,'en','Quick Sheath','Speeds up weapon sheathing.');
INSERT INTO skilltree_text VALUES(72,'en','Wide-Range','Allows the effects of certain items to also affect nearby allies.');
INSERT INTO skilltree_text VALUES(73,'en','Item Prolonger','Extends the duration of some item effects.');
INSERT INTO skilltree_text VALUES(74,'en','Free Meal','Gives you a predetermined chance of consuming a food or drink item for free.');
INSERT INTO skilltree_text VALUES(75,'en','Speed Eating','Increases meat-eating and item-consumption speed.');
INSERT INTO skilltree_text VALUES(76,'en','Speed Sharpening','Speeds up weapon sharpening when using a whetstone.');
INSERT INTO skilltree_text VALUES(77,'en','Bombardier','Increases the damage of explosive items.');
INSERT INTO skilltree_text VALUES(78,'en','Mushroomancer','Lets you digest mushrooms that would otherwise be inedible and gain their advantageous effects.');
INSERT INTO skilltree_text VALUES(79,'en','Master Fisher','Improves your skill at fishing.');
INSERT INTO skilltree_text VALUES(80,'en','Pro Transporter','Increases your speed while transporting items and decreases the likelihood of dropping them.');
INSERT INTO skilltree_text VALUES(81,'en','Master Gatherer','Allows you to gather more quickly, and also prevents attacks from knocking you back while gathering.');
INSERT INTO skilltree_text VALUES(82,'en','Honey Hunter','Increases the quantity of honey you receive when gathering in the field.');
INSERT INTO skilltree_text VALUES(83,'en','Carving Pro','Prevents knockback from attacks while carving.');
INSERT INTO skilltree_text VALUES(84,'en','Divine Blessing','Has a predetermined chance of reducing the damage you take.');
INSERT INTO skilltree_text VALUES(85,'en','Palico Rally','Powers up Palicoes.');
INSERT INTO skilltree_text VALUES(86,'en','Botanist','Increases the quantity of herbs and other consumable items you gather.');
INSERT INTO skilltree_text VALUES(87,'en','Geologist','Increases the number of times you can use a gathering point.');
INSERT INTO skilltree_text VALUES(88,'en','Maximum Might','Increases affinity as long as stamina is kept full for a period of time.');
INSERT INTO skilltree_text VALUES(89,'en','Slinger Capacity','Increases loading capacity for slinger ammo obtained in the field. Limits the amount of ammo used when firing certain shots.');
INSERT INTO skilltree_text VALUES(90,'en','Stealth','Makes it easier for monsters to lose sight of you.');
INSERT INTO skilltree_text VALUES(91,'en','Flinch Free','Prevents knockbacks and other reactions to small damage.');
INSERT INTO skilltree_text VALUES(92,'en','Scoutfly Range Up','Expands your scoutflies'' detection range.');
INSERT INTO skilltree_text VALUES(93,'en','Speed Crawler','Increases movement speed while crouching.');
INSERT INTO skilltree_text VALUES(94,'en','Jump Master','Prevents attacks from knocking you back during a jump.');
INSERT INTO skilltree_text VALUES(95,'en','Survival Expert','Extra health is recovered from environmental interactables like Sporepuffs or Wiggly Litchi.');
INSERT INTO skilltree_text VALUES(96,'en','Aquatic/Polar Mobility','Lets you move more freely in water. Also prevents you from being slowed down by terrain effects, such as deep snow.');
INSERT INTO skilltree_text VALUES(97,'en','Cliffhanger','Decreases stamina depletion when evading while clinging to walls or ivy, or when moving while grappling onto an enemy.');
INSERT INTO skilltree_text VALUES(98,'en','Blindsider','Improves the effectiveness of flash attacks and items.');
INSERT INTO skilltree_text VALUES(99,'en','Scholar','Speeds up progress on research levels and special investigations. (Effect is applied at the quest results screen.)');
INSERT INTO skilltree_text VALUES(100,'en','Entomologist','Decreases the chances of destroying the bodies of small insect monsters, allowing them to be carved.');
INSERT INTO skilltree_text VALUES(101,'en','Effluvia Resistance','Gain a resistance to effluvial buildup.');
INSERT INTO skilltree_text VALUES(102,'en','Scenthound','Increases your scoutflies'' gauge fill rate when you find tracks and other traces left by monsters.');
INSERT INTO skilltree_text VALUES(103,'en','Forager''s Luck','Increases the chance of finding rare gathering points.');
INSERT INTO skilltree_text VALUES(104,'en','Detector','Shows rare gathering points on the Wildlife Map.');
INSERT INTO skilltree_text VALUES(105,'en','Tool Specialist','Reduces the recharge time for specialized tools.');
INSERT INTO skilltree_text VALUES(106,'en','Affinity Sliding','Sliding increases your affinity for a short time.');
INSERT INTO skilltree_text VALUES(107,'en','Intimidator','Reduces the chances small monsters will attack after spotting you. (No effect on certain monsters.)');
INSERT INTO skilltree_text VALUES(108,'en','Hasten Recovery','Regenerates your health as you continually attack a monster. Recovery varies by weapon.');
INSERT INTO skilltree_text VALUES(109,'en','Super Recovery','Allows recovery to exceed the red portion of the health gauge.');
INSERT INTO skilltree_text VALUES(110,'en','Poison Duration Up','Extends the duration of your poison''s effect on monsters.');
INSERT INTO skilltree_text VALUES(111,'en','Adrenaline','Temporarily reduces stamina depletion when health is at 40% or lower.');
INSERT INTO skilltree_text VALUES(112,'en','Stamina Cap Up','Increases stamina cap.');
INSERT INTO skilltree_text VALUES(113,'en','Critical Element','Increases elemental damage (fire, water, thunder, ice, dragon) when landing critical hits.');
INSERT INTO skilltree_text VALUES(114,'en','Mind''s Eye/Ballistics','Prevents attacks from being deflected. Also shortens the distance before ammo and arrows reach maximum power.');
INSERT INTO skilltree_text VALUES(115,'en','Bludgeoner','Raises attack as your weapon loses sharpness. Also boosts ranged weapon melee attacks and odds of stunning.');
INSERT INTO skilltree_text VALUES(116,'en','Non-elemental Boost','Powers up non-elemental weapons you have equipped.');
INSERT INTO skilltree_text VALUES(117,'en','Capture Master','High chance of increased capture rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(118,'en','Guard Up','Allows you to guard against ordinarily unblockable attacks.');
INSERT INTO skilltree_text VALUES(119,'en','Guts','Above a certain health threshold, you withstand an attack that would normally cart you (once only).');
INSERT INTO skilltree_text VALUES(120,'en','Master''s Touch','Prevents your weapon from losing sharpness during critical hits.');
INSERT INTO skilltree_text VALUES(121,'en','Nullify Wind Pressure','Negates all wind pressure.');
INSERT INTO skilltree_text VALUES(122,'en','Razor Sharp/Spare Shot','Halves sharpness loss. For bows and bowguns, shots have a chance not to expend coatings or ammo.');
INSERT INTO skilltree_text VALUES(123,'en','Critical Status','Increases abnormal status effect damage (paralysis, poison, sleep, blast) when landing critical hits.');
INSERT INTO skilltree_text VALUES(124,'en','Great Luck','High chance of increased quest rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(125,'en','Carving Master','Lets you carve one additional time. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(126,'en','Good Luck','Good chance of increased quest rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(127,'en','Bow Charge Plus','Increases max bow charge level by one.');
INSERT INTO skilltree_text VALUES(128,'en','Punishing Draw','Adds a stun effect to draw attacks and slightly increases attack power.');
INSERT INTO skilltree_text VALUES(129,'en','Protective Polish','Weapon sharpness does not decrease for a set time after sharpening.');
INSERT INTO skilltree_text VALUES(130,'en','BBQ Master','Improves your skill at cooking meat.');
INSERT INTO skilltree_text VALUES(131,'en','Blast Functionality','Allows you to apply blast coatings.');
INSERT INTO skilltree_text VALUES(132,'en','Elderseal Boost','Increases the Elderseal of weapons and dragon ammo.');
INSERT INTO skilltree_text VALUES(133,'en','Para Functionality','Allows you to apply paralysis coatings.');
INSERT INTO skilltree_text VALUES(134,'en','Poison Functionality','Allows you to apply poison coatings.');
INSERT INTO skilltree_text VALUES(135,'en','Sleep Functionality','Allows you to apply sleep coatings.');
INSERT INTO skilltree_text VALUES(136,'en','Elemental Airborne','Elemental damage increased for jumping attacks.');
INSERT INTO skilltree_text VALUES(137,'en','True Razor Sharp/Spare Shot','Greatly reduces sharpness loss. Bows and bowguns have a chance not to expend coatings or ammo.');
INSERT INTO skilltree_text VALUES(138,'en','Offensive Guard','Temporarily increases attack power after executing a perfectly-timed guard.');
INSERT INTO skilltree_text VALUES(139,'en','Coalescence','Temporarily enhances attacks after recovering from blights or abnormal status.');
INSERT INTO skilltree_text VALUES(140,'en','Frostcraft','An aura of frost builds when your weapon is sheathed, raising attack. Wanes each melee hit or shot fired.');
INSERT INTO skilltree_text VALUES(141,'en','Element Acceleration','Continually attacking a monster activates Free Element/Ammo Up Lv2 and increases elemental damage.');
INSERT INTO skilltree_text VALUES(142,'en','True Element Acceleration','Continually attacking a monster activates Free Element/Ammo Up Lv3 and increases elemental damage.');
INSERT INTO skilltree_text VALUES(143,'en','Gaia''s Veil','While wearing a mantle, gain Windproof Lv3, Earplugs Lv3, Tremor Res Lv3, and Flinch Free.');
INSERT INTO skilltree_text VALUES(144,'en','True Gaia''s Veil','While wearing a mantle, gain Tremor Resistance Lv3, Earplugs Lv5, max Windproof, and Flinch Free.');
INSERT INTO skilltree_text VALUES(145,'en','Dragonvein Awakening','Elem., abnormal status, & affinity up with weapon drawn. Take damage when attacking, but can be recovered by continually attacking.');
INSERT INTO skilltree_text VALUES(146,'en','True Dragonvein Awakening','Enhances attacks even more with weapon drawn. Take damage when attacking, but can be recovered by continually attacking.');
INSERT INTO skilltree_text VALUES(147,'en','Free Meal Secret','Raises the maximum level of the Free Meal skill.');
INSERT INTO skilltree_text VALUES(148,'en','Maximum Might Secret','Raises the maximum level of the Maximum Might skill.');
INSERT INTO skilltree_text VALUES(149,'en','Bombardier Secret','Raises the maximum level of the Bombardier skill.');
INSERT INTO skilltree_text VALUES(150,'en','Slugger Secret','Raises the maximum level of the Slugger skill.');
INSERT INTO skilltree_text VALUES(151,'en','Agitator Secret','Raises the maximum level of the Agitator skill.');
INSERT INTO skilltree_text VALUES(152,'en','Artillery Secret','Raises the maximum level of the Artillery skill.');
INSERT INTO skilltree_text VALUES(153,'en','Stamina Thief Secret','Raises the maximum level of the Stamina Thief skill.');
INSERT INTO skilltree_text VALUES(154,'en','Tool Specialist Secret','Raises the maximum level of the Tool Specialist skill.');
INSERT INTO skilltree_text VALUES(155,'en','Latent Power Secret','Raises the maximum level of the Latent Power skill.');
INSERT INTO skilltree_text VALUES(156,'en','Divine Blessing Secret','Raises the maximum level of the Divine Blessing skill.');
INSERT INTO skilltree_text VALUES(157,'en','Slinger Ammo Secret','Raises the maximum level of the Slinger Capacity skill.');
INSERT INTO skilltree_text VALUES(158,'en','Heroics Secret','Raises the maximum level of the Heroics skill.');
INSERT INTO skilltree_text VALUES(159,'en','True Critical Status','Greatly increases status effect damage (paralysis, poison, sleep, blast) when landing critical hits.');
INSERT INTO skilltree_text VALUES(160,'en','True Critical Element','Greatly increases elemental damage (fire, water, thunder, ice, dragon) when landing critical hits.');
INSERT INTO skilltree_text VALUES(161,'en','Joy''s Gift','Increases odds of getting special Holiday Joy rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(162,'en','Joy''s Gratitude','Greatly increases odds of getting special Holiday Joy rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(163,'en','Gratitude''s Gift','Increases odds of getting special Grand Appreciation rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(164,'en','Gratitude''s Blessing','Greatly increases odds of getting special Grand Appreciation rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(165,'en','Full Bloom''s Gift','Increases odds of getting special Full Bloom rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(166,'en','Full Bloom Gratitude','Greatly increases odds of getting special Full Bloom rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(167,'en','Element Conversion','Equipped weapon''s elemental power increases as your armor''s elemental resistance increases.');
INSERT INTO skilltree_text VALUES(168,'en','All Elemental Resistance','Increases all elemental resistances +20%.');
INSERT INTO skilltree_text VALUES(169,'en','Clutch Claw Boost','Clutch claw weapon attacks wound monsters easier, and have a better chance of dropping slinger ammo.');
INSERT INTO skilltree_text VALUES(170,'en','Inheritance','Removes the skill level cap for the skill secrets.');
INSERT INTO skilltree_text VALUES(171,'en','Transcendance','Grants True Razor Sharp/Spare Shot. Health/Stamina +100 at the start of a quest or after fainting. (Effect doesn''t stack.)');
INSERT INTO skilltree_text VALUES(172,'en','Fun Fright''s Gift','Increases odds of getting special Fun Fright rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(173,'en','Fun Fright''s Gratitude','Greatly increases odds of getting special Fun Fright rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(174,'en','Sizzling Gift','Increases odds of getting special Sizzling Spice rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(175,'en','Sizzling Gratitude','Greatly increases odds of getting special Sizzling Spice rewards. (No effect when joining mid-quest.)');
INSERT INTO skilltree_text VALUES(176,'en','Coldproof','Nullifies the effects of cold weather.');
INSERT INTO skilltree_text VALUES(177,'en','Provoker','Increases the attention drawn when attacking a monster.');
INSERT INTO skilltree_text VALUES(178,'en','Safe Landing','Allows you to quickly recover from heavy attacks that blow you back when you have your weapon unsheathed.');

COMMIT;