BEGIN;

INSERT INTO armorset_bonus_text VALUES(1,'de','Anjanath-Macht',NULL);
INSERT INTO armorset_bonus_text VALUES(2,'de','Legiana-Segen',NULL);
INSERT INTO armorset_bonus_text VALUES(3,'de','Odogaron-Macht',NULL);
INSERT INTO armorset_bonus_text VALUES(4,'de','Rathalos-Macht',NULL);
INSERT INTO armorset_bonus_text VALUES(5,'de','Diablos-Kraft',NULL);
INSERT INTO armorset_bonus_text VALUES(6,'de','Kirin-Segen',NULL);
INSERT INTO armorset_bonus_text VALUES(7,'de','Anjanath-Wille',NULL);
INSERT INTO armorset_bonus_text VALUES(8,'de','RosaRathianMeisterung',NULL);
INSERT INTO armorset_bonus_text VALUES(9,'de','ZorahMagdarosMeisterung',NULL);
INSERT INTO armorset_bonus_text VALUES(10,'de','Legiana-Gefallen',NULL);
INSERT INTO armorset_bonus_text VALUES(11,'de','Odogaron-Meisterung',NULL);
INSERT INTO armorset_bonus_text VALUES(12,'de','Rathalos-Meisterung',NULL);
INSERT INTO armorset_bonus_text VALUES(13,'de','Diablos-Meisterung',NULL);
INSERT INTO armorset_bonus_text VALUES(14,'de','Uragaan-Schutz',NULL);
INSERT INTO armorset_bonus_text VALUES(15,'de','Bazelgeuse-Schutz',NULL);
INSERT INTO armorset_bonus_text VALUES(16,'de','Nergigante-Hunger',NULL);
INSERT INTO armorset_bonus_text VALUES(17,'de','Teostra-Technik',NULL);
INSERT INTO armorset_bonus_text VALUES(18,'de','Kushala-Daora-Flug',NULL);
INSERT INTO armorset_bonus_text VALUES(19,'de','Vaal-Hazak-Lebenskraft',NULL);
INSERT INTO armorset_bonus_text VALUES(20,'de','Kirin-Gefallen',NULL);
INSERT INTO armorset_bonus_text VALUES(21,'de','Xeno''jiiva-Göttlichkeit',NULL);
INSERT INTO armorset_bonus_text VALUES(22,'de','Gildenführung',NULL);
INSERT INTO armorset_bonus_text VALUES(23,'de','Kommissionsführung',NULL);
INSERT INTO armorset_bonus_text VALUES(24,'de','Lunastra-Vorteil',NULL);
INSERT INTO armorset_bonus_text VALUES(25,'de','Astera-Segen',NULL);
INSERT INTO armorset_bonus_text VALUES(26,'de','Dragoon-Kristall',NULL);
INSERT INTO armorset_bonus_text VALUES(27,'de','Anjanath-Dominanz',NULL);
INSERT INTO armorset_bonus_text VALUES(28,'de','Rathian-Essenz',NULL);
INSERT INTO armorset_bonus_text VALUES(29,'de','Uralte Göttlichkeit',NULL);
INSERT INTO armorset_bonus_text VALUES(30,'de','Kommissionsalchemie',NULL);
INSERT INTO armorset_bonus_text VALUES(31,'de','Geheime Barioth-Kunst',NULL);
INSERT INTO armorset_bonus_text VALUES(32,'de','Rathalos-Essenz',NULL);
INSERT INTO armorset_bonus_text VALUES(33,'de','Diablos-Ehrgeiz',NULL);
INSERT INTO armorset_bonus_text VALUES(34,'de','Legiana-Ehrgeiz',NULL);
INSERT INTO armorset_bonus_text VALUES(35,'de','Odogaron-Essenz',NULL);
INSERT INTO armorset_bonus_text VALUES(36,'de','Uragaan-Ehrgeiz',NULL);
INSERT INTO armorset_bonus_text VALUES(37,'de','Nargacuga-Essenz',NULL);
INSERT INTO armorset_bonus_text VALUES(38,'de','Glavenus-Essenz',NULL);
INSERT INTO armorset_bonus_text VALUES(39,'de','Brachydios-Essenz',NULL);
INSERT INTO armorset_bonus_text VALUES(40,'de','Tigrex-Essenz',NULL);
INSERT INTO armorset_bonus_text VALUES(41,'de','Ausbilderführung',NULL);
INSERT INTO armorset_bonus_text VALUES(42,'de','Bazelgeuse-Ehrgeiz',NULL);
INSERT INTO armorset_bonus_text VALUES(43,'de','Dämonjho-Essenz',NULL);
INSERT INTO armorset_bonus_text VALUES(44,'de','Velkhana-Göttlichkeit',NULL);
INSERT INTO armorset_bonus_text VALUES(45,'de','Vaal-Seelenader',NULL);
INSERT INTO armorset_bonus_text VALUES(46,'de','Kirin-Göttlichkeit',NULL);
INSERT INTO armorset_bonus_text VALUES(47,'de','Namielle-Göttlichkeit',NULL);
INSERT INTO armorset_bonus_text VALUES(48,'de','Gildenstolz',NULL);
INSERT INTO armorset_bonus_text VALUES(49,'de','Shara-Ishvalda-Göttlichkeit',NULL);
INSERT INTO armorset_bonus_text VALUES(50,'de','Zorah-Magdaros-Essenz',NULL);
INSERT INTO armorset_bonus_text VALUES(51,'de','Zinogre-Essenz',NULL);
INSERT INTO armorset_bonus_text VALUES(52,'de','Goldene-Rathian-Essenz',NULL);
INSERT INTO armorset_bonus_text VALUES(53,'de','Silberner-Rathalos-Essenz',NULL);
INSERT INTO armorset_bonus_text VALUES(54,'de','Lunastra-Essenz',NULL);
INSERT INTO armorset_bonus_text VALUES(55,'de','Nergigante-Ehrgeiz',NULL);
INSERT INTO armorset_bonus_text VALUES(56,'de','Lunar-Dankbarkeit',NULL);
INSERT INTO armorset_bonus_text VALUES(57,'de','Astral-Dankbarkeit',NULL);
INSERT INTO armorset_bonus_text VALUES(58,'de','Rajangs Rage',NULL);
INSERT INTO armorset_bonus_text VALUES(59,'de','Rajang-Wille',NULL);
INSERT INTO armorset_bonus_text VALUES(60,'de','Safi''jiiva-Siegel',NULL);
INSERT INTO armorset_bonus_text VALUES(61,'de','Brachydios-Wille',NULL);
INSERT INTO armorset_bonus_text VALUES(62,'de','Flor-Segen',NULL);
INSERT INTO armorset_bonus_text VALUES(63,'de','Alatreon-Göttlichkeit',NULL);
INSERT INTO armorset_bonus_text VALUES(64,'de','Kulve-Taroth-Essenz',NULL);
INSERT INTO armorset_bonus_text VALUES(65,'de','Frosthauer-Absolutkunst',NULL);
INSERT INTO armorset_bonus_text VALUES(66,'de','New World',NULL);
INSERT INTO armorset_bonus_text VALUES(67,'de','Fatalis Legend',NULL);
INSERT INTO armorset_bonus_text VALUES(68,'de','Fun Fright Blessing',NULL);
INSERT INTO armorset_bonus_text VALUES(69,'de','Sizzling Blessing',NULL);
INSERT INTO armorset_bonus_text VALUES(1,'en','Anjanath Power',NULL);
INSERT INTO armorset_bonus_text VALUES(2,'en','Legiana Blessing',NULL);
INSERT INTO armorset_bonus_text VALUES(3,'en','Odogaron Power',NULL);
INSERT INTO armorset_bonus_text VALUES(4,'en','Rathalos Power',NULL);
INSERT INTO armorset_bonus_text VALUES(5,'en','Diablos Power',NULL);
INSERT INTO armorset_bonus_text VALUES(6,'en','Kirin Blessing',NULL);
INSERT INTO armorset_bonus_text VALUES(7,'en','Anjanath Will',NULL);
INSERT INTO armorset_bonus_text VALUES(8,'en','Pink Rathian Mastery',NULL);
INSERT INTO armorset_bonus_text VALUES(9,'en','Zorah Magdaros Mastery',NULL);
INSERT INTO armorset_bonus_text VALUES(10,'en','Legiana Favor',NULL);
INSERT INTO armorset_bonus_text VALUES(11,'en','Odogaron Mastery',NULL);
INSERT INTO armorset_bonus_text VALUES(12,'en','Rathalos Mastery',NULL);
INSERT INTO armorset_bonus_text VALUES(13,'en','Diablos Mastery',NULL);
INSERT INTO armorset_bonus_text VALUES(14,'en','Uragaan Protection',NULL);
INSERT INTO armorset_bonus_text VALUES(15,'en','Bazelgeuse Protection',NULL);
INSERT INTO armorset_bonus_text VALUES(16,'en','Nergigante Hunger',NULL);
INSERT INTO armorset_bonus_text VALUES(17,'en','Teostra Technique',NULL);
INSERT INTO armorset_bonus_text VALUES(18,'en','Kushala Daora Flight',NULL);
INSERT INTO armorset_bonus_text VALUES(19,'en','Vaal Hazak Vitality',NULL);
INSERT INTO armorset_bonus_text VALUES(20,'en','Kirin Favor',NULL);
INSERT INTO armorset_bonus_text VALUES(21,'en','Xeno''jiiva Divinity',NULL);
INSERT INTO armorset_bonus_text VALUES(22,'en','Guild Guidance',NULL);
INSERT INTO armorset_bonus_text VALUES(23,'en','Commission Guidance',NULL);
INSERT INTO armorset_bonus_text VALUES(24,'en','Lunastra Favor',NULL);
INSERT INTO armorset_bonus_text VALUES(25,'en','Astera Blessing',NULL);
INSERT INTO armorset_bonus_text VALUES(26,'en','Soul of the Dragoon',NULL);
INSERT INTO armorset_bonus_text VALUES(27,'en','Anjanath Dominance',NULL);
INSERT INTO armorset_bonus_text VALUES(28,'en','Rathian Essence',NULL);
INSERT INTO armorset_bonus_text VALUES(29,'en','Ancient Divinity',NULL);
INSERT INTO armorset_bonus_text VALUES(30,'en','Commission Alchemy',NULL);
INSERT INTO armorset_bonus_text VALUES(31,'en','Barioth Hidden Art',NULL);
INSERT INTO armorset_bonus_text VALUES(32,'en','Rathalos Essence',NULL);
INSERT INTO armorset_bonus_text VALUES(33,'en','Diablos Ambition',NULL);
INSERT INTO armorset_bonus_text VALUES(34,'en','Legiana Ambition',NULL);
INSERT INTO armorset_bonus_text VALUES(35,'en','Odogaron Essence',NULL);
INSERT INTO armorset_bonus_text VALUES(36,'en','Uragaan Ambition',NULL);
INSERT INTO armorset_bonus_text VALUES(37,'en','Nargacuga Essence',NULL);
INSERT INTO armorset_bonus_text VALUES(38,'en','Glavenus Essence',NULL);
INSERT INTO armorset_bonus_text VALUES(39,'en','Brachydios Essence',NULL);
INSERT INTO armorset_bonus_text VALUES(40,'en','Tigrex Essence',NULL);
INSERT INTO armorset_bonus_text VALUES(41,'en','Instructor''s Guidance',NULL);
INSERT INTO armorset_bonus_text VALUES(42,'en','Bazelgeuse Ambition',NULL);
INSERT INTO armorset_bonus_text VALUES(43,'en','Deviljho Essence',NULL);
INSERT INTO armorset_bonus_text VALUES(44,'en','Velkhana Divinity',NULL);
INSERT INTO armorset_bonus_text VALUES(45,'en','Vaal Soulvein',NULL);
INSERT INTO armorset_bonus_text VALUES(46,'en','Kirin Divinity',NULL);
INSERT INTO armorset_bonus_text VALUES(47,'en','Namielle Divinity',NULL);
INSERT INTO armorset_bonus_text VALUES(48,'en','Guild Pride',NULL);
INSERT INTO armorset_bonus_text VALUES(49,'en','Shara Ishvalda Divinity',NULL);
INSERT INTO armorset_bonus_text VALUES(50,'en','Zorah Magdaros Essence',NULL);
INSERT INTO armorset_bonus_text VALUES(51,'en','Zinogre Essence',NULL);
INSERT INTO armorset_bonus_text VALUES(52,'en','Gold Rathian Essence',NULL);
INSERT INTO armorset_bonus_text VALUES(53,'en','Silver Rathalos Essence',NULL);
INSERT INTO armorset_bonus_text VALUES(54,'en','Lunastra Essence',NULL);
INSERT INTO armorset_bonus_text VALUES(55,'en','Nergigante Ambition',NULL);
INSERT INTO armorset_bonus_text VALUES(56,'en','Joyful Blessing',NULL);
INSERT INTO armorset_bonus_text VALUES(57,'en','Appreciation Blessing',NULL);
INSERT INTO armorset_bonus_text VALUES(58,'en','Rajang''s Rage',NULL);
INSERT INTO armorset_bonus_text VALUES(59,'en','Rajang Will',NULL);
INSERT INTO armorset_bonus_text VALUES(60,'en','Safi''jiiva Seal',NULL);
INSERT INTO armorset_bonus_text VALUES(61,'en','Brachydios Will',NULL);
INSERT INTO armorset_bonus_text VALUES(62,'en','Full Bloom Blessing',NULL);
INSERT INTO armorset_bonus_text VALUES(63,'en','Alatreon Divinity',NULL);
INSERT INTO armorset_bonus_text VALUES(64,'en','Kulve Taroth Essence',NULL);
INSERT INTO armorset_bonus_text VALUES(65,'en','Frostfang Absolute Art',NULL);
INSERT INTO armorset_bonus_text VALUES(66,'en','New World',NULL);
INSERT INTO armorset_bonus_text VALUES(67,'en','Fatalis Legend',NULL);
INSERT INTO armorset_bonus_text VALUES(68,'en','Fun Fright Blessing',NULL);
INSERT INTO armorset_bonus_text VALUES(69,'en','Sizzling Blessing',NULL);

COMMIT;