BEGIN;

INSERT INTO weapon_melody_text VALUES(1,'de','Selbstverbesserung','Bewegungsgeschwindigkeit hoch','Angriff hoch + Angriffsablenkungsschutz');
INSERT INTO weapon_melody_text VALUES(2,'de','Angriff hoch (S)','Angriff hoch (S)','Angriff hoch (L)');
INSERT INTO weapon_melody_text VALUES(3,'de','Angriff hoch (L)','Angriff hoch (L)','Angriff hoch (XL)');
INSERT INTO weapon_melody_text VALUES(4,'de','Gesundheitsboost (S)','Gesundheitsboost (S)','Gesundheitsboost Zeitbonus');
INSERT INTO weapon_melody_text VALUES(5,'de','Gesundheitsboost (L)','Gesundheitsboost (L)','Gesundheitsboost Zeitbonus');
INSERT INTO weapon_melody_text VALUES(6,'de','Ausdauernutzung reduziert (S)','Ausdauernutzung reduziert (S)','Ausdauernutzung reduziert Zeitbonus');
INSERT INTO weapon_melody_text VALUES(7,'de','Ausdauernutzung reduziert (L)','Ausdauernutzung reduziert (L)','Ausdauernutzung reduziert Zeitbonus');
INSERT INTO weapon_melody_text VALUES(8,'de','Winddruck negiert','Winddruck negiert','Winddruck negiert Zeitbonus');
INSERT INTO weapon_melody_text VALUES(9,'de','Jeden Winddruck negiert','Jeden Winddruck negiert','Jeden Winddruck negiert Zeitbonus');
INSERT INTO weapon_melody_text VALUES(10,'de','Verteidigung hoch (S)','Verteidigung hoch (S)','Verteidigung hoch (L)');
INSERT INTO weapon_melody_text VALUES(11,'de','Verteidigung hoch (L)','Verteidigung hoch (L)','Verteidigung hoch (XL)');
INSERT INTO weapon_melody_text VALUES(12,'de','Werkzeugverbrauch reduziert (S)','Werkzeugverbrauch reduziert (S)','Werkzeugverbrauch reduziert Zeitbonus');
INSERT INTO weapon_melody_text VALUES(13,'de','Werkzeugverbrauch reduziert (L)','Werkzeugverbrauch reduziert (L)','Werkzeugverbrauch reduziert Zeitbonus');
INSERT INTO weapon_melody_text VALUES(14,'de','Gesundheitserholung (S)','Gesundheitserholung (S)','N/A');
INSERT INTO weapon_melody_text VALUES(15,'de','Gesundheitserholung (L)','Gesundheitserholung (L)','N/A');
INSERT INTO weapon_melody_text VALUES(16,'de','Gesundheitserholung (S) + Gegengift','Gesundheitserholung (S) + Gegengift','N/A');
INSERT INTO weapon_melody_text VALUES(17,'de','Gesundheitserholung (M) + Gegengift','Gesundheitserholung (M) + Gegengift','N/A');
INSERT INTO weapon_melody_text VALUES(18,'de','Erholungsgeschwindigkeit (S)','Erholungsgeschwindigkeit (S)','Erholungsgeschwindigkeit Zeitbonus');
INSERT INTO weapon_melody_text VALUES(19,'de','Erholungsgeschwindigkeit (L)','Erholungsgeschwindigkeit (L)','Erholungsgeschwindigkeit Zeitbonus');
INSERT INTO weapon_melody_text VALUES(20,'de','Ohrstöpsel (S)','Ohrstöpsel (S)','Ohrstöpsel (S) Zeitbonus');
INSERT INTO weapon_melody_text VALUES(21,'de','Ohrstöpsel (L)','Ohrstöpsel (L)','Ohrstöpsel (L) Zeitbonus');
INSERT INTO weapon_melody_text VALUES(22,'de','Göttlicher Schutz','Göttlicher Schutz','Göttlicher Schutz Zeitbonus');
INSERT INTO weapon_melody_text VALUES(23,'de','Spähkäfer-Kraft hoch','Spähkäfer-Stufe +1','Spähkäfer-Stufe +1 Zeitbonus');
INSERT INTO weapon_melody_text VALUES(24,'de','Umgebungsschaden negiert','Umgebungsschaden negiert','Umgebungsschaden negiert Zeitbonus');
INSERT INTO weapon_melody_text VALUES(25,'de','Betäuben negiert','Betäuben negiert','Betäuben negiert Zeitbonus');
INSERT INTO weapon_melody_text VALUES(26,'de','Lähmung negiert','Lähmung negiert','Lähmung negiert Zeitbonus');
INSERT INTO weapon_melody_text VALUES(27,'de','Erschütterungen negiert','Erschütterungen negiert','Erschütterungen negiert Zeitbonus');
INSERT INTO weapon_melody_text VALUES(28,'de','Schlamm/Wasser/Schnee-Widerstand','Schlamm/Wasser/Schnee-Widerstand','Schlamm/Wasser/Schnee-Widerstand-Zeitbonus');
INSERT INTO weapon_melody_text VALUES(29,'de','Feuerwiderstand-Boost (S)','Feuerwiderstand-Boost (S)','Feuerwiderstand-Boost (L)');
INSERT INTO weapon_melody_text VALUES(30,'de','Feuerwiderstand-Boost (L)','Feuerwiderstand-Boost (L)','Feuerwiderstand-Boost (XL)');
INSERT INTO weapon_melody_text VALUES(31,'de','Wasserwiderstand-Boost (S)','Wasserwiderstand-Boost (S)','Wasserwiderstand-Boost (L)');
INSERT INTO weapon_melody_text VALUES(32,'de','Wasserwiderstand-Boost (L)','Wasserwiderstand-Boost (L)','Wasserwiderstand-Boost (XL)');
INSERT INTO weapon_melody_text VALUES(33,'de','Donnerwiderstand-Boost (S)','Donnerwiderstand-Boost (S)','Donnerwiderstand-Boost (L)');
INSERT INTO weapon_melody_text VALUES(34,'de','Donnerwiderstand-Boost (L)','Donnerwiderstand-Boost (L)','Donnerwiderstand-Boost (XL)');
INSERT INTO weapon_melody_text VALUES(35,'de','Eiswiderstand-Boost (S)','Eiswiderstand-Boost (S)','Eiswiderstand-Boost (L)');
INSERT INTO weapon_melody_text VALUES(36,'de','Eiswiderstand-Boost (L)','Eiswiderstand-Boost (L)','Eiswiderstand-Boost (XL)');
INSERT INTO weapon_melody_text VALUES(37,'de','Drachenwiderstand-Boost (S)','Drachenwiderstand-Boost (S)','Drachenwiderstand-Boost (L)');
INSERT INTO weapon_melody_text VALUES(38,'de','Drachenwiderstand-Boost (L)','Drachenwiderstand-Boost (L)','Drachenwiderstand-Boost (XL)');
INSERT INTO weapon_melody_text VALUES(39,'de','Elementangriff-Boost','Elementangriff-Boost (S)','Elementangriff-Boost (L)');
INSERT INTO weapon_melody_text VALUES(40,'de','Pest negiert','Pest negiert','Pest negiert Zeitbonus');
INSERT INTO weapon_melody_text VALUES(41,'de','Schallwellen','Schallwellen','N/A');
INSERT INTO weapon_melody_text VALUES(42,'de','Alle Medodie-Effekte Zeitbonus','Alle Medodie-Effekte Zeitbonus','N/A');
INSERT INTO weapon_melody_text VALUES(43,'de','Rückschläge negiert','Rückschläge negiert','Rückschläge negiert Zeitbonus');
INSERT INTO weapon_melody_text VALUES(44,'de','Angriff und Verteidigung hoch (S)','Angriff und Verteidigung hoch (S)','Angriff hoch (L) / Verteidigung hoch (L)');
INSERT INTO weapon_melody_text VALUES(45,'de','Pestwiderstand hoch','Pestwiderstand hoch (S)','Pestwiderstand hoch (L)');
INSERT INTO weapon_melody_text VALUES(46,'de','Affinität hoch / Gesundheitserholung (S)','Affinität hoch (S) / Gesundheitserholung (S)','Affinität hoch (L) / Gesundheitserholung (S)');
INSERT INTO weapon_melody_text VALUES(47,'de','Alle anorm. Status negiert','Alle anorm. Status negiert','Anorm. Status negiert Zeitbonus');
INSERT INTO weapon_melody_text VALUES(48,'de','Ohrstöpsel (S) / Winddruck negiert','Ohrstöpsel (S) / Winddruck negiert','Ohrstöpsel (S) / Winddruck negiert Zeitbonus');
INSERT INTO weapon_melody_text VALUES(49,'de','Anormaler Statusangriff verbessert','Anormaler Statusangriff hoch (S)','Anormaler Statusangriff hoch (L)');
INSERT INTO weapon_melody_text VALUES(50,'de','Gesundheitserholung (M)','Gesundheitserholung (M)','N/A');
INSERT INTO weapon_melody_text VALUES(51,'de','Einschlagsecho-Welle','Einschlagsecho-Welle','N/A');
INSERT INTO weapon_melody_text VALUES(52,'de','Echo-Welle "Drachen"','Echo-Welle "Drachen"','N/A');
INSERT INTO weapon_melody_text VALUES(53,'de','Max. Ausdauer hoch + Erholung','Max. Ausdauer hoch + Erholung','N/A');
INSERT INTO weapon_melody_text VALUES(54,'de','Verbesserte Gesundheitserholung','Verbesserte Gesundheitserholung','N/A');
INSERT INTO weapon_melody_text VALUES(55,'de','Geschw-Boost + Unverwundbarkeit hoch','Geschw-Boost + Unverwundbarkeit hoch','N/A');
INSERT INTO weapon_melody_text VALUES(56,'de','Elementeffektivität hoch','Elementeffektivität hoch','N/A');
INSERT INTO weapon_melody_text VALUES(1,'en','Self-improvement','Movement Speed Up','Attack Up + Deflected Attack Prevention');
INSERT INTO weapon_melody_text VALUES(2,'en','Attack Up (S)','Attack Up (S)','Attack Up (L)');
INSERT INTO weapon_melody_text VALUES(3,'en','Attack Up (L)','Attack Up (L)','Attack Up (XL)');
INSERT INTO weapon_melody_text VALUES(4,'en','Health Boost (S)','Health Boost (S)','Health Boost Extended');
INSERT INTO weapon_melody_text VALUES(5,'en','Health Boost (L)','Health Boost (L)','Health Boost Extended');
INSERT INTO weapon_melody_text VALUES(6,'en','Stamina Use Reduced (S)','Stamina Use Reduced (S)','Stamina Use Reduction Extended');
INSERT INTO weapon_melody_text VALUES(7,'en','Stamina Use Reduced (L)','Stamina Use Reduced (L)','Stamina Use Reduction Extended');
INSERT INTO weapon_melody_text VALUES(8,'en','Wind Pressure Negated','Wind Pressure Negated','Wind Pressure Negation Extended');
INSERT INTO weapon_melody_text VALUES(9,'en','All Wind Pressure Negated','All Wind Pressure Negated','All Wind Pressure Negation Extended');
INSERT INTO weapon_melody_text VALUES(10,'en','Defense Up (S)','Defense Up (S)','Defense Up (L)');
INSERT INTO weapon_melody_text VALUES(11,'en','Defense Up (L)','Defense Up (L)','Defense Up (XL)');
INSERT INTO weapon_melody_text VALUES(12,'en','Tool Use Drain Reduced (S)','Tool Use Drain Reduced (S)','Tool Use Drain Reduction Extended');
INSERT INTO weapon_melody_text VALUES(13,'en','Tool Use Drain Reduced (L)','Tool Use Drain Reduced (L)','Tool Use Drain Reduction Extended');
INSERT INTO weapon_melody_text VALUES(14,'en','Health Rec. (S)','Health Rec. (S)','N/A');
INSERT INTO weapon_melody_text VALUES(15,'en','Health Rec. (L)','Health Rec. (L)','N/A');
INSERT INTO weapon_melody_text VALUES(16,'en','Health Rec. (S) + Antidote','Health Rec. (S) + Antidote','N/A');
INSERT INTO weapon_melody_text VALUES(17,'en','Health Rec. (M) + Antidote','Health Rec. (M) + Antidote','N/A');
INSERT INTO weapon_melody_text VALUES(18,'en','Recovery Speed (S)','Recovery Speed (S)','Recovery Speed Extended');
INSERT INTO weapon_melody_text VALUES(19,'en','Recovery Speed (L)','Recovery Speed (L)','Recovery Speed Extended');
INSERT INTO weapon_melody_text VALUES(20,'en','Earplugs (S)','Earplugs (S)','Earplugs (S) Extended');
INSERT INTO weapon_melody_text VALUES(21,'en','Earplugs (L)','Earplugs (L)','Earplugs (L) Extended');
INSERT INTO weapon_melody_text VALUES(22,'en','Divine Protection','Divine Protection','Divine Protection Extended');
INSERT INTO weapon_melody_text VALUES(23,'en','Scoutfly Power Up','Scoutfly Level +1','Scoutfly Level +1 Extended');
INSERT INTO weapon_melody_text VALUES(24,'en','Envir. Damage Negated','Envir. Damage Negated','Envir. Damage Negation Extended');
INSERT INTO weapon_melody_text VALUES(25,'en','Stun Negated','Stun Negated','Stun Negation Extended');
INSERT INTO weapon_melody_text VALUES(26,'en','Paralysis Negated','Paralysis Negated','Paralysis Negation Extended');
INSERT INTO weapon_melody_text VALUES(27,'en','Tremors Negated','Tremors Negated','Tremor Negation Extended');
INSERT INTO weapon_melody_text VALUES(28,'en','Muck/Water/Deep Snow Res','Muck/Water/Deep Snow Res','Muck/Water/Deep Snow Res Extended');
INSERT INTO weapon_melody_text VALUES(29,'en','Fire Res Boost (S)','Fire Res Boost (S)','Fire Res Boost (L)');
INSERT INTO weapon_melody_text VALUES(30,'en','Fire Res Boost (L)','Fire Res Boost (L)','Fire Res Boost (XL)');
INSERT INTO weapon_melody_text VALUES(31,'en','Water Res Boost (S)','Water Res Boost (S)','Water Res Boost (L)');
INSERT INTO weapon_melody_text VALUES(32,'en','Water Res Boost (L)','Water Res Boost (L)','Water Res Boost (XL)');
INSERT INTO weapon_melody_text VALUES(33,'en','Thunder Res Boost (S)','Thunder Res Boost (S)','Thunder Res Boost (L)');
INSERT INTO weapon_melody_text VALUES(34,'en','Thunder Res Boost (L)','Thunder Res Boost (L)','Thunder Res Boost (XL)');
INSERT INTO weapon_melody_text VALUES(35,'en','Ice Res Boost (S)','Ice Res Boost (S)','Ice Res Boost (L)');
INSERT INTO weapon_melody_text VALUES(36,'en','Ice Res Boost (L)','Ice Res Boost (L)','Ice Res Boost (XL)');
INSERT INTO weapon_melody_text VALUES(37,'en','Dragon Res Boost (S)','Dragon Res Boost (S)','Dragon Res Boost (L)');
INSERT INTO weapon_melody_text VALUES(38,'en','Dragon Res Boost (L)','Dragon Res Boost (L)','Dragon Res Boost (XL)');
INSERT INTO weapon_melody_text VALUES(39,'en','Elemental Attack Boost','Elemental Attack Boost (S)','Elemental Attack Boost (L)');
INSERT INTO weapon_melody_text VALUES(40,'en','Blight Negated','Blight Negated','Blight Negation Extended');
INSERT INTO weapon_melody_text VALUES(41,'en','Sonic Waves','Sonic Waves','N/A');
INSERT INTO weapon_melody_text VALUES(42,'en','All Melody Effects Extended','All Melody Effects Extended','N/A');
INSERT INTO weapon_melody_text VALUES(43,'en','Knockbacks Negated','Knockbacks Negated','Knockback Negation Extended');
INSERT INTO weapon_melody_text VALUES(44,'en','Attack and Defense Up (S)','Attack and Defense Up (S)','Attack Up (L) / Defense Up (L)');
INSERT INTO weapon_melody_text VALUES(45,'en','Blight Res Up','Blight Res Up (S)','Blight Res Up (L)');
INSERT INTO weapon_melody_text VALUES(46,'en','Affinity Up and Health Rec. (S)','Affinity Up (S) / Health Rec. (S)','Affinity Up (L) / Health Rec. (S)');
INSERT INTO weapon_melody_text VALUES(47,'en','All Ailments Negated','All Ailments Negated','Ailment Negation Extended');
INSERT INTO weapon_melody_text VALUES(48,'en','Earplugs (S) / Wind Pressure Negated','Earplugs (S) / Wind Pressure Negated','Earplugs (S) / Wind Pressure Negation Extended');
INSERT INTO weapon_melody_text VALUES(49,'en','Abnormal Status Atk. Increased','Abnormal Status Atk. Up (S)','Abnormal Status Atk. Up (L)');
INSERT INTO weapon_melody_text VALUES(50,'en','Health Recovery (M)','Health Recovery (M)','N/A');
INSERT INTO weapon_melody_text VALUES(51,'en','Impact Echo Wave','Impact Echo Wave','N/A');
INSERT INTO weapon_melody_text VALUES(52,'en','Echo Wave "Dragon"','Echo Wave "Dragon"','N/A');
INSERT INTO weapon_melody_text VALUES(53,'en','Max Stamina Up + Recovery','Max Stamina Up + Recovery','N/A');
INSERT INTO weapon_melody_text VALUES(54,'en','Extended Health Recovery','Extended Health Recovery','N/A');
INSERT INTO weapon_melody_text VALUES(55,'en','Speed Boost + Evade Window Up','Speed Boost + Evade Window Up','N/A');
INSERT INTO weapon_melody_text VALUES(56,'en','Elemental Effectiveness Up','Elemental Effectiveness Up','N/A');

COMMIT;