BEGIN;

INSERT INTO tool_text VALUES(1,'de','Ghillie-Mantel+',NULL,'Macht dich kurzzeitig unsichtbar. Wenn du angreifst oder Schaden erleidest, endet die Wirkung.');
INSERT INTO tool_text VALUES(2,'de','Lebensretter-Mantel+',NULL,'Negiert den Schaden von kraftvollen Angriffen durch automatisches Ausweichen.');
INSERT INTO tool_text VALUES(3,'de','Gesundheit-Booster+',NULL,'Platziert eine Räucher-Vorrichtung, die langsam deine Gesundheit regeneriert.');
INSERT INTO tool_text VALUES(4,'de','Trutzmantel+',NULL,'Eliminiert Schadensreaktionen, verhindert Windeffekte und schützt dein Gehör sowie vor Erschütterungen. Mindert außerdem Schaden von Angriffen.');
INSERT INTO tool_text VALUES(5,'de','Herausforderer-Mantel+',NULL,'Lenkt die Aufmerksamkeit von Monstern auf dich, wodurch du sie leichter anlocken kannst. Der Effekt endet, wenn du angegriffen wirst.');
INSERT INTO tool_text VALUES(6,'de','Lebenskraft-Mantel+',NULL,'Negiert eine bestimmte Schadensmenge – danach endet der Effekt.');
INSERT INTO tool_text VALUES(7,'de','Feuerschutz-Mantel+',NULL,'Reduziert Feuerelement-Schaden und negiert Feuerpest, Explosionspest, sowie Schaden von heißen Umgebungen.');
INSERT INTO tool_text VALUES(8,'de','Wasserschutz-Mantel+',NULL,'Reduziert Wasserelement-Schaden. Negiert Wasserpest und Bewegungseinschränkungen in tiefem Wasser sowie Schlamm.');
INSERT INTO tool_text VALUES(9,'de','Eisschutz-Mantel+',NULL,'Reduziert Eiselement-Schaden und negiert Eispest.');
INSERT INTO tool_text VALUES(10,'de','Donnerschutz-Mantel+',NULL,'Reduziert Donnerelement-Schaden und negiert Donnerpest sowie Lähmung.');
INSERT INTO tool_text VALUES(11,'de','Drachenschutz-Mantel+',NULL,'Reduziert Drachenelement-Schaden. Negiert Drachenpest und verbessert die Drachen-Eigenschaften deiner Waffe.');
INSERT INTO tool_text VALUES(12,'de','Reiniger-Booster+',NULL,'Platziert eine Räucher-Vorrichtung, die alle anomalen Statuseffekte und elementbasierten Pestarten aufhebt.');
INSERT INTO tool_text VALUES(13,'de','Gleiter-Mantel+',NULL,'Du springst länger und kannst auf Winden reiten. Erleichtert zudem den Aufstieg auf Monster.');
INSERT INTO tool_text VALUES(14,'de','Ausweich-Mantel+',NULL,'Macht beim Ausweichen länger unverwundbar; zudem kurzzeitiger Angriffsbonus beim Ausweichen eines Angriffs im letzten Moment.');
INSERT INTO tool_text VALUES(15,'de','Aufschlag-Mantel+',NULL,'Fügt den meisten Angriffen einen Betäubungseffekt hinzu oder verstärkt einen bestehenden Betäubungseffekt.');
INSERT INTO tool_text VALUES(16,'de','Apotheker-Mantel+',NULL,'Häufigere Status-Ansammlungen beim Angriff mit Waffen, die anomale Statuseffekte verursachen.');
INSERT INTO tool_text VALUES(17,'de','Immunität-Mantel+',NULL,'Entfernt und negiert alle anomalen Statuseffekte, solange die Wirkung andauert.');
INSERT INTO tool_text VALUES(18,'de','Affinität-Booster+',NULL,'Platziert eine Räucher-Vorrichtung, die die Affinität erhöht.');
INSERT INTO tool_text VALUES(19,'de','Banditen-Mantel+',NULL,'Monster lassen seltene Wertobjekte fallen, wenn du sie angreifst.');
INSERT INTO tool_text VALUES(20,'de','Assassinenkapuze+',NULL,'Erhöht die Bewegungsgeschwindigkeit und erlaubt schnelleres Verstecken. Richtet bei einem arglosen Monster großen Schaden an und endet dann.');
INSERT INTO tool_text VALUES(1,'en','Ghillie Mantle+',NULL,'Conceals you from enemy view temporarily. The effect expires if you perform an attack or take damage.');
INSERT INTO tool_text VALUES(2,'en','Temporal Mantle+',NULL,'Nullifies damage from powerful attacks by automatically evading.');
INSERT INTO tool_text VALUES(3,'en','Health Booster+',NULL,'Places a smoker that gradually restores your health.');
INSERT INTO tool_text VALUES(4,'en','Rocksteady Mantle+',NULL,'Eliminates damage reactions, prevents wind effects, protects your hearing, and grants tremor resistance. You also receive less damage from attacks.');
INSERT INTO tool_text VALUES(5,'en','Challenger Mantle+',NULL,'Prompts monsters to target you more often and makes them easier to lure. The effect expires if you are attacked.');
INSERT INTO tool_text VALUES(6,'en','Vitality Mantle+',NULL,'Negates a fixed amount of damage, after which the effect expires.');
INSERT INTO tool_text VALUES(7,'en','Fireproof Mantle+',NULL,'Reduces fire damage, nullifies fireblight and blastblight, and prevents damage from hot environments.');
INSERT INTO tool_text VALUES(8,'en','Waterproof Mantle+',NULL,'Reduces water damage, nullifies waterblight, reduces mobility restrictions in muck and negates them entirely for deep water.');
INSERT INTO tool_text VALUES(9,'en','Iceproof Mantle+',NULL,'Reduces ice damage and nullifies iceblight.');
INSERT INTO tool_text VALUES(10,'en','Thunderproof Mantle+',NULL,'Reduces thunder damage and nullifies thunderblight and paralysis.');
INSERT INTO tool_text VALUES(11,'en','Dragonproof Mantle+',NULL,'Reduces dragon damage, nullifies dragonblight, and powers up your weapon''s dragon properties.');
INSERT INTO tool_text VALUES(12,'en','Cleanser Booster+',NULL,'Places a smoker that removes any abnormal status effects and elemental blights.');
INSERT INTO tool_text VALUES(13,'en','Glider Mantle+',NULL,'Increases jump airtime and grants the power to ride strong winds. Also makes it easier to mount monsters.');
INSERT INTO tool_text VALUES(14,'en','Evasion Mantle+',NULL,'Increases the invulnerability window while evading and grants a temporary attack boost for evading a monster attack at the very last moment.');
INSERT INTO tool_text VALUES(15,'en','Impact Mantle+',NULL,'Adds a stun effect to most attacks or increases the potency of an existing stun effect.');
INSERT INTO tool_text VALUES(16,'en','Apothecary Mantle+',NULL,'Increases the probability of triggering status buildup when attacking with weapons that induce abnormal statuses.');
INSERT INTO tool_text VALUES(17,'en','Immunity Mantle+',NULL,'Removes and nullifies all abnormal status effects for the duration of the effect.');
INSERT INTO tool_text VALUES(18,'en','Affinity Booster+',NULL,'Places a smoker that increases affinity.');
INSERT INTO tool_text VALUES(19,'en','Bandit Mantle+',NULL,'Causes monsters to drop rare trade-in items when you attack them.');
INSERT INTO tool_text VALUES(20,'en','Assassin''s Hood+',NULL,'Increases movement speed and allows you to hide quicker. Deals big damage to a monster caught unaware, then the effect ends.');

COMMIT;