BEGIN;

INSERT INTO monster_hitzone_text VALUES(1,'de','Head');
INSERT INTO monster_hitzone_text VALUES(2,'de','Body');
INSERT INTO monster_hitzone_text VALUES(3,'de','Head');
INSERT INTO monster_hitzone_text VALUES(4,'de','Body');
INSERT INTO monster_hitzone_text VALUES(5,'de','Head');
INSERT INTO monster_hitzone_text VALUES(6,'de','Body');
INSERT INTO monster_hitzone_text VALUES(7,'de','Body');
INSERT INTO monster_hitzone_text VALUES(8,'de','Body');
INSERT INTO monster_hitzone_text VALUES(9,'de','Head');
INSERT INTO monster_hitzone_text VALUES(10,'de','Body');
INSERT INTO monster_hitzone_text VALUES(11,'de','Head');
INSERT INTO monster_hitzone_text VALUES(12,'de','Body');
INSERT INTO monster_hitzone_text VALUES(13,'de','Head');
INSERT INTO monster_hitzone_text VALUES(14,'de','Body');
INSERT INTO monster_hitzone_text VALUES(15,'de','Head');
INSERT INTO monster_hitzone_text VALUES(16,'de','Body');
INSERT INTO monster_hitzone_text VALUES(17,'de','Horn');
INSERT INTO monster_hitzone_text VALUES(18,'de','Head / Body');
INSERT INTO monster_hitzone_text VALUES(19,'de','Head');
INSERT INTO monster_hitzone_text VALUES(20,'de','Body');
INSERT INTO monster_hitzone_text VALUES(21,'de','Head');
INSERT INTO monster_hitzone_text VALUES(22,'de','Body');
INSERT INTO monster_hitzone_text VALUES(23,'de','Head');
INSERT INTO monster_hitzone_text VALUES(24,'de','Body');
INSERT INTO monster_hitzone_text VALUES(25,'de','Body');
INSERT INTO monster_hitzone_text VALUES(26,'de','Head');
INSERT INTO monster_hitzone_text VALUES(27,'de','Body');
INSERT INTO monster_hitzone_text VALUES(28,'de','Head');
INSERT INTO monster_hitzone_text VALUES(29,'de','Body');
INSERT INTO monster_hitzone_text VALUES(30,'de','Head');
INSERT INTO monster_hitzone_text VALUES(31,'de','Body');
INSERT INTO monster_hitzone_text VALUES(32,'de','Head');
INSERT INTO monster_hitzone_text VALUES(33,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(34,'de','Body');
INSERT INTO monster_hitzone_text VALUES(35,'de','Stomach (Inflated)');
INSERT INTO monster_hitzone_text VALUES(36,'de','Back');
INSERT INTO monster_hitzone_text VALUES(37,'de','Left Foreleg');
INSERT INTO monster_hitzone_text VALUES(38,'de','Right Foreleg');
INSERT INTO monster_hitzone_text VALUES(39,'de','Left Hindleg');
INSERT INTO monster_hitzone_text VALUES(40,'de','Right Hindleg');
INSERT INTO monster_hitzone_text VALUES(41,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(42,'de','Head');
INSERT INTO monster_hitzone_text VALUES(43,'de','Forearms');
INSERT INTO monster_hitzone_text VALUES(44,'de','Body');
INSERT INTO monster_hitzone_text VALUES(45,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(46,'de','Rock');
INSERT INTO monster_hitzone_text VALUES(47,'de','Head');
INSERT INTO monster_hitzone_text VALUES(48,'de','Head (Red)');
INSERT INTO monster_hitzone_text VALUES(49,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(50,'de','Body');
INSERT INTO monster_hitzone_text VALUES(51,'de','Left Wing');
INSERT INTO monster_hitzone_text VALUES(52,'de','Right Wing');
INSERT INTO monster_hitzone_text VALUES(53,'de','Left Leg');
INSERT INTO monster_hitzone_text VALUES(54,'de','Right Leg');
INSERT INTO monster_hitzone_text VALUES(55,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(56,'de','Head');
INSERT INTO monster_hitzone_text VALUES(57,'de','Head (Mud)');
INSERT INTO monster_hitzone_text VALUES(58,'de','Body');
INSERT INTO monster_hitzone_text VALUES(59,'de','Body (Mud)');
INSERT INTO monster_hitzone_text VALUES(60,'de','Forearms');
INSERT INTO monster_hitzone_text VALUES(61,'de','Forearms (Mud)');
INSERT INTO monster_hitzone_text VALUES(62,'de','Left Hindleg');
INSERT INTO monster_hitzone_text VALUES(63,'de','Left Hindleg (Mud)');
INSERT INTO monster_hitzone_text VALUES(64,'de','Right Hindleg');
INSERT INTO monster_hitzone_text VALUES(65,'de','Right Hindleg (Mud)');
INSERT INTO monster_hitzone_text VALUES(66,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(67,'de','Tail (Mud)');
INSERT INTO monster_hitzone_text VALUES(68,'de','Head');
INSERT INTO monster_hitzone_text VALUES(69,'de','Head (Mud)');
INSERT INTO monster_hitzone_text VALUES(70,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(71,'de','Body');
INSERT INTO monster_hitzone_text VALUES(72,'de','Body (Mud)');
INSERT INTO monster_hitzone_text VALUES(73,'de','Back');
INSERT INTO monster_hitzone_text VALUES(74,'de','Fin');
INSERT INTO monster_hitzone_text VALUES(75,'de','Left Leg');
INSERT INTO monster_hitzone_text VALUES(76,'de','Left Leg (Mud)');
INSERT INTO monster_hitzone_text VALUES(77,'de','Right Leg');
INSERT INTO monster_hitzone_text VALUES(78,'de','Right Leg (Mud)');
INSERT INTO monster_hitzone_text VALUES(79,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(80,'de','Tail (Mud)');
INSERT INTO monster_hitzone_text VALUES(81,'de','Head');
INSERT INTO monster_hitzone_text VALUES(82,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(83,'de','Body');
INSERT INTO monster_hitzone_text VALUES(84,'de','Back');
INSERT INTO monster_hitzone_text VALUES(85,'de','Left Foreleg');
INSERT INTO monster_hitzone_text VALUES(86,'de','Right Foreleg');
INSERT INTO monster_hitzone_text VALUES(87,'de','Left Hindleg');
INSERT INTO monster_hitzone_text VALUES(88,'de','Right Hindleg');
INSERT INTO monster_hitzone_text VALUES(89,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(90,'de','Nose');
INSERT INTO monster_hitzone_text VALUES(91,'de','Head');
INSERT INTO monster_hitzone_text VALUES(92,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(93,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(94,'de','Body');
INSERT INTO monster_hitzone_text VALUES(95,'de','Left Leg');
INSERT INTO monster_hitzone_text VALUES(96,'de','Left Leg (Wounded)');
INSERT INTO monster_hitzone_text VALUES(97,'de','Right Leg');
INSERT INTO monster_hitzone_text VALUES(98,'de','Right Leg (Wounded)');
INSERT INTO monster_hitzone_text VALUES(99,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(100,'de','Head');
INSERT INTO monster_hitzone_text VALUES(101,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(102,'de','Body');
INSERT INTO monster_hitzone_text VALUES(103,'de','Back');
INSERT INTO monster_hitzone_text VALUES(104,'de','Left Wing');
INSERT INTO monster_hitzone_text VALUES(105,'de','Right Wing');
INSERT INTO monster_hitzone_text VALUES(106,'de','Left Leg');
INSERT INTO monster_hitzone_text VALUES(107,'de','Right Leg');
INSERT INTO monster_hitzone_text VALUES(108,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(109,'de','Antennae');
INSERT INTO monster_hitzone_text VALUES(110,'de','Head');
INSERT INTO monster_hitzone_text VALUES(111,'de','Arms');
INSERT INTO monster_hitzone_text VALUES(112,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(113,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(114,'de','Head');
INSERT INTO monster_hitzone_text VALUES(115,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(116,'de','Neck Pouch');
INSERT INTO monster_hitzone_text VALUES(117,'de','Body');
INSERT INTO monster_hitzone_text VALUES(118,'de','Left Leg');
INSERT INTO monster_hitzone_text VALUES(119,'de','Right Leg');
INSERT INTO monster_hitzone_text VALUES(120,'de','Left Wing');
INSERT INTO monster_hitzone_text VALUES(121,'de','Right Wing');
INSERT INTO monster_hitzone_text VALUES(122,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(123,'de','Head');
INSERT INTO monster_hitzone_text VALUES(124,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(125,'de','Body');
INSERT INTO monster_hitzone_text VALUES(126,'de','Back');
INSERT INTO monster_hitzone_text VALUES(127,'de','Left Foreleg');
INSERT INTO monster_hitzone_text VALUES(128,'de','Right Foreleg');
INSERT INTO monster_hitzone_text VALUES(129,'de','Left Hindleg');
INSERT INTO monster_hitzone_text VALUES(130,'de','Right Hindleg');
INSERT INTO monster_hitzone_text VALUES(131,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(132,'de','Head');
INSERT INTO monster_hitzone_text VALUES(133,'de','Head Bone');
INSERT INTO monster_hitzone_text VALUES(134,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(135,'de','Body');
INSERT INTO monster_hitzone_text VALUES(136,'de','Back Bone');
INSERT INTO monster_hitzone_text VALUES(137,'de','Left Hindleg');
INSERT INTO monster_hitzone_text VALUES(138,'de','Left Hindleg Bone');
INSERT INTO monster_hitzone_text VALUES(139,'de','Right Hindleg');
INSERT INTO monster_hitzone_text VALUES(140,'de','Right Hindleg Bone');
INSERT INTO monster_hitzone_text VALUES(141,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(142,'de','Head');
INSERT INTO monster_hitzone_text VALUES(143,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(144,'de','Body');
INSERT INTO monster_hitzone_text VALUES(145,'de','Back');
INSERT INTO monster_hitzone_text VALUES(146,'de','Left Wing');
INSERT INTO monster_hitzone_text VALUES(147,'de','Right Wing');
INSERT INTO monster_hitzone_text VALUES(148,'de','Left Leg');
INSERT INTO monster_hitzone_text VALUES(149,'de','Right Leg');
INSERT INTO monster_hitzone_text VALUES(150,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(151,'de','Head');
INSERT INTO monster_hitzone_text VALUES(152,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(153,'de','Body');
INSERT INTO monster_hitzone_text VALUES(154,'de','Back');
INSERT INTO monster_hitzone_text VALUES(155,'de','Left Foreleg');
INSERT INTO monster_hitzone_text VALUES(156,'de','Right Foreleg');
INSERT INTO monster_hitzone_text VALUES(157,'de','Left Hindleg');
INSERT INTO monster_hitzone_text VALUES(158,'de','Right Hindleg');
INSERT INTO monster_hitzone_text VALUES(159,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(160,'de','Head');
INSERT INTO monster_hitzone_text VALUES(161,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(162,'de','Body');
INSERT INTO monster_hitzone_text VALUES(163,'de','Back');
INSERT INTO monster_hitzone_text VALUES(164,'de','Left Wing');
INSERT INTO monster_hitzone_text VALUES(165,'de','Right Wing');
INSERT INTO monster_hitzone_text VALUES(166,'de','Left Leg');
INSERT INTO monster_hitzone_text VALUES(167,'de','Right Leg');
INSERT INTO monster_hitzone_text VALUES(168,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(169,'de','Horn');
INSERT INTO monster_hitzone_text VALUES(170,'de','Head');
INSERT INTO monster_hitzone_text VALUES(171,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(172,'de','Stomach');
INSERT INTO monster_hitzone_text VALUES(173,'de','Back');
INSERT INTO monster_hitzone_text VALUES(174,'de','Left Wing');
INSERT INTO monster_hitzone_text VALUES(175,'de','Right Wing');
INSERT INTO monster_hitzone_text VALUES(176,'de','Left Leg');
INSERT INTO monster_hitzone_text VALUES(177,'de','Right Leg');
INSERT INTO monster_hitzone_text VALUES(178,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(179,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(180,'de','Head');
INSERT INTO monster_hitzone_text VALUES(181,'de','Body');
INSERT INTO monster_hitzone_text VALUES(182,'de','Body (Electricity)');
INSERT INTO monster_hitzone_text VALUES(183,'de','Lower Body');
INSERT INTO monster_hitzone_text VALUES(184,'de','Lower Body (Electricity)');
INSERT INTO monster_hitzone_text VALUES(185,'de','Head');
INSERT INTO monster_hitzone_text VALUES(186,'de','Body');
INSERT INTO monster_hitzone_text VALUES(187,'de','Chest (Before Wounded)');
INSERT INTO monster_hitzone_text VALUES(188,'de','Chest (After Wounded)');
INSERT INTO monster_hitzone_text VALUES(189,'de','Left Foreleg');
INSERT INTO monster_hitzone_text VALUES(190,'de','Right Foreleg');
INSERT INTO monster_hitzone_text VALUES(191,'de','Left Hindleg');
INSERT INTO monster_hitzone_text VALUES(192,'de','Right Hindleg');
INSERT INTO monster_hitzone_text VALUES(193,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(194,'de','Shell');
INSERT INTO monster_hitzone_text VALUES(195,'de','Exhaust Organ (Crater)');
INSERT INTO monster_hitzone_text VALUES(196,'de','Exhaust Organ (Head)');
INSERT INTO monster_hitzone_text VALUES(197,'de','Exhaust Organ (Central)');
INSERT INTO monster_hitzone_text VALUES(198,'de','Exhaust Organ (Rear)');
INSERT INTO monster_hitzone_text VALUES(199,'de','Left Weak Shell');
INSERT INTO monster_hitzone_text VALUES(200,'de','Right Weak Shell');
INSERT INTO monster_hitzone_text VALUES(201,'de','Head');
INSERT INTO monster_hitzone_text VALUES(202,'de','Head (Rock 1)');
INSERT INTO monster_hitzone_text VALUES(203,'de','Head (Rock 2)');
INSERT INTO monster_hitzone_text VALUES(204,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(205,'de','Neck (Rock 1)');
INSERT INTO monster_hitzone_text VALUES(206,'de','Neck (Rock 2)');
INSERT INTO monster_hitzone_text VALUES(207,'de','Body');
INSERT INTO monster_hitzone_text VALUES(208,'de','Back');
INSERT INTO monster_hitzone_text VALUES(209,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(210,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(211,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(212,'de','Head');
INSERT INTO monster_hitzone_text VALUES(213,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(214,'de','Body');
INSERT INTO monster_hitzone_text VALUES(215,'de','Back');
INSERT INTO monster_hitzone_text VALUES(216,'de','Left Wing');
INSERT INTO monster_hitzone_text VALUES(217,'de','Right Wing');
INSERT INTO monster_hitzone_text VALUES(218,'de','Left Leg');
INSERT INTO monster_hitzone_text VALUES(219,'de','Right Leg');
INSERT INTO monster_hitzone_text VALUES(220,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(221,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(222,'de','Head');
INSERT INTO monster_hitzone_text VALUES(223,'de','Body');
INSERT INTO monster_hitzone_text VALUES(224,'de','Back');
INSERT INTO monster_hitzone_text VALUES(225,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(226,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(227,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(228,'de','Head');
INSERT INTO monster_hitzone_text VALUES(229,'de','Chest');
INSERT INTO monster_hitzone_text VALUES(230,'de','Body');
INSERT INTO monster_hitzone_text VALUES(231,'de','Lower Body');
INSERT INTO monster_hitzone_text VALUES(232,'de','Arms');
INSERT INTO monster_hitzone_text VALUES(233,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(234,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(235,'de','Head (Enraged)');
INSERT INTO monster_hitzone_text VALUES(236,'de','Chest (Enraged)');
INSERT INTO monster_hitzone_text VALUES(237,'de','Body (Enraged)');
INSERT INTO monster_hitzone_text VALUES(238,'de','Lower Body (Enraged)');
INSERT INTO monster_hitzone_text VALUES(239,'de','Arms (Enraged)');
INSERT INTO monster_hitzone_text VALUES(240,'de','Legs (Enraged)');
INSERT INTO monster_hitzone_text VALUES(241,'de','Tail (Enraged)');
INSERT INTO monster_hitzone_text VALUES(242,'de','Head');
INSERT INTO monster_hitzone_text VALUES(243,'de','Head (Wounded)');
INSERT INTO monster_hitzone_text VALUES(244,'de','Head (Molten)');
INSERT INTO monster_hitzone_text VALUES(245,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(246,'de','Body');
INSERT INTO monster_hitzone_text VALUES(247,'de','Back');
INSERT INTO monster_hitzone_text VALUES(248,'de','Back (Wounded)');
INSERT INTO monster_hitzone_text VALUES(249,'de','Back (Molten)');
INSERT INTO monster_hitzone_text VALUES(250,'de','Fins');
INSERT INTO monster_hitzone_text VALUES(251,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(252,'de','Legs (Wounded)');
INSERT INTO monster_hitzone_text VALUES(253,'de','Legs (Molten)');
INSERT INTO monster_hitzone_text VALUES(254,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(255,'de','Tail (Wounded)');
INSERT INTO monster_hitzone_text VALUES(256,'de','Tail (Molten)');
INSERT INTO monster_hitzone_text VALUES(257,'de','Head');
INSERT INTO monster_hitzone_text VALUES(258,'de','Jaw');
INSERT INTO monster_hitzone_text VALUES(259,'de','Jaw (Wounded)');
INSERT INTO monster_hitzone_text VALUES(260,'de','Upper Neck');
INSERT INTO monster_hitzone_text VALUES(261,'de','Lower Neck');
INSERT INTO monster_hitzone_text VALUES(262,'de','Body');
INSERT INTO monster_hitzone_text VALUES(263,'de','Back');
INSERT INTO monster_hitzone_text VALUES(264,'de','Forearms');
INSERT INTO monster_hitzone_text VALUES(265,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(266,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(267,'de','Head');
INSERT INTO monster_hitzone_text VALUES(268,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(269,'de','Body');
INSERT INTO monster_hitzone_text VALUES(270,'de','Back');
INSERT INTO monster_hitzone_text VALUES(271,'de','Left Wing');
INSERT INTO monster_hitzone_text VALUES(272,'de','Right Wing');
INSERT INTO monster_hitzone_text VALUES(273,'de','Left Leg');
INSERT INTO monster_hitzone_text VALUES(274,'de','Right Leg');
INSERT INTO monster_hitzone_text VALUES(275,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(276,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(277,'de','Horn');
INSERT INTO monster_hitzone_text VALUES(278,'de','Head');
INSERT INTO monster_hitzone_text VALUES(279,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(280,'de','Stomach');
INSERT INTO monster_hitzone_text VALUES(281,'de','Back');
INSERT INTO monster_hitzone_text VALUES(282,'de','Left Wing');
INSERT INTO monster_hitzone_text VALUES(283,'de','Right Wing');
INSERT INTO monster_hitzone_text VALUES(284,'de','Left Leg');
INSERT INTO monster_hitzone_text VALUES(285,'de','Right Leg');
INSERT INTO monster_hitzone_text VALUES(286,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(287,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(288,'de','Horn');
INSERT INTO monster_hitzone_text VALUES(289,'de','Horn (Wounded)');
INSERT INTO monster_hitzone_text VALUES(290,'de','Head');
INSERT INTO monster_hitzone_text VALUES(291,'de','Head (White)');
INSERT INTO monster_hitzone_text VALUES(292,'de','Head (Black)');
INSERT INTO monster_hitzone_text VALUES(293,'de','Head (Gloss Black)');
INSERT INTO monster_hitzone_text VALUES(294,'de','Body');
INSERT INTO monster_hitzone_text VALUES(295,'de','Back');
INSERT INTO monster_hitzone_text VALUES(296,'de','Forearms');
INSERT INTO monster_hitzone_text VALUES(297,'de','Forearms (White)');
INSERT INTO monster_hitzone_text VALUES(298,'de','Forearms (Black)');
INSERT INTO monster_hitzone_text VALUES(299,'de','Forearms (Gloss Black)');
INSERT INTO monster_hitzone_text VALUES(300,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(301,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(302,'de','Wings (White)');
INSERT INTO monster_hitzone_text VALUES(303,'de','Wings (Black)');
INSERT INTO monster_hitzone_text VALUES(304,'de','Wings (Gloss Black)');
INSERT INTO monster_hitzone_text VALUES(305,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(306,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(307,'de','Tail Tip (White)');
INSERT INTO monster_hitzone_text VALUES(308,'de','Tail Tip (Black)');
INSERT INTO monster_hitzone_text VALUES(309,'de','Tail Tip (Gloss Black)');
INSERT INTO monster_hitzone_text VALUES(310,'de','Head');
INSERT INTO monster_hitzone_text VALUES(311,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(312,'de','Body');
INSERT INTO monster_hitzone_text VALUES(313,'de','Back');
INSERT INTO monster_hitzone_text VALUES(314,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(315,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(316,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(317,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(318,'de','Head');
INSERT INTO monster_hitzone_text VALUES(319,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(320,'de','Chest');
INSERT INTO monster_hitzone_text VALUES(321,'de','Back');
INSERT INTO monster_hitzone_text VALUES(322,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(323,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(324,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(325,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(326,'de','Head');
INSERT INTO monster_hitzone_text VALUES(327,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(328,'de','Body');
INSERT INTO monster_hitzone_text VALUES(329,'de','Back');
INSERT INTO monster_hitzone_text VALUES(330,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(331,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(332,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(333,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(334,'de','Head');
INSERT INTO monster_hitzone_text VALUES(335,'de','Head (Wounded)');
INSERT INTO monster_hitzone_text VALUES(336,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(337,'de','Chest');
INSERT INTO monster_hitzone_text VALUES(338,'de','Stomach');
INSERT INTO monster_hitzone_text VALUES(339,'de','Stomach (Wounded)');
INSERT INTO monster_hitzone_text VALUES(340,'de','Back');
INSERT INTO monster_hitzone_text VALUES(341,'de','Back (Wounded)');
INSERT INTO monster_hitzone_text VALUES(342,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(343,'de','Forelegs (Wounded)');
INSERT INTO monster_hitzone_text VALUES(344,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(345,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(346,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(347,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(348,'de','Head');
INSERT INTO monster_hitzone_text VALUES(349,'de','Chest');
INSERT INTO monster_hitzone_text VALUES(350,'de','Torso');
INSERT INTO monster_hitzone_text VALUES(351,'de','Body / Forelimb / Tail');
INSERT INTO monster_hitzone_text VALUES(352,'de','Hind Legs');
INSERT INTO monster_hitzone_text VALUES(353,'de','Head (Molten)');
INSERT INTO monster_hitzone_text VALUES(354,'de','Body / Forelimb / Tail (Molten)');
INSERT INTO monster_hitzone_text VALUES(355,'de','Head (Exposed)');
INSERT INTO monster_hitzone_text VALUES(356,'de','Forelimbs (Exposed)');
INSERT INTO monster_hitzone_text VALUES(357,'de','Tail (Exposed)');
INSERT INTO monster_hitzone_text VALUES(358,'de','Head');
INSERT INTO monster_hitzone_text VALUES(359,'de','Head (Wounded)');
INSERT INTO monster_hitzone_text VALUES(360,'de','Head (Critical State)');
INSERT INTO monster_hitzone_text VALUES(361,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(362,'de','Neck (Critical State)');
INSERT INTO monster_hitzone_text VALUES(363,'de','Body');
INSERT INTO monster_hitzone_text VALUES(364,'de','Body (Critical State)');
INSERT INTO monster_hitzone_text VALUES(365,'de','Chest');
INSERT INTO monster_hitzone_text VALUES(366,'de','Chest (Critical State)');
INSERT INTO monster_hitzone_text VALUES(367,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(368,'de','Forelegs (Wounded)');
INSERT INTO monster_hitzone_text VALUES(369,'de','Forelegs (Critical State)');
INSERT INTO monster_hitzone_text VALUES(370,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(371,'de','Hindlegs (Critical State)');
INSERT INTO monster_hitzone_text VALUES(372,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(373,'de','Wings (Wounded)');
INSERT INTO monster_hitzone_text VALUES(374,'de','Wings (Critical State)');
INSERT INTO monster_hitzone_text VALUES(375,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(376,'de','Tail (Critical State)');
INSERT INTO monster_hitzone_text VALUES(377,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(378,'de','Tail Tip (Critical State)');
INSERT INTO monster_hitzone_text VALUES(379,'de','Head');
INSERT INTO monster_hitzone_text VALUES(380,'de','Head (Snow)');
INSERT INTO monster_hitzone_text VALUES(381,'de','Body/Back');
INSERT INTO monster_hitzone_text VALUES(382,'de','Body/Back (Snow)');
INSERT INTO monster_hitzone_text VALUES(383,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(384,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(385,'de','Tail (Snow)');
INSERT INTO monster_hitzone_text VALUES(386,'de','Horns');
INSERT INTO monster_hitzone_text VALUES(387,'de','Horns (Broken)');
INSERT INTO monster_hitzone_text VALUES(388,'de','Head');
INSERT INTO monster_hitzone_text VALUES(389,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(390,'de','Body');
INSERT INTO monster_hitzone_text VALUES(391,'de','Forearms');
INSERT INTO monster_hitzone_text VALUES(392,'de','Hind Legs');
INSERT INTO monster_hitzone_text VALUES(393,'de','Hind Legs (Broken)');
INSERT INTO monster_hitzone_text VALUES(394,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(395,'de','Head');
INSERT INTO monster_hitzone_text VALUES(396,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(397,'de','Body');
INSERT INTO monster_hitzone_text VALUES(398,'de','Mane');
INSERT INTO monster_hitzone_text VALUES(399,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(400,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(401,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(402,'de','Head');
INSERT INTO monster_hitzone_text VALUES(403,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(404,'de','Neck Pouch');
INSERT INTO monster_hitzone_text VALUES(405,'de','Body');
INSERT INTO monster_hitzone_text VALUES(406,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(407,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(408,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(409,'de','Head');
INSERT INTO monster_hitzone_text VALUES(410,'de','Body');
INSERT INTO monster_hitzone_text VALUES(411,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(412,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(413,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(414,'de','Head');
INSERT INTO monster_hitzone_text VALUES(415,'de','Neck/Back');
INSERT INTO monster_hitzone_text VALUES(416,'de','Belly');
INSERT INTO monster_hitzone_text VALUES(417,'de','Claws');
INSERT INTO monster_hitzone_text VALUES(418,'de','Claws (Broken)');
INSERT INTO monster_hitzone_text VALUES(419,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(420,'de','Front Legs');
INSERT INTO monster_hitzone_text VALUES(421,'de','Hind Legs');
INSERT INTO monster_hitzone_text VALUES(422,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(423,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(424,'de','Head');
INSERT INTO monster_hitzone_text VALUES(425,'de','Neck/Back');
INSERT INTO monster_hitzone_text VALUES(426,'de','Belly');
INSERT INTO monster_hitzone_text VALUES(427,'de','Front Legs');
INSERT INTO monster_hitzone_text VALUES(428,'de','Front Legs (Broken)');
INSERT INTO monster_hitzone_text VALUES(429,'de','Hind Legs');
INSERT INTO monster_hitzone_text VALUES(430,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(431,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(432,'de','Head');
INSERT INTO monster_hitzone_text VALUES(433,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(434,'de','Throat');
INSERT INTO monster_hitzone_text VALUES(435,'de','Back');
INSERT INTO monster_hitzone_text VALUES(436,'de','Body');
INSERT INTO monster_hitzone_text VALUES(437,'de','Forearms');
INSERT INTO monster_hitzone_text VALUES(438,'de','Hind Legs');
INSERT INTO monster_hitzone_text VALUES(439,'de','Tail Base');
INSERT INTO monster_hitzone_text VALUES(440,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(441,'de','Tail (Rusted)');
INSERT INTO monster_hitzone_text VALUES(442,'de','Tail (Heated)');
INSERT INTO monster_hitzone_text VALUES(443,'de','Head');
INSERT INTO monster_hitzone_text VALUES(444,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(445,'de','Belly');
INSERT INTO monster_hitzone_text VALUES(446,'de','Back');
INSERT INTO monster_hitzone_text VALUES(447,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(448,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(449,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(450,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(451,'de','Head');
INSERT INTO monster_hitzone_text VALUES(452,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(453,'de','Body');
INSERT INTO monster_hitzone_text VALUES(454,'de','Forearms');
INSERT INTO monster_hitzone_text VALUES(455,'de','Hind Legs');
INSERT INTO monster_hitzone_text VALUES(456,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(457,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(458,'de','Head');
INSERT INTO monster_hitzone_text VALUES(459,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(460,'de','Body');
INSERT INTO monster_hitzone_text VALUES(461,'de','Back');
INSERT INTO monster_hitzone_text VALUES(462,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(463,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(464,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(465,'de','Nose');
INSERT INTO monster_hitzone_text VALUES(466,'de','Nose (Charged)');
INSERT INTO monster_hitzone_text VALUES(467,'de','Head');
INSERT INTO monster_hitzone_text VALUES(468,'de','Head (Charged)');
INSERT INTO monster_hitzone_text VALUES(469,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(470,'de','Neck (Charged)');
INSERT INTO monster_hitzone_text VALUES(471,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(472,'de','Wings (Charged)');
INSERT INTO monster_hitzone_text VALUES(473,'de','Body');
INSERT INTO monster_hitzone_text VALUES(474,'de','Body (Charged)');
INSERT INTO monster_hitzone_text VALUES(475,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(476,'de','Legs (Charged)');
INSERT INTO monster_hitzone_text VALUES(477,'de','Legs (Broken)');
INSERT INTO monster_hitzone_text VALUES(478,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(479,'de','Tail (Charged)');
INSERT INTO monster_hitzone_text VALUES(480,'de','Tail (Broken)');
INSERT INTO monster_hitzone_text VALUES(481,'de','Head');
INSERT INTO monster_hitzone_text VALUES(482,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(483,'de','Throat');
INSERT INTO monster_hitzone_text VALUES(484,'de','Back');
INSERT INTO monster_hitzone_text VALUES(485,'de','Body');
INSERT INTO monster_hitzone_text VALUES(486,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(487,'de','Hind Legs');
INSERT INTO monster_hitzone_text VALUES(488,'de','Tail Base');
INSERT INTO monster_hitzone_text VALUES(489,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(490,'de','Tail (Crystal)');
INSERT INTO monster_hitzone_text VALUES(491,'de','Tail (Sharpened)');
INSERT INTO monster_hitzone_text VALUES(492,'de','Head');
INSERT INTO monster_hitzone_text VALUES(493,'de','Head (Broken)');
INSERT INTO monster_hitzone_text VALUES(494,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(495,'de','Body');
INSERT INTO monster_hitzone_text VALUES(496,'de','Back');
INSERT INTO monster_hitzone_text VALUES(497,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(498,'de','Forelegs (Broken)');
INSERT INTO monster_hitzone_text VALUES(499,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(500,'de','Hindlegs (Broken)');
INSERT INTO monster_hitzone_text VALUES(501,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(502,'de','Tail (Broken)');
INSERT INTO monster_hitzone_text VALUES(503,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(504,'de','Head');
INSERT INTO monster_hitzone_text VALUES(505,'de','Head (Broken)');
INSERT INTO monster_hitzone_text VALUES(506,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(507,'de','Neck (Broken)');
INSERT INTO monster_hitzone_text VALUES(508,'de','Body');
INSERT INTO monster_hitzone_text VALUES(509,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(510,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(511,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(512,'de','Wings (Broken)');
INSERT INTO monster_hitzone_text VALUES(513,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(514,'de','Tail (Broken)');
INSERT INTO monster_hitzone_text VALUES(515,'de','Head');
INSERT INTO monster_hitzone_text VALUES(516,'de','Body');
INSERT INTO monster_hitzone_text VALUES(517,'de','Back');
INSERT INTO monster_hitzone_text VALUES(518,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(519,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(520,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(521,'de','Head');
INSERT INTO monster_hitzone_text VALUES(522,'de','Head (Broken)');
INSERT INTO monster_hitzone_text VALUES(523,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(524,'de','Chest');
INSERT INTO monster_hitzone_text VALUES(525,'de','Chest (Spore Sac)');
INSERT INTO monster_hitzone_text VALUES(526,'de','Stomach');
INSERT INTO monster_hitzone_text VALUES(527,'de','Stomach (Broken)');
INSERT INTO monster_hitzone_text VALUES(528,'de','Back');
INSERT INTO monster_hitzone_text VALUES(529,'de','Back (Broken)');
INSERT INTO monster_hitzone_text VALUES(530,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(531,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(532,'de','Forelegs (Broken)');
INSERT INTO monster_hitzone_text VALUES(533,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(534,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(535,'de','Tail (Spore Sac)');
INSERT INTO monster_hitzone_text VALUES(536,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(537,'de','Head');
INSERT INTO monster_hitzone_text VALUES(538,'de','Head (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(539,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(540,'de','Neck (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(541,'de','Back');
INSERT INTO monster_hitzone_text VALUES(542,'de','Back (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(543,'de','Stomach');
INSERT INTO monster_hitzone_text VALUES(544,'de','Stomach (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(545,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(546,'de','Forelegs (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(547,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(548,'de','Hindlegs (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(549,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(550,'de','Wings (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(551,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(552,'de','Tail (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(553,'de','Head');
INSERT INTO monster_hitzone_text VALUES(554,'de','Head (Broken)');
INSERT INTO monster_hitzone_text VALUES(555,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(556,'de','Chest');
INSERT INTO monster_hitzone_text VALUES(557,'de','Chest (Broken)');
INSERT INTO monster_hitzone_text VALUES(558,'de','Torso');
INSERT INTO monster_hitzone_text VALUES(559,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(560,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(561,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(562,'de','Tail (Broken)');
INSERT INTO monster_hitzone_text VALUES(563,'de','Horn');
INSERT INTO monster_hitzone_text VALUES(564,'de','Horn (Broken)');
INSERT INTO monster_hitzone_text VALUES(565,'de','Head');
INSERT INTO monster_hitzone_text VALUES(566,'de','Head (White)');
INSERT INTO monster_hitzone_text VALUES(567,'de','Head (Black)');
INSERT INTO monster_hitzone_text VALUES(568,'de','Body');
INSERT INTO monster_hitzone_text VALUES(569,'de','Back');
INSERT INTO monster_hitzone_text VALUES(570,'de','Forearms');
INSERT INTO monster_hitzone_text VALUES(571,'de','Forearms (White)');
INSERT INTO monster_hitzone_text VALUES(572,'de','Forearms (Black)');
INSERT INTO monster_hitzone_text VALUES(573,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(574,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(575,'de','Wings (White)');
INSERT INTO monster_hitzone_text VALUES(576,'de','Wings (Black)');
INSERT INTO monster_hitzone_text VALUES(577,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(578,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(579,'de','Tail Tip (White)');
INSERT INTO monster_hitzone_text VALUES(580,'de','Tail Tip (Black)');
INSERT INTO monster_hitzone_text VALUES(581,'de','Head');
INSERT INTO monster_hitzone_text VALUES(582,'de','Head Casing (Top)');
INSERT INTO monster_hitzone_text VALUES(583,'de','Head Casing (Bottom)');
INSERT INTO monster_hitzone_text VALUES(584,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(585,'de','Wings (Broken)');
INSERT INTO monster_hitzone_text VALUES(586,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(587,'de','Forelegs (Broken)');
INSERT INTO monster_hitzone_text VALUES(588,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(589,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(590,'de','Head (Released)');
INSERT INTO monster_hitzone_text VALUES(591,'de','Body (Released)');
INSERT INTO monster_hitzone_text VALUES(592,'de','Wings (Released)');
INSERT INTO monster_hitzone_text VALUES(593,'de','Forelegs (Released)');
INSERT INTO monster_hitzone_text VALUES(594,'de','Hindlegs (Released)');
INSERT INTO monster_hitzone_text VALUES(595,'de','Tail (Released)');
INSERT INTO monster_hitzone_text VALUES(596,'de','Head');
INSERT INTO monster_hitzone_text VALUES(597,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(598,'de','Body');
INSERT INTO monster_hitzone_text VALUES(599,'de','Back');
INSERT INTO monster_hitzone_text VALUES(600,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(601,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(602,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(603,'de','Head (Charged)');
INSERT INTO monster_hitzone_text VALUES(604,'de','Neck (Charged)');
INSERT INTO monster_hitzone_text VALUES(605,'de','Body (Charged)');
INSERT INTO monster_hitzone_text VALUES(606,'de','Back (Charged)');
INSERT INTO monster_hitzone_text VALUES(607,'de','Forelegs (Charged)');
INSERT INTO monster_hitzone_text VALUES(608,'de','Hindlegs (Charged)');
INSERT INTO monster_hitzone_text VALUES(609,'de','Tail (Charged)');
INSERT INTO monster_hitzone_text VALUES(610,'de','Ears');
INSERT INTO monster_hitzone_text VALUES(611,'de','Head');
INSERT INTO monster_hitzone_text VALUES(612,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(613,'de','Back');
INSERT INTO monster_hitzone_text VALUES(614,'de','Belly');
INSERT INTO monster_hitzone_text VALUES(615,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(616,'de','Wings (Broken)');
INSERT INTO monster_hitzone_text VALUES(617,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(618,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(619,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(620,'de','Ears');
INSERT INTO monster_hitzone_text VALUES(621,'de','Head');
INSERT INTO monster_hitzone_text VALUES(622,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(623,'de','Back');
INSERT INTO monster_hitzone_text VALUES(624,'de','Belly');
INSERT INTO monster_hitzone_text VALUES(625,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(626,'de','Wings (Broken)');
INSERT INTO monster_hitzone_text VALUES(627,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(628,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(629,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(630,'de','Head');
INSERT INTO monster_hitzone_text VALUES(631,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(632,'de','Belly');
INSERT INTO monster_hitzone_text VALUES(633,'de','Back');
INSERT INTO monster_hitzone_text VALUES(634,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(635,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(636,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(637,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(638,'de','Head');
INSERT INTO monster_hitzone_text VALUES(639,'de','Head (Broken)');
INSERT INTO monster_hitzone_text VALUES(640,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(641,'de','Neck (Broken)');
INSERT INTO monster_hitzone_text VALUES(642,'de','Body');
INSERT INTO monster_hitzone_text VALUES(643,'de','Back');
INSERT INTO monster_hitzone_text VALUES(644,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(645,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(646,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(647,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(648,'de','Head');
INSERT INTO monster_hitzone_text VALUES(649,'de','Head (Broken)');
INSERT INTO monster_hitzone_text VALUES(650,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(651,'de','Neck (Broken)');
INSERT INTO monster_hitzone_text VALUES(652,'de','Body');
INSERT INTO monster_hitzone_text VALUES(653,'de','Back');
INSERT INTO monster_hitzone_text VALUES(654,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(655,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(656,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(657,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(658,'de','Head');
INSERT INTO monster_hitzone_text VALUES(659,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(660,'de','Forelegs (Charged)');
INSERT INTO monster_hitzone_text VALUES(661,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(662,'de','Body');
INSERT INTO monster_hitzone_text VALUES(663,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(664,'de','Tail (Charged)');
INSERT INTO monster_hitzone_text VALUES(665,'de','Head');
INSERT INTO monster_hitzone_text VALUES(666,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(667,'de','Body');
INSERT INTO monster_hitzone_text VALUES(668,'de','Back');
INSERT INTO monster_hitzone_text VALUES(669,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(670,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(671,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(672,'de','Head (Charged)');
INSERT INTO monster_hitzone_text VALUES(673,'de','Neck (Charged)');
INSERT INTO monster_hitzone_text VALUES(674,'de','Body (Charged)');
INSERT INTO monster_hitzone_text VALUES(675,'de','Back (Charged)');
INSERT INTO monster_hitzone_text VALUES(676,'de','Forelegs (Charged)');
INSERT INTO monster_hitzone_text VALUES(677,'de','Hindlegs (Charged)');
INSERT INTO monster_hitzone_text VALUES(678,'de','Tail (Charged)');
INSERT INTO monster_hitzone_text VALUES(679,'de','Head');
INSERT INTO monster_hitzone_text VALUES(680,'de','Back');
INSERT INTO monster_hitzone_text VALUES(681,'de','Stomach');
INSERT INTO monster_hitzone_text VALUES(682,'de','Claws');
INSERT INTO monster_hitzone_text VALUES(683,'de','Claws (Broken)');
INSERT INTO monster_hitzone_text VALUES(684,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(685,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(686,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(687,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(688,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(689,'de','Head');
INSERT INTO monster_hitzone_text VALUES(690,'de','Head (Broken)');
INSERT INTO monster_hitzone_text VALUES(691,'de','Head (SCritical)');
INSERT INTO monster_hitzone_text VALUES(692,'de','Head (Broken+SCritical)');
INSERT INTO monster_hitzone_text VALUES(693,'de','Snout');
INSERT INTO monster_hitzone_text VALUES(694,'de','Snout (Broken)');
INSERT INTO monster_hitzone_text VALUES(695,'de','Snout (SCritical)');
INSERT INTO monster_hitzone_text VALUES(696,'de','Snout (Broken+SCritical)');
INSERT INTO monster_hitzone_text VALUES(697,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(698,'de','Neck (SCritical)');
INSERT INTO monster_hitzone_text VALUES(699,'de','Body');
INSERT INTO monster_hitzone_text VALUES(700,'de','Body (SCritical)');
INSERT INTO monster_hitzone_text VALUES(701,'de','Back');
INSERT INTO monster_hitzone_text VALUES(702,'de','Back (SCritical)');
INSERT INTO monster_hitzone_text VALUES(703,'de','Chest');
INSERT INTO monster_hitzone_text VALUES(704,'de','Chest (SCritical)');
INSERT INTO monster_hitzone_text VALUES(705,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(706,'de','Forelegs (SCritical)');
INSERT INTO monster_hitzone_text VALUES(707,'de','Forefeet');
INSERT INTO monster_hitzone_text VALUES(708,'de','Forefeet (SCritical)');
INSERT INTO monster_hitzone_text VALUES(709,'de','Foreleg+Feet (Broken)');
INSERT INTO monster_hitzone_text VALUES(710,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(711,'de','Hindlegs (SCritical)');
INSERT INTO monster_hitzone_text VALUES(712,'de','Hindfeet');
INSERT INTO monster_hitzone_text VALUES(713,'de','Hindfeet (SCritical)');
INSERT INTO monster_hitzone_text VALUES(714,'de','Hindleg+Feet (Broken)');
INSERT INTO monster_hitzone_text VALUES(715,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(716,'de','Wings (SCritical)');
INSERT INTO monster_hitzone_text VALUES(717,'de','Wing Tips');
INSERT INTO monster_hitzone_text VALUES(718,'de','Wing Tips (SCritical)');
INSERT INTO monster_hitzone_text VALUES(719,'de','Webbing');
INSERT INTO monster_hitzone_text VALUES(720,'de','Webbing (SCritical)');
INSERT INTO monster_hitzone_text VALUES(721,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(722,'de','Tail (SCritical)');
INSERT INTO monster_hitzone_text VALUES(723,'de','Upper Tail');
INSERT INTO monster_hitzone_text VALUES(724,'de','Upper Tail (SCritical)');
INSERT INTO monster_hitzone_text VALUES(725,'de','Head');
INSERT INTO monster_hitzone_text VALUES(726,'de','Head (Rampage)');
INSERT INTO monster_hitzone_text VALUES(727,'de','Body');
INSERT INTO monster_hitzone_text VALUES(728,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(729,'de','Forelegs (Rampage)');
INSERT INTO monster_hitzone_text VALUES(730,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(731,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(732,'de','Tail (Rampage)');
INSERT INTO monster_hitzone_text VALUES(733,'de','Horns');
INSERT INTO monster_hitzone_text VALUES(734,'de','Horns (Red Slime)');
INSERT INTO monster_hitzone_text VALUES(735,'de','Head');
INSERT INTO monster_hitzone_text VALUES(736,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(737,'de','Body');
INSERT INTO monster_hitzone_text VALUES(738,'de','Forearms');
INSERT INTO monster_hitzone_text VALUES(739,'de','Forearms (Red Slime)');
INSERT INTO monster_hitzone_text VALUES(740,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(741,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(742,'de','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(743,'de','Tail Tip (Red Slime)');
INSERT INTO monster_hitzone_text VALUES(744,'de','Head (Fire)');
INSERT INTO monster_hitzone_text VALUES(745,'de','Neck (Fire)');
INSERT INTO monster_hitzone_text VALUES(746,'de','Body (Fire)');
INSERT INTO monster_hitzone_text VALUES(747,'de','Wings (Fire)');
INSERT INTO monster_hitzone_text VALUES(748,'de','Arms (Fire)');
INSERT INTO monster_hitzone_text VALUES(749,'de','Legs (Fire)');
INSERT INTO monster_hitzone_text VALUES(750,'de','Tail (Fire)');
INSERT INTO monster_hitzone_text VALUES(751,'de','Head (Ice)');
INSERT INTO monster_hitzone_text VALUES(752,'de','Neck (Ice)');
INSERT INTO monster_hitzone_text VALUES(753,'de','Body (Ice)');
INSERT INTO monster_hitzone_text VALUES(754,'de','Wings (Ice)');
INSERT INTO monster_hitzone_text VALUES(755,'de','Arms (Ice)');
INSERT INTO monster_hitzone_text VALUES(756,'de','Legs (Ice)');
INSERT INTO monster_hitzone_text VALUES(757,'de','Tail (Ice)');
INSERT INTO monster_hitzone_text VALUES(758,'de','Head (Dragon)');
INSERT INTO monster_hitzone_text VALUES(759,'de','Neck (Dragon)');
INSERT INTO monster_hitzone_text VALUES(760,'de','Body (Dragon)');
INSERT INTO monster_hitzone_text VALUES(761,'de','Wings (Dragon)');
INSERT INTO monster_hitzone_text VALUES(762,'de','Arms (Dragon)');
INSERT INTO monster_hitzone_text VALUES(763,'de','Legs (Dragon)');
INSERT INTO monster_hitzone_text VALUES(764,'de','Tail (Dragon)');
INSERT INTO monster_hitzone_text VALUES(765,'de','Head');
INSERT INTO monster_hitzone_text VALUES(766,'de','Neck');
INSERT INTO monster_hitzone_text VALUES(767,'de','Chest');
INSERT INTO monster_hitzone_text VALUES(768,'de','Back');
INSERT INTO monster_hitzone_text VALUES(769,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(770,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(771,'de','Wings');
INSERT INTO monster_hitzone_text VALUES(772,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(773,'de','Chest (Critical State)');
INSERT INTO monster_hitzone_text VALUES(774,'de','Horns');
INSERT INTO monster_hitzone_text VALUES(775,'de','Horns (Broken)');
INSERT INTO monster_hitzone_text VALUES(776,'de','Head');
INSERT INTO monster_hitzone_text VALUES(777,'de','Forelegs');
INSERT INTO monster_hitzone_text VALUES(778,'de','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(779,'de','Tail');
INSERT INTO monster_hitzone_text VALUES(780,'de','Behind');
INSERT INTO monster_hitzone_text VALUES(781,'de','Head');
INSERT INTO monster_hitzone_text VALUES(782,'de','Torso');
INSERT INTO monster_hitzone_text VALUES(783,'de','Arms');
INSERT INTO monster_hitzone_text VALUES(784,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(785,'de','Head');
INSERT INTO monster_hitzone_text VALUES(786,'de','Torso');
INSERT INTO monster_hitzone_text VALUES(787,'de','Arms');
INSERT INTO monster_hitzone_text VALUES(788,'de','Legs');
INSERT INTO monster_hitzone_text VALUES(1,'en','Head');
INSERT INTO monster_hitzone_text VALUES(2,'en','Body');
INSERT INTO monster_hitzone_text VALUES(3,'en','Head');
INSERT INTO monster_hitzone_text VALUES(4,'en','Body');
INSERT INTO monster_hitzone_text VALUES(5,'en','Head');
INSERT INTO monster_hitzone_text VALUES(6,'en','Body');
INSERT INTO monster_hitzone_text VALUES(7,'en','Body');
INSERT INTO monster_hitzone_text VALUES(8,'en','Body');
INSERT INTO monster_hitzone_text VALUES(9,'en','Head');
INSERT INTO monster_hitzone_text VALUES(10,'en','Body');
INSERT INTO monster_hitzone_text VALUES(11,'en','Head');
INSERT INTO monster_hitzone_text VALUES(12,'en','Body');
INSERT INTO monster_hitzone_text VALUES(13,'en','Head');
INSERT INTO monster_hitzone_text VALUES(14,'en','Body');
INSERT INTO monster_hitzone_text VALUES(15,'en','Head');
INSERT INTO monster_hitzone_text VALUES(16,'en','Body');
INSERT INTO monster_hitzone_text VALUES(17,'en','Horn');
INSERT INTO monster_hitzone_text VALUES(18,'en','Head / Body');
INSERT INTO monster_hitzone_text VALUES(19,'en','Head');
INSERT INTO monster_hitzone_text VALUES(20,'en','Body');
INSERT INTO monster_hitzone_text VALUES(21,'en','Head');
INSERT INTO monster_hitzone_text VALUES(22,'en','Body');
INSERT INTO monster_hitzone_text VALUES(23,'en','Head');
INSERT INTO monster_hitzone_text VALUES(24,'en','Body');
INSERT INTO monster_hitzone_text VALUES(25,'en','Body');
INSERT INTO monster_hitzone_text VALUES(26,'en','Head');
INSERT INTO monster_hitzone_text VALUES(27,'en','Body');
INSERT INTO monster_hitzone_text VALUES(28,'en','Head');
INSERT INTO monster_hitzone_text VALUES(29,'en','Body');
INSERT INTO monster_hitzone_text VALUES(30,'en','Head');
INSERT INTO monster_hitzone_text VALUES(31,'en','Body');
INSERT INTO monster_hitzone_text VALUES(32,'en','Head');
INSERT INTO monster_hitzone_text VALUES(33,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(34,'en','Body');
INSERT INTO monster_hitzone_text VALUES(35,'en','Stomach (Inflated)');
INSERT INTO monster_hitzone_text VALUES(36,'en','Back');
INSERT INTO monster_hitzone_text VALUES(37,'en','Left Foreleg');
INSERT INTO monster_hitzone_text VALUES(38,'en','Right Foreleg');
INSERT INTO monster_hitzone_text VALUES(39,'en','Left Hindleg');
INSERT INTO monster_hitzone_text VALUES(40,'en','Right Hindleg');
INSERT INTO monster_hitzone_text VALUES(41,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(42,'en','Head');
INSERT INTO monster_hitzone_text VALUES(43,'en','Forearms');
INSERT INTO monster_hitzone_text VALUES(44,'en','Body');
INSERT INTO monster_hitzone_text VALUES(45,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(46,'en','Rock');
INSERT INTO monster_hitzone_text VALUES(47,'en','Head');
INSERT INTO monster_hitzone_text VALUES(48,'en','Head (Red)');
INSERT INTO monster_hitzone_text VALUES(49,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(50,'en','Body');
INSERT INTO monster_hitzone_text VALUES(51,'en','Left Wing');
INSERT INTO monster_hitzone_text VALUES(52,'en','Right Wing');
INSERT INTO monster_hitzone_text VALUES(53,'en','Left Leg');
INSERT INTO monster_hitzone_text VALUES(54,'en','Right Leg');
INSERT INTO monster_hitzone_text VALUES(55,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(56,'en','Head');
INSERT INTO monster_hitzone_text VALUES(57,'en','Head (Mud)');
INSERT INTO monster_hitzone_text VALUES(58,'en','Body');
INSERT INTO monster_hitzone_text VALUES(59,'en','Body (Mud)');
INSERT INTO monster_hitzone_text VALUES(60,'en','Forearms');
INSERT INTO monster_hitzone_text VALUES(61,'en','Forearms (Mud)');
INSERT INTO monster_hitzone_text VALUES(62,'en','Left Hindleg');
INSERT INTO monster_hitzone_text VALUES(63,'en','Left Hindleg (Mud)');
INSERT INTO monster_hitzone_text VALUES(64,'en','Right Hindleg');
INSERT INTO monster_hitzone_text VALUES(65,'en','Right Hindleg (Mud)');
INSERT INTO monster_hitzone_text VALUES(66,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(67,'en','Tail (Mud)');
INSERT INTO monster_hitzone_text VALUES(68,'en','Head');
INSERT INTO monster_hitzone_text VALUES(69,'en','Head (Mud)');
INSERT INTO monster_hitzone_text VALUES(70,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(71,'en','Body');
INSERT INTO monster_hitzone_text VALUES(72,'en','Body (Mud)');
INSERT INTO monster_hitzone_text VALUES(73,'en','Back');
INSERT INTO monster_hitzone_text VALUES(74,'en','Fin');
INSERT INTO monster_hitzone_text VALUES(75,'en','Left Leg');
INSERT INTO monster_hitzone_text VALUES(76,'en','Left Leg (Mud)');
INSERT INTO monster_hitzone_text VALUES(77,'en','Right Leg');
INSERT INTO monster_hitzone_text VALUES(78,'en','Right Leg (Mud)');
INSERT INTO monster_hitzone_text VALUES(79,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(80,'en','Tail (Mud)');
INSERT INTO monster_hitzone_text VALUES(81,'en','Head');
INSERT INTO monster_hitzone_text VALUES(82,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(83,'en','Body');
INSERT INTO monster_hitzone_text VALUES(84,'en','Back');
INSERT INTO monster_hitzone_text VALUES(85,'en','Left Foreleg');
INSERT INTO monster_hitzone_text VALUES(86,'en','Right Foreleg');
INSERT INTO monster_hitzone_text VALUES(87,'en','Left Hindleg');
INSERT INTO monster_hitzone_text VALUES(88,'en','Right Hindleg');
INSERT INTO monster_hitzone_text VALUES(89,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(90,'en','Nose');
INSERT INTO monster_hitzone_text VALUES(91,'en','Head');
INSERT INTO monster_hitzone_text VALUES(92,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(93,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(94,'en','Body');
INSERT INTO monster_hitzone_text VALUES(95,'en','Left Leg');
INSERT INTO monster_hitzone_text VALUES(96,'en','Left Leg (Wounded)');
INSERT INTO monster_hitzone_text VALUES(97,'en','Right Leg');
INSERT INTO monster_hitzone_text VALUES(98,'en','Right Leg (Wounded)');
INSERT INTO monster_hitzone_text VALUES(99,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(100,'en','Head');
INSERT INTO monster_hitzone_text VALUES(101,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(102,'en','Body');
INSERT INTO monster_hitzone_text VALUES(103,'en','Back');
INSERT INTO monster_hitzone_text VALUES(104,'en','Left Wing');
INSERT INTO monster_hitzone_text VALUES(105,'en','Right Wing');
INSERT INTO monster_hitzone_text VALUES(106,'en','Left Leg');
INSERT INTO monster_hitzone_text VALUES(107,'en','Right Leg');
INSERT INTO monster_hitzone_text VALUES(108,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(109,'en','Antennae');
INSERT INTO monster_hitzone_text VALUES(110,'en','Head');
INSERT INTO monster_hitzone_text VALUES(111,'en','Arms');
INSERT INTO monster_hitzone_text VALUES(112,'en','Legs');
INSERT INTO monster_hitzone_text VALUES(113,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(114,'en','Head');
INSERT INTO monster_hitzone_text VALUES(115,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(116,'en','Neck Pouch');
INSERT INTO monster_hitzone_text VALUES(117,'en','Body');
INSERT INTO monster_hitzone_text VALUES(118,'en','Left Leg');
INSERT INTO monster_hitzone_text VALUES(119,'en','Right Leg');
INSERT INTO monster_hitzone_text VALUES(120,'en','Left Wing');
INSERT INTO monster_hitzone_text VALUES(121,'en','Right Wing');
INSERT INTO monster_hitzone_text VALUES(122,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(123,'en','Head');
INSERT INTO monster_hitzone_text VALUES(124,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(125,'en','Body');
INSERT INTO monster_hitzone_text VALUES(126,'en','Back');
INSERT INTO monster_hitzone_text VALUES(127,'en','Left Foreleg');
INSERT INTO monster_hitzone_text VALUES(128,'en','Right Foreleg');
INSERT INTO monster_hitzone_text VALUES(129,'en','Left Hindleg');
INSERT INTO monster_hitzone_text VALUES(130,'en','Right Hindleg');
INSERT INTO monster_hitzone_text VALUES(131,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(132,'en','Head');
INSERT INTO monster_hitzone_text VALUES(133,'en','Head Bone');
INSERT INTO monster_hitzone_text VALUES(134,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(135,'en','Body');
INSERT INTO monster_hitzone_text VALUES(136,'en','Back Bone');
INSERT INTO monster_hitzone_text VALUES(137,'en','Left Hindleg');
INSERT INTO monster_hitzone_text VALUES(138,'en','Left Hindleg Bone');
INSERT INTO monster_hitzone_text VALUES(139,'en','Right Hindleg');
INSERT INTO monster_hitzone_text VALUES(140,'en','Right Hindleg Bone');
INSERT INTO monster_hitzone_text VALUES(141,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(142,'en','Head');
INSERT INTO monster_hitzone_text VALUES(143,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(144,'en','Body');
INSERT INTO monster_hitzone_text VALUES(145,'en','Back');
INSERT INTO monster_hitzone_text VALUES(146,'en','Left Wing');
INSERT INTO monster_hitzone_text VALUES(147,'en','Right Wing');
INSERT INTO monster_hitzone_text VALUES(148,'en','Left Leg');
INSERT INTO monster_hitzone_text VALUES(149,'en','Right Leg');
INSERT INTO monster_hitzone_text VALUES(150,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(151,'en','Head');
INSERT INTO monster_hitzone_text VALUES(152,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(153,'en','Body');
INSERT INTO monster_hitzone_text VALUES(154,'en','Back');
INSERT INTO monster_hitzone_text VALUES(155,'en','Left Foreleg');
INSERT INTO monster_hitzone_text VALUES(156,'en','Right Foreleg');
INSERT INTO monster_hitzone_text VALUES(157,'en','Left Hindleg');
INSERT INTO monster_hitzone_text VALUES(158,'en','Right Hindleg');
INSERT INTO monster_hitzone_text VALUES(159,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(160,'en','Head');
INSERT INTO monster_hitzone_text VALUES(161,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(162,'en','Body');
INSERT INTO monster_hitzone_text VALUES(163,'en','Back');
INSERT INTO monster_hitzone_text VALUES(164,'en','Left Wing');
INSERT INTO monster_hitzone_text VALUES(165,'en','Right Wing');
INSERT INTO monster_hitzone_text VALUES(166,'en','Left Leg');
INSERT INTO monster_hitzone_text VALUES(167,'en','Right Leg');
INSERT INTO monster_hitzone_text VALUES(168,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(169,'en','Horn');
INSERT INTO monster_hitzone_text VALUES(170,'en','Head');
INSERT INTO monster_hitzone_text VALUES(171,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(172,'en','Stomach');
INSERT INTO monster_hitzone_text VALUES(173,'en','Back');
INSERT INTO monster_hitzone_text VALUES(174,'en','Left Wing');
INSERT INTO monster_hitzone_text VALUES(175,'en','Right Wing');
INSERT INTO monster_hitzone_text VALUES(176,'en','Left Leg');
INSERT INTO monster_hitzone_text VALUES(177,'en','Right Leg');
INSERT INTO monster_hitzone_text VALUES(178,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(179,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(180,'en','Head');
INSERT INTO monster_hitzone_text VALUES(181,'en','Body');
INSERT INTO monster_hitzone_text VALUES(182,'en','Body (Electricity)');
INSERT INTO monster_hitzone_text VALUES(183,'en','Lower Body');
INSERT INTO monster_hitzone_text VALUES(184,'en','Lower Body (Electricity)');
INSERT INTO monster_hitzone_text VALUES(185,'en','Head');
INSERT INTO monster_hitzone_text VALUES(186,'en','Body');
INSERT INTO monster_hitzone_text VALUES(187,'en','Chest (Before Wounded)');
INSERT INTO monster_hitzone_text VALUES(188,'en','Chest (After Wounded)');
INSERT INTO monster_hitzone_text VALUES(189,'en','Left Foreleg');
INSERT INTO monster_hitzone_text VALUES(190,'en','Right Foreleg');
INSERT INTO monster_hitzone_text VALUES(191,'en','Left Hindleg');
INSERT INTO monster_hitzone_text VALUES(192,'en','Right Hindleg');
INSERT INTO monster_hitzone_text VALUES(193,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(194,'en','Shell');
INSERT INTO monster_hitzone_text VALUES(195,'en','Exhaust Organ (Crater)');
INSERT INTO monster_hitzone_text VALUES(196,'en','Exhaust Organ (Head)');
INSERT INTO monster_hitzone_text VALUES(197,'en','Exhaust Organ (Central)');
INSERT INTO monster_hitzone_text VALUES(198,'en','Exhaust Organ (Rear)');
INSERT INTO monster_hitzone_text VALUES(199,'en','Left Weak Shell');
INSERT INTO monster_hitzone_text VALUES(200,'en','Right Weak Shell');
INSERT INTO monster_hitzone_text VALUES(201,'en','Head');
INSERT INTO monster_hitzone_text VALUES(202,'en','Head (Rock 1)');
INSERT INTO monster_hitzone_text VALUES(203,'en','Head (Rock 2)');
INSERT INTO monster_hitzone_text VALUES(204,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(205,'en','Neck (Rock 1)');
INSERT INTO monster_hitzone_text VALUES(206,'en','Neck (Rock 2)');
INSERT INTO monster_hitzone_text VALUES(207,'en','Body');
INSERT INTO monster_hitzone_text VALUES(208,'en','Back');
INSERT INTO monster_hitzone_text VALUES(209,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(210,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(211,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(212,'en','Head');
INSERT INTO monster_hitzone_text VALUES(213,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(214,'en','Body');
INSERT INTO monster_hitzone_text VALUES(215,'en','Back');
INSERT INTO monster_hitzone_text VALUES(216,'en','Left Wing');
INSERT INTO monster_hitzone_text VALUES(217,'en','Right Wing');
INSERT INTO monster_hitzone_text VALUES(218,'en','Left Leg');
INSERT INTO monster_hitzone_text VALUES(219,'en','Right Leg');
INSERT INTO monster_hitzone_text VALUES(220,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(221,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(222,'en','Head');
INSERT INTO monster_hitzone_text VALUES(223,'en','Body');
INSERT INTO monster_hitzone_text VALUES(224,'en','Back');
INSERT INTO monster_hitzone_text VALUES(225,'en','Legs');
INSERT INTO monster_hitzone_text VALUES(226,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(227,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(228,'en','Head');
INSERT INTO monster_hitzone_text VALUES(229,'en','Chest');
INSERT INTO monster_hitzone_text VALUES(230,'en','Body');
INSERT INTO monster_hitzone_text VALUES(231,'en','Lower Body');
INSERT INTO monster_hitzone_text VALUES(232,'en','Arms');
INSERT INTO monster_hitzone_text VALUES(233,'en','Legs');
INSERT INTO monster_hitzone_text VALUES(234,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(235,'en','Head (Enraged)');
INSERT INTO monster_hitzone_text VALUES(236,'en','Chest (Enraged)');
INSERT INTO monster_hitzone_text VALUES(237,'en','Body (Enraged)');
INSERT INTO monster_hitzone_text VALUES(238,'en','Lower Body (Enraged)');
INSERT INTO monster_hitzone_text VALUES(239,'en','Arms (Enraged)');
INSERT INTO monster_hitzone_text VALUES(240,'en','Legs (Enraged)');
INSERT INTO monster_hitzone_text VALUES(241,'en','Tail (Enraged)');
INSERT INTO monster_hitzone_text VALUES(242,'en','Head');
INSERT INTO monster_hitzone_text VALUES(243,'en','Head (Wounded)');
INSERT INTO monster_hitzone_text VALUES(244,'en','Head (Molten)');
INSERT INTO monster_hitzone_text VALUES(245,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(246,'en','Body');
INSERT INTO monster_hitzone_text VALUES(247,'en','Back');
INSERT INTO monster_hitzone_text VALUES(248,'en','Back (Wounded)');
INSERT INTO monster_hitzone_text VALUES(249,'en','Back (Molten)');
INSERT INTO monster_hitzone_text VALUES(250,'en','Fins');
INSERT INTO monster_hitzone_text VALUES(251,'en','Legs');
INSERT INTO monster_hitzone_text VALUES(252,'en','Legs (Wounded)');
INSERT INTO monster_hitzone_text VALUES(253,'en','Legs (Molten)');
INSERT INTO monster_hitzone_text VALUES(254,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(255,'en','Tail (Wounded)');
INSERT INTO monster_hitzone_text VALUES(256,'en','Tail (Molten)');
INSERT INTO monster_hitzone_text VALUES(257,'en','Head');
INSERT INTO monster_hitzone_text VALUES(258,'en','Jaw');
INSERT INTO monster_hitzone_text VALUES(259,'en','Jaw (Wounded)');
INSERT INTO monster_hitzone_text VALUES(260,'en','Upper Neck');
INSERT INTO monster_hitzone_text VALUES(261,'en','Lower Neck');
INSERT INTO monster_hitzone_text VALUES(262,'en','Body');
INSERT INTO monster_hitzone_text VALUES(263,'en','Back');
INSERT INTO monster_hitzone_text VALUES(264,'en','Forearms');
INSERT INTO monster_hitzone_text VALUES(265,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(266,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(267,'en','Head');
INSERT INTO monster_hitzone_text VALUES(268,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(269,'en','Body');
INSERT INTO monster_hitzone_text VALUES(270,'en','Back');
INSERT INTO monster_hitzone_text VALUES(271,'en','Left Wing');
INSERT INTO monster_hitzone_text VALUES(272,'en','Right Wing');
INSERT INTO monster_hitzone_text VALUES(273,'en','Left Leg');
INSERT INTO monster_hitzone_text VALUES(274,'en','Right Leg');
INSERT INTO monster_hitzone_text VALUES(275,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(276,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(277,'en','Horn');
INSERT INTO monster_hitzone_text VALUES(278,'en','Head');
INSERT INTO monster_hitzone_text VALUES(279,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(280,'en','Stomach');
INSERT INTO monster_hitzone_text VALUES(281,'en','Back');
INSERT INTO monster_hitzone_text VALUES(282,'en','Left Wing');
INSERT INTO monster_hitzone_text VALUES(283,'en','Right Wing');
INSERT INTO monster_hitzone_text VALUES(284,'en','Left Leg');
INSERT INTO monster_hitzone_text VALUES(285,'en','Right Leg');
INSERT INTO monster_hitzone_text VALUES(286,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(287,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(288,'en','Horn');
INSERT INTO monster_hitzone_text VALUES(289,'en','Horn (Wounded)');
INSERT INTO monster_hitzone_text VALUES(290,'en','Head');
INSERT INTO monster_hitzone_text VALUES(291,'en','Head (White)');
INSERT INTO monster_hitzone_text VALUES(292,'en','Head (Black)');
INSERT INTO monster_hitzone_text VALUES(293,'en','Head (Gloss Black)');
INSERT INTO monster_hitzone_text VALUES(294,'en','Body');
INSERT INTO monster_hitzone_text VALUES(295,'en','Back');
INSERT INTO monster_hitzone_text VALUES(296,'en','Forearms');
INSERT INTO monster_hitzone_text VALUES(297,'en','Forearms (White)');
INSERT INTO monster_hitzone_text VALUES(298,'en','Forearms (Black)');
INSERT INTO monster_hitzone_text VALUES(299,'en','Forearms (Gloss Black)');
INSERT INTO monster_hitzone_text VALUES(300,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(301,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(302,'en','Wings (White)');
INSERT INTO monster_hitzone_text VALUES(303,'en','Wings (Black)');
INSERT INTO monster_hitzone_text VALUES(304,'en','Wings (Gloss Black)');
INSERT INTO monster_hitzone_text VALUES(305,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(306,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(307,'en','Tail Tip (White)');
INSERT INTO monster_hitzone_text VALUES(308,'en','Tail Tip (Black)');
INSERT INTO monster_hitzone_text VALUES(309,'en','Tail Tip (Gloss Black)');
INSERT INTO monster_hitzone_text VALUES(310,'en','Head');
INSERT INTO monster_hitzone_text VALUES(311,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(312,'en','Body');
INSERT INTO monster_hitzone_text VALUES(313,'en','Back');
INSERT INTO monster_hitzone_text VALUES(314,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(315,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(316,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(317,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(318,'en','Head');
INSERT INTO monster_hitzone_text VALUES(319,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(320,'en','Chest');
INSERT INTO monster_hitzone_text VALUES(321,'en','Back');
INSERT INTO monster_hitzone_text VALUES(322,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(323,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(324,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(325,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(326,'en','Head');
INSERT INTO monster_hitzone_text VALUES(327,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(328,'en','Body');
INSERT INTO monster_hitzone_text VALUES(329,'en','Back');
INSERT INTO monster_hitzone_text VALUES(330,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(331,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(332,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(333,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(334,'en','Head');
INSERT INTO monster_hitzone_text VALUES(335,'en','Head (Wounded)');
INSERT INTO monster_hitzone_text VALUES(336,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(337,'en','Chest');
INSERT INTO monster_hitzone_text VALUES(338,'en','Stomach');
INSERT INTO monster_hitzone_text VALUES(339,'en','Stomach (Wounded)');
INSERT INTO monster_hitzone_text VALUES(340,'en','Back');
INSERT INTO monster_hitzone_text VALUES(341,'en','Back (Wounded)');
INSERT INTO monster_hitzone_text VALUES(342,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(343,'en','Forelegs (Wounded)');
INSERT INTO monster_hitzone_text VALUES(344,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(345,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(346,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(347,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(348,'en','Head');
INSERT INTO monster_hitzone_text VALUES(349,'en','Chest');
INSERT INTO monster_hitzone_text VALUES(350,'en','Torso');
INSERT INTO monster_hitzone_text VALUES(351,'en','Body / Forelimb / Tail');
INSERT INTO monster_hitzone_text VALUES(352,'en','Hind Legs');
INSERT INTO monster_hitzone_text VALUES(353,'en','Head (Molten)');
INSERT INTO monster_hitzone_text VALUES(354,'en','Body / Forelimb / Tail (Molten)');
INSERT INTO monster_hitzone_text VALUES(355,'en','Head (Exposed)');
INSERT INTO monster_hitzone_text VALUES(356,'en','Forelimbs (Exposed)');
INSERT INTO monster_hitzone_text VALUES(357,'en','Tail (Exposed)');
INSERT INTO monster_hitzone_text VALUES(358,'en','Head');
INSERT INTO monster_hitzone_text VALUES(359,'en','Head (Wounded)');
INSERT INTO monster_hitzone_text VALUES(360,'en','Head (Critical State)');
INSERT INTO monster_hitzone_text VALUES(361,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(362,'en','Neck (Critical State)');
INSERT INTO monster_hitzone_text VALUES(363,'en','Body');
INSERT INTO monster_hitzone_text VALUES(364,'en','Body (Critical State)');
INSERT INTO monster_hitzone_text VALUES(365,'en','Chest');
INSERT INTO monster_hitzone_text VALUES(366,'en','Chest (Critical State)');
INSERT INTO monster_hitzone_text VALUES(367,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(368,'en','Forelegs (Wounded)');
INSERT INTO monster_hitzone_text VALUES(369,'en','Forelegs (Critical State)');
INSERT INTO monster_hitzone_text VALUES(370,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(371,'en','Hindlegs (Critical State)');
INSERT INTO monster_hitzone_text VALUES(372,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(373,'en','Wings (Wounded)');
INSERT INTO monster_hitzone_text VALUES(374,'en','Wings (Critical State)');
INSERT INTO monster_hitzone_text VALUES(375,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(376,'en','Tail (Critical State)');
INSERT INTO monster_hitzone_text VALUES(377,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(378,'en','Tail Tip (Critical State)');
INSERT INTO monster_hitzone_text VALUES(379,'en','Head');
INSERT INTO monster_hitzone_text VALUES(380,'en','Head (Snow)');
INSERT INTO monster_hitzone_text VALUES(381,'en','Body/Back');
INSERT INTO monster_hitzone_text VALUES(382,'en','Body/Back (Snow)');
INSERT INTO monster_hitzone_text VALUES(383,'en','Legs');
INSERT INTO monster_hitzone_text VALUES(384,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(385,'en','Tail (Snow)');
INSERT INTO monster_hitzone_text VALUES(386,'en','Horns');
INSERT INTO monster_hitzone_text VALUES(387,'en','Horns (Broken)');
INSERT INTO monster_hitzone_text VALUES(388,'en','Head');
INSERT INTO monster_hitzone_text VALUES(389,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(390,'en','Body');
INSERT INTO monster_hitzone_text VALUES(391,'en','Forearms');
INSERT INTO monster_hitzone_text VALUES(392,'en','Hind Legs');
INSERT INTO monster_hitzone_text VALUES(393,'en','Hind Legs (Broken)');
INSERT INTO monster_hitzone_text VALUES(394,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(395,'en','Head');
INSERT INTO monster_hitzone_text VALUES(396,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(397,'en','Body');
INSERT INTO monster_hitzone_text VALUES(398,'en','Mane');
INSERT INTO monster_hitzone_text VALUES(399,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(400,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(401,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(402,'en','Head');
INSERT INTO monster_hitzone_text VALUES(403,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(404,'en','Neck Pouch');
INSERT INTO monster_hitzone_text VALUES(405,'en','Body');
INSERT INTO monster_hitzone_text VALUES(406,'en','Legs');
INSERT INTO monster_hitzone_text VALUES(407,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(408,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(409,'en','Head');
INSERT INTO monster_hitzone_text VALUES(410,'en','Body');
INSERT INTO monster_hitzone_text VALUES(411,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(412,'en','Legs');
INSERT INTO monster_hitzone_text VALUES(413,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(414,'en','Head');
INSERT INTO monster_hitzone_text VALUES(415,'en','Neck/Back');
INSERT INTO monster_hitzone_text VALUES(416,'en','Belly');
INSERT INTO monster_hitzone_text VALUES(417,'en','Claws');
INSERT INTO monster_hitzone_text VALUES(418,'en','Claws (Broken)');
INSERT INTO monster_hitzone_text VALUES(419,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(420,'en','Front Legs');
INSERT INTO monster_hitzone_text VALUES(421,'en','Hind Legs');
INSERT INTO monster_hitzone_text VALUES(422,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(423,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(424,'en','Head');
INSERT INTO monster_hitzone_text VALUES(425,'en','Neck/Back');
INSERT INTO monster_hitzone_text VALUES(426,'en','Belly');
INSERT INTO monster_hitzone_text VALUES(427,'en','Front Legs');
INSERT INTO monster_hitzone_text VALUES(428,'en','Front Legs (Broken)');
INSERT INTO monster_hitzone_text VALUES(429,'en','Hind Legs');
INSERT INTO monster_hitzone_text VALUES(430,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(431,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(432,'en','Head');
INSERT INTO monster_hitzone_text VALUES(433,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(434,'en','Throat');
INSERT INTO monster_hitzone_text VALUES(435,'en','Back');
INSERT INTO monster_hitzone_text VALUES(436,'en','Body');
INSERT INTO monster_hitzone_text VALUES(437,'en','Forearms');
INSERT INTO monster_hitzone_text VALUES(438,'en','Hind Legs');
INSERT INTO monster_hitzone_text VALUES(439,'en','Tail Base');
INSERT INTO monster_hitzone_text VALUES(440,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(441,'en','Tail (Rusted)');
INSERT INTO monster_hitzone_text VALUES(442,'en','Tail (Heated)');
INSERT INTO monster_hitzone_text VALUES(443,'en','Head');
INSERT INTO monster_hitzone_text VALUES(444,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(445,'en','Belly');
INSERT INTO monster_hitzone_text VALUES(446,'en','Back');
INSERT INTO monster_hitzone_text VALUES(447,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(448,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(449,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(450,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(451,'en','Head');
INSERT INTO monster_hitzone_text VALUES(452,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(453,'en','Body');
INSERT INTO monster_hitzone_text VALUES(454,'en','Forearms');
INSERT INTO monster_hitzone_text VALUES(455,'en','Hind Legs');
INSERT INTO monster_hitzone_text VALUES(456,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(457,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(458,'en','Head');
INSERT INTO monster_hitzone_text VALUES(459,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(460,'en','Body');
INSERT INTO monster_hitzone_text VALUES(461,'en','Back');
INSERT INTO monster_hitzone_text VALUES(462,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(463,'en','Legs');
INSERT INTO monster_hitzone_text VALUES(464,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(465,'en','Nose');
INSERT INTO monster_hitzone_text VALUES(466,'en','Nose (Charged)');
INSERT INTO monster_hitzone_text VALUES(467,'en','Head');
INSERT INTO monster_hitzone_text VALUES(468,'en','Head (Charged)');
INSERT INTO monster_hitzone_text VALUES(469,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(470,'en','Neck (Charged)');
INSERT INTO monster_hitzone_text VALUES(471,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(472,'en','Wings (Charged)');
INSERT INTO monster_hitzone_text VALUES(473,'en','Body');
INSERT INTO monster_hitzone_text VALUES(474,'en','Body (Charged)');
INSERT INTO monster_hitzone_text VALUES(475,'en','Legs');
INSERT INTO monster_hitzone_text VALUES(476,'en','Legs (Charged)');
INSERT INTO monster_hitzone_text VALUES(477,'en','Legs (Broken)');
INSERT INTO monster_hitzone_text VALUES(478,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(479,'en','Tail (Charged)');
INSERT INTO monster_hitzone_text VALUES(480,'en','Tail (Broken)');
INSERT INTO monster_hitzone_text VALUES(481,'en','Head');
INSERT INTO monster_hitzone_text VALUES(482,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(483,'en','Throat');
INSERT INTO monster_hitzone_text VALUES(484,'en','Back');
INSERT INTO monster_hitzone_text VALUES(485,'en','Body');
INSERT INTO monster_hitzone_text VALUES(486,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(487,'en','Hind Legs');
INSERT INTO monster_hitzone_text VALUES(488,'en','Tail Base');
INSERT INTO monster_hitzone_text VALUES(489,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(490,'en','Tail (Crystal)');
INSERT INTO monster_hitzone_text VALUES(491,'en','Tail (Sharpened)');
INSERT INTO monster_hitzone_text VALUES(492,'en','Head');
INSERT INTO monster_hitzone_text VALUES(493,'en','Head (Broken)');
INSERT INTO monster_hitzone_text VALUES(494,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(495,'en','Body');
INSERT INTO monster_hitzone_text VALUES(496,'en','Back');
INSERT INTO monster_hitzone_text VALUES(497,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(498,'en','Forelegs (Broken)');
INSERT INTO monster_hitzone_text VALUES(499,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(500,'en','Hindlegs (Broken)');
INSERT INTO monster_hitzone_text VALUES(501,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(502,'en','Tail (Broken)');
INSERT INTO monster_hitzone_text VALUES(503,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(504,'en','Head');
INSERT INTO monster_hitzone_text VALUES(505,'en','Head (Broken)');
INSERT INTO monster_hitzone_text VALUES(506,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(507,'en','Neck (Broken)');
INSERT INTO monster_hitzone_text VALUES(508,'en','Body');
INSERT INTO monster_hitzone_text VALUES(509,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(510,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(511,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(512,'en','Wings (Broken)');
INSERT INTO monster_hitzone_text VALUES(513,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(514,'en','Tail (Broken)');
INSERT INTO monster_hitzone_text VALUES(515,'en','Head');
INSERT INTO monster_hitzone_text VALUES(516,'en','Body');
INSERT INTO monster_hitzone_text VALUES(517,'en','Back');
INSERT INTO monster_hitzone_text VALUES(518,'en','Legs');
INSERT INTO monster_hitzone_text VALUES(519,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(520,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(521,'en','Head');
INSERT INTO monster_hitzone_text VALUES(522,'en','Head (Broken)');
INSERT INTO monster_hitzone_text VALUES(523,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(524,'en','Chest');
INSERT INTO monster_hitzone_text VALUES(525,'en','Chest (Spore Sac)');
INSERT INTO monster_hitzone_text VALUES(526,'en','Stomach');
INSERT INTO monster_hitzone_text VALUES(527,'en','Stomach (Broken)');
INSERT INTO monster_hitzone_text VALUES(528,'en','Back');
INSERT INTO monster_hitzone_text VALUES(529,'en','Back (Broken)');
INSERT INTO monster_hitzone_text VALUES(530,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(531,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(532,'en','Forelegs (Broken)');
INSERT INTO monster_hitzone_text VALUES(533,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(534,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(535,'en','Tail (Spore Sac)');
INSERT INTO monster_hitzone_text VALUES(536,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(537,'en','Head');
INSERT INTO monster_hitzone_text VALUES(538,'en','Head (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(539,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(540,'en','Neck (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(541,'en','Back');
INSERT INTO monster_hitzone_text VALUES(542,'en','Back (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(543,'en','Stomach');
INSERT INTO monster_hitzone_text VALUES(544,'en','Stomach (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(545,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(546,'en','Forelegs (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(547,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(548,'en','Hindlegs (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(549,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(550,'en','Wings (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(551,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(552,'en','Tail (Dehydrated)');
INSERT INTO monster_hitzone_text VALUES(553,'en','Head');
INSERT INTO monster_hitzone_text VALUES(554,'en','Head (Broken)');
INSERT INTO monster_hitzone_text VALUES(555,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(556,'en','Chest');
INSERT INTO monster_hitzone_text VALUES(557,'en','Chest (Broken)');
INSERT INTO monster_hitzone_text VALUES(558,'en','Torso');
INSERT INTO monster_hitzone_text VALUES(559,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(560,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(561,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(562,'en','Tail (Broken)');
INSERT INTO monster_hitzone_text VALUES(563,'en','Horn');
INSERT INTO monster_hitzone_text VALUES(564,'en','Horn (Broken)');
INSERT INTO monster_hitzone_text VALUES(565,'en','Head');
INSERT INTO monster_hitzone_text VALUES(566,'en','Head (White)');
INSERT INTO monster_hitzone_text VALUES(567,'en','Head (Black)');
INSERT INTO monster_hitzone_text VALUES(568,'en','Body');
INSERT INTO monster_hitzone_text VALUES(569,'en','Back');
INSERT INTO monster_hitzone_text VALUES(570,'en','Forearms');
INSERT INTO monster_hitzone_text VALUES(571,'en','Forearms (White)');
INSERT INTO monster_hitzone_text VALUES(572,'en','Forearms (Black)');
INSERT INTO monster_hitzone_text VALUES(573,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(574,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(575,'en','Wings (White)');
INSERT INTO monster_hitzone_text VALUES(576,'en','Wings (Black)');
INSERT INTO monster_hitzone_text VALUES(577,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(578,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(579,'en','Tail Tip (White)');
INSERT INTO monster_hitzone_text VALUES(580,'en','Tail Tip (Black)');
INSERT INTO monster_hitzone_text VALUES(581,'en','Head');
INSERT INTO monster_hitzone_text VALUES(582,'en','Head Casing (Top)');
INSERT INTO monster_hitzone_text VALUES(583,'en','Head Casing (Bottom)');
INSERT INTO monster_hitzone_text VALUES(584,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(585,'en','Wings (Broken)');
INSERT INTO monster_hitzone_text VALUES(586,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(587,'en','Forelegs (Broken)');
INSERT INTO monster_hitzone_text VALUES(588,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(589,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(590,'en','Head (Released)');
INSERT INTO monster_hitzone_text VALUES(591,'en','Body (Released)');
INSERT INTO monster_hitzone_text VALUES(592,'en','Wings (Released)');
INSERT INTO monster_hitzone_text VALUES(593,'en','Forelegs (Released)');
INSERT INTO monster_hitzone_text VALUES(594,'en','Hindlegs (Released)');
INSERT INTO monster_hitzone_text VALUES(595,'en','Tail (Released)');
INSERT INTO monster_hitzone_text VALUES(596,'en','Head');
INSERT INTO monster_hitzone_text VALUES(597,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(598,'en','Body');
INSERT INTO monster_hitzone_text VALUES(599,'en','Back');
INSERT INTO monster_hitzone_text VALUES(600,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(601,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(602,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(603,'en','Head (Charged)');
INSERT INTO monster_hitzone_text VALUES(604,'en','Neck (Charged)');
INSERT INTO monster_hitzone_text VALUES(605,'en','Body (Charged)');
INSERT INTO monster_hitzone_text VALUES(606,'en','Back (Charged)');
INSERT INTO monster_hitzone_text VALUES(607,'en','Forelegs (Charged)');
INSERT INTO monster_hitzone_text VALUES(608,'en','Hindlegs (Charged)');
INSERT INTO monster_hitzone_text VALUES(609,'en','Tail (Charged)');
INSERT INTO monster_hitzone_text VALUES(610,'en','Ears');
INSERT INTO monster_hitzone_text VALUES(611,'en','Head');
INSERT INTO monster_hitzone_text VALUES(612,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(613,'en','Back');
INSERT INTO monster_hitzone_text VALUES(614,'en','Belly');
INSERT INTO monster_hitzone_text VALUES(615,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(616,'en','Wings (Broken)');
INSERT INTO monster_hitzone_text VALUES(617,'en','Legs');
INSERT INTO monster_hitzone_text VALUES(618,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(619,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(620,'en','Ears');
INSERT INTO monster_hitzone_text VALUES(621,'en','Head');
INSERT INTO monster_hitzone_text VALUES(622,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(623,'en','Back');
INSERT INTO monster_hitzone_text VALUES(624,'en','Belly');
INSERT INTO monster_hitzone_text VALUES(625,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(626,'en','Wings (Broken)');
INSERT INTO monster_hitzone_text VALUES(627,'en','Legs');
INSERT INTO monster_hitzone_text VALUES(628,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(629,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(630,'en','Head');
INSERT INTO monster_hitzone_text VALUES(631,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(632,'en','Belly');
INSERT INTO monster_hitzone_text VALUES(633,'en','Back');
INSERT INTO monster_hitzone_text VALUES(634,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(635,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(636,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(637,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(638,'en','Head');
INSERT INTO monster_hitzone_text VALUES(639,'en','Head (Broken)');
INSERT INTO monster_hitzone_text VALUES(640,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(641,'en','Neck (Broken)');
INSERT INTO monster_hitzone_text VALUES(642,'en','Body');
INSERT INTO monster_hitzone_text VALUES(643,'en','Back');
INSERT INTO monster_hitzone_text VALUES(644,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(645,'en','Legs');
INSERT INTO monster_hitzone_text VALUES(646,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(647,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(648,'en','Head');
INSERT INTO monster_hitzone_text VALUES(649,'en','Head (Broken)');
INSERT INTO monster_hitzone_text VALUES(650,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(651,'en','Neck (Broken)');
INSERT INTO monster_hitzone_text VALUES(652,'en','Body');
INSERT INTO monster_hitzone_text VALUES(653,'en','Back');
INSERT INTO monster_hitzone_text VALUES(654,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(655,'en','Legs');
INSERT INTO monster_hitzone_text VALUES(656,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(657,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(658,'en','Head');
INSERT INTO monster_hitzone_text VALUES(659,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(660,'en','Forelegs (Charged)');
INSERT INTO monster_hitzone_text VALUES(661,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(662,'en','Body');
INSERT INTO monster_hitzone_text VALUES(663,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(664,'en','Tail (Charged)');
INSERT INTO monster_hitzone_text VALUES(665,'en','Head');
INSERT INTO monster_hitzone_text VALUES(666,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(667,'en','Body');
INSERT INTO monster_hitzone_text VALUES(668,'en','Back');
INSERT INTO monster_hitzone_text VALUES(669,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(670,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(671,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(672,'en','Head (Charged)');
INSERT INTO monster_hitzone_text VALUES(673,'en','Neck (Charged)');
INSERT INTO monster_hitzone_text VALUES(674,'en','Body (Charged)');
INSERT INTO monster_hitzone_text VALUES(675,'en','Back (Charged)');
INSERT INTO monster_hitzone_text VALUES(676,'en','Forelegs (Charged)');
INSERT INTO monster_hitzone_text VALUES(677,'en','Hindlegs (Charged)');
INSERT INTO monster_hitzone_text VALUES(678,'en','Tail (Charged)');
INSERT INTO monster_hitzone_text VALUES(679,'en','Head');
INSERT INTO monster_hitzone_text VALUES(680,'en','Back');
INSERT INTO monster_hitzone_text VALUES(681,'en','Stomach');
INSERT INTO monster_hitzone_text VALUES(682,'en','Claws');
INSERT INTO monster_hitzone_text VALUES(683,'en','Claws (Broken)');
INSERT INTO monster_hitzone_text VALUES(684,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(685,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(686,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(687,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(688,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(689,'en','Head');
INSERT INTO monster_hitzone_text VALUES(690,'en','Head (Broken)');
INSERT INTO monster_hitzone_text VALUES(691,'en','Head (SCritical)');
INSERT INTO monster_hitzone_text VALUES(692,'en','Head (Broken+SCritical)');
INSERT INTO monster_hitzone_text VALUES(693,'en','Snout');
INSERT INTO monster_hitzone_text VALUES(694,'en','Snout (Broken)');
INSERT INTO monster_hitzone_text VALUES(695,'en','Snout (SCritical)');
INSERT INTO monster_hitzone_text VALUES(696,'en','Snout (Broken+SCritical)');
INSERT INTO monster_hitzone_text VALUES(697,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(698,'en','Neck (SCritical)');
INSERT INTO monster_hitzone_text VALUES(699,'en','Body');
INSERT INTO monster_hitzone_text VALUES(700,'en','Body (SCritical)');
INSERT INTO monster_hitzone_text VALUES(701,'en','Back');
INSERT INTO monster_hitzone_text VALUES(702,'en','Back (SCritical)');
INSERT INTO monster_hitzone_text VALUES(703,'en','Chest');
INSERT INTO monster_hitzone_text VALUES(704,'en','Chest (SCritical)');
INSERT INTO monster_hitzone_text VALUES(705,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(706,'en','Forelegs (SCritical)');
INSERT INTO monster_hitzone_text VALUES(707,'en','Forefeet');
INSERT INTO monster_hitzone_text VALUES(708,'en','Forefeet (SCritical)');
INSERT INTO monster_hitzone_text VALUES(709,'en','Foreleg+Feet (Broken)');
INSERT INTO monster_hitzone_text VALUES(710,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(711,'en','Hindlegs (SCritical)');
INSERT INTO monster_hitzone_text VALUES(712,'en','Hindfeet');
INSERT INTO monster_hitzone_text VALUES(713,'en','Hindfeet (SCritical)');
INSERT INTO monster_hitzone_text VALUES(714,'en','Hindleg+Feet (Broken)');
INSERT INTO monster_hitzone_text VALUES(715,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(716,'en','Wings (SCritical)');
INSERT INTO monster_hitzone_text VALUES(717,'en','Wing Tips');
INSERT INTO monster_hitzone_text VALUES(718,'en','Wing Tips (SCritical)');
INSERT INTO monster_hitzone_text VALUES(719,'en','Webbing');
INSERT INTO monster_hitzone_text VALUES(720,'en','Webbing (SCritical)');
INSERT INTO monster_hitzone_text VALUES(721,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(722,'en','Tail (SCritical)');
INSERT INTO monster_hitzone_text VALUES(723,'en','Upper Tail');
INSERT INTO monster_hitzone_text VALUES(724,'en','Upper Tail (SCritical)');
INSERT INTO monster_hitzone_text VALUES(725,'en','Head');
INSERT INTO monster_hitzone_text VALUES(726,'en','Head (Rampage)');
INSERT INTO monster_hitzone_text VALUES(727,'en','Body');
INSERT INTO monster_hitzone_text VALUES(728,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(729,'en','Forelegs (Rampage)');
INSERT INTO monster_hitzone_text VALUES(730,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(731,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(732,'en','Tail (Rampage)');
INSERT INTO monster_hitzone_text VALUES(733,'en','Horns');
INSERT INTO monster_hitzone_text VALUES(734,'en','Horns (Red Slime)');
INSERT INTO monster_hitzone_text VALUES(735,'en','Head');
INSERT INTO monster_hitzone_text VALUES(736,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(737,'en','Body');
INSERT INTO monster_hitzone_text VALUES(738,'en','Forearms');
INSERT INTO monster_hitzone_text VALUES(739,'en','Forearms (Red Slime)');
INSERT INTO monster_hitzone_text VALUES(740,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(741,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(742,'en','Tail Tip');
INSERT INTO monster_hitzone_text VALUES(743,'en','Tail Tip (Red Slime)');
INSERT INTO monster_hitzone_text VALUES(744,'en','Head (Fire)');
INSERT INTO monster_hitzone_text VALUES(745,'en','Neck (Fire)');
INSERT INTO monster_hitzone_text VALUES(746,'en','Body (Fire)');
INSERT INTO monster_hitzone_text VALUES(747,'en','Wings (Fire)');
INSERT INTO monster_hitzone_text VALUES(748,'en','Arms (Fire)');
INSERT INTO monster_hitzone_text VALUES(749,'en','Legs (Fire)');
INSERT INTO monster_hitzone_text VALUES(750,'en','Tail (Fire)');
INSERT INTO monster_hitzone_text VALUES(751,'en','Head (Ice)');
INSERT INTO monster_hitzone_text VALUES(752,'en','Neck (Ice)');
INSERT INTO monster_hitzone_text VALUES(753,'en','Body (Ice)');
INSERT INTO monster_hitzone_text VALUES(754,'en','Wings (Ice)');
INSERT INTO monster_hitzone_text VALUES(755,'en','Arms (Ice)');
INSERT INTO monster_hitzone_text VALUES(756,'en','Legs (Ice)');
INSERT INTO monster_hitzone_text VALUES(757,'en','Tail (Ice)');
INSERT INTO monster_hitzone_text VALUES(758,'en','Head (Dragon)');
INSERT INTO monster_hitzone_text VALUES(759,'en','Neck (Dragon)');
INSERT INTO monster_hitzone_text VALUES(760,'en','Body (Dragon)');
INSERT INTO monster_hitzone_text VALUES(761,'en','Wings (Dragon)');
INSERT INTO monster_hitzone_text VALUES(762,'en','Arms (Dragon)');
INSERT INTO monster_hitzone_text VALUES(763,'en','Legs (Dragon)');
INSERT INTO monster_hitzone_text VALUES(764,'en','Tail (Dragon)');
INSERT INTO monster_hitzone_text VALUES(765,'en','Head');
INSERT INTO monster_hitzone_text VALUES(766,'en','Neck');
INSERT INTO monster_hitzone_text VALUES(767,'en','Chest');
INSERT INTO monster_hitzone_text VALUES(768,'en','Back');
INSERT INTO monster_hitzone_text VALUES(769,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(770,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(771,'en','Wings');
INSERT INTO monster_hitzone_text VALUES(772,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(773,'en','Chest (Critical State)');
INSERT INTO monster_hitzone_text VALUES(774,'en','Horns');
INSERT INTO monster_hitzone_text VALUES(775,'en','Horns (Broken)');
INSERT INTO monster_hitzone_text VALUES(776,'en','Head');
INSERT INTO monster_hitzone_text VALUES(777,'en','Forelegs');
INSERT INTO monster_hitzone_text VALUES(778,'en','Hindlegs');
INSERT INTO monster_hitzone_text VALUES(779,'en','Tail');
INSERT INTO monster_hitzone_text VALUES(780,'en','Behind');
INSERT INTO monster_hitzone_text VALUES(781,'en','Head');
INSERT INTO monster_hitzone_text VALUES(782,'en','Torso');
INSERT INTO monster_hitzone_text VALUES(783,'en','Arms');
INSERT INTO monster_hitzone_text VALUES(784,'en','Legs');
INSERT INTO monster_hitzone_text VALUES(785,'en','Head');
INSERT INTO monster_hitzone_text VALUES(786,'en','Torso');
INSERT INTO monster_hitzone_text VALUES(787,'en','Arms');
INSERT INTO monster_hitzone_text VALUES(788,'en','Legs');

COMMIT;