BEGIN;

INSERT INTO monster_break_text VALUES(1,'de','Head');
INSERT INTO monster_break_text VALUES(2,'de','Body');
INSERT INTO monster_break_text VALUES(3,'de','Body (Inflated)');
INSERT INTO monster_break_text VALUES(4,'de','Forelegs');
INSERT INTO monster_break_text VALUES(5,'de','Legs');
INSERT INTO monster_break_text VALUES(6,'de','Tail');
INSERT INTO monster_break_text VALUES(7,'de','Head');
INSERT INTO monster_break_text VALUES(8,'de','Forearms');
INSERT INTO monster_break_text VALUES(9,'de','Body');
INSERT INTO monster_break_text VALUES(10,'de','Tail');
INSERT INTO monster_break_text VALUES(11,'de','Rock');
INSERT INTO monster_break_text VALUES(12,'de','Head');
INSERT INTO monster_break_text VALUES(13,'de','Body');
INSERT INTO monster_break_text VALUES(14,'de','Left Wing');
INSERT INTO monster_break_text VALUES(15,'de','Right Wing');
INSERT INTO monster_break_text VALUES(16,'de','Left Leg');
INSERT INTO monster_break_text VALUES(17,'de','Right Leg');
INSERT INTO monster_break_text VALUES(18,'de','Tail');
INSERT INTO monster_break_text VALUES(19,'de','Head');
INSERT INTO monster_break_text VALUES(20,'de','Head (Mud)');
INSERT INTO monster_break_text VALUES(21,'de','Body');
INSERT INTO monster_break_text VALUES(22,'de','Body (Mud)');
INSERT INTO monster_break_text VALUES(23,'de','Forearms');
INSERT INTO monster_break_text VALUES(24,'de','Forearms (Mud)');
INSERT INTO monster_break_text VALUES(25,'de','Left Leg');
INSERT INTO monster_break_text VALUES(26,'de','Left Leg (Mud)');
INSERT INTO monster_break_text VALUES(27,'de','Right Leg');
INSERT INTO monster_break_text VALUES(28,'de','Right Leg (Mud)');
INSERT INTO monster_break_text VALUES(29,'de','Tail');
INSERT INTO monster_break_text VALUES(30,'de','Tail (Mud)');
INSERT INTO monster_break_text VALUES(31,'de','Head');
INSERT INTO monster_break_text VALUES(32,'de','Head (Mud)');
INSERT INTO monster_break_text VALUES(33,'de','Body');
INSERT INTO monster_break_text VALUES(34,'de','Body (Mud)');
INSERT INTO monster_break_text VALUES(35,'de','Left Leg');
INSERT INTO monster_break_text VALUES(36,'de','Left Leg (Mud)');
INSERT INTO monster_break_text VALUES(37,'de','Right Leg');
INSERT INTO monster_break_text VALUES(38,'de','Right Leg (Mud)');
INSERT INTO monster_break_text VALUES(39,'de','Tail');
INSERT INTO monster_break_text VALUES(40,'de','Tail (Mud)');
INSERT INTO monster_break_text VALUES(41,'de','Head');
INSERT INTO monster_break_text VALUES(42,'de','Body');
INSERT INTO monster_break_text VALUES(43,'de','Back');
INSERT INTO monster_break_text VALUES(44,'de','Forelegs');
INSERT INTO monster_break_text VALUES(45,'de','Hindlegs');
INSERT INTO monster_break_text VALUES(46,'de','Tail');
INSERT INTO monster_break_text VALUES(47,'de','Head');
INSERT INTO monster_break_text VALUES(48,'de','Body');
INSERT INTO monster_break_text VALUES(49,'de','Left Leg');
INSERT INTO monster_break_text VALUES(50,'de','Right Leg');
INSERT INTO monster_break_text VALUES(51,'de','Tail');
INSERT INTO monster_break_text VALUES(52,'de','Head');
INSERT INTO monster_break_text VALUES(53,'de','Body');
INSERT INTO monster_break_text VALUES(54,'de','Left Wing');
INSERT INTO monster_break_text VALUES(55,'de','Right Wing');
INSERT INTO monster_break_text VALUES(56,'de','Left Leg');
INSERT INTO monster_break_text VALUES(57,'de','Right Leg');
INSERT INTO monster_break_text VALUES(58,'de','Tail');
INSERT INTO monster_break_text VALUES(59,'de','Antennae');
INSERT INTO monster_break_text VALUES(60,'de','Head');
INSERT INTO monster_break_text VALUES(61,'de','Forearms');
INSERT INTO monster_break_text VALUES(62,'de','Body');
INSERT INTO monster_break_text VALUES(63,'de','Tail');
INSERT INTO monster_break_text VALUES(64,'de','Head');
INSERT INTO monster_break_text VALUES(65,'de','Neck Pouch');
INSERT INTO monster_break_text VALUES(66,'de','Body');
INSERT INTO monster_break_text VALUES(67,'de','Left Leg');
INSERT INTO monster_break_text VALUES(68,'de','Right Leg');
INSERT INTO monster_break_text VALUES(69,'de','Left Wing');
INSERT INTO monster_break_text VALUES(70,'de','Right Wing');
INSERT INTO monster_break_text VALUES(71,'de','Tail');
INSERT INTO monster_break_text VALUES(72,'de','Head');
INSERT INTO monster_break_text VALUES(73,'de','Body');
INSERT INTO monster_break_text VALUES(74,'de','Forearms');
INSERT INTO monster_break_text VALUES(75,'de','Legs');
INSERT INTO monster_break_text VALUES(76,'de','Tail');
INSERT INTO monster_break_text VALUES(77,'de','Head');
INSERT INTO monster_break_text VALUES(78,'de','Head Bone');
INSERT INTO monster_break_text VALUES(79,'de','Body');
INSERT INTO monster_break_text VALUES(80,'de','Back Bone');
INSERT INTO monster_break_text VALUES(81,'de','Left Hindleg');
INSERT INTO monster_break_text VALUES(82,'de','Left Hindleg Bone');
INSERT INTO monster_break_text VALUES(83,'de','Right Hindleg');
INSERT INTO monster_break_text VALUES(84,'de','Right Hindleg Bone');
INSERT INTO monster_break_text VALUES(85,'de','Tail');
INSERT INTO monster_break_text VALUES(86,'de','Head');
INSERT INTO monster_break_text VALUES(87,'de','Body');
INSERT INTO monster_break_text VALUES(88,'de','Left Wing');
INSERT INTO monster_break_text VALUES(89,'de','Right Wing');
INSERT INTO monster_break_text VALUES(90,'de','Left Leg');
INSERT INTO monster_break_text VALUES(91,'de','Right Leg');
INSERT INTO monster_break_text VALUES(92,'de','Tail');
INSERT INTO monster_break_text VALUES(93,'de','Head');
INSERT INTO monster_break_text VALUES(94,'de','Body');
INSERT INTO monster_break_text VALUES(95,'de','Forearms');
INSERT INTO monster_break_text VALUES(96,'de','Legs');
INSERT INTO monster_break_text VALUES(97,'de','Tail');
INSERT INTO monster_break_text VALUES(98,'de','Head');
INSERT INTO monster_break_text VALUES(99,'de','Body');
INSERT INTO monster_break_text VALUES(100,'de','Left Wing');
INSERT INTO monster_break_text VALUES(101,'de','Right Wing');
INSERT INTO monster_break_text VALUES(102,'de','Left Leg');
INSERT INTO monster_break_text VALUES(103,'de','Right Leg');
INSERT INTO monster_break_text VALUES(104,'de','Tail');
INSERT INTO monster_break_text VALUES(105,'de','Head');
INSERT INTO monster_break_text VALUES(106,'de','Body');
INSERT INTO monster_break_text VALUES(107,'de','Left Wing');
INSERT INTO monster_break_text VALUES(108,'de','Right Wing');
INSERT INTO monster_break_text VALUES(109,'de','Left Leg');
INSERT INTO monster_break_text VALUES(110,'de','Right Leg');
INSERT INTO monster_break_text VALUES(111,'de','Tail');
INSERT INTO monster_break_text VALUES(112,'de','Head');
INSERT INTO monster_break_text VALUES(113,'de','Upper Body');
INSERT INTO monster_break_text VALUES(114,'de','Lower Body');
INSERT INTO monster_break_text VALUES(115,'de','Head');
INSERT INTO monster_break_text VALUES(116,'de','Body');
INSERT INTO monster_break_text VALUES(117,'de','Chest');
INSERT INTO monster_break_text VALUES(118,'de','Left Foreleg');
INSERT INTO monster_break_text VALUES(119,'de','Right Foreleg');
INSERT INTO monster_break_text VALUES(120,'de','Left Hindleg');
INSERT INTO monster_break_text VALUES(121,'de','Right Hindleg');
INSERT INTO monster_break_text VALUES(122,'de','Tail');
INSERT INTO monster_break_text VALUES(123,'de','Shell');
INSERT INTO monster_break_text VALUES(124,'de','Exhaust Organ (Small)');
INSERT INTO monster_break_text VALUES(125,'de','Exhaust Organ (Large)');
INSERT INTO monster_break_text VALUES(126,'de','Weak Shell');
INSERT INTO monster_break_text VALUES(127,'de','Head');
INSERT INTO monster_break_text VALUES(128,'de','Body');
INSERT INTO monster_break_text VALUES(129,'de','Forelegs');
INSERT INTO monster_break_text VALUES(130,'de','Legs');
INSERT INTO monster_break_text VALUES(131,'de','Tail');
INSERT INTO monster_break_text VALUES(132,'de','Head');
INSERT INTO monster_break_text VALUES(133,'de','Body');
INSERT INTO monster_break_text VALUES(134,'de','Left Wing');
INSERT INTO monster_break_text VALUES(135,'de','Right Wing');
INSERT INTO monster_break_text VALUES(136,'de','Left Leg');
INSERT INTO monster_break_text VALUES(137,'de','Right Leg');
INSERT INTO monster_break_text VALUES(138,'de','Tail');
INSERT INTO monster_break_text VALUES(139,'de','Head');
INSERT INTO monster_break_text VALUES(140,'de','Body');
INSERT INTO monster_break_text VALUES(141,'de','Legs');
INSERT INTO monster_break_text VALUES(142,'de','Left Wing');
INSERT INTO monster_break_text VALUES(143,'de','Right Wing');
INSERT INTO monster_break_text VALUES(144,'de','Tail');
INSERT INTO monster_break_text VALUES(145,'de','Head');
INSERT INTO monster_break_text VALUES(146,'de','Body');
INSERT INTO monster_break_text VALUES(147,'de','Chest');
INSERT INTO monster_break_text VALUES(148,'de','Lower Body');
INSERT INTO monster_break_text VALUES(149,'de','Arms');
INSERT INTO monster_break_text VALUES(150,'de','Legs');
INSERT INTO monster_break_text VALUES(151,'de','Tail');
INSERT INTO monster_break_text VALUES(152,'de','Head');
INSERT INTO monster_break_text VALUES(153,'de','Back');
INSERT INTO monster_break_text VALUES(154,'de','Body');
INSERT INTO monster_break_text VALUES(155,'de','Left Foot');
INSERT INTO monster_break_text VALUES(156,'de','Right Foot');
INSERT INTO monster_break_text VALUES(157,'de','Tail');
INSERT INTO monster_break_text VALUES(158,'de','Head');
INSERT INTO monster_break_text VALUES(159,'de','Neck');
INSERT INTO monster_break_text VALUES(160,'de','Body');
INSERT INTO monster_break_text VALUES(161,'de','Forearms');
INSERT INTO monster_break_text VALUES(162,'de','Left Leg');
INSERT INTO monster_break_text VALUES(163,'de','Right Leg');
INSERT INTO monster_break_text VALUES(164,'de','Tail');
INSERT INTO monster_break_text VALUES(165,'de','Head');
INSERT INTO monster_break_text VALUES(166,'de','Body');
INSERT INTO monster_break_text VALUES(167,'de','Left Wing');
INSERT INTO monster_break_text VALUES(168,'de','Right Wing');
INSERT INTO monster_break_text VALUES(169,'de','Left Leg');
INSERT INTO monster_break_text VALUES(170,'de','Right Leg');
INSERT INTO monster_break_text VALUES(171,'de','Tail');
INSERT INTO monster_break_text VALUES(172,'de','Head');
INSERT INTO monster_break_text VALUES(173,'de','Body');
INSERT INTO monster_break_text VALUES(174,'de','Left Wing');
INSERT INTO monster_break_text VALUES(175,'de','Right Wing');
INSERT INTO monster_break_text VALUES(176,'de','Left Leg');
INSERT INTO monster_break_text VALUES(177,'de','Right Leg');
INSERT INTO monster_break_text VALUES(178,'de','Tail');
INSERT INTO monster_break_text VALUES(179,'de','Horns');
INSERT INTO monster_break_text VALUES(180,'de','Head');
INSERT INTO monster_break_text VALUES(181,'de','Body');
INSERT INTO monster_break_text VALUES(182,'de','Left Foreleg');
INSERT INTO monster_break_text VALUES(183,'de','Right Foreleg');
INSERT INTO monster_break_text VALUES(184,'de','Left Hindleg');
INSERT INTO monster_break_text VALUES(185,'de','Right Hindleg');
INSERT INTO monster_break_text VALUES(186,'de','Left Wing');
INSERT INTO monster_break_text VALUES(187,'de','Right Wing');
INSERT INTO monster_break_text VALUES(188,'de','Tail');
INSERT INTO monster_break_text VALUES(189,'de','Head');
INSERT INTO monster_break_text VALUES(190,'de','Body');
INSERT INTO monster_break_text VALUES(191,'de','Forelegs');
INSERT INTO monster_break_text VALUES(192,'de','Hindlegs');
INSERT INTO monster_break_text VALUES(193,'de','Wings');
INSERT INTO monster_break_text VALUES(194,'de','Tail');
INSERT INTO monster_break_text VALUES(195,'de','Head');
INSERT INTO monster_break_text VALUES(196,'de','Body');
INSERT INTO monster_break_text VALUES(197,'de','Forelegs');
INSERT INTO monster_break_text VALUES(198,'de','Hindlegs');
INSERT INTO monster_break_text VALUES(199,'de','Wings');
INSERT INTO monster_break_text VALUES(200,'de','Tail');
INSERT INTO monster_break_text VALUES(201,'de','Head');
INSERT INTO monster_break_text VALUES(202,'de','Body');
INSERT INTO monster_break_text VALUES(203,'de','Tail');
INSERT INTO monster_break_text VALUES(204,'de','Left Legs');
INSERT INTO monster_break_text VALUES(205,'de','Right Legs');
INSERT INTO monster_break_text VALUES(206,'de','Wings');
INSERT INTO monster_break_text VALUES(207,'de','Head');
INSERT INTO monster_break_text VALUES(208,'de','Chest');
INSERT INTO monster_break_text VALUES(209,'de','Body');
INSERT INTO monster_break_text VALUES(210,'de','Tail');
INSERT INTO monster_break_text VALUES(211,'de','Left Foreleg');
INSERT INTO monster_break_text VALUES(212,'de','Right Foreleg');
INSERT INTO monster_break_text VALUES(213,'de','Left Hindleg');
INSERT INTO monster_break_text VALUES(214,'de','Right Hindleg');
INSERT INTO monster_break_text VALUES(215,'de','Wings');
INSERT INTO monster_break_text VALUES(216,'de','Head');
INSERT INTO monster_break_text VALUES(217,'de','Neck');
INSERT INTO monster_break_text VALUES(218,'de','Body');
INSERT INTO monster_break_text VALUES(219,'de','Chest');
INSERT INTO monster_break_text VALUES(220,'de','Left Foreleg');
INSERT INTO monster_break_text VALUES(221,'de','Right Foreleg');
INSERT INTO monster_break_text VALUES(222,'de','Left Hindleg');
INSERT INTO monster_break_text VALUES(223,'de','Right Hindleg');
INSERT INTO monster_break_text VALUES(224,'de','Wings');
INSERT INTO monster_break_text VALUES(225,'de','Tail');
INSERT INTO monster_break_text VALUES(226,'de','Head');
INSERT INTO monster_break_text VALUES(227,'de','Body');
INSERT INTO monster_break_text VALUES(228,'de','Left Foreleg');
INSERT INTO monster_break_text VALUES(229,'de','Right Foreleg');
INSERT INTO monster_break_text VALUES(230,'de','Left Hindleg');
INSERT INTO monster_break_text VALUES(231,'de','Right Hindleg');
INSERT INTO monster_break_text VALUES(232,'de','Tail');
INSERT INTO monster_break_text VALUES(233,'de','Head');
INSERT INTO monster_break_text VALUES(234,'de','Body');
INSERT INTO monster_break_text VALUES(235,'de','Wings');
INSERT INTO monster_break_text VALUES(236,'de','Arms');
INSERT INTO monster_break_text VALUES(237,'de','Legs');
INSERT INTO monster_break_text VALUES(238,'de','Tail');
INSERT INTO monster_break_text VALUES(239,'de','Head');
INSERT INTO monster_break_text VALUES(240,'de','Neck');
INSERT INTO monster_break_text VALUES(241,'de','Chest');
INSERT INTO monster_break_text VALUES(242,'de','Back');
INSERT INTO monster_break_text VALUES(243,'de','Left Foreleg');
INSERT INTO monster_break_text VALUES(244,'de','Right Foreleg');
INSERT INTO monster_break_text VALUES(245,'de','Left Hindleg');
INSERT INTO monster_break_text VALUES(246,'de','Right Hindleg');
INSERT INTO monster_break_text VALUES(247,'de','Left Wing');
INSERT INTO monster_break_text VALUES(248,'de','Right Wing');
INSERT INTO monster_break_text VALUES(249,'de','Tail');
INSERT INTO monster_break_text VALUES(250,'de','Horns');
INSERT INTO monster_break_text VALUES(251,'de','Head');
INSERT INTO monster_break_text VALUES(252,'de','Back');
INSERT INTO monster_break_text VALUES(253,'de','Belly');
INSERT INTO monster_break_text VALUES(254,'de','Forearms');
INSERT INTO monster_break_text VALUES(255,'de','Hindlegs');
INSERT INTO monster_break_text VALUES(256,'de','Tail');
INSERT INTO monster_break_text VALUES(1,'en','Head');
INSERT INTO monster_break_text VALUES(2,'en','Body');
INSERT INTO monster_break_text VALUES(3,'en','Body (Inflated)');
INSERT INTO monster_break_text VALUES(4,'en','Forelegs');
INSERT INTO monster_break_text VALUES(5,'en','Legs');
INSERT INTO monster_break_text VALUES(6,'en','Tail');
INSERT INTO monster_break_text VALUES(7,'en','Head');
INSERT INTO monster_break_text VALUES(8,'en','Forearms');
INSERT INTO monster_break_text VALUES(9,'en','Body');
INSERT INTO monster_break_text VALUES(10,'en','Tail');
INSERT INTO monster_break_text VALUES(11,'en','Rock');
INSERT INTO monster_break_text VALUES(12,'en','Head');
INSERT INTO monster_break_text VALUES(13,'en','Body');
INSERT INTO monster_break_text VALUES(14,'en','Left Wing');
INSERT INTO monster_break_text VALUES(15,'en','Right Wing');
INSERT INTO monster_break_text VALUES(16,'en','Left Leg');
INSERT INTO monster_break_text VALUES(17,'en','Right Leg');
INSERT INTO monster_break_text VALUES(18,'en','Tail');
INSERT INTO monster_break_text VALUES(19,'en','Head');
INSERT INTO monster_break_text VALUES(20,'en','Head (Mud)');
INSERT INTO monster_break_text VALUES(21,'en','Body');
INSERT INTO monster_break_text VALUES(22,'en','Body (Mud)');
INSERT INTO monster_break_text VALUES(23,'en','Forearms');
INSERT INTO monster_break_text VALUES(24,'en','Forearms (Mud)');
INSERT INTO monster_break_text VALUES(25,'en','Left Leg');
INSERT INTO monster_break_text VALUES(26,'en','Left Leg (Mud)');
INSERT INTO monster_break_text VALUES(27,'en','Right Leg');
INSERT INTO monster_break_text VALUES(28,'en','Right Leg (Mud)');
INSERT INTO monster_break_text VALUES(29,'en','Tail');
INSERT INTO monster_break_text VALUES(30,'en','Tail (Mud)');
INSERT INTO monster_break_text VALUES(31,'en','Head');
INSERT INTO monster_break_text VALUES(32,'en','Head (Mud)');
INSERT INTO monster_break_text VALUES(33,'en','Body');
INSERT INTO monster_break_text VALUES(34,'en','Body (Mud)');
INSERT INTO monster_break_text VALUES(35,'en','Left Leg');
INSERT INTO monster_break_text VALUES(36,'en','Left Leg (Mud)');
INSERT INTO monster_break_text VALUES(37,'en','Right Leg');
INSERT INTO monster_break_text VALUES(38,'en','Right Leg (Mud)');
INSERT INTO monster_break_text VALUES(39,'en','Tail');
INSERT INTO monster_break_text VALUES(40,'en','Tail (Mud)');
INSERT INTO monster_break_text VALUES(41,'en','Head');
INSERT INTO monster_break_text VALUES(42,'en','Body');
INSERT INTO monster_break_text VALUES(43,'en','Back');
INSERT INTO monster_break_text VALUES(44,'en','Forelegs');
INSERT INTO monster_break_text VALUES(45,'en','Hindlegs');
INSERT INTO monster_break_text VALUES(46,'en','Tail');
INSERT INTO monster_break_text VALUES(47,'en','Head');
INSERT INTO monster_break_text VALUES(48,'en','Body');
INSERT INTO monster_break_text VALUES(49,'en','Left Leg');
INSERT INTO monster_break_text VALUES(50,'en','Right Leg');
INSERT INTO monster_break_text VALUES(51,'en','Tail');
INSERT INTO monster_break_text VALUES(52,'en','Head');
INSERT INTO monster_break_text VALUES(53,'en','Body');
INSERT INTO monster_break_text VALUES(54,'en','Left Wing');
INSERT INTO monster_break_text VALUES(55,'en','Right Wing');
INSERT INTO monster_break_text VALUES(56,'en','Left Leg');
INSERT INTO monster_break_text VALUES(57,'en','Right Leg');
INSERT INTO monster_break_text VALUES(58,'en','Tail');
INSERT INTO monster_break_text VALUES(59,'en','Antennae');
INSERT INTO monster_break_text VALUES(60,'en','Head');
INSERT INTO monster_break_text VALUES(61,'en','Forearms');
INSERT INTO monster_break_text VALUES(62,'en','Body');
INSERT INTO monster_break_text VALUES(63,'en','Tail');
INSERT INTO monster_break_text VALUES(64,'en','Head');
INSERT INTO monster_break_text VALUES(65,'en','Neck Pouch');
INSERT INTO monster_break_text VALUES(66,'en','Body');
INSERT INTO monster_break_text VALUES(67,'en','Left Leg');
INSERT INTO monster_break_text VALUES(68,'en','Right Leg');
INSERT INTO monster_break_text VALUES(69,'en','Left Wing');
INSERT INTO monster_break_text VALUES(70,'en','Right Wing');
INSERT INTO monster_break_text VALUES(71,'en','Tail');
INSERT INTO monster_break_text VALUES(72,'en','Head');
INSERT INTO monster_break_text VALUES(73,'en','Body');
INSERT INTO monster_break_text VALUES(74,'en','Forearms');
INSERT INTO monster_break_text VALUES(75,'en','Legs');
INSERT INTO monster_break_text VALUES(76,'en','Tail');
INSERT INTO monster_break_text VALUES(77,'en','Head');
INSERT INTO monster_break_text VALUES(78,'en','Head Bone');
INSERT INTO monster_break_text VALUES(79,'en','Body');
INSERT INTO monster_break_text VALUES(80,'en','Back Bone');
INSERT INTO monster_break_text VALUES(81,'en','Left Hindleg');
INSERT INTO monster_break_text VALUES(82,'en','Left Hindleg Bone');
INSERT INTO monster_break_text VALUES(83,'en','Right Hindleg');
INSERT INTO monster_break_text VALUES(84,'en','Right Hindleg Bone');
INSERT INTO monster_break_text VALUES(85,'en','Tail');
INSERT INTO monster_break_text VALUES(86,'en','Head');
INSERT INTO monster_break_text VALUES(87,'en','Body');
INSERT INTO monster_break_text VALUES(88,'en','Left Wing');
INSERT INTO monster_break_text VALUES(89,'en','Right Wing');
INSERT INTO monster_break_text VALUES(90,'en','Left Leg');
INSERT INTO monster_break_text VALUES(91,'en','Right Leg');
INSERT INTO monster_break_text VALUES(92,'en','Tail');
INSERT INTO monster_break_text VALUES(93,'en','Head');
INSERT INTO monster_break_text VALUES(94,'en','Body');
INSERT INTO monster_break_text VALUES(95,'en','Forearms');
INSERT INTO monster_break_text VALUES(96,'en','Legs');
INSERT INTO monster_break_text VALUES(97,'en','Tail');
INSERT INTO monster_break_text VALUES(98,'en','Head');
INSERT INTO monster_break_text VALUES(99,'en','Body');
INSERT INTO monster_break_text VALUES(100,'en','Left Wing');
INSERT INTO monster_break_text VALUES(101,'en','Right Wing');
INSERT INTO monster_break_text VALUES(102,'en','Left Leg');
INSERT INTO monster_break_text VALUES(103,'en','Right Leg');
INSERT INTO monster_break_text VALUES(104,'en','Tail');
INSERT INTO monster_break_text VALUES(105,'en','Head');
INSERT INTO monster_break_text VALUES(106,'en','Body');
INSERT INTO monster_break_text VALUES(107,'en','Left Wing');
INSERT INTO monster_break_text VALUES(108,'en','Right Wing');
INSERT INTO monster_break_text VALUES(109,'en','Left Leg');
INSERT INTO monster_break_text VALUES(110,'en','Right Leg');
INSERT INTO monster_break_text VALUES(111,'en','Tail');
INSERT INTO monster_break_text VALUES(112,'en','Head');
INSERT INTO monster_break_text VALUES(113,'en','Upper Body');
INSERT INTO monster_break_text VALUES(114,'en','Lower Body');
INSERT INTO monster_break_text VALUES(115,'en','Head');
INSERT INTO monster_break_text VALUES(116,'en','Body');
INSERT INTO monster_break_text VALUES(117,'en','Chest');
INSERT INTO monster_break_text VALUES(118,'en','Left Foreleg');
INSERT INTO monster_break_text VALUES(119,'en','Right Foreleg');
INSERT INTO monster_break_text VALUES(120,'en','Left Hindleg');
INSERT INTO monster_break_text VALUES(121,'en','Right Hindleg');
INSERT INTO monster_break_text VALUES(122,'en','Tail');
INSERT INTO monster_break_text VALUES(123,'en','Shell');
INSERT INTO monster_break_text VALUES(124,'en','Exhaust Organ (Small)');
INSERT INTO monster_break_text VALUES(125,'en','Exhaust Organ (Large)');
INSERT INTO monster_break_text VALUES(126,'en','Weak Shell');
INSERT INTO monster_break_text VALUES(127,'en','Head');
INSERT INTO monster_break_text VALUES(128,'en','Body');
INSERT INTO monster_break_text VALUES(129,'en','Forelegs');
INSERT INTO monster_break_text VALUES(130,'en','Legs');
INSERT INTO monster_break_text VALUES(131,'en','Tail');
INSERT INTO monster_break_text VALUES(132,'en','Head');
INSERT INTO monster_break_text VALUES(133,'en','Body');
INSERT INTO monster_break_text VALUES(134,'en','Left Wing');
INSERT INTO monster_break_text VALUES(135,'en','Right Wing');
INSERT INTO monster_break_text VALUES(136,'en','Left Leg');
INSERT INTO monster_break_text VALUES(137,'en','Right Leg');
INSERT INTO monster_break_text VALUES(138,'en','Tail');
INSERT INTO monster_break_text VALUES(139,'en','Head');
INSERT INTO monster_break_text VALUES(140,'en','Body');
INSERT INTO monster_break_text VALUES(141,'en','Legs');
INSERT INTO monster_break_text VALUES(142,'en','Left Wing');
INSERT INTO monster_break_text VALUES(143,'en','Right Wing');
INSERT INTO monster_break_text VALUES(144,'en','Tail');
INSERT INTO monster_break_text VALUES(145,'en','Head');
INSERT INTO monster_break_text VALUES(146,'en','Body');
INSERT INTO monster_break_text VALUES(147,'en','Chest');
INSERT INTO monster_break_text VALUES(148,'en','Lower Body');
INSERT INTO monster_break_text VALUES(149,'en','Arms');
INSERT INTO monster_break_text VALUES(150,'en','Legs');
INSERT INTO monster_break_text VALUES(151,'en','Tail');
INSERT INTO monster_break_text VALUES(152,'en','Head');
INSERT INTO monster_break_text VALUES(153,'en','Back');
INSERT INTO monster_break_text VALUES(154,'en','Body');
INSERT INTO monster_break_text VALUES(155,'en','Left Foot');
INSERT INTO monster_break_text VALUES(156,'en','Right Foot');
INSERT INTO monster_break_text VALUES(157,'en','Tail');
INSERT INTO monster_break_text VALUES(158,'en','Head');
INSERT INTO monster_break_text VALUES(159,'en','Neck');
INSERT INTO monster_break_text VALUES(160,'en','Body');
INSERT INTO monster_break_text VALUES(161,'en','Forearms');
INSERT INTO monster_break_text VALUES(162,'en','Left Leg');
INSERT INTO monster_break_text VALUES(163,'en','Right Leg');
INSERT INTO monster_break_text VALUES(164,'en','Tail');
INSERT INTO monster_break_text VALUES(165,'en','Head');
INSERT INTO monster_break_text VALUES(166,'en','Body');
INSERT INTO monster_break_text VALUES(167,'en','Left Wing');
INSERT INTO monster_break_text VALUES(168,'en','Right Wing');
INSERT INTO monster_break_text VALUES(169,'en','Left Leg');
INSERT INTO monster_break_text VALUES(170,'en','Right Leg');
INSERT INTO monster_break_text VALUES(171,'en','Tail');
INSERT INTO monster_break_text VALUES(172,'en','Head');
INSERT INTO monster_break_text VALUES(173,'en','Body');
INSERT INTO monster_break_text VALUES(174,'en','Left Wing');
INSERT INTO monster_break_text VALUES(175,'en','Right Wing');
INSERT INTO monster_break_text VALUES(176,'en','Left Leg');
INSERT INTO monster_break_text VALUES(177,'en','Right Leg');
INSERT INTO monster_break_text VALUES(178,'en','Tail');
INSERT INTO monster_break_text VALUES(179,'en','Horns');
INSERT INTO monster_break_text VALUES(180,'en','Head');
INSERT INTO monster_break_text VALUES(181,'en','Body');
INSERT INTO monster_break_text VALUES(182,'en','Left Foreleg');
INSERT INTO monster_break_text VALUES(183,'en','Right Foreleg');
INSERT INTO monster_break_text VALUES(184,'en','Left Hindleg');
INSERT INTO monster_break_text VALUES(185,'en','Right Hindleg');
INSERT INTO monster_break_text VALUES(186,'en','Left Wing');
INSERT INTO monster_break_text VALUES(187,'en','Right Wing');
INSERT INTO monster_break_text VALUES(188,'en','Tail');
INSERT INTO monster_break_text VALUES(189,'en','Head');
INSERT INTO monster_break_text VALUES(190,'en','Body');
INSERT INTO monster_break_text VALUES(191,'en','Forelegs');
INSERT INTO monster_break_text VALUES(192,'en','Hindlegs');
INSERT INTO monster_break_text VALUES(193,'en','Wings');
INSERT INTO monster_break_text VALUES(194,'en','Tail');
INSERT INTO monster_break_text VALUES(195,'en','Head');
INSERT INTO monster_break_text VALUES(196,'en','Body');
INSERT INTO monster_break_text VALUES(197,'en','Forelegs');
INSERT INTO monster_break_text VALUES(198,'en','Hindlegs');
INSERT INTO monster_break_text VALUES(199,'en','Wings');
INSERT INTO monster_break_text VALUES(200,'en','Tail');
INSERT INTO monster_break_text VALUES(201,'en','Head');
INSERT INTO monster_break_text VALUES(202,'en','Body');
INSERT INTO monster_break_text VALUES(203,'en','Tail');
INSERT INTO monster_break_text VALUES(204,'en','Left Legs');
INSERT INTO monster_break_text VALUES(205,'en','Right Legs');
INSERT INTO monster_break_text VALUES(206,'en','Wings');
INSERT INTO monster_break_text VALUES(207,'en','Head');
INSERT INTO monster_break_text VALUES(208,'en','Chest');
INSERT INTO monster_break_text VALUES(209,'en','Body');
INSERT INTO monster_break_text VALUES(210,'en','Tail');
INSERT INTO monster_break_text VALUES(211,'en','Left Foreleg');
INSERT INTO monster_break_text VALUES(212,'en','Right Foreleg');
INSERT INTO monster_break_text VALUES(213,'en','Left Hindleg');
INSERT INTO monster_break_text VALUES(214,'en','Right Hindleg');
INSERT INTO monster_break_text VALUES(215,'en','Wings');
INSERT INTO monster_break_text VALUES(216,'en','Head');
INSERT INTO monster_break_text VALUES(217,'en','Neck');
INSERT INTO monster_break_text VALUES(218,'en','Body');
INSERT INTO monster_break_text VALUES(219,'en','Chest');
INSERT INTO monster_break_text VALUES(220,'en','Left Foreleg');
INSERT INTO monster_break_text VALUES(221,'en','Right Foreleg');
INSERT INTO monster_break_text VALUES(222,'en','Left Hindleg');
INSERT INTO monster_break_text VALUES(223,'en','Right Hindleg');
INSERT INTO monster_break_text VALUES(224,'en','Wings');
INSERT INTO monster_break_text VALUES(225,'en','Tail');
INSERT INTO monster_break_text VALUES(226,'en','Head');
INSERT INTO monster_break_text VALUES(227,'en','Body');
INSERT INTO monster_break_text VALUES(228,'en','Left Foreleg');
INSERT INTO monster_break_text VALUES(229,'en','Right Foreleg');
INSERT INTO monster_break_text VALUES(230,'en','Left Hindleg');
INSERT INTO monster_break_text VALUES(231,'en','Right Hindleg');
INSERT INTO monster_break_text VALUES(232,'en','Tail');
INSERT INTO monster_break_text VALUES(233,'en','Head');
INSERT INTO monster_break_text VALUES(234,'en','Body');
INSERT INTO monster_break_text VALUES(235,'en','Wings');
INSERT INTO monster_break_text VALUES(236,'en','Arms');
INSERT INTO monster_break_text VALUES(237,'en','Legs');
INSERT INTO monster_break_text VALUES(238,'en','Tail');
INSERT INTO monster_break_text VALUES(239,'en','Head');
INSERT INTO monster_break_text VALUES(240,'en','Neck');
INSERT INTO monster_break_text VALUES(241,'en','Chest');
INSERT INTO monster_break_text VALUES(242,'en','Back');
INSERT INTO monster_break_text VALUES(243,'en','Left Foreleg');
INSERT INTO monster_break_text VALUES(244,'en','Right Foreleg');
INSERT INTO monster_break_text VALUES(245,'en','Left Hindleg');
INSERT INTO monster_break_text VALUES(246,'en','Right Hindleg');
INSERT INTO monster_break_text VALUES(247,'en','Left Wing');
INSERT INTO monster_break_text VALUES(248,'en','Right Wing');
INSERT INTO monster_break_text VALUES(249,'en','Tail');
INSERT INTO monster_break_text VALUES(250,'en','Horns');
INSERT INTO monster_break_text VALUES(251,'en','Head');
INSERT INTO monster_break_text VALUES(252,'en','Back');
INSERT INTO monster_break_text VALUES(253,'en','Belly');
INSERT INTO monster_break_text VALUES(254,'en','Forearms');
INSERT INTO monster_break_text VALUES(255,'en','Hindlegs');
INSERT INTO monster_break_text VALUES(256,'en','Tail');

COMMIT;