BEGIN;

INSERT INTO armorset_text VALUES(1,'de','Leder-Set');
INSERT INTO armorset_text VALUES(2,'de','Ketten-Set');
INSERT INTO armorset_text VALUES(3,'de','Jäger-Set');
INSERT INTO armorset_text VALUES(4,'de','Knochen-Set');
INSERT INTO armorset_text VALUES(5,'de','Vespoid-Set');
INSERT INTO armorset_text VALUES(6,'de','Kestodon-Set');
INSERT INTO armorset_text VALUES(7,'de','Gajau-Set');
INSERT INTO armorset_text VALUES(8,'de','Jagras-Set');
INSERT INTO armorset_text VALUES(9,'de','Kulu-Set');
INSERT INTO armorset_text VALUES(10,'de','Legierungs-Set');
INSERT INTO armorset_text VALUES(11,'de','Pukei-Set');
INSERT INTO armorset_text VALUES(12,'de','Barroth-Set');
INSERT INTO armorset_text VALUES(13,'de','Jyuratodus-Set');
INSERT INTO armorset_text VALUES(14,'de','Kadachi-Set');
INSERT INTO armorset_text VALUES(15,'de','Hochmetall-Set');
INSERT INTO armorset_text VALUES(16,'de','Königskäfer-Set');
INSERT INTO armorset_text VALUES(17,'de','Shamos-Set');
INSERT INTO armorset_text VALUES(18,'de','Hornetaur-Set');
INSERT INTO armorset_text VALUES(19,'de','Anjanath-Set');
INSERT INTO armorset_text VALUES(20,'de','Rathian-Set');
INSERT INTO armorset_text VALUES(21,'de','Tzitzi-Set');
INSERT INTO armorset_text VALUES(22,'de','Paolumu-Set');
INSERT INTO armorset_text VALUES(23,'de','Girros-Set');
INSERT INTO armorset_text VALUES(24,'de','Baan-Set');
INSERT INTO armorset_text VALUES(25,'de','Guss-Set');
INSERT INTO armorset_text VALUES(26,'de','Todesgestank-Set');
INSERT INTO armorset_text VALUES(27,'de','Brigade-Set');
INSERT INTO armorset_text VALUES(28,'de','Legiana-Set');
INSERT INTO armorset_text VALUES(29,'de','Odogaron-Set');
INSERT INTO armorset_text VALUES(30,'de','Rathalos-Set');
INSERT INTO armorset_text VALUES(31,'de','Diablos-Set');
INSERT INTO armorset_text VALUES(32,'de','Kirin-Set');
INSERT INTO armorset_text VALUES(33,'de','Blüten-Set');
INSERT INTO armorset_text VALUES(34,'de','Taucher-Set');
INSERT INTO armorset_text VALUES(35,'de','Ernte-Set');
INSERT INTO armorset_text VALUES(36,'de','Orion-Set');
INSERT INTO armorset_text VALUES(37,'de','Galaanzug-Set');
INSERT INTO armorset_text VALUES(38,'de','Schmetterling-Set');
INSERT INTO armorset_text VALUES(39,'de','Leder-Set α');
INSERT INTO armorset_text VALUES(40,'de','Leder-Set β');
INSERT INTO armorset_text VALUES(41,'de','Ketten-Set α');
INSERT INTO armorset_text VALUES(42,'de','Ketten-Set β');
INSERT INTO armorset_text VALUES(43,'de','Jäger-Set α');
INSERT INTO armorset_text VALUES(44,'de','Jäger-Set β');
INSERT INTO armorset_text VALUES(45,'de','Knochen-Set α');
INSERT INTO armorset_text VALUES(46,'de','Knochen-Set β');
INSERT INTO armorset_text VALUES(47,'de','Legierungs-Set α');
INSERT INTO armorset_text VALUES(48,'de','Legierungs-Set β');
INSERT INTO armorset_text VALUES(49,'de','Königskäfer-Set α');
INSERT INTO armorset_text VALUES(50,'de','Königskäfer-Set β');
INSERT INTO armorset_text VALUES(51,'de','Vespoid-Set α');
INSERT INTO armorset_text VALUES(52,'de','Vespoid-Set β');
INSERT INTO armorset_text VALUES(53,'de','Hornetaur-Set α');
INSERT INTO armorset_text VALUES(54,'de','Hornetaur-Set β');
INSERT INTO armorset_text VALUES(55,'de','Mosswine-Set α');
INSERT INTO armorset_text VALUES(56,'de','Kestodon-Set α');
INSERT INTO armorset_text VALUES(57,'de','Kestodon-Set β');
INSERT INTO armorset_text VALUES(58,'de','Gajau-Set α');
INSERT INTO armorset_text VALUES(59,'de','Gajau-Set β');
INSERT INTO armorset_text VALUES(60,'de','Shamos-Set α');
INSERT INTO armorset_text VALUES(61,'de','Shamos-Set β');
INSERT INTO armorset_text VALUES(62,'de','Jagras-Set α');
INSERT INTO armorset_text VALUES(63,'de','Jagras-Set β');
INSERT INTO armorset_text VALUES(64,'de','Kulu-Set α');
INSERT INTO armorset_text VALUES(65,'de','Kulu-Set β');
INSERT INTO armorset_text VALUES(66,'de','Tzitzi-Set α');
INSERT INTO armorset_text VALUES(67,'de','Tzitzi-Set β');
INSERT INTO armorset_text VALUES(68,'de','Girros-Set α');
INSERT INTO armorset_text VALUES(69,'de','Girros-Set β');
INSERT INTO armorset_text VALUES(70,'de','Pukei-Set α');
INSERT INTO armorset_text VALUES(71,'de','Pukei-Set β');
INSERT INTO armorset_text VALUES(72,'de','Barroth-Set α');
INSERT INTO armorset_text VALUES(73,'de','Barroth-Set β');
INSERT INTO armorset_text VALUES(74,'de','Anjanath-Set α');
INSERT INTO armorset_text VALUES(75,'de','Anjanath-Set β');
INSERT INTO armorset_text VALUES(76,'de','Jyuratodus-Set α');
INSERT INTO armorset_text VALUES(77,'de','Jyuratodus-Set β');
INSERT INTO armorset_text VALUES(78,'de','Kadachi-Set α');
INSERT INTO armorset_text VALUES(79,'de','Kadachi-Set β');
INSERT INTO armorset_text VALUES(80,'de','Paolumu-Set α');
INSERT INTO armorset_text VALUES(81,'de','Paolumu-Set β');
INSERT INTO armorset_text VALUES(82,'de','Rathian-Set α');
INSERT INTO armorset_text VALUES(83,'de','Rathian-Set β');
INSERT INTO armorset_text VALUES(84,'de','Rathianherz-Set α');
INSERT INTO armorset_text VALUES(85,'de','Rathianherz-Set β');
INSERT INTO armorset_text VALUES(86,'de','Baan-Set α');
INSERT INTO armorset_text VALUES(87,'de','Baan-Set β');
INSERT INTO armorset_text VALUES(88,'de','Gastodon-Set α');
INSERT INTO armorset_text VALUES(89,'de','Gastodon-Set β');
INSERT INTO armorset_text VALUES(90,'de','Barnos-Set α');
INSERT INTO armorset_text VALUES(91,'de','Barnos-Set β');
INSERT INTO armorset_text VALUES(92,'de','Dodogama-Set α');
INSERT INTO armorset_text VALUES(93,'de','Dodogama-Set β');
INSERT INTO armorset_text VALUES(94,'de','Zorah-Set α');
INSERT INTO armorset_text VALUES(95,'de','Zorah-Set β');
INSERT INTO armorset_text VALUES(96,'de','Hochmetall-Set α');
INSERT INTO armorset_text VALUES(97,'de','Hochmetall-Set β');
INSERT INTO armorset_text VALUES(98,'de','Guss-Set α');
INSERT INTO armorset_text VALUES(99,'de','Guss-Set β');
INSERT INTO armorset_text VALUES(100,'de','Brigade-Set α');
INSERT INTO armorset_text VALUES(101,'de','Brigade-Set β');
INSERT INTO armorset_text VALUES(102,'de','Falscher-Felyne-Set α');
INSERT INTO armorset_text VALUES(103,'de','Strategiker-Set α');
INSERT INTO armorset_text VALUES(104,'de','Lavasioth-Set α');
INSERT INTO armorset_text VALUES(105,'de','Lavasioth-Set β');
INSERT INTO armorset_text VALUES(106,'de','Legiana-Set α');
INSERT INTO armorset_text VALUES(107,'de','Legiana-Set β');
INSERT INTO armorset_text VALUES(108,'de','Odogaron-Set α');
INSERT INTO armorset_text VALUES(109,'de','Odogaron-Set β');
INSERT INTO armorset_text VALUES(110,'de','Rathalos-Set α');
INSERT INTO armorset_text VALUES(111,'de','Rathalos-Set β');
INSERT INTO armorset_text VALUES(112,'de','Rathalosseelen-Set α');
INSERT INTO armorset_text VALUES(113,'de','Rathalosseelen-Set β');
INSERT INTO armorset_text VALUES(114,'de','Diablos-Set α');
INSERT INTO armorset_text VALUES(115,'de','Diablos-Set β');
INSERT INTO armorset_text VALUES(116,'de','Diablos-Nero-Set α');
INSERT INTO armorset_text VALUES(117,'de','Diablos-Nero-Set β');
INSERT INTO armorset_text VALUES(118,'de','Uragaan-Set α');
INSERT INTO armorset_text VALUES(119,'de','Uragaan-Set β');
INSERT INTO armorset_text VALUES(120,'de','Bazel-Set α');
INSERT INTO armorset_text VALUES(121,'de','Bazel-Set β');
INSERT INTO armorset_text VALUES(122,'de','Damaskus-Set α');
INSERT INTO armorset_text VALUES(123,'de','Damaskus-Set β');
INSERT INTO armorset_text VALUES(124,'de','Dober-Set α');
INSERT INTO armorset_text VALUES(125,'de','Dober-Set β');
INSERT INTO armorset_text VALUES(126,'de','Todesgestank-Set α');
INSERT INTO armorset_text VALUES(127,'de','Todesgestank-Set β');
INSERT INTO armorset_text VALUES(128,'de','Schädel-Set α');
INSERT INTO armorset_text VALUES(129,'de','Nergigante-Set α');
INSERT INTO armorset_text VALUES(130,'de','Nergigante-Set β');
INSERT INTO armorset_text VALUES(131,'de','Kaiser-Set α');
INSERT INTO armorset_text VALUES(132,'de','Kaiser-Set β');
INSERT INTO armorset_text VALUES(133,'de','Kushala-Set α');
INSERT INTO armorset_text VALUES(134,'de','Kushala-Set β');
INSERT INTO armorset_text VALUES(135,'de','Vaal-Hazak-Set α');
INSERT INTO armorset_text VALUES(136,'de','Vaal-Hazak-Set β');
INSERT INTO armorset_text VALUES(137,'de','Kirin-Set α');
INSERT INTO armorset_text VALUES(138,'de','Kirin-Set β');
INSERT INTO armorset_text VALUES(139,'de','Xeno''jiiva-Set α');
INSERT INTO armorset_text VALUES(140,'de','Xeno''jiiva-Set β');
INSERT INTO armorset_text VALUES(141,'de','Gildenkreuz-Set α');
INSERT INTO armorset_text VALUES(142,'de','Gildenkreuz-Set β');
INSERT INTO armorset_text VALUES(143,'de','Drachenkönig-Set α');
INSERT INTO armorset_text VALUES(144,'de','Kommissionsset α');
INSERT INTO armorset_text VALUES(145,'de','Kommissionsset β');
INSERT INTO armorset_text VALUES(146,'de','Dämonjho-Set α');
INSERT INTO armorset_text VALUES(147,'de','Dämonjho-Set β');
INSERT INTO armorset_text VALUES(148,'de','Kulve-Taroth-Set α');
INSERT INTO armorset_text VALUES(149,'de','Kulve-Taroth-Set β');
INSERT INTO armorset_text VALUES(150,'de','Kaiserin-Set α');
INSERT INTO armorset_text VALUES(151,'de','Kaiserin-Set β');
INSERT INTO armorset_text VALUES(152,'de','Blüten-Set α');
INSERT INTO armorset_text VALUES(153,'de','Taucher-Set α');
INSERT INTO armorset_text VALUES(154,'de','Ernte-Set α');
INSERT INTO armorset_text VALUES(155,'de','Orion-Set α');
INSERT INTO armorset_text VALUES(156,'de','Galaanzug-Set α');
INSERT INTO armorset_text VALUES(157,'de','Schmetterling-Set α');
INSERT INTO armorset_text VALUES(158,'de','Schmetterling-Set β');
INSERT INTO armorset_text VALUES(159,'de','Vaal-Hazak-Set γ');
INSERT INTO armorset_text VALUES(160,'de','Kirin-Set γ');
INSERT INTO armorset_text VALUES(161,'de','Kaiser-Set γ');
INSERT INTO armorset_text VALUES(162,'de','Kushala-Set γ');
INSERT INTO armorset_text VALUES(163,'de','Nergigante-Set γ');
INSERT INTO armorset_text VALUES(164,'de','Zorah-Set γ');
INSERT INTO armorset_text VALUES(165,'de','Xeno''jiiva-Set γ');
INSERT INTO armorset_text VALUES(166,'de','Kaiserin-Set γ');
INSERT INTO armorset_text VALUES(167,'de','Kulve-Taroth-Set γ');
INSERT INTO armorset_text VALUES(168,'de','Azurstern-Gebieter-Set α');
INSERT INTO armorset_text VALUES(169,'de','Dante-Set α');
INSERT INTO armorset_text VALUES(170,'de','Drachenreiter-Set α');
INSERT INTO armorset_text VALUES(171,'de','Dichte Augenklappe α');
INSERT INTO armorset_text VALUES(172,'de','Schatten-Sonnenbrille α');
INSERT INTO armorset_text VALUES(173,'de','Kulu-Ya-Ku-Kopf α');
INSERT INTO armorset_text VALUES(174,'de','Wackelwurm-Kopf α');
INSERT INTO armorset_text VALUES(175,'de','Knochen-Set α+');
INSERT INTO armorset_text VALUES(176,'de','Knochen-Set β+');
INSERT INTO armorset_text VALUES(177,'de','Legierungs-Set α+');
INSERT INTO armorset_text VALUES(178,'de','Legierungs-Set β+');
INSERT INTO armorset_text VALUES(179,'de','Vespoid-Set α+');
INSERT INTO armorset_text VALUES(180,'de','Vespoid-Set β+');
INSERT INTO armorset_text VALUES(181,'de','Hornetaur-Set α+');
INSERT INTO armorset_text VALUES(182,'de','Hornetaur-Set β+');
INSERT INTO armorset_text VALUES(183,'de','Kestodon-Set α+');
INSERT INTO armorset_text VALUES(184,'de','Kestodon-Set β+');
INSERT INTO armorset_text VALUES(185,'de','Gajau-Set α+');
INSERT INTO armorset_text VALUES(186,'de','Gajau-Set β+');
INSERT INTO armorset_text VALUES(187,'de','Shamos-Set α+');
INSERT INTO armorset_text VALUES(188,'de','Shamos-Set β+');
INSERT INTO armorset_text VALUES(189,'de','Gastodon-Set α+');
INSERT INTO armorset_text VALUES(190,'de','Gastodon-Set β+');
INSERT INTO armorset_text VALUES(191,'de','Barnos-Set α+');
INSERT INTO armorset_text VALUES(192,'de','Barnos-Set β+');
INSERT INTO armorset_text VALUES(193,'de','Wulg-Set α+');
INSERT INTO armorset_text VALUES(194,'de','Wulg-Set β+');
INSERT INTO armorset_text VALUES(195,'de','Cortos-Set α+');
INSERT INTO armorset_text VALUES(196,'de','Cortos-Set β+');
INSERT INTO armorset_text VALUES(197,'de','Jagras-Set α+');
INSERT INTO armorset_text VALUES(198,'de','Jagras-Set β+');
INSERT INTO armorset_text VALUES(199,'de','Tzitzi-Set α+');
INSERT INTO armorset_text VALUES(200,'de','Tzitzi-Set β+');
INSERT INTO armorset_text VALUES(201,'de','Girros-Set α+');
INSERT INTO armorset_text VALUES(202,'de','Girros-Set β+');
INSERT INTO armorset_text VALUES(203,'de','Dodogama-Set α+');
INSERT INTO armorset_text VALUES(204,'de','Dodogama-Set β+');
INSERT INTO armorset_text VALUES(205,'de','Kulu-Set α+');
INSERT INTO armorset_text VALUES(206,'de','Kulu-Set β+');
INSERT INTO armorset_text VALUES(207,'de','Pukei-Set α+');
INSERT INTO armorset_text VALUES(208,'de','Pukei-Set β+');
INSERT INTO armorset_text VALUES(209,'de','Korallen-Set α+');
INSERT INTO armorset_text VALUES(210,'de','Korallen-Set β+');
INSERT INTO armorset_text VALUES(211,'de','Barroth-Set α+');
INSERT INTO armorset_text VALUES(212,'de','Barroth-Set β+');
INSERT INTO armorset_text VALUES(213,'de','Jyuratodus-Set α+');
INSERT INTO armorset_text VALUES(214,'de','Jyuratodus-Set β+');
INSERT INTO armorset_text VALUES(215,'de','Beo-Set α+');
INSERT INTO armorset_text VALUES(216,'de','Beo-Set β+');
INSERT INTO armorset_text VALUES(217,'de','Kadachi-Set α+');
INSERT INTO armorset_text VALUES(218,'de','Kadachi-Set β+');
INSERT INTO armorset_text VALUES(219,'de','Viper-Set α+');
INSERT INTO armorset_text VALUES(220,'de','Viper-Set β+');
INSERT INTO armorset_text VALUES(221,'de','Hochmetall-Set α+');
INSERT INTO armorset_text VALUES(222,'de','Hochmetall-Set β+');
INSERT INTO armorset_text VALUES(223,'de','Banbaro-Set α+');
INSERT INTO armorset_text VALUES(224,'de','Banbaro-Set β+');
INSERT INTO armorset_text VALUES(225,'de','Anjanath-Set α+');
INSERT INTO armorset_text VALUES(226,'de','Anjanath-Set β+');
INSERT INTO armorset_text VALUES(227,'de','Fulgur-Set α+');
INSERT INTO armorset_text VALUES(228,'de','Fulgur-Set β+');
INSERT INTO armorset_text VALUES(229,'de','Rathian-Set α+');
INSERT INTO armorset_text VALUES(230,'de','Rathian-Set β+');
INSERT INTO armorset_text VALUES(231,'de','Rathianherz-Set α+');
INSERT INTO armorset_text VALUES(232,'de','Rathianherz-Set β+');
INSERT INTO armorset_text VALUES(233,'de','Paolumu-Set α+');
INSERT INTO armorset_text VALUES(234,'de','Paolumu-Set β+');
INSERT INTO armorset_text VALUES(235,'de','Nachtschatten-Set α+');
INSERT INTO armorset_text VALUES(236,'de','Nachtschatten-Set β+');
INSERT INTO armorset_text VALUES(237,'de','Baan-Set α+');
INSERT INTO armorset_text VALUES(238,'de','Baan-Set β+');
INSERT INTO armorset_text VALUES(239,'de','Artian-Set α+');
INSERT INTO armorset_text VALUES(240,'de','Artian-Set β+');
INSERT INTO armorset_text VALUES(241,'de','Steampunk-Set α+');
INSERT INTO armorset_text VALUES(242,'de','Steampunk-Set β+');
INSERT INTO armorset_text VALUES(243,'de','Guss-Set α+');
INSERT INTO armorset_text VALUES(244,'de','Guss-Set β+');
INSERT INTO armorset_text VALUES(245,'de','Barioth-Set α+');
INSERT INTO armorset_text VALUES(246,'de','Barioth-Set β+');
INSERT INTO armorset_text VALUES(247,'de','Rathalos-Set α+');
INSERT INTO armorset_text VALUES(248,'de','Rathalos-Set β+');
INSERT INTO armorset_text VALUES(249,'de','Rathalosseelen-Set α+');
INSERT INTO armorset_text VALUES(250,'de','Rathalosseelen-Set β+');
INSERT INTO armorset_text VALUES(251,'de','Diablos-Set α+');
INSERT INTO armorset_text VALUES(252,'de','Diablos-Set β+');
INSERT INTO armorset_text VALUES(253,'de','Diablos-Nero-Set α+');
INSERT INTO armorset_text VALUES(254,'de','Diablos-Nero-Set β+');
INSERT INTO armorset_text VALUES(255,'de','Legiana-Set α+');
INSERT INTO armorset_text VALUES(256,'de','Legiana-Set β+');
INSERT INTO armorset_text VALUES(257,'de','Schneesturm-Set α+');
INSERT INTO armorset_text VALUES(258,'de','Schneesturm-Set β+');
INSERT INTO armorset_text VALUES(259,'de','Odogaron-Set α+');
INSERT INTO armorset_text VALUES(260,'de','Odogaron-Set β+');
INSERT INTO armorset_text VALUES(261,'de','Vulkan-Set α+');
INSERT INTO armorset_text VALUES(262,'de','Vulkan-Set β+');
INSERT INTO armorset_text VALUES(263,'de','Lavasioth-Set α+');
INSERT INTO armorset_text VALUES(264,'de','Lavasioth-Set β+');
INSERT INTO armorset_text VALUES(265,'de','Uragaan-Set α+');
INSERT INTO armorset_text VALUES(266,'de','Uragaan-Set β+');
INSERT INTO armorset_text VALUES(267,'de','Nargacuga-Set α+');
INSERT INTO armorset_text VALUES(268,'de','Nargacuga-Set β+');
INSERT INTO armorset_text VALUES(269,'de','Glavenus-Set α+');
INSERT INTO armorset_text VALUES(270,'de','Glavenus-Set β+');
INSERT INTO armorset_text VALUES(271,'de','Säure-Set α+');
INSERT INTO armorset_text VALUES(272,'de','Säure-Set β+');
INSERT INTO armorset_text VALUES(273,'de','Brachydios-Set α+');
INSERT INTO armorset_text VALUES(274,'de','Brachydios-Set β+');
INSERT INTO armorset_text VALUES(275,'de','Tigrex-Set α+');
INSERT INTO armorset_text VALUES(276,'de','Tigrex-Set β+');
INSERT INTO armorset_text VALUES(277,'de','Brachial-Set α+');
INSERT INTO armorset_text VALUES(278,'de','Brachial-Set β+');
INSERT INTO armorset_text VALUES(279,'de','Schwarzgurt-Set α+');
INSERT INTO armorset_text VALUES(280,'de','Schwarzgurt-Set β+');
INSERT INTO armorset_text VALUES(281,'de','Dober-Set α+');
INSERT INTO armorset_text VALUES(282,'de','Dober-Set β+');
INSERT INTO armorset_text VALUES(283,'de','Damaskus-Set α+');
INSERT INTO armorset_text VALUES(284,'de','Damaskus-Set β+');
INSERT INTO armorset_text VALUES(285,'de','Brodelnder-Set α+');
INSERT INTO armorset_text VALUES(286,'de','Brodelnder-Set β+');
INSERT INTO armorset_text VALUES(287,'de','Wilder-Jho-Set α+');
INSERT INTO armorset_text VALUES(288,'de','Wilder-Jho-Set β+');
INSERT INTO armorset_text VALUES(289,'de','Velkhana-Set α+');
INSERT INTO armorset_text VALUES(290,'de','Velkhana-Set β+');
INSERT INTO armorset_text VALUES(291,'de','Velum-Set α+');
INSERT INTO armorset_text VALUES(292,'de','Velum-Set β+');
INSERT INTO armorset_text VALUES(293,'de','Kaiser-Set α+');
INSERT INTO armorset_text VALUES(294,'de','Kaiser-Set β+');
INSERT INTO armorset_text VALUES(295,'de','Kushala-Set α+');
INSERT INTO armorset_text VALUES(296,'de','Kushala-Set β+');
INSERT INTO armorset_text VALUES(297,'de','Kirin-Set α+');
INSERT INTO armorset_text VALUES(298,'de','Kirin-Set β+');
INSERT INTO armorset_text VALUES(299,'de','Namielle-Set α+');
INSERT INTO armorset_text VALUES(300,'de','Namielle-Set β+');
INSERT INTO armorset_text VALUES(301,'de','Palast-Set α+');
INSERT INTO armorset_text VALUES(302,'de','Palast-Set β+');
INSERT INTO armorset_text VALUES(303,'de','Shara-Ishvalda-Set α+');
INSERT INTO armorset_text VALUES(304,'de','Shara-Ishvalda-Set β+');
INSERT INTO armorset_text VALUES(305,'de','Zorah-Set α+');
INSERT INTO armorset_text VALUES(306,'de','Zorah-Set β+');
INSERT INTO armorset_text VALUES(307,'de','Yian-Garuga-Set α+');
INSERT INTO armorset_text VALUES(308,'de','Yian-Garuga-Set β+');
INSERT INTO armorset_text VALUES(309,'de','Zinogre-Set α+');
INSERT INTO armorset_text VALUES(310,'de','Zinogre-Set β+');
INSERT INTO armorset_text VALUES(311,'de','Gold-Mond-Set α+');
INSERT INTO armorset_text VALUES(312,'de','Gold-Mond-Set β+');
INSERT INTO armorset_text VALUES(313,'de','Silber-Sonnen-Set α+');
INSERT INTO armorset_text VALUES(314,'de','Silber-Sonnen-Set β+');
INSERT INTO armorset_text VALUES(315,'de','Kaiserin-Set α+');
INSERT INTO armorset_text VALUES(316,'de','Kaiserin-Set β+');
INSERT INTO armorset_text VALUES(317,'de','Ruinen-Set α+');
INSERT INTO armorset_text VALUES(318,'de','Ruinen-Set β+');
INSERT INTO armorset_text VALUES(319,'de','Gildenuniform-Set α+');
INSERT INTO armorset_text VALUES(320,'de','Gildenuniform-Set β+');
INSERT INTO armorset_text VALUES(321,'de','Rajang-Set α+');
INSERT INTO armorset_text VALUES(322,'de','Rajang-Set β+');
INSERT INTO armorset_text VALUES(323,'de','Zorniger-Rajang-Set α+');
INSERT INTO armorset_text VALUES(324,'de','Zorniger-Rajang-Set β+');
INSERT INTO armorset_text VALUES(325,'de','Höllen-Zinogre-Set α+');
INSERT INTO armorset_text VALUES(326,'de','Höllen-Zinogre-Set β+');
INSERT INTO armorset_text VALUES(327,'de','Safi''jiiva-Set α+');
INSERT INTO armorset_text VALUES(328,'de','Safi''jiiva-Set β+');
INSERT INTO armorset_text VALUES(329,'de','Wütiger-Brachydium-Set α+');
INSERT INTO armorset_text VALUES(330,'de','Wütiger-Brachydium-Set β+');
INSERT INTO armorset_text VALUES(331,'de','Frosthauer-Barioth-Set α+');
INSERT INTO armorset_text VALUES(332,'de','Frosthauer-Barioth-Set β+');
INSERT INTO armorset_text VALUES(333,'de','Alatreon-Set α+');
INSERT INTO armorset_text VALUES(334,'de','Alatreon-Set β+');
INSERT INTO armorset_text VALUES(335,'de','Kulve-Taroth-Set α+');
INSERT INTO armorset_text VALUES(336,'de','Kulve-Taroth-Set β+');
INSERT INTO armorset_text VALUES(337,'de','Namielle γ+');
INSERT INTO armorset_text VALUES(338,'de','Velkhana γ+');
INSERT INTO armorset_text VALUES(339,'de','Oolong-Set α+');
INSERT INTO armorset_text VALUES(340,'de','Astral-Set α+');
INSERT INTO armorset_text VALUES(341,'de','Rosen-Set α+');
INSERT INTO armorset_text VALUES(342,'de','Passionate α+');
INSERT INTO armorset_text VALUES(343,'de','Demonlord α+');
INSERT INTO armorset_text VALUES(344,'de','Dragon α+');
INSERT INTO armorset_text VALUES(345,'de','Dragon β+');
INSERT INTO armorset_text VALUES(346,'de','Azure Age α+');
INSERT INTO armorset_text VALUES(347,'de','Artemis α+');
INSERT INTO armorset_text VALUES(348,'de','Perlenquell-Set α+');
INSERT INTO armorset_text VALUES(349,'de','Bauschpinguin-Maske α+');
INSERT INTO armorset_text VALUES(350,'de','Drachenstoff-Schal α+');
INSERT INTO armorset_text VALUES(351,'de','Wyverianer-Ohren α+');
INSERT INTO armorset_text VALUES(1,'en','Leather');
INSERT INTO armorset_text VALUES(2,'en','Chainmail');
INSERT INTO armorset_text VALUES(3,'en','Hunter''s');
INSERT INTO armorset_text VALUES(4,'en','Bone');
INSERT INTO armorset_text VALUES(5,'en','Vespoid');
INSERT INTO armorset_text VALUES(6,'en','Kestodon');
INSERT INTO armorset_text VALUES(7,'en','Gajau');
INSERT INTO armorset_text VALUES(8,'en','Jagras');
INSERT INTO armorset_text VALUES(9,'en','Kulu');
INSERT INTO armorset_text VALUES(10,'en','Alloy');
INSERT INTO armorset_text VALUES(11,'en','Pukei');
INSERT INTO armorset_text VALUES(12,'en','Barroth');
INSERT INTO armorset_text VALUES(13,'en','Jyura');
INSERT INTO armorset_text VALUES(14,'en','Kadachi');
INSERT INTO armorset_text VALUES(15,'en','High Metal');
INSERT INTO armorset_text VALUES(16,'en','King Beetle');
INSERT INTO armorset_text VALUES(17,'en','Shamos');
INSERT INTO armorset_text VALUES(18,'en','Hornetaur');
INSERT INTO armorset_text VALUES(19,'en','Anja');
INSERT INTO armorset_text VALUES(20,'en','Rathian');
INSERT INTO armorset_text VALUES(21,'en','Tzitzi');
INSERT INTO armorset_text VALUES(22,'en','Lumu');
INSERT INTO armorset_text VALUES(23,'en','Girros');
INSERT INTO armorset_text VALUES(24,'en','Baan');
INSERT INTO armorset_text VALUES(25,'en','Ingot');
INSERT INTO armorset_text VALUES(26,'en','Death Stench');
INSERT INTO armorset_text VALUES(27,'en','Brigade');
INSERT INTO armorset_text VALUES(28,'en','Legiana');
INSERT INTO armorset_text VALUES(29,'en','Odogaron');
INSERT INTO armorset_text VALUES(30,'en','Rathalos');
INSERT INTO armorset_text VALUES(31,'en','Diablos');
INSERT INTO armorset_text VALUES(32,'en','Kirin');
INSERT INTO armorset_text VALUES(33,'en','Blossom');
INSERT INTO armorset_text VALUES(34,'en','Diver');
INSERT INTO armorset_text VALUES(35,'en','Harvest');
INSERT INTO armorset_text VALUES(36,'en','Orion');
INSERT INTO armorset_text VALUES(37,'en','Gala Suit');
INSERT INTO armorset_text VALUES(38,'en','Butterfly');
INSERT INTO armorset_text VALUES(39,'en','Leather α');
INSERT INTO armorset_text VALUES(40,'en','Leather β');
INSERT INTO armorset_text VALUES(41,'en','Chainmail α');
INSERT INTO armorset_text VALUES(42,'en','Chainmail β');
INSERT INTO armorset_text VALUES(43,'en','Hunter''s α');
INSERT INTO armorset_text VALUES(44,'en','Hunter''s β');
INSERT INTO armorset_text VALUES(45,'en','Bone α');
INSERT INTO armorset_text VALUES(46,'en','Bone β');
INSERT INTO armorset_text VALUES(47,'en','Alloy α');
INSERT INTO armorset_text VALUES(48,'en','Alloy β');
INSERT INTO armorset_text VALUES(49,'en','King Beetle α');
INSERT INTO armorset_text VALUES(50,'en','King Beetle β');
INSERT INTO armorset_text VALUES(51,'en','Vespoid α');
INSERT INTO armorset_text VALUES(52,'en','Vespoid β');
INSERT INTO armorset_text VALUES(53,'en','Hornetaur α');
INSERT INTO armorset_text VALUES(54,'en','Hornetaur β');
INSERT INTO armorset_text VALUES(55,'en','Mosswine Mask α');
INSERT INTO armorset_text VALUES(56,'en','Kestodon α');
INSERT INTO armorset_text VALUES(57,'en','Kestodon β');
INSERT INTO armorset_text VALUES(58,'en','Gajau α');
INSERT INTO armorset_text VALUES(59,'en','Gajau β');
INSERT INTO armorset_text VALUES(60,'en','Shamos α');
INSERT INTO armorset_text VALUES(61,'en','Shamos β');
INSERT INTO armorset_text VALUES(62,'en','Jagras α');
INSERT INTO armorset_text VALUES(63,'en','Jagras β');
INSERT INTO armorset_text VALUES(64,'en','Kulu α');
INSERT INTO armorset_text VALUES(65,'en','Kulu β');
INSERT INTO armorset_text VALUES(66,'en','Tzitzi α');
INSERT INTO armorset_text VALUES(67,'en','Tzitzi β');
INSERT INTO armorset_text VALUES(68,'en','Girros α');
INSERT INTO armorset_text VALUES(69,'en','Girros β');
INSERT INTO armorset_text VALUES(70,'en','Pukei α');
INSERT INTO armorset_text VALUES(71,'en','Pukei β');
INSERT INTO armorset_text VALUES(72,'en','Barroth α');
INSERT INTO armorset_text VALUES(73,'en','Barroth β');
INSERT INTO armorset_text VALUES(74,'en','Anja α');
INSERT INTO armorset_text VALUES(75,'en','Anja β');
INSERT INTO armorset_text VALUES(76,'en','Jyura α');
INSERT INTO armorset_text VALUES(77,'en','Jyura β');
INSERT INTO armorset_text VALUES(78,'en','Kadachi α');
INSERT INTO armorset_text VALUES(79,'en','Kadachi β');
INSERT INTO armorset_text VALUES(80,'en','Lumu α');
INSERT INTO armorset_text VALUES(81,'en','Lumu β');
INSERT INTO armorset_text VALUES(82,'en','Rathian α');
INSERT INTO armorset_text VALUES(83,'en','Rathian β');
INSERT INTO armorset_text VALUES(84,'en','Rath Heart α');
INSERT INTO armorset_text VALUES(85,'en','Rath Heart β');
INSERT INTO armorset_text VALUES(86,'en','Baan α');
INSERT INTO armorset_text VALUES(87,'en','Baan β');
INSERT INTO armorset_text VALUES(88,'en','Gastodon α');
INSERT INTO armorset_text VALUES(89,'en','Gastodon β');
INSERT INTO armorset_text VALUES(90,'en','Barnos α');
INSERT INTO armorset_text VALUES(91,'en','Barnos β');
INSERT INTO armorset_text VALUES(92,'en','Dodogama α');
INSERT INTO armorset_text VALUES(93,'en','Dodogama β');
INSERT INTO armorset_text VALUES(94,'en','Zorah α');
INSERT INTO armorset_text VALUES(95,'en','Zorah β');
INSERT INTO armorset_text VALUES(96,'en','High Metal α');
INSERT INTO armorset_text VALUES(97,'en','High Metal β');
INSERT INTO armorset_text VALUES(98,'en','Ingot α');
INSERT INTO armorset_text VALUES(99,'en','Ingot β');
INSERT INTO armorset_text VALUES(100,'en','Brigade α');
INSERT INTO armorset_text VALUES(101,'en','Brigade β');
INSERT INTO armorset_text VALUES(102,'en','Faux Felyne α');
INSERT INTO armorset_text VALUES(103,'en','Strategist α');
INSERT INTO armorset_text VALUES(104,'en','Lavasioth α');
INSERT INTO armorset_text VALUES(105,'en','Lavasioth β');
INSERT INTO armorset_text VALUES(106,'en','Legiana α');
INSERT INTO armorset_text VALUES(107,'en','Legiana β');
INSERT INTO armorset_text VALUES(108,'en','Odogaron α');
INSERT INTO armorset_text VALUES(109,'en','Odogaron β');
INSERT INTO armorset_text VALUES(110,'en','Rathalos α');
INSERT INTO armorset_text VALUES(111,'en','Rathalos β');
INSERT INTO armorset_text VALUES(112,'en','Rath Soul α');
INSERT INTO armorset_text VALUES(113,'en','Rath Soul β');
INSERT INTO armorset_text VALUES(114,'en','Diablos α');
INSERT INTO armorset_text VALUES(115,'en','Diablos β');
INSERT INTO armorset_text VALUES(116,'en','Diablos Nero α');
INSERT INTO armorset_text VALUES(117,'en','Diablos Nero β');
INSERT INTO armorset_text VALUES(118,'en','Uragaan α');
INSERT INTO armorset_text VALUES(119,'en','Uragaan β');
INSERT INTO armorset_text VALUES(120,'en','Bazel α');
INSERT INTO armorset_text VALUES(121,'en','Bazel β');
INSERT INTO armorset_text VALUES(122,'en','Damascus α');
INSERT INTO armorset_text VALUES(123,'en','Damascus β');
INSERT INTO armorset_text VALUES(124,'en','Dober α');
INSERT INTO armorset_text VALUES(125,'en','Dober β');
INSERT INTO armorset_text VALUES(126,'en','Death Stench α');
INSERT INTO armorset_text VALUES(127,'en','Death Stench β');
INSERT INTO armorset_text VALUES(128,'en','Skull α');
INSERT INTO armorset_text VALUES(129,'en','Nergigante α');
INSERT INTO armorset_text VALUES(130,'en','Nergigante β');
INSERT INTO armorset_text VALUES(131,'en','Teostra α');
INSERT INTO armorset_text VALUES(132,'en','Teostra β');
INSERT INTO armorset_text VALUES(133,'en','Kushala α');
INSERT INTO armorset_text VALUES(134,'en','Kushala β');
INSERT INTO armorset_text VALUES(135,'en','Vaal Hazak α');
INSERT INTO armorset_text VALUES(136,'en','Vaal Hazak β');
INSERT INTO armorset_text VALUES(137,'en','Kirin α');
INSERT INTO armorset_text VALUES(138,'en','Kirin β');
INSERT INTO armorset_text VALUES(139,'en','Xeno''jiiva α');
INSERT INTO armorset_text VALUES(140,'en','Xeno''jiiva β');
INSERT INTO armorset_text VALUES(141,'en','Guild Cross α');
INSERT INTO armorset_text VALUES(142,'en','Guild Cross β');
INSERT INTO armorset_text VALUES(143,'en','Dragonking α');
INSERT INTO armorset_text VALUES(144,'en','Commission α');
INSERT INTO armorset_text VALUES(145,'en','Commission β');
INSERT INTO armorset_text VALUES(146,'en','Deviljho α');
INSERT INTO armorset_text VALUES(147,'en','Deviljho β');
INSERT INTO armorset_text VALUES(148,'en','Kulve Taroth α');
INSERT INTO armorset_text VALUES(149,'en','Kulve Taroth β');
INSERT INTO armorset_text VALUES(150,'en','Lunastra α');
INSERT INTO armorset_text VALUES(151,'en','Lunastra β');
INSERT INTO armorset_text VALUES(152,'en','Blossom α');
INSERT INTO armorset_text VALUES(153,'en','Diver α');
INSERT INTO armorset_text VALUES(154,'en','Harvest α');
INSERT INTO armorset_text VALUES(155,'en','Orion α');
INSERT INTO armorset_text VALUES(156,'en','Gala Suit α');
INSERT INTO armorset_text VALUES(157,'en','Butterfly α');
INSERT INTO armorset_text VALUES(158,'en','Butterfly β');
INSERT INTO armorset_text VALUES(159,'en','Vaal Hazak γ');
INSERT INTO armorset_text VALUES(160,'en','Kirin γ');
INSERT INTO armorset_text VALUES(161,'en','Teostra γ');
INSERT INTO armorset_text VALUES(162,'en','Kushala γ');
INSERT INTO armorset_text VALUES(163,'en','Nergigante γ');
INSERT INTO armorset_text VALUES(164,'en','Zorah γ');
INSERT INTO armorset_text VALUES(165,'en','Xeno''jiiva γ');
INSERT INTO armorset_text VALUES(166,'en','Lunastra γ');
INSERT INTO armorset_text VALUES(167,'en','Kulve Taroth γ');
INSERT INTO armorset_text VALUES(168,'en','Azure Starlord α');
INSERT INTO armorset_text VALUES(169,'en','Dante α');
INSERT INTO armorset_text VALUES(170,'en','Drachen α');
INSERT INTO armorset_text VALUES(171,'en','Sealed Eyepatch α');
INSERT INTO armorset_text VALUES(172,'en','Shadow Shades α');
INSERT INTO armorset_text VALUES(173,'en','Kulu-Ya-Ku Head α');
INSERT INTO armorset_text VALUES(174,'en','Wiggler Head α');
INSERT INTO armorset_text VALUES(175,'en','Bone α+');
INSERT INTO armorset_text VALUES(176,'en','Bone β+');
INSERT INTO armorset_text VALUES(177,'en','Alloy α+');
INSERT INTO armorset_text VALUES(178,'en','Alloy β+');
INSERT INTO armorset_text VALUES(179,'en','Vespoid α+');
INSERT INTO armorset_text VALUES(180,'en','Vespoid β+');
INSERT INTO armorset_text VALUES(181,'en','Hornetaur α+');
INSERT INTO armorset_text VALUES(182,'en','Hornetaur β+');
INSERT INTO armorset_text VALUES(183,'en','Kestodon α+');
INSERT INTO armorset_text VALUES(184,'en','Kestodon β+');
INSERT INTO armorset_text VALUES(185,'en','Gajau α+');
INSERT INTO armorset_text VALUES(186,'en','Gajau β+');
INSERT INTO armorset_text VALUES(187,'en','Shamos α+');
INSERT INTO armorset_text VALUES(188,'en','Shamos β+');
INSERT INTO armorset_text VALUES(189,'en','Gastodon α+');
INSERT INTO armorset_text VALUES(190,'en','Gastodon β+');
INSERT INTO armorset_text VALUES(191,'en','Barnos α+');
INSERT INTO armorset_text VALUES(192,'en','Barnos β+');
INSERT INTO armorset_text VALUES(193,'en','Wulg α+');
INSERT INTO armorset_text VALUES(194,'en','Wulg β+');
INSERT INTO armorset_text VALUES(195,'en','Cortos α+');
INSERT INTO armorset_text VALUES(196,'en','Cortos β+');
INSERT INTO armorset_text VALUES(197,'en','Jagras α+');
INSERT INTO armorset_text VALUES(198,'en','Jagras β+');
INSERT INTO armorset_text VALUES(199,'en','Tzitzi α+');
INSERT INTO armorset_text VALUES(200,'en','Tzitzi β+');
INSERT INTO armorset_text VALUES(201,'en','Girros α+');
INSERT INTO armorset_text VALUES(202,'en','Girros β+');
INSERT INTO armorset_text VALUES(203,'en','Dodogama α+');
INSERT INTO armorset_text VALUES(204,'en','Dodogama β+');
INSERT INTO armorset_text VALUES(205,'en','Kulu α+');
INSERT INTO armorset_text VALUES(206,'en','Kulu β+');
INSERT INTO armorset_text VALUES(207,'en','Pukei α+');
INSERT INTO armorset_text VALUES(208,'en','Pukei β+');
INSERT INTO armorset_text VALUES(209,'en','Coral Pukei α+');
INSERT INTO armorset_text VALUES(210,'en','Coral Pukei β+');
INSERT INTO armorset_text VALUES(211,'en','Barroth α+');
INSERT INTO armorset_text VALUES(212,'en','Barroth β+');
INSERT INTO armorset_text VALUES(213,'en','Jyura α+');
INSERT INTO armorset_text VALUES(214,'en','Jyura β+');
INSERT INTO armorset_text VALUES(215,'en','Beo α+');
INSERT INTO armorset_text VALUES(216,'en','Beo β+');
INSERT INTO armorset_text VALUES(217,'en','Kadachi α+');
INSERT INTO armorset_text VALUES(218,'en','Kadachi β+');
INSERT INTO armorset_text VALUES(219,'en','Viper Kadachi α+');
INSERT INTO armorset_text VALUES(220,'en','Viper Kadachi β+');
INSERT INTO armorset_text VALUES(221,'en','High Metal α+');
INSERT INTO armorset_text VALUES(222,'en','High Metal β+');
INSERT INTO armorset_text VALUES(223,'en','Banbaro α+');
INSERT INTO armorset_text VALUES(224,'en','Banbaro β+');
INSERT INTO armorset_text VALUES(225,'en','Anja α+');
INSERT INTO armorset_text VALUES(226,'en','Anja β+');
INSERT INTO armorset_text VALUES(227,'en','Fulgur Anja α+');
INSERT INTO armorset_text VALUES(228,'en','Fulgur Anja β+');
INSERT INTO armorset_text VALUES(229,'en','Rathian α+');
INSERT INTO armorset_text VALUES(230,'en','Rathian β+');
INSERT INTO armorset_text VALUES(231,'en','Rath Heart α+');
INSERT INTO armorset_text VALUES(232,'en','Rath Heart β+');
INSERT INTO armorset_text VALUES(233,'en','Lumu α+');
INSERT INTO armorset_text VALUES(234,'en','Lumu β+');
INSERT INTO armorset_text VALUES(235,'en','Lumu Phantasm α+');
INSERT INTO armorset_text VALUES(236,'en','Lumu Phantasm β+');
INSERT INTO armorset_text VALUES(237,'en','Baan α+');
INSERT INTO armorset_text VALUES(238,'en','Baan β+');
INSERT INTO armorset_text VALUES(239,'en','Artian α+');
INSERT INTO armorset_text VALUES(240,'en','Artian β+');
INSERT INTO armorset_text VALUES(241,'en','Clockwork α+');
INSERT INTO armorset_text VALUES(242,'en','Clockwork β+');
INSERT INTO armorset_text VALUES(243,'en','Ingot α+');
INSERT INTO armorset_text VALUES(244,'en','Ingot β+');
INSERT INTO armorset_text VALUES(245,'en','Barioth α+');
INSERT INTO armorset_text VALUES(246,'en','Barioth β+');
INSERT INTO armorset_text VALUES(247,'en','Rathalos α+');
INSERT INTO armorset_text VALUES(248,'en','Rathalos β+');
INSERT INTO armorset_text VALUES(249,'en','Rath Soul α+');
INSERT INTO armorset_text VALUES(250,'en','Rath Soul β+');
INSERT INTO armorset_text VALUES(251,'en','Diablos α+');
INSERT INTO armorset_text VALUES(252,'en','Diablos β+');
INSERT INTO armorset_text VALUES(253,'en','Diablos Nero α+');
INSERT INTO armorset_text VALUES(254,'en','Diablos Nero β+');
INSERT INTO armorset_text VALUES(255,'en','Legiana α+');
INSERT INTO armorset_text VALUES(256,'en','Legiana β+');
INSERT INTO armorset_text VALUES(257,'en','Shrieking Legia α+');
INSERT INTO armorset_text VALUES(258,'en','Shrieking Legia β+');
INSERT INTO armorset_text VALUES(259,'en','Odogaron α+');
INSERT INTO armorset_text VALUES(260,'en','Odogaron β+');
INSERT INTO armorset_text VALUES(261,'en','Death Garon α+');
INSERT INTO armorset_text VALUES(262,'en','Death Garon β+');
INSERT INTO armorset_text VALUES(263,'en','Lavasioth α+');
INSERT INTO armorset_text VALUES(264,'en','Lavasioth β+');
INSERT INTO armorset_text VALUES(265,'en','Uragaan α+');
INSERT INTO armorset_text VALUES(266,'en','Uragaan β+');
INSERT INTO armorset_text VALUES(267,'en','Nargacuga α+');
INSERT INTO armorset_text VALUES(268,'en','Nargacuga β+');
INSERT INTO armorset_text VALUES(269,'en','Glavenus α+');
INSERT INTO armorset_text VALUES(270,'en','Glavenus β+');
INSERT INTO armorset_text VALUES(271,'en','Acidic Glavenus α+');
INSERT INTO armorset_text VALUES(272,'en','Acidic Glavenus β+');
INSERT INTO armorset_text VALUES(273,'en','Brachydios α+');
INSERT INTO armorset_text VALUES(274,'en','Brachydios β+');
INSERT INTO armorset_text VALUES(275,'en','Tigrex α+');
INSERT INTO armorset_text VALUES(276,'en','Tigrex β+');
INSERT INTO armorset_text VALUES(277,'en','Brute Tigrex α+');
INSERT INTO armorset_text VALUES(278,'en','Brute Tigrex β+');
INSERT INTO armorset_text VALUES(279,'en','Black Belt α+');
INSERT INTO armorset_text VALUES(280,'en','Black Belt β+');
INSERT INTO armorset_text VALUES(281,'en','Dober α+');
INSERT INTO armorset_text VALUES(282,'en','Dober β+');
INSERT INTO armorset_text VALUES(283,'en','Damascus α+');
INSERT INTO armorset_text VALUES(284,'en','Damascus β+');
INSERT INTO armorset_text VALUES(285,'en','Seething Bazel α+');
INSERT INTO armorset_text VALUES(286,'en','Seething Bazel β+');
INSERT INTO armorset_text VALUES(287,'en','Savage Jho α+');
INSERT INTO armorset_text VALUES(288,'en','Savage Jho β+');
INSERT INTO armorset_text VALUES(289,'en','Velkhana α+');
INSERT INTO armorset_text VALUES(290,'en','Velkhana β+');
INSERT INTO armorset_text VALUES(291,'en','Blackveil Hazak α+');
INSERT INTO armorset_text VALUES(292,'en','Blackveil Hazak β+');
INSERT INTO armorset_text VALUES(293,'en','Teostra α+');
INSERT INTO armorset_text VALUES(294,'en','Teostra β+');
INSERT INTO armorset_text VALUES(295,'en','Kushala α+');
INSERT INTO armorset_text VALUES(296,'en','Kushala β+');
INSERT INTO armorset_text VALUES(297,'en','Kirin α+');
INSERT INTO armorset_text VALUES(298,'en','Kirin β+');
INSERT INTO armorset_text VALUES(299,'en','Namielle α+');
INSERT INTO armorset_text VALUES(300,'en','Namielle β+');
INSERT INTO armorset_text VALUES(301,'en','Guild Palace α+');
INSERT INTO armorset_text VALUES(302,'en','Guild Palace β+');
INSERT INTO armorset_text VALUES(303,'en','Shara Ishvalda α+');
INSERT INTO armorset_text VALUES(304,'en','Shara Ishvalda β+');
INSERT INTO armorset_text VALUES(305,'en','Zorah α+');
INSERT INTO armorset_text VALUES(306,'en','Zorah β+');
INSERT INTO armorset_text VALUES(307,'en','Yian Garuga α+');
INSERT INTO armorset_text VALUES(308,'en','Yian Garuga β+');
INSERT INTO armorset_text VALUES(309,'en','Zinogre α+');
INSERT INTO armorset_text VALUES(310,'en','Zinogre β+');
INSERT INTO armorset_text VALUES(311,'en','Golden Lune α+');
INSERT INTO armorset_text VALUES(312,'en','Golden Lune β+');
INSERT INTO armorset_text VALUES(313,'en','Silver Sol α+');
INSERT INTO armorset_text VALUES(314,'en','Silver Sol β+');
INSERT INTO armorset_text VALUES(315,'en','Lunastra α+');
INSERT INTO armorset_text VALUES(316,'en','Lunastra β+');
INSERT INTO armorset_text VALUES(317,'en','Ruiner Nergi α+');
INSERT INTO armorset_text VALUES(318,'en','Ruiner Nergi β+');
INSERT INTO armorset_text VALUES(319,'en','Guildwork α+');
INSERT INTO armorset_text VALUES(320,'en','Guildwork β+');
INSERT INTO armorset_text VALUES(321,'en','Rajang α+');
INSERT INTO armorset_text VALUES(322,'en','Rajang β+');
INSERT INTO armorset_text VALUES(323,'en','Furious Rajang α+');
INSERT INTO armorset_text VALUES(324,'en','Furious Rajang β+');
INSERT INTO armorset_text VALUES(325,'en','Stygian Zin α+');
INSERT INTO armorset_text VALUES(326,'en','Stygian Zin β+');
INSERT INTO armorset_text VALUES(327,'en','Safi''jiiva α+');
INSERT INTO armorset_text VALUES(328,'en','Safi''jiiva β+');
INSERT INTO armorset_text VALUES(329,'en','Raging Brachy α+');
INSERT INTO armorset_text VALUES(330,'en','Raging Brachy β+');
INSERT INTO armorset_text VALUES(331,'en','Frostfang Barioth α+');
INSERT INTO armorset_text VALUES(332,'en','Frostfang Barioth β+');
INSERT INTO armorset_text VALUES(333,'en','Alatreon α+');
INSERT INTO armorset_text VALUES(334,'en','Alatreon β+');
INSERT INTO armorset_text VALUES(335,'en','Kulve Taroth α+');
INSERT INTO armorset_text VALUES(336,'en','Kulve Taroth β+');
INSERT INTO armorset_text VALUES(337,'en','Namielle γ+');
INSERT INTO armorset_text VALUES(338,'en','Velkhana γ+');
INSERT INTO armorset_text VALUES(339,'en','Oolong α+');
INSERT INTO armorset_text VALUES(340,'en','Astral α+');
INSERT INTO armorset_text VALUES(341,'en','Rose α+');
INSERT INTO armorset_text VALUES(342,'en','Passionate α+');
INSERT INTO armorset_text VALUES(343,'en','Demonlord α+');
INSERT INTO armorset_text VALUES(344,'en','Dragon α+');
INSERT INTO armorset_text VALUES(345,'en','Dragon β+');
INSERT INTO armorset_text VALUES(346,'en','Azure Age α+');
INSERT INTO armorset_text VALUES(347,'en','Artemis α+');
INSERT INTO armorset_text VALUES(348,'en','Pearlspring α+');
INSERT INTO armorset_text VALUES(349,'en','Duffel Penguin Mask α+');
INSERT INTO armorset_text VALUES(350,'en','Sealed Dragon Cloth α+');
INSERT INTO armorset_text VALUES(351,'en','Wyverian Ears α+');

COMMIT;