BEGIN;

INSERT INTO decoration_text VALUES(1,'de','Gegengift-Juwel 1');
INSERT INTO decoration_text VALUES(2,'de','Geologie-Juwel 1');
INSERT INTO decoration_text VALUES(3,'de','Schwere-Artillerie-Juwel 1');
INSERT INTO decoration_text VALUES(4,'de','Hungerfrei-Juwel 1');
INSERT INTO decoration_text VALUES(5,'de','Sattes Juwel 1');
INSERT INTO decoration_text VALUES(6,'de','Schutz-Juwel 1');
INSERT INTO decoration_text VALUES(7,'de','Miauster-Juwel 1');
INSERT INTO decoration_text VALUES(8,'de','Botanik-Juwel 1');
INSERT INTO decoration_text VALUES(9,'de','Schleich-Juwel 1');
INSERT INTO decoration_text VALUES(10,'de','Flug-Juwel 2');
INSERT INTO decoration_text VALUES(12,'de','Sumpfläufer-Juwel 1');
INSERT INTO decoration_text VALUES(13,'de','Insektenforscher-Juwel 1');
INSERT INTO decoration_text VALUES(14,'de','Miasma-Juwel 1');
INSERT INTO decoration_text VALUES(15,'de','Geruchs-Juwel 1');
INSERT INTO decoration_text VALUES(16,'de','Einschüchtern-Juwel 1');
INSERT INTO decoration_text VALUES(17,'de','Krisen-Juwel 1');
INSERT INTO decoration_text VALUES(18,'de','Anti-Lähm-Juwel 1');
INSERT INTO decoration_text VALUES(19,'de','Kraft-Juwel 1');
INSERT INTO decoration_text VALUES(20,'de','Wasserabwehr-Juwel 1');
INSERT INTO decoration_text VALUES(21,'de','Naht-Juwel 1');
INSERT INTO decoration_text VALUES(22,'de','Drachenabwehr-Juwel 1');
INSERT INTO decoration_text VALUES(23,'de','Feuerabwehr-Juwel 1');
INSERT INTO decoration_text VALUES(24,'de','Eisabwehr-Juwel 1');
INSERT INTO decoration_text VALUES(25,'de','Abwehrsperre-Juwel 1');
INSERT INTO decoration_text VALUES(26,'de','Donnerabwehr-Juwel 1');
INSERT INTO decoration_text VALUES(27,'de','Pepp-Juwel 1');
INSERT INTO decoration_text VALUES(28,'de','Anti-Explosion-Juwel 1');
INSERT INTO decoration_text VALUES(29,'de','Wartungs-Juwel 1');
INSERT INTO decoration_text VALUES(30,'de','Verschling-Juwel 1');
INSERT INTO decoration_text VALUES(31,'de','Figur-Juwel 2');
INSERT INTO decoration_text VALUES(32,'de','Lohe-Juwel 1');
INSERT INTO decoration_text VALUES(33,'de','Ausweich-Juwel 2');
INSERT INTO decoration_text VALUES(34,'de','Sprung-Juwel 2');
INSERT INTO decoration_text VALUES(35,'de','Wegsteck-Juwel 1');
INSERT INTO decoration_text VALUES(36,'de','Freundschaft-Juwel 1');
INSERT INTO decoration_text VALUES(37,'de','Dauer-Juwel 1');
INSERT INTO decoration_text VALUES(38,'de','Medizin-Juwel 1');
INSERT INTO decoration_text VALUES(39,'de','Schleif-Juwel 1');
INSERT INTO decoration_text VALUES(40,'de','Felsenfest-Juwel 1');
INSERT INTO decoration_text VALUES(41,'de','Bomber-Juwel 1');
INSERT INTO decoration_text VALUES(42,'de','Erholung-Juwel 1');
INSERT INTO decoration_text VALUES(43,'de','Gleiter-Juwel 2');
INSERT INTO decoration_text VALUES(44,'de','Verteidigung-Juwel 1');
INSERT INTO decoration_text VALUES(45,'de','Steinwerfer-Juwel 1');
INSERT INTO decoration_text VALUES(46,'de','Halt-Juwel 2');
INSERT INTO decoration_text VALUES(47,'de','Wappnungs-Juwel 3');
INSERT INTO decoration_text VALUES(48,'de','Windresistenz-Juwel 2');
INSERT INTO decoration_text VALUES(49,'de','Ohrstöpsel-Juwel 3');
INSERT INTO decoration_text VALUES(50,'de','Lebenskraft-Juwel 1');
INSERT INTO decoration_text VALUES(51,'de','Resistor-Juwel 1');
INSERT INTO decoration_text VALUES(52,'de','Klang-Juwel 1');
INSERT INTO decoration_text VALUES(53,'de','Knock-out-Juwel 2');
INSERT INTO decoration_text VALUES(54,'de','Fluss-Juwel 1');
INSERT INTO decoration_text VALUES(55,'de','Frost-Juwel 1');
INSERT INTO decoration_text VALUES(56,'de','Blitz-Juwel 1');
INSERT INTO decoration_text VALUES(57,'de','Drachen-Juwel 1');
INSERT INTO decoration_text VALUES(58,'de','Gift-Juwel 1');
INSERT INTO decoration_text VALUES(59,'de','Giftbeschichtung-Juwel 3');
INSERT INTO decoration_text VALUES(60,'de','Experten-Juwel 1');
INSERT INTO decoration_text VALUES(61,'de','Aufweich-Juwel 2');
INSERT INTO decoration_text VALUES(62,'de','Zerstörer-Juwel 2');
INSERT INTO decoration_text VALUES(63,'de','Elementloses Juwel 2');
INSERT INTO decoration_text VALUES(64,'de','Entzug-Juwel 1');
INSERT INTO decoration_text VALUES(65,'de','Lähmbeschichtung-Juwel 3');
INSERT INTO decoration_text VALUES(66,'de','Scharfes Juwel 2');
INSERT INTO decoration_text VALUES(67,'de','Schild-Juwel 2');
INSERT INTO decoration_text VALUES(68,'de','Drachensiegel-Juwel 3');
INSERT INTO decoration_text VALUES(69,'de','Volltreffer-Juwel 1');
INSERT INTO decoration_text VALUES(70,'de','Verstärker-Juwel 2');
INSERT INTO decoration_text VALUES(71,'de','Starkschuss-Juwel 3');
INSERT INTO decoration_text VALUES(72,'de','Furor-Juwel 2');
INSERT INTO decoration_text VALUES(73,'de','Potenzial-Juwel 2');
INSERT INTO decoration_text VALUES(74,'de','Lähmangriff-Juwel 1');
INSERT INTO decoration_text VALUES(75,'de','Schlaf-Juwel 1');
INSERT INTO decoration_text VALUES(76,'de','Eisenmauer-Juwel 1');
INSERT INTO decoration_text VALUES(77,'de','Erfrischungs-Juwel 2');
INSERT INTO decoration_text VALUES(78,'de','Explosion-Juwel 1');
INSERT INTO decoration_text VALUES(79,'de','Schlafbeschichtung-Juwel 3');
INSERT INTO decoration_text VALUES(80,'de','Sprengbeschichtung-Juwel 3');
INSERT INTO decoration_text VALUES(81,'de','Vollgas-Juwel 2');
INSERT INTO decoration_text VALUES(82,'de','Herausforderer-Juwel 2');
INSERT INTO decoration_text VALUES(83,'de','Angriff-Juwel 1');
INSERT INTO decoration_text VALUES(84,'de','Makellos-Juwel 2');
INSERT INTO decoration_text VALUES(85,'de','Magazin-Juwel 2');
INSERT INTO decoration_text VALUES(86,'de','Mächtiges Juwel 2');
INSERT INTO decoration_text VALUES(87,'de','Sprinter-Juwel 2');
INSERT INTO decoration_text VALUES(88,'de','Kritisches Juwel 2');
INSERT INTO decoration_text VALUES(89,'de','Artillerie-Juwel 1');
INSERT INTO decoration_text VALUES(90,'de','Pilzform-Juwel 1');
INSERT INTO decoration_text VALUES(91,'de','Freisetzung-Juwel 3');
INSERT INTO decoration_text VALUES(92,'de','Schrot-Juwel 3');
INSERT INTO decoration_text VALUES(93,'de','Ladungs-Juwel 2');
INSERT INTO decoration_text VALUES(94,'de','Handwerk-Juwel 3');
INSERT INTO decoration_text VALUES(95,'de','Mächtiger-Bogen-Juwel 2');
INSERT INTO decoration_text VALUES(96,'de','Geistiges-Auge-Juwel 2');
INSERT INTO decoration_text VALUES(97,'de','Ziehen-Juwel 2');
INSERT INTO decoration_text VALUES(98,'de','Perforations-Juwel 3');
INSERT INTO decoration_text VALUES(99,'de','Phönix-Juwel 3');
INSERT INTO decoration_text VALUES(100,'de','Feuerabwehr-Juwel+ 4');
INSERT INTO decoration_text VALUES(101,'de','Wasserabwehr-Juwel+ 4');
INSERT INTO decoration_text VALUES(102,'de','Eisabwehr-Juwel+ 4');
INSERT INTO decoration_text VALUES(103,'de','Donnerabwehr-Juwel+ 4');
INSERT INTO decoration_text VALUES(104,'de','Drachenabwehr-Juwel+ 4');
INSERT INTO decoration_text VALUES(105,'de','Lohe-Juwel+ 4');
INSERT INTO decoration_text VALUES(106,'de','Fluss-Juwel+ 4');
INSERT INTO decoration_text VALUES(107,'de','Frost-Juwel+ 4');
INSERT INTO decoration_text VALUES(108,'de','Blitz-Juwel+ 4');
INSERT INTO decoration_text VALUES(109,'de','Drachen-Juwel+ 4');
INSERT INTO decoration_text VALUES(110,'de','Gift-Juwel+ 4');
INSERT INTO decoration_text VALUES(111,'de','Lähmangriff-Juwel+ 4');
INSERT INTO decoration_text VALUES(112,'de','Schlaf-Juwel+ 4');
INSERT INTO decoration_text VALUES(113,'de','Explosion-Juwel+ 4');
INSERT INTO decoration_text VALUES(114,'de','Hartes Feuerabwehr-Juwel 4');
INSERT INTO decoration_text VALUES(115,'de','Hartes Wasserabwehr-Juwel 4');
INSERT INTO decoration_text VALUES(116,'de','Hartes Eisabwehr-Juwel 4');
INSERT INTO decoration_text VALUES(117,'de','Hartes Donnerabwehr-Juwel 4');
INSERT INTO decoration_text VALUES(118,'de','Hartes Drachenabwehr-Juwel 4');
INSERT INTO decoration_text VALUES(119,'de','Gegengift-Juwel+ 4');
INSERT INTO decoration_text VALUES(120,'de','Anti-Lähm-Juwel+ 4');
INSERT INTO decoration_text VALUES(121,'de','Pepp-Juwel+ 4');
INSERT INTO decoration_text VALUES(122,'de','Felsenfest-Juwel+ 4');
INSERT INTO decoration_text VALUES(123,'de','Anti-Explosion-Juwel+ 4');
INSERT INTO decoration_text VALUES(124,'de','Naht-Juwel+ 4');
INSERT INTO decoration_text VALUES(125,'de','Abwehrsperre-Juwel+ 4');
INSERT INTO decoration_text VALUES(126,'de','Miasma-Juwel+ 4');
INSERT INTO decoration_text VALUES(127,'de','Hungerfrei-Juwel+ 4');
INSERT INTO decoration_text VALUES(128,'de','Erholung-Juwel+ 4');
INSERT INTO decoration_text VALUES(129,'de','Schleich-Juwel+ 4');
INSERT INTO decoration_text VALUES(130,'de','Einschüchtern-Juwel+ 4');
INSERT INTO decoration_text VALUES(131,'de','Miauster-Juwel+ 4');
INSERT INTO decoration_text VALUES(132,'de','Hartes Schleich-Juwel 4');
INSERT INTO decoration_text VALUES(133,'de','Hartes Einschüchtern-Juwel 4');
INSERT INTO decoration_text VALUES(134,'de','Hartes Miauster-Juwel 4');
INSERT INTO decoration_text VALUES(135,'de','Volltreffer-Juwel+ 4');
INSERT INTO decoration_text VALUES(136,'de','Schwere-Artillerie-Juwel+ 4');
INSERT INTO decoration_text VALUES(137,'de','Botanik-Juwel+ 4');
INSERT INTO decoration_text VALUES(138,'de','Geologie-Juwel+ 4');
INSERT INTO decoration_text VALUES(139,'de','Überleben-Juwel+ 4');
INSERT INTO decoration_text VALUES(140,'de','Sumpfläufer-Juwel+ 4');
INSERT INTO decoration_text VALUES(141,'de','Insektenforscher-Juwel+ 4');
INSERT INTO decoration_text VALUES(142,'de','Klang-Juwel+ 4');
INSERT INTO decoration_text VALUES(143,'de','Hartes Botanik-Juwel+ 4');
INSERT INTO decoration_text VALUES(144,'de','Hartes Geologie-Juwel 4');
INSERT INTO decoration_text VALUES(145,'de','Hartes Überleben-Juwel 4');
INSERT INTO decoration_text VALUES(146,'de','Hartes InsektenforscherJuwel 4');
INSERT INTO decoration_text VALUES(147,'de','Dauer-Juwel+ 4');
INSERT INTO decoration_text VALUES(148,'de','Verteidigung-Juwel+ 4');
INSERT INTO decoration_text VALUES(149,'de','Hartes Dauer-Juwel 4');
INSERT INTO decoration_text VALUES(150,'de','Hartes Verteidigung-Juwel 4');
INSERT INTO decoration_text VALUES(151,'de','Artillerie-Juwel+ 4');
INSERT INTO decoration_text VALUES(152,'de','Ohrstöpsel-Juwel+ 4');
INSERT INTO decoration_text VALUES(153,'de','Windresistenz-Juwel+ 4');
INSERT INTO decoration_text VALUES(154,'de','Angriff-Juwel+ 4');
INSERT INTO decoration_text VALUES(155,'de','Experten-Juwel+ 4');
INSERT INTO decoration_text VALUES(156,'de','Handwerk-Juwel+ 4');
INSERT INTO decoration_text VALUES(157,'de','Vollgas-Juwel+ 4');
INSERT INTO decoration_text VALUES(158,'de','Herausforderer-Juwel+ 4');
INSERT INTO decoration_text VALUES(159,'de','Potenzial-Juwel+ 4');
INSERT INTO decoration_text VALUES(160,'de','Furor-Juwel+ 4');
INSERT INTO decoration_text VALUES(161,'de','Figur-Juwel+ 4');
INSERT INTO decoration_text VALUES(162,'de','Ausweich-Juwel+ 4');
INSERT INTO decoration_text VALUES(163,'de','Eisenmauer-Juwel+ 4');
INSERT INTO decoration_text VALUES(164,'de','Freundschaft-Juwel+ 4');
INSERT INTO decoration_text VALUES(165,'de','Entzug-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(166,'de','Kraft-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(167,'de','Krisen-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(168,'de','Eisenmauer-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(169,'de','Freundschaft-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(170,'de','Sattes/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(171,'de','Steinwerfer-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(172,'de','Resistor-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(173,'de','Flug-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(174,'de','Sprinter-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(175,'de','Erfrischungs-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(176,'de','Sprung-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(177,'de','Wegsteck-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(178,'de','Verschling-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(179,'de','Schleif-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(180,'de','Bomber-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(181,'de','Pilzform-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(182,'de','Gleiter-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(183,'de','Wächter-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(184,'de','Entzug-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(185,'de','Kraft-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(186,'de','Krisen-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(187,'de','Eisenmauer-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(188,'de','Freundschaft-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(189,'de','Sattes/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(190,'de','Steinwerfer-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(191,'de','Resistor-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(192,'de','Flug-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(193,'de','Sprinter-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(194,'de','Erfrischungs-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(195,'de','Sprung-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(196,'de','Wegsteck-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(197,'de','Verschling-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(198,'de','Schleif-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(199,'de','Bomber-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(200,'de','Pilzform-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(201,'de','Gleiter-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(202,'de','Wächter-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(203,'de','Entzug-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(204,'de','Kraft-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(205,'de','Krisen-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(206,'de','Eisenmauer-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(207,'de','Freundschaft-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(208,'de','Sattes/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(209,'de','Steinwerfer-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(210,'de','Resistor-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(211,'de','Flug-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(212,'de','Sprinter-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(213,'de','Erfrischungs-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(214,'de','Sprung-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(215,'de','Wegsteck-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(216,'de','Verschling-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(217,'de','Schleif-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(218,'de','Bomber-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(219,'de','Pilzform-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(220,'de','Gleiter-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(221,'de','Wächter-/Angriff-Juwel 4');
INSERT INTO decoration_text VALUES(222,'de','Entzug-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(223,'de','Kraft-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(224,'de','Krisen-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(225,'de','Eisenmauer-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(226,'de','Freundschaft-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(227,'de','Sattes/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(228,'de','Steinwerfer-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(229,'de','Resistor-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(230,'de','Flug-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(231,'de','Sprinter-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(232,'de','Erfrischungs-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(233,'de','Sprung-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(234,'de','Wegsteck-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(235,'de','Verschling-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(236,'de','Schleif-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(237,'de','Bomber-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(238,'de','Pilzform-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(239,'de','Gleiter-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(240,'de','Wächter-/Experten-Juwel 4');
INSERT INTO decoration_text VALUES(241,'de','Entzug-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(242,'de','Kraft-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(243,'de','Krisen-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(244,'de','Eisenmauer-/Freisetzung-Juwel4');
INSERT INTO decoration_text VALUES(245,'de','Freundschaft-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(246,'de','Sattes/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(247,'de','Steinwerfer/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(248,'de','Resistor-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(249,'de','Flug-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(250,'de','Sprinter-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(251,'de','Erfrischungs-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(252,'de','Sprung-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(253,'de','Wegsteck-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(254,'de','Verschling-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(255,'de','Schleif-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(256,'de','Bomber-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(257,'de','Pilzform-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(258,'de','Gleiter-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(259,'de','Wächter-/Freisetzung-Juwel 4');
INSERT INTO decoration_text VALUES(260,'de','Entzug-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(261,'de','Kraft-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(262,'de','Krisen-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(263,'de','Eisenmauer-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(264,'de','Freundschaft-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(265,'de','Sattes/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(266,'de','Steinwerfer-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(267,'de','Resistor-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(268,'de','Flug-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(269,'de','Sprinter-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(270,'de','Erfrischungs-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(271,'de','Sprung-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(272,'de','Wegsteck-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(273,'de','Verschling-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(274,'de','Schleif-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(275,'de','Bomber-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(276,'de','Pilzform-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(277,'de','Gleiter-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(278,'de','Wächter-/Handwerk-Juwel 4');
INSERT INTO decoration_text VALUES(279,'de','Halt-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(280,'de','Ladungs-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(281,'de','Verstärker-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(282,'de','Zerstörer-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(283,'de','Knock-out-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(284,'de','Potenzial-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(285,'de','Windresistenz-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(286,'de','Ziehen-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(287,'de','Vollgas-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(288,'de','Herausforderer-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(289,'de','Makellos-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(290,'de','Furor-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(291,'de','Mächtiges/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(292,'de','Wappnungs-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(293,'de','Phönix-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(294,'de','Ohrstöpsel-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(295,'de','Kritisches/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(296,'de','Aufweich-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(297,'de','Handwerk-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(298,'de','Freisetzung-/Schutz-Juwel 4');
INSERT INTO decoration_text VALUES(299,'de','Halt-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(300,'de','Ladungs-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(301,'de','Verstärker-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(302,'de','Zerstörer-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(303,'de','Knock-out-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(304,'de','Potenzial-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(305,'de','Windresistenz-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(306,'de','Ziehen-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(307,'de','Vollgas-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(308,'de','Herausforderer-/Medizin-Juwel4');
INSERT INTO decoration_text VALUES(309,'de','Makellos-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(310,'de','Furor-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(311,'de','Mächtiges/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(312,'de','Wappnungs-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(313,'de','Phönix-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(314,'de','Ohrstöpsel-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(315,'de','Kritisches/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(316,'de','Aufweich-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(317,'de','Handwerk-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(318,'de','Freisetzung-/Medizin-Juwel 4');
INSERT INTO decoration_text VALUES(319,'de','Halt-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(320,'de','Ladungs-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(321,'de','Verstärker-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(322,'de','Zerstörer-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(323,'de','Knock-out-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(324,'de','Potenzial-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(325,'de','Windresistenz-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(326,'de','Ziehen-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(327,'de','Vollgas-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(328,'de','Herausforderer-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(329,'de','Makellos-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(330,'de','Furor-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(331,'de','Mächtiges/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(332,'de','Wappnungs-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(333,'de','Phönix-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(334,'de','Ohrstöpsel-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(335,'de','Kritisches/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(336,'de','Aufweich-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(337,'de','Handwerk-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(338,'de','Freisetzung-/Lebenskraft-Juwel 4');
INSERT INTO decoration_text VALUES(339,'de','Halt-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(340,'de','Ladungs-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(341,'de','Verstärker-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(342,'de','Zerstörer-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(343,'de','Knock-out-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(344,'de','Potenzial-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(345,'de','Windresistenz-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(346,'de','Ziehen-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(347,'de','Vollgas-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(348,'de','Herausforderer-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(349,'de','Makellos-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(350,'de','Furor-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(351,'de','Mächtiges/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(352,'de','Wappnungs-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(353,'de','Phönix-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(354,'de','Ohrstöpsel-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(355,'de','Kritisches/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(356,'de','Aufweich-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(357,'de','Handwerk-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(358,'de','Freisetzung-/Wartungs-Juwel 4');
INSERT INTO decoration_text VALUES(359,'de','Halt-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(360,'de','Ladungs-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(361,'de','Verstärker-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(362,'de','Zerstörer-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(363,'de','Knock-out-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(364,'de','Potenzial-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(365,'de','Windresistenz-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(366,'de','Ziehen-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(367,'de','Vollgas-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(368,'de','Herausforderer-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(369,'de','Makellos-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(370,'de','Furor-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(371,'de','Mächtiges/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(372,'de','Wappnungs-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(373,'de','Phönix-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(374,'de','Ohrstöpsel-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(375,'de','Kritisches/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(376,'de','Aufweich-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(377,'de','Handwerk-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(378,'de','Freisetzung-/Figur-Juwel 4');
INSERT INTO decoration_text VALUES(379,'de','Halt-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(380,'de','Ladungs-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(381,'de','Verstärker-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(382,'de','Zerstörer-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(383,'de','Knock-out-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(384,'de','Potenzial-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(385,'de','Windresistenz-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(386,'de','Ziehen-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(387,'de','Vollgas-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(388,'de','Herausforderer/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(389,'de','Makellos-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(390,'de','Furor-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(391,'de','Mächtiges/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(392,'de','Wappnungs-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(393,'de','Phönix-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(394,'de','Ohrstöpsel-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(395,'de','Kritisches/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(396,'de','Aufweich-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(397,'de','Handwerk-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(398,'de','Freisetzung-/Ausweich-Juwel 4');
INSERT INTO decoration_text VALUES(399,'de','Survival Jewel 1');
INSERT INTO decoration_text VALUES(400,'de','Guardian Jewel 2');
INSERT INTO decoration_text VALUES(402,'de','Cooling Jewel 2');
INSERT INTO decoration_text VALUES(403,'de','Warming Jewel 2');
INSERT INTO decoration_text VALUES(404,'de','Diversion Jewel 3');
INSERT INTO decoration_text VALUES(405,'de','Acrobat Jewel 3');
INSERT INTO decoration_text VALUES(406,'de','Shaver Jewel 3');
INSERT INTO decoration_text VALUES(1,'en','Antidote Jewel 1');
INSERT INTO decoration_text VALUES(2,'en','Geology Jewel 1');
INSERT INTO decoration_text VALUES(3,'en','Heavy Artillery Jewel 1');
INSERT INTO decoration_text VALUES(4,'en','Hungerless Jewel 1');
INSERT INTO decoration_text VALUES(5,'en','Satiated Jewel 1');
INSERT INTO decoration_text VALUES(6,'en','Protection Jewel 1');
INSERT INTO decoration_text VALUES(7,'en','Meowster Jewel 1');
INSERT INTO decoration_text VALUES(8,'en','Botany Jewel 1');
INSERT INTO decoration_text VALUES(9,'en','Tip Toe Jewel 1');
INSERT INTO decoration_text VALUES(10,'en','Flight Jewel 2');
INSERT INTO decoration_text VALUES(12,'en','Mirewalker Jewel 1');
INSERT INTO decoration_text VALUES(13,'en','Specimen Jewel 1');
INSERT INTO decoration_text VALUES(14,'en','Miasma Jewel 1');
INSERT INTO decoration_text VALUES(15,'en','Scent Jewel 1');
INSERT INTO decoration_text VALUES(16,'en','Intimidator Jewel 1');
INSERT INTO decoration_text VALUES(17,'en','Crisis Jewel 1');
INSERT INTO decoration_text VALUES(18,'en','Antipara Jewel 1');
INSERT INTO decoration_text VALUES(19,'en','Fortitude Jewel 1');
INSERT INTO decoration_text VALUES(20,'en','Water Res Jewel 1');
INSERT INTO decoration_text VALUES(21,'en','Suture Jewel 1');
INSERT INTO decoration_text VALUES(22,'en','Dragon Res Jewel 1');
INSERT INTO decoration_text VALUES(23,'en','Fire Res Jewel 1');
INSERT INTO decoration_text VALUES(24,'en','Ice Res Jewel 1');
INSERT INTO decoration_text VALUES(25,'en','Def Lock Jewel 1');
INSERT INTO decoration_text VALUES(26,'en','Thunder Res Jewel 1');
INSERT INTO decoration_text VALUES(27,'en','Pep Jewel 1');
INSERT INTO decoration_text VALUES(28,'en','Antiblast Jewel 1');
INSERT INTO decoration_text VALUES(29,'en','Maintenance Jewel 1');
INSERT INTO decoration_text VALUES(30,'en','Gobbler Jewel 1');
INSERT INTO decoration_text VALUES(31,'en','Physique Jewel 2');
INSERT INTO decoration_text VALUES(32,'en','Blaze Jewel 1');
INSERT INTO decoration_text VALUES(33,'en','Evasion Jewel 2');
INSERT INTO decoration_text VALUES(34,'en','Jumping Jewel 2');
INSERT INTO decoration_text VALUES(35,'en','Sheath Jewel 1');
INSERT INTO decoration_text VALUES(36,'en','Friendship Jewel 1');
INSERT INTO decoration_text VALUES(37,'en','Enduring Jewel 1');
INSERT INTO decoration_text VALUES(38,'en','Medicine Jewel 1');
INSERT INTO decoration_text VALUES(39,'en','Grinder Jewel 1');
INSERT INTO decoration_text VALUES(40,'en','Steadfast Jewel 1');
INSERT INTO decoration_text VALUES(41,'en','Bomber Jewel 1');
INSERT INTO decoration_text VALUES(42,'en','Recovery Jewel 1');
INSERT INTO decoration_text VALUES(43,'en','Slider Jewel 2');
INSERT INTO decoration_text VALUES(44,'en','Defense Jewel 1');
INSERT INTO decoration_text VALUES(45,'en','Stonethrower Jewel 1');
INSERT INTO decoration_text VALUES(46,'en','Footing Jewel 2');
INSERT INTO decoration_text VALUES(47,'en','Brace Jewel 3');
INSERT INTO decoration_text VALUES(48,'en','Wind Resist Jewel 2');
INSERT INTO decoration_text VALUES(49,'en','Earplug Jewel 3');
INSERT INTO decoration_text VALUES(50,'en','Vitality Jewel 1');
INSERT INTO decoration_text VALUES(51,'en','Resistor Jewel 1');
INSERT INTO decoration_text VALUES(52,'en','Sonorous Jewel 1');
INSERT INTO decoration_text VALUES(53,'en','KO Jewel 2');
INSERT INTO decoration_text VALUES(54,'en','Stream Jewel 1');
INSERT INTO decoration_text VALUES(55,'en','Frost Jewel 1');
INSERT INTO decoration_text VALUES(56,'en','Bolt Jewel 1');
INSERT INTO decoration_text VALUES(57,'en','Dragon Jewel 1');
INSERT INTO decoration_text VALUES(58,'en','Venom Jewel 1');
INSERT INTO decoration_text VALUES(59,'en','Poisoncoat Jewel 3');
INSERT INTO decoration_text VALUES(60,'en','Expert Jewel 1');
INSERT INTO decoration_text VALUES(61,'en','Tenderizer Jewel 2');
INSERT INTO decoration_text VALUES(62,'en','Destroyer Jewel 2');
INSERT INTO decoration_text VALUES(63,'en','Elementless Jewel 2');
INSERT INTO decoration_text VALUES(64,'en','Drain Jewel 1');
INSERT INTO decoration_text VALUES(65,'en','Paracoat Jewel 3');
INSERT INTO decoration_text VALUES(66,'en','Sharp Jewel 2');
INSERT INTO decoration_text VALUES(67,'en','Shield Jewel 2');
INSERT INTO decoration_text VALUES(68,'en','Dragonseal Jewel 3');
INSERT INTO decoration_text VALUES(69,'en','Trueshot Jewel 1');
INSERT INTO decoration_text VALUES(70,'en','Enhancer Jewel 2');
INSERT INTO decoration_text VALUES(71,'en','Forceshot Jewel 3');
INSERT INTO decoration_text VALUES(72,'en','Furor Jewel 2');
INSERT INTO decoration_text VALUES(73,'en','Potential Jewel 2');
INSERT INTO decoration_text VALUES(74,'en','Paralyzer Jewel 1');
INSERT INTO decoration_text VALUES(75,'en','Sleep Jewel 1');
INSERT INTO decoration_text VALUES(76,'en','Ironwall Jewel 1');
INSERT INTO decoration_text VALUES(77,'en','Refresh Jewel 2');
INSERT INTO decoration_text VALUES(78,'en','Blast Jewel 1');
INSERT INTO decoration_text VALUES(79,'en','Sleepcoat Jewel 3');
INSERT INTO decoration_text VALUES(80,'en','Blastcoat Jewel 3');
INSERT INTO decoration_text VALUES(81,'en','Throttle Jewel 2');
INSERT INTO decoration_text VALUES(82,'en','Challenger Jewel 2');
INSERT INTO decoration_text VALUES(83,'en','Attack Jewel 1');
INSERT INTO decoration_text VALUES(84,'en','Flawless Jewel 2');
INSERT INTO decoration_text VALUES(85,'en','Magazine Jewel 2');
INSERT INTO decoration_text VALUES(86,'en','Mighty Jewel 2');
INSERT INTO decoration_text VALUES(87,'en','Sprinter Jewel 2');
INSERT INTO decoration_text VALUES(88,'en','Critical Jewel 2');
INSERT INTO decoration_text VALUES(89,'en','Artillery Jewel 1');
INSERT INTO decoration_text VALUES(90,'en','Fungiform Jewel 1');
INSERT INTO decoration_text VALUES(91,'en','Release Jewel 3');
INSERT INTO decoration_text VALUES(92,'en','Spread Jewel 3');
INSERT INTO decoration_text VALUES(93,'en','Charger Jewel 2');
INSERT INTO decoration_text VALUES(94,'en','Handicraft Jewel 3');
INSERT INTO decoration_text VALUES(95,'en','Mighty Bow Jewel 2');
INSERT INTO decoration_text VALUES(96,'en','Mind''s Eye Jewel 2');
INSERT INTO decoration_text VALUES(97,'en','Draw Jewel 2');
INSERT INTO decoration_text VALUES(98,'en','Pierce Jewel 3');
INSERT INTO decoration_text VALUES(99,'en','Phoenix Jewel 3');
INSERT INTO decoration_text VALUES(100,'en','Fire Res Jewel+ 4');
INSERT INTO decoration_text VALUES(101,'en','Water Res Jewel+ 4');
INSERT INTO decoration_text VALUES(102,'en','Ice Res Jewel+ 4');
INSERT INTO decoration_text VALUES(103,'en','Thunder Res Jewel+ 4');
INSERT INTO decoration_text VALUES(104,'en','Dragon Res Jewel+ 4');
INSERT INTO decoration_text VALUES(105,'en','Blaze Jewel+ 4');
INSERT INTO decoration_text VALUES(106,'en','Stream Jewel+ 4');
INSERT INTO decoration_text VALUES(107,'en','Frost Jewel+ 4');
INSERT INTO decoration_text VALUES(108,'en','Bolt Jewel+ 4');
INSERT INTO decoration_text VALUES(109,'en','Dragon Jewel+ 4');
INSERT INTO decoration_text VALUES(110,'en','Venom Jewel+ 4');
INSERT INTO decoration_text VALUES(111,'en','Paralyzer Jewel+ 4');
INSERT INTO decoration_text VALUES(112,'en','Sleep Jewel+ 4');
INSERT INTO decoration_text VALUES(113,'en','Blast Jewel+ 4');
INSERT INTO decoration_text VALUES(114,'en','Hard Fire Res Jewel 4');
INSERT INTO decoration_text VALUES(115,'en','Hard Water Res Jewel 4');
INSERT INTO decoration_text VALUES(116,'en','Hard Ice Res Jewel 4');
INSERT INTO decoration_text VALUES(117,'en','Hard Thunder Res Jewel 4');
INSERT INTO decoration_text VALUES(118,'en','Hard Dragon Res Jewel 4');
INSERT INTO decoration_text VALUES(119,'en','Antidote Jewel+ 4');
INSERT INTO decoration_text VALUES(120,'en','Antipara Jewel+ 4');
INSERT INTO decoration_text VALUES(121,'en','Pep Jewel+ 4');
INSERT INTO decoration_text VALUES(122,'en','Steadfast Jewel+ 4');
INSERT INTO decoration_text VALUES(123,'en','Antiblast Jewel+ 4');
INSERT INTO decoration_text VALUES(124,'en','Suture Jewel+ 4');
INSERT INTO decoration_text VALUES(125,'en','Def Lock Jewel+ 4');
INSERT INTO decoration_text VALUES(126,'en','Miasma Jewel+ 4');
INSERT INTO decoration_text VALUES(127,'en','Hungerless Jewel+ 4');
INSERT INTO decoration_text VALUES(128,'en','Recovery Jewel+ 4');
INSERT INTO decoration_text VALUES(129,'en','Tip Toe Jewel+ 4');
INSERT INTO decoration_text VALUES(130,'en','Intimidator Jewel+ 4');
INSERT INTO decoration_text VALUES(131,'en','Meowster Jewel+ 4');
INSERT INTO decoration_text VALUES(132,'en','Hard Tip Toe Jewel 4');
INSERT INTO decoration_text VALUES(133,'en','Hard Intimidator Jewel 4');
INSERT INTO decoration_text VALUES(134,'en','Hard Meowster Jewel 4');
INSERT INTO decoration_text VALUES(135,'en','Trueshot Jewel+ 4');
INSERT INTO decoration_text VALUES(136,'en','Heavy Artillery Jewel+ 4');
INSERT INTO decoration_text VALUES(137,'en','Botany Jewel+ 4');
INSERT INTO decoration_text VALUES(138,'en','Geology Jewel+ 4');
INSERT INTO decoration_text VALUES(139,'en','Survival Jewel+ 4');
INSERT INTO decoration_text VALUES(140,'en','Mirewalker Jewel+ 4');
INSERT INTO decoration_text VALUES(141,'en','Specimen Jewel+ 4');
INSERT INTO decoration_text VALUES(142,'en','Sonorous Jewel+ 4');
INSERT INTO decoration_text VALUES(143,'en','Hard Botany Jewel+ 4');
INSERT INTO decoration_text VALUES(144,'en','Hard Geology Jewel 4');
INSERT INTO decoration_text VALUES(145,'en','Hard Survival Jewel 4');
INSERT INTO decoration_text VALUES(146,'en','Hard Specimen Jewel 4');
INSERT INTO decoration_text VALUES(147,'en','Enduring Jewel+ 4');
INSERT INTO decoration_text VALUES(148,'en','Defense Jewel+ 4');
INSERT INTO decoration_text VALUES(149,'en','Hard Enduring Jewel 4');
INSERT INTO decoration_text VALUES(150,'en','Hard Defense Jewel 4');
INSERT INTO decoration_text VALUES(151,'en','Artillery Jewel+ 4');
INSERT INTO decoration_text VALUES(152,'en','Earplug Jewel+ 4');
INSERT INTO decoration_text VALUES(153,'en','Wind Resist Jewel+ 4');
INSERT INTO decoration_text VALUES(154,'en','Attack Jewel+ 4');
INSERT INTO decoration_text VALUES(155,'en','Expert Jewel+ 4');
INSERT INTO decoration_text VALUES(156,'en','Handicraft Jewel+ 4');
INSERT INTO decoration_text VALUES(157,'en','Throttle Jewel+ 4');
INSERT INTO decoration_text VALUES(158,'en','Challenger Jewel+ 4');
INSERT INTO decoration_text VALUES(159,'en','Potential Jewel+ 4');
INSERT INTO decoration_text VALUES(160,'en','Furor Jewel+ 4');
INSERT INTO decoration_text VALUES(161,'en','Physique Jewel+ 4');
INSERT INTO decoration_text VALUES(162,'en','Evasion Jewel+ 4');
INSERT INTO decoration_text VALUES(163,'en','Ironwall Jewel+ 4');
INSERT INTO decoration_text VALUES(164,'en','Friendship Jewel+ 4');
INSERT INTO decoration_text VALUES(165,'en','Drain/Physique Jewel 4');
INSERT INTO decoration_text VALUES(166,'en','Fortitude/Physique Jewel 4');
INSERT INTO decoration_text VALUES(167,'en','Crisis/Physique Jewel 4');
INSERT INTO decoration_text VALUES(168,'en','Ironwall/Physique Jewel 4');
INSERT INTO decoration_text VALUES(169,'en','Friendship/Physique Jewel 4');
INSERT INTO decoration_text VALUES(170,'en','Satiated/Physique Jewel 4');
INSERT INTO decoration_text VALUES(171,'en','Stonethrower/Physique Jewel 4');
INSERT INTO decoration_text VALUES(172,'en','Resistor/Physique Jewel 4');
INSERT INTO decoration_text VALUES(173,'en','Flight/Physique Jewel 4');
INSERT INTO decoration_text VALUES(174,'en','Sprinter/Physique Jewel 4');
INSERT INTO decoration_text VALUES(175,'en','Refresh/Physique Jewel 4');
INSERT INTO decoration_text VALUES(176,'en','Jumping/Physique Jewel 4');
INSERT INTO decoration_text VALUES(177,'en','Sheath/Physique Jewel 4');
INSERT INTO decoration_text VALUES(178,'en','Gobbler/Physique Jewel 4');
INSERT INTO decoration_text VALUES(179,'en','Grinder/Physique Jewel 4');
INSERT INTO decoration_text VALUES(180,'en','Bomber/Physique Jewel 4');
INSERT INTO decoration_text VALUES(181,'en','Fungiform/Physique Jewel 4');
INSERT INTO decoration_text VALUES(182,'en','Slider/Physique Jewel 4');
INSERT INTO decoration_text VALUES(183,'en','Guardian/Physique Jewel 4');
INSERT INTO decoration_text VALUES(184,'en','Drain/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(185,'en','Fortitude/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(186,'en','Crisis/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(187,'en','Ironwall/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(188,'en','Friendship/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(189,'en','Satiated/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(190,'en','Stonethrower/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(191,'en','Resistor/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(192,'en','Flight/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(193,'en','Sprinter/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(194,'en','Refresh/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(195,'en','Jumping/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(196,'en','Sheath/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(197,'en','Gobbler/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(198,'en','Grinder/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(199,'en','Bomber/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(200,'en','Fungiform/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(201,'en','Slider/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(202,'en','Guardian/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(203,'en','Drain/Attack Jewel 4');
INSERT INTO decoration_text VALUES(204,'en','Fortitude/Attack Jewel 4');
INSERT INTO decoration_text VALUES(205,'en','Crisis/Attack Jewel 4');
INSERT INTO decoration_text VALUES(206,'en','Ironwall/Attack Jewel 4');
INSERT INTO decoration_text VALUES(207,'en','Friendship/Attack Jewel 4');
INSERT INTO decoration_text VALUES(208,'en','Satiated/Attack Jewel 4');
INSERT INTO decoration_text VALUES(209,'en','Stonethrower/Attack Jewel 4');
INSERT INTO decoration_text VALUES(210,'en','Resistor/Attack Jewel 4');
INSERT INTO decoration_text VALUES(211,'en','Flight/Attack Jewel 4');
INSERT INTO decoration_text VALUES(212,'en','Sprinter/Attack Jewel 4');
INSERT INTO decoration_text VALUES(213,'en','Refresh/Attack Jewel 4');
INSERT INTO decoration_text VALUES(214,'en','Jumping/Attack Jewel 4');
INSERT INTO decoration_text VALUES(215,'en','Sheath/Attack Jewel 4');
INSERT INTO decoration_text VALUES(216,'en','Gobbler/Attack Jewel 4');
INSERT INTO decoration_text VALUES(217,'en','Grinder/Attack Jewel 4');
INSERT INTO decoration_text VALUES(218,'en','Bomber/Attack Jewel 4');
INSERT INTO decoration_text VALUES(219,'en','Fungiform/Attack Jewel 4');
INSERT INTO decoration_text VALUES(220,'en','Slider/Attack Jewel 4');
INSERT INTO decoration_text VALUES(221,'en','Guardian/Attack Jewel 4');
INSERT INTO decoration_text VALUES(222,'en','Drain/Expert Jewel 4');
INSERT INTO decoration_text VALUES(223,'en','Fortitude/Expert Jewel 4');
INSERT INTO decoration_text VALUES(224,'en','Crisis/Expert Jewel 4');
INSERT INTO decoration_text VALUES(225,'en','Ironwall/Expert Jewel 4');
INSERT INTO decoration_text VALUES(226,'en','Friendship/Expert Jewel 4');
INSERT INTO decoration_text VALUES(227,'en','Satiated/Expert Jewel 4');
INSERT INTO decoration_text VALUES(228,'en','Stonethrower/Expert Jewel 4');
INSERT INTO decoration_text VALUES(229,'en','Resistor/Expert Jewel 4');
INSERT INTO decoration_text VALUES(230,'en','Flight/Expert Jewel 4');
INSERT INTO decoration_text VALUES(231,'en','Sprinter/Expert Jewel 4');
INSERT INTO decoration_text VALUES(232,'en','Refresh/Expert Jewel 4');
INSERT INTO decoration_text VALUES(233,'en','Jumping/Expert Jewel 4');
INSERT INTO decoration_text VALUES(234,'en','Sheath/Expert Jewel 4');
INSERT INTO decoration_text VALUES(235,'en','Gobbler/Expert Jewel 4');
INSERT INTO decoration_text VALUES(236,'en','Grinder/Expert Jewel 4');
INSERT INTO decoration_text VALUES(237,'en','Bomber/Expert Jewel 4');
INSERT INTO decoration_text VALUES(238,'en','Fungiform/Expert Jewel 4');
INSERT INTO decoration_text VALUES(239,'en','Slider/Expert Jewel 4');
INSERT INTO decoration_text VALUES(240,'en','Guardian/Expert Jewel 4');
INSERT INTO decoration_text VALUES(241,'en','Drain/Release Jewel 4');
INSERT INTO decoration_text VALUES(242,'en','Fortitude/Release Jewel 4');
INSERT INTO decoration_text VALUES(243,'en','Crisis/Release Jewel 4');
INSERT INTO decoration_text VALUES(244,'en','Ironwall/Release Jewel 4');
INSERT INTO decoration_text VALUES(245,'en','Friendship/Release Jewel 4');
INSERT INTO decoration_text VALUES(246,'en','Satiated/Release Jewel 4');
INSERT INTO decoration_text VALUES(247,'en','Stonethrower/Release Jewel 4');
INSERT INTO decoration_text VALUES(248,'en','Resistor/Release Jewel 4');
INSERT INTO decoration_text VALUES(249,'en','Flight/Release Jewel 4');
INSERT INTO decoration_text VALUES(250,'en','Sprinter/Release Jewel 4');
INSERT INTO decoration_text VALUES(251,'en','Refresh/Release Jewel 4');
INSERT INTO decoration_text VALUES(252,'en','Jumping/Release Jewel 4');
INSERT INTO decoration_text VALUES(253,'en','Sheath/Release Jewel 4');
INSERT INTO decoration_text VALUES(254,'en','Gobbler/Release Jewel 4');
INSERT INTO decoration_text VALUES(255,'en','Grinder/Release Jewel 4');
INSERT INTO decoration_text VALUES(256,'en','Bomber/Release Jewel 4');
INSERT INTO decoration_text VALUES(257,'en','Fungiform/Release Jewel 4');
INSERT INTO decoration_text VALUES(258,'en','Slider/Release Jewel 4');
INSERT INTO decoration_text VALUES(259,'en','Guardian/Release Jewel 4');
INSERT INTO decoration_text VALUES(260,'en','Drain/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(261,'en','Fortitude/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(262,'en','Crisis/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(263,'en','Ironwall/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(264,'en','Friendship/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(265,'en','Satiated/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(266,'en','Stonethrower/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(267,'en','Resistor/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(268,'en','Flight/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(269,'en','Sprinter/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(270,'en','Refresh/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(271,'en','Jumping/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(272,'en','Sheath/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(273,'en','Gobbler/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(274,'en','Grinder/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(275,'en','Bomber/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(276,'en','Fungiform/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(277,'en','Slider/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(278,'en','Guardian/Handicraft Jewel 4');
INSERT INTO decoration_text VALUES(279,'en','Footing/Protection Jewel 4');
INSERT INTO decoration_text VALUES(280,'en','Charger/Protection Jewel 4');
INSERT INTO decoration_text VALUES(281,'en','Enhancer/Protection Jewel 4');
INSERT INTO decoration_text VALUES(282,'en','Destroyer/Protection Jewel 4');
INSERT INTO decoration_text VALUES(283,'en','KO/Protection Jewel 4');
INSERT INTO decoration_text VALUES(284,'en','Potential/Protection Jewel 4');
INSERT INTO decoration_text VALUES(285,'en','Wind Resist/Protection Jewel 4');
INSERT INTO decoration_text VALUES(286,'en','Draw/Protection Jewel 4');
INSERT INTO decoration_text VALUES(287,'en','Throttle/Protection Jewel 4');
INSERT INTO decoration_text VALUES(288,'en','Challenger/Protection Jewel 4');
INSERT INTO decoration_text VALUES(289,'en','Flawless/Protection Jewel 4');
INSERT INTO decoration_text VALUES(290,'en','Furor/Protection Jewel 4');
INSERT INTO decoration_text VALUES(291,'en','Mighty/Protection Jewel 4');
INSERT INTO decoration_text VALUES(292,'en','Brace/Protection Jewel 4');
INSERT INTO decoration_text VALUES(293,'en','Phoenix/Protection Jewel 4');
INSERT INTO decoration_text VALUES(294,'en','Earplug/Protection Jewel 4');
INSERT INTO decoration_text VALUES(295,'en','Critical/Protection Jewel 4');
INSERT INTO decoration_text VALUES(296,'en','Tenderizer/Protection Jewel 4');
INSERT INTO decoration_text VALUES(297,'en','Handicraft/Protection Jewel 4');
INSERT INTO decoration_text VALUES(298,'en','Release/Protection Jewel 4');
INSERT INTO decoration_text VALUES(299,'en','Footing/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(300,'en','Charger/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(301,'en','Enhancer/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(302,'en','Destroyer/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(303,'en','KO/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(304,'en','Potential/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(305,'en','Wind Resist/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(306,'en','Draw/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(307,'en','Throttle/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(308,'en','Challenger/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(309,'en','Flawless/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(310,'en','Furor/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(311,'en','Mighty/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(312,'en','Brace/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(313,'en','Phoenix/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(314,'en','Earplug/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(315,'en','Critical/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(316,'en','Tenderizer/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(317,'en','Handicraft/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(318,'en','Release/Medicine Jewel 4');
INSERT INTO decoration_text VALUES(319,'en','Footing/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(320,'en','Charger/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(321,'en','Enhancer/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(322,'en','Destroyer/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(323,'en','KO/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(324,'en','Potential/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(325,'en','Wind Resist/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(326,'en','Draw/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(327,'en','Throttle/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(328,'en','Challenger/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(329,'en','Flawless/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(330,'en','Furor/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(331,'en','Mighty/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(332,'en','Brace/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(333,'en','Phoenix/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(334,'en','Earplug/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(335,'en','Critical/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(336,'en','Tenderizer/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(337,'en','Handicraft/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(338,'en','Release/Vitality Jewel 4');
INSERT INTO decoration_text VALUES(339,'en','Footing/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(340,'en','Charger/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(341,'en','Enhancer/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(342,'en','Destroyer/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(343,'en','KO/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(344,'en','Potential/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(345,'en','Wind Resist/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(346,'en','Draw/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(347,'en','Throttle/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(348,'en','Challenger/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(349,'en','Flawless/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(350,'en','Furor/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(351,'en','Mighty/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(352,'en','Brace/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(353,'en','Phoenix/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(354,'en','Earplug/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(355,'en','Critical/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(356,'en','Tenderizer/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(357,'en','Handicraft/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(358,'en','Release/Maintenance Jewel 4');
INSERT INTO decoration_text VALUES(359,'en','Footing/Physique Jewel 4');
INSERT INTO decoration_text VALUES(360,'en','Charger/Physique Jewel 4');
INSERT INTO decoration_text VALUES(361,'en','Enhancer/Physique Jewel 4');
INSERT INTO decoration_text VALUES(362,'en','Destroyer/Physique Jewel 4');
INSERT INTO decoration_text VALUES(363,'en','KO/Physique Jewel 4');
INSERT INTO decoration_text VALUES(364,'en','Potential/Physique Jewel 4');
INSERT INTO decoration_text VALUES(365,'en','Wind Resist/Physique Jewel 4');
INSERT INTO decoration_text VALUES(366,'en','Draw/Physique Jewel 4');
INSERT INTO decoration_text VALUES(367,'en','Throttle/Physique Jewel 4');
INSERT INTO decoration_text VALUES(368,'en','Challenger/Physique Jewel 4');
INSERT INTO decoration_text VALUES(369,'en','Flawless/Physique Jewel 4');
INSERT INTO decoration_text VALUES(370,'en','Furor/Physique Jewel 4');
INSERT INTO decoration_text VALUES(371,'en','Mighty/Physique Jewel 4');
INSERT INTO decoration_text VALUES(372,'en','Brace/Physique Jewel 4');
INSERT INTO decoration_text VALUES(373,'en','Phoenix/Physique Jewel 4');
INSERT INTO decoration_text VALUES(374,'en','Earplug/Physique Jewel 4');
INSERT INTO decoration_text VALUES(375,'en','Critical/Physique Jewel 4');
INSERT INTO decoration_text VALUES(376,'en','Tenderizer/Physique Jewel 4');
INSERT INTO decoration_text VALUES(377,'en','Handicraft/Physique Jewel 4');
INSERT INTO decoration_text VALUES(378,'en','Release/Physique Jewel 4');
INSERT INTO decoration_text VALUES(379,'en','Footing/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(380,'en','Charger/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(381,'en','Enhancer/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(382,'en','Destroyer/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(383,'en','KO/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(384,'en','Potential/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(385,'en','Wind Resist/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(386,'en','Draw/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(387,'en','Throttle/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(388,'en','Challenger/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(389,'en','Flawless/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(390,'en','Furor/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(391,'en','Mighty/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(392,'en','Brace/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(393,'en','Phoenix/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(394,'en','Earplug/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(395,'en','Critical/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(396,'en','Tenderizer/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(397,'en','Handicraft/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(398,'en','Release/Evasion Jewel 4');
INSERT INTO decoration_text VALUES(399,'en','Survival Jewel 1');
INSERT INTO decoration_text VALUES(400,'en','Guardian Jewel 2');
INSERT INTO decoration_text VALUES(402,'en','Cooling Jewel 2');
INSERT INTO decoration_text VALUES(403,'en','Warming Jewel 2');
INSERT INTO decoration_text VALUES(404,'en','Diversion Jewel 3');
INSERT INTO decoration_text VALUES(405,'en','Acrobat Jewel 3');
INSERT INTO decoration_text VALUES(406,'en','Shaver Jewel 3');

COMMIT;