BEGIN;

INSERT INTO charm_text VALUES(1,'de','Gift-Talisman I',NULL);
INSERT INTO charm_text VALUES(2,'de','Gift-Talisman II',NULL);
INSERT INTO charm_text VALUES(3,'de','Gift-Talisman III',NULL);
INSERT INTO charm_text VALUES(4,'de','Angriff-Talisman I',NULL);
INSERT INTO charm_text VALUES(5,'de','Angriff-Talisman II',NULL);
INSERT INTO charm_text VALUES(6,'de','Angriff-Talisman III',NULL);
INSERT INTO charm_text VALUES(235,'de','Angriff-Talisman IV',NULL);
INSERT INTO charm_text VALUES(7,'de','VerteidigTalisman I',NULL);
INSERT INTO charm_text VALUES(8,'de','VerteidigTalisman II',NULL);
INSERT INTO charm_text VALUES(9,'de','VerteidigTalisman III',NULL);
INSERT INTO charm_text VALUES(236,'de','VerteidigTalisman IV',NULL);
INSERT INTO charm_text VALUES(237,'de','VerteidigTalisman V',NULL);
INSERT INTO charm_text VALUES(10,'de','Lähm-Talisman I',NULL);
INSERT INTO charm_text VALUES(11,'de','Lähm-Talisman II',NULL);
INSERT INTO charm_text VALUES(12,'de','Lähm-Talisman III',NULL);
INSERT INTO charm_text VALUES(13,'de','Schlaf-Talisman I',NULL);
INSERT INTO charm_text VALUES(14,'de','Schlaf-Talisman II',NULL);
INSERT INTO charm_text VALUES(15,'de','Schlaf-Talisman III',NULL);
INSERT INTO charm_text VALUES(16,'de','BetäubungTalisman I',NULL);
INSERT INTO charm_text VALUES(17,'de','BetäubungTalismanII',NULL);
INSERT INTO charm_text VALUES(18,'de','BetäubungTalismanIII',NULL);
INSERT INTO charm_text VALUES(19,'de','Windsicher-Talisman I',NULL);
INSERT INTO charm_text VALUES(20,'de','WindsicherTalisman II',NULL);
INSERT INTO charm_text VALUES(21,'de','WindsicherTalismanIII',NULL);
INSERT INTO charm_text VALUES(238,'de','WindsicherTalisman IV',NULL);
INSERT INTO charm_text VALUES(22,'de','GesundheitTalisman I',NULL);
INSERT INTO charm_text VALUES(23,'de','GesundheitTalismanII',NULL);
INSERT INTO charm_text VALUES(24,'de','GesundheitTalismanIII',NULL);
INSERT INTO charm_text VALUES(25,'de','Erholung-Talisman I',NULL);
INSERT INTO charm_text VALUES(26,'de','Erholung-Talisman II',NULL);
INSERT INTO charm_text VALUES(27,'de','Erholung-Talisman III',NULL);
INSERT INTO charm_text VALUES(28,'de','Feuer-Talisman I',NULL);
INSERT INTO charm_text VALUES(29,'de','Feuer-Talisman II',NULL);
INSERT INTO charm_text VALUES(30,'de','Feuer-Talisman III',NULL);
INSERT INTO charm_text VALUES(31,'de','Wasser-Talisman I',NULL);
INSERT INTO charm_text VALUES(32,'de','Wasser-Talisman II',NULL);
INSERT INTO charm_text VALUES(33,'de','Wasser-Talisman III',NULL);
INSERT INTO charm_text VALUES(34,'de','Donner-Talisman I',NULL);
INSERT INTO charm_text VALUES(35,'de','Donner-Talisman II',NULL);
INSERT INTO charm_text VALUES(36,'de','Donner-Talisman III',NULL);
INSERT INTO charm_text VALUES(37,'de','Geloder-Talisman I',NULL);
INSERT INTO charm_text VALUES(38,'de','Geloder-Talisman II',NULL);
INSERT INTO charm_text VALUES(39,'de','Geloder-Talisman III',NULL);
INSERT INTO charm_text VALUES(239,'de','Geloder-Talisman IV',NULL);
INSERT INTO charm_text VALUES(240,'de','Geloder-Talisman V',NULL);
INSERT INTO charm_text VALUES(40,'de','Flut-Talisman I',NULL);
INSERT INTO charm_text VALUES(41,'de','Flut-Talisman II',NULL);
INSERT INTO charm_text VALUES(42,'de','Flut-Talisman III',NULL);
INSERT INTO charm_text VALUES(241,'de','Flut-Talisman IV',NULL);
INSERT INTO charm_text VALUES(242,'de','Flut-Talisman V',NULL);
INSERT INTO charm_text VALUES(43,'de','Gewitter-Talisman I',NULL);
INSERT INTO charm_text VALUES(44,'de','Gewitter-Talisman II',NULL);
INSERT INTO charm_text VALUES(45,'de','Gewitter-Talisman III',NULL);
INSERT INTO charm_text VALUES(243,'de','Gewitter-Talisman IV',NULL);
INSERT INTO charm_text VALUES(244,'de','Gewitter-Talisman V',NULL);
INSERT INTO charm_text VALUES(46,'de','Giftbiss-Talisman I',NULL);
INSERT INTO charm_text VALUES(47,'de','Giftbiss-Talisman II',NULL);
INSERT INTO charm_text VALUES(48,'de','Giftbiss-Talisman III',NULL);
INSERT INTO charm_text VALUES(245,'de','Giftbiss-Talisman IV',NULL);
INSERT INTO charm_text VALUES(49,'de','ImmobilitätTalisman I',NULL);
INSERT INTO charm_text VALUES(50,'de','ImmobilitätTalismanII',NULL);
INSERT INTO charm_text VALUES(51,'de','ImmobilitätTalismnIII',NULL);
INSERT INTO charm_text VALUES(246,'de','ImmobilitätTalismanIV',NULL);
INSERT INTO charm_text VALUES(52,'de','Beruhigung-Talisman I',NULL);
INSERT INTO charm_text VALUES(53,'de','BeruhigungTalisman II',NULL);
INSERT INTO charm_text VALUES(54,'de','BeruhigungTalismanIII',NULL);
INSERT INTO charm_text VALUES(247,'de','BeruhigungTalismanIV',NULL);
INSERT INTO charm_text VALUES(55,'de','KO-Talisman I',NULL);
INSERT INTO charm_text VALUES(56,'de','KO-Talisman II',NULL);
INSERT INTO charm_text VALUES(57,'de','KO-Talisman III',NULL);
INSERT INTO charm_text VALUES(58,'de','Entkräften-Talisman I',NULL);
INSERT INTO charm_text VALUES(59,'de','EntkräftenTalisman II',NULL);
INSERT INTO charm_text VALUES(60,'de','EntkräftenTalismanIII',NULL);
INSERT INTO charm_text VALUES(61,'de','Artillerie-Talisman I',NULL);
INSERT INTO charm_text VALUES(62,'de','ArtillerieTalisman II',NULL);
INSERT INTO charm_text VALUES(63,'de','ArtillerieTalismanIII',NULL);
INSERT INTO charm_text VALUES(64,'de','Hungerfrei-Talisman I',NULL);
INSERT INTO charm_text VALUES(65,'de','HungerfreiTalisman II',NULL);
INSERT INTO charm_text VALUES(66,'de','HungerfreiTalisman III',NULL);
INSERT INTO charm_text VALUES(67,'de','EisenplatteTalisman I',NULL);
INSERT INTO charm_text VALUES(68,'de','EisenplatteTalismanII',NULL);
INSERT INTO charm_text VALUES(69,'de','EisenplatteTalismnIII',NULL);
INSERT INTO charm_text VALUES(248,'de','EisenplatteTalismanIV',NULL);
INSERT INTO charm_text VALUES(249,'de','EisenplatteTalisman V',NULL);
INSERT INTO charm_text VALUES(70,'de','FreundschaftTalismn I',NULL);
INSERT INTO charm_text VALUES(71,'de','FreundschaftTalismnII',NULL);
INSERT INTO charm_text VALUES(72,'de','FreundschaftTlismnIII',NULL);
INSERT INTO charm_text VALUES(250,'de','FreundschaftTalismnIV',NULL);
INSERT INTO charm_text VALUES(251,'de','FreundschaftTalismn V',NULL);
INSERT INTO charm_text VALUES(73,'de','VerlängerungTalismn I',NULL);
INSERT INTO charm_text VALUES(74,'de','VerlängerungTalismnII',NULL);
INSERT INTO charm_text VALUES(75,'de','VerlängerungTlismnIII',NULL);
INSERT INTO charm_text VALUES(76,'de','Vielfraß-Talisman I',NULL);
INSERT INTO charm_text VALUES(77,'de','Vielfraß-Talisman II',NULL);
INSERT INTO charm_text VALUES(78,'de','Vielfraß-Talisman III',NULL);
INSERT INTO charm_text VALUES(79,'de','Segen-Talisman I',NULL);
INSERT INTO charm_text VALUES(80,'de','Segen-Talisman II',NULL);
INSERT INTO charm_text VALUES(81,'de','Segen-Talisman III',NULL);
INSERT INTO charm_text VALUES(82,'de','VersammlungTalisman I',NULL);
INSERT INTO charm_text VALUES(83,'de','VersammlungTalismn II',NULL);
INSERT INTO charm_text VALUES(84,'de','VersammlungTalismnIII',NULL);
INSERT INTO charm_text VALUES(252,'de','VersammlungTalismn IV',NULL);
INSERT INTO charm_text VALUES(253,'de','VersammlungTalisman V',NULL);
INSERT INTO charm_text VALUES(85,'de','Botanik-Talisman I',NULL);
INSERT INTO charm_text VALUES(86,'de','Botanik-Talisman II',NULL);
INSERT INTO charm_text VALUES(87,'de','Botanik-Talisman III',NULL);
INSERT INTO charm_text VALUES(254,'de','Botanik-Talisman IV',NULL);
INSERT INTO charm_text VALUES(88,'de','Geologie-Talisman I',NULL);
INSERT INTO charm_text VALUES(89,'de','Geologie-Talisman II',NULL);
INSERT INTO charm_text VALUES(90,'de','Geologie-Talisman III',NULL);
INSERT INTO charm_text VALUES(91,'de','Schleuder-Talisman I',NULL);
INSERT INTO charm_text VALUES(92,'de','Schleuder-Talisman II',NULL);
INSERT INTO charm_text VALUES(93,'de','SchleuderTalisman III',NULL);
INSERT INTO charm_text VALUES(94,'de','Tarnung-Talisman I',NULL);
INSERT INTO charm_text VALUES(95,'de','Tarnung-Talisman II',NULL);
INSERT INTO charm_text VALUES(96,'de','Tarnung-Talisman III',NULL);
INSERT INTO charm_text VALUES(97,'de','Rauch-Talisman I',NULL);
INSERT INTO charm_text VALUES(98,'de','Rauch-Talisman II',NULL);
INSERT INTO charm_text VALUES(99,'de','Rauch-Talisman III',NULL);
INSERT INTO charm_text VALUES(100,'de','SumpfläuferTalisman I',NULL);
INSERT INTO charm_text VALUES(101,'de','SumpfläuferTalismn II',NULL);
INSERT INTO charm_text VALUES(102,'de','SumpfläuferTalismnIII',NULL);
INSERT INTO charm_text VALUES(103,'de','Insekten-Talisman I',NULL);
INSERT INTO charm_text VALUES(104,'de','Insekten-Talisman II',NULL);
INSERT INTO charm_text VALUES(105,'de','Insekten-Talisman III',NULL);
INSERT INTO charm_text VALUES(106,'de','EinschüchternTlismn I',NULL);
INSERT INTO charm_text VALUES(107,'de','EinschüchternTlismnII',NULL);
INSERT INTO charm_text VALUES(108,'de','EinschüchtrnTlismnIII',NULL);
INSERT INTO charm_text VALUES(109,'de','Geschütz-Talisman I',NULL);
INSERT INTO charm_text VALUES(110,'de','Geschütz-Talisman II',NULL);
INSERT INTO charm_text VALUES(111,'de','KleinHungerTalisman',NULL);
INSERT INTO charm_text VALUES(112,'de','Spürhund-Talisman',NULL);
INSERT INTO charm_text VALUES(113,'de','Kräftigung-Talisman',NULL);
INSERT INTO charm_text VALUES(114,'de','Darbietung-Talisman I',NULL);
INSERT INTO charm_text VALUES(255,'de','DarbietungTalismanII',NULL);
INSERT INTO charm_text VALUES(115,'de','Kapazität-Talisman',NULL);
INSERT INTO charm_text VALUES(116,'de','Blutung-Talisman I',NULL);
INSERT INTO charm_text VALUES(117,'de','Blutung-Talisman II',NULL);
INSERT INTO charm_text VALUES(118,'de','Blutung-Talisman III',NULL);
INSERT INTO charm_text VALUES(119,'de','SchnellheilTalisman I',NULL);
INSERT INTO charm_text VALUES(120,'de','SchnellheilTalismanII',NULL);
INSERT INTO charm_text VALUES(121,'de','SchnellheilTalismnIII',NULL);
INSERT INTO charm_text VALUES(122,'de','Eis-Talisman I',NULL);
INSERT INTO charm_text VALUES(123,'de','Eis-Talisman II',NULL);
INSERT INTO charm_text VALUES(124,'de','Eis-Talisman III',NULL);
INSERT INTO charm_text VALUES(125,'de','Pest-Talisman I',NULL);
INSERT INTO charm_text VALUES(126,'de','Pest-Talisman II',NULL);
INSERT INTO charm_text VALUES(127,'de','Pest-Talisman III',NULL);
INSERT INTO charm_text VALUES(128,'de','Frost-Talisman I',NULL);
INSERT INTO charm_text VALUES(129,'de','Frost-Talisman II',NULL);
INSERT INTO charm_text VALUES(130,'de','Frost-Talisman III',NULL);
INSERT INTO charm_text VALUES(256,'de','Frost-Talisman IV',NULL);
INSERT INTO charm_text VALUES(257,'de','Frost-Talisman V',NULL);
INSERT INTO charm_text VALUES(131,'de','Meister-Talisman I',NULL);
INSERT INTO charm_text VALUES(132,'de','Meister-Talisman II',NULL);
INSERT INTO charm_text VALUES(133,'de','Meister-Talisman III',NULL);
INSERT INTO charm_text VALUES(258,'de','Meister-Talisman IV',NULL);
INSERT INTO charm_text VALUES(134,'de','Ausweich-Talisman I',NULL);
INSERT INTO charm_text VALUES(135,'de','Ausweich-Talisman II',NULL);
INSERT INTO charm_text VALUES(136,'de','Ausweich-Talisman III',NULL);
INSERT INTO charm_text VALUES(259,'de','Ausweich-Talisman IV',NULL);
INSERT INTO charm_text VALUES(137,'de','Wegstecken-Talisman I',NULL);
INSERT INTO charm_text VALUES(138,'de','WegsteckenTalisman II',NULL);
INSERT INTO charm_text VALUES(139,'de','WegsteckenTalismanIII',NULL);
INSERT INTO charm_text VALUES(140,'de','Wetzstein-Talisman I',NULL);
INSERT INTO charm_text VALUES(141,'de','Wetzstein-Talisman II',NULL);
INSERT INTO charm_text VALUES(142,'de','Wetzstein-Talisman III',NULL);
INSERT INTO charm_text VALUES(143,'de','Explosion-Talisman I',NULL);
INSERT INTO charm_text VALUES(144,'de','ExplosionTalisman II',NULL);
INSERT INTO charm_text VALUES(145,'de','ExplosionTalismanIII',NULL);
INSERT INTO charm_text VALUES(146,'de','Drachen-Talisman I',NULL);
INSERT INTO charm_text VALUES(147,'de','Drachen-Talisman II',NULL);
INSERT INTO charm_text VALUES(148,'de','Drachen-Talisman III',NULL);
INSERT INTO charm_text VALUES(149,'de','Wyrmgeißel-Talisman I',NULL);
INSERT INTO charm_text VALUES(150,'de','WyrmgeißelTalisman II',NULL);
INSERT INTO charm_text VALUES(151,'de','WyrmgeißelTalismanIII',NULL);
INSERT INTO charm_text VALUES(260,'de','WyrmgeißelTalisman IV',NULL);
INSERT INTO charm_text VALUES(261,'de','Wyrmgeißel-Talisman V',NULL);
INSERT INTO charm_text VALUES(152,'de','Zerstörung-Talisman I',NULL);
INSERT INTO charm_text VALUES(153,'de','ZerstörungTalisman II',NULL);
INSERT INTO charm_text VALUES(154,'de','ZerstörungTalismanIII',NULL);
INSERT INTO charm_text VALUES(262,'de','ZerstörungTalismanIV',NULL);
INSERT INTO charm_text VALUES(155,'de','Ziehen-Talisman I',NULL);
INSERT INTO charm_text VALUES(156,'de','Ziehen-Talisman II',NULL);
INSERT INTO charm_text VALUES(301,'de','Ziehen-Talisman III',NULL);
INSERT INTO charm_text VALUES(157,'de','SpezialschussTalsmn I',NULL);
INSERT INTO charm_text VALUES(158,'de','SpezialschussTalsmnII',NULL);
INSERT INTO charm_text VALUES(159,'de','Marathon-Talisman I',NULL);
INSERT INTO charm_text VALUES(160,'de','Marathon-Talisman II',NULL);
INSERT INTO charm_text VALUES(263,'de','Marathon-Talisman III',NULL);
INSERT INTO charm_text VALUES(161,'de','Fitness-Talisman I',NULL);
INSERT INTO charm_text VALUES(162,'de','Fitness-Talisman II',NULL);
INSERT INTO charm_text VALUES(163,'de','Fitness-Talisman III',NULL);
INSERT INTO charm_text VALUES(264,'de','Fitness-Talisman IV',NULL);
INSERT INTO charm_text VALUES(303,'de','Fitness-Talisman V',NULL);
INSERT INTO charm_text VALUES(164,'de','Energie-Talisman I',NULL);
INSERT INTO charm_text VALUES(165,'de','Energie-Talisman II',NULL);
INSERT INTO charm_text VALUES(265,'de','Energie-Talisman III',NULL);
INSERT INTO charm_text VALUES(166,'de','Luftsprung-Talisman I',NULL);
INSERT INTO charm_text VALUES(167,'de','LuftsprungTalisman II',NULL);
INSERT INTO charm_text VALUES(266,'de','LuftsprungTalismanIII',NULL);
INSERT INTO charm_text VALUES(168,'de','Bombardier-Talisman I',NULL);
INSERT INTO charm_text VALUES(169,'de','BombardierTalisman II',NULL);
INSERT INTO charm_text VALUES(170,'de','BombardierTalismanIII',NULL);
INSERT INTO charm_text VALUES(171,'de','Pilz-Talisman I',NULL);
INSERT INTO charm_text VALUES(172,'de','Pilz-Talisman II',NULL);
INSERT INTO charm_text VALUES(267,'de','Pilz-Talisman III',NULL);
INSERT INTO charm_text VALUES(173,'de','Erwachen-Talisman I',NULL);
INSERT INTO charm_text VALUES(174,'de','Erwachen-Talisman II',NULL);
INSERT INTO charm_text VALUES(268,'de','Erwachen-Talisman III',NULL);
INSERT INTO charm_text VALUES(175,'de','Handwerk-Talisman I',NULL);
INSERT INTO charm_text VALUES(176,'de','Handwerk-Talisman II',NULL);
INSERT INTO charm_text VALUES(177,'de','Handwerk-Talisman III',NULL);
INSERT INTO charm_text VALUES(269,'de','Handwerk-Talisman IV',NULL);
INSERT INTO charm_text VALUES(178,'de','Schlamm-Talisman',NULL);
INSERT INTO charm_text VALUES(179,'de','Kunstschuss-Talisman',NULL);
INSERT INTO charm_text VALUES(180,'de','Jägerleben-Talisman',NULL);
INSERT INTO charm_text VALUES(181,'de','Vermittler-Talisman',NULL);
INSERT INTO charm_text VALUES(182,'de','Sammler-Talisman',NULL);
INSERT INTO charm_text VALUES(183,'de','Block-Talisman I',NULL);
INSERT INTO charm_text VALUES(184,'de','Block-Talisman II',NULL);
INSERT INTO charm_text VALUES(185,'de','Block-Talisman III',NULL);
INSERT INTO charm_text VALUES(186,'de','OhrstöpselTalisman I',NULL);
INSERT INTO charm_text VALUES(187,'de','OhrstöpselTalisman II',NULL);
INSERT INTO charm_text VALUES(188,'de','OhrstöpselTalismanIII',NULL);
INSERT INTO charm_text VALUES(270,'de','OhrstöpselTalisman IV',NULL);
INSERT INTO charm_text VALUES(189,'de','Beben-Talisman I',NULL);
INSERT INTO charm_text VALUES(190,'de','Beben-Talisman II',NULL);
INSERT INTO charm_text VALUES(271,'de','Beben-Talisman III',NULL);
INSERT INTO charm_text VALUES(191,'de','Vorteil-Talisman I',NULL);
INSERT INTO charm_text VALUES(192,'de','Vorteil-Talisman II',NULL);
INSERT INTO charm_text VALUES(193,'de','Fokus-Talisman I',NULL);
INSERT INTO charm_text VALUES(194,'de','Fokus-Talisman II',NULL);
INSERT INTO charm_text VALUES(272,'de','Fokus-Talisman III',NULL);
INSERT INTO charm_text VALUES(195,'de','Brecher-Talisman I',NULL);
INSERT INTO charm_text VALUES(196,'de','Brecher-Talisman II',NULL);
INSERT INTO charm_text VALUES(273,'de','Brecher-Talisman III',NULL);
INSERT INTO charm_text VALUES(197,'de','Zorn-Talisman I',NULL);
INSERT INTO charm_text VALUES(198,'de','Zorn-Talisman II',NULL);
INSERT INTO charm_text VALUES(274,'de','Zorn-Talisman III',NULL);
INSERT INTO charm_text VALUES(275,'de','Zorn-Talisman IV',NULL);
INSERT INTO charm_text VALUES(297,'de','Zorn-Talisman V',NULL);
INSERT INTO charm_text VALUES(199,'de','Schneid-Talisman I',NULL);
INSERT INTO charm_text VALUES(200,'de','Schneid-Talisman II',NULL);
INSERT INTO charm_text VALUES(276,'de','Schneid-Talisman III',NULL);
INSERT INTO charm_text VALUES(277,'de','Schneid-Talisman IV',NULL);
INSERT INTO charm_text VALUES(201,'de','Wartung-Talisman I',NULL);
INSERT INTO charm_text VALUES(202,'de','Wartung-Talisman II',NULL);
INSERT INTO charm_text VALUES(203,'de','Wartung-Talisman III',NULL);
INSERT INTO charm_text VALUES(204,'de','Kraft-Talisman I',NULL);
INSERT INTO charm_text VALUES(205,'de','Kraft-Talisman II',NULL);
INSERT INTO charm_text VALUES(278,'de','Kraft-Talisman III',NULL);
INSERT INTO charm_text VALUES(279,'de','Kraft-Talisman IV',NULL);
INSERT INTO charm_text VALUES(298,'de','Kraft-Talisman V',NULL);
INSERT INTO charm_text VALUES(206,'de','Hetzer-Talisman I',NULL);
INSERT INTO charm_text VALUES(207,'de','Hetzer-Talisman II',NULL);
INSERT INTO charm_text VALUES(280,'de','Hetzer-Talisman III',NULL);
INSERT INTO charm_text VALUES(281,'de','Hetzer-Talisman IV',NULL);
INSERT INTO charm_text VALUES(300,'de','Hetzer-Talisman V',NULL);
INSERT INTO charm_text VALUES(208,'de','Unversehrt-Talisman I',NULL);
INSERT INTO charm_text VALUES(209,'de','UnversehrtTalisman II',NULL);
INSERT INTO charm_text VALUES(210,'de','Macht-Talisman I',NULL);
INSERT INTO charm_text VALUES(211,'de','Macht-Talisman II',NULL);
INSERT INTO charm_text VALUES(299,'de','Macht-Talisman III',NULL);
INSERT INTO charm_text VALUES(212,'de','Treffer-Talisman I',NULL);
INSERT INTO charm_text VALUES(213,'de','Treffer-Talisman II',NULL);
INSERT INTO charm_text VALUES(282,'de','Treffer-Talisman III',NULL);
INSERT INTO charm_text VALUES(214,'de','Miasma-Talisman I',NULL);
INSERT INTO charm_text VALUES(215,'de','Miasma-Talisman II',NULL);
INSERT INTO charm_text VALUES(216,'de','Miasma-Talisman III',NULL);
INSERT INTO charm_text VALUES(217,'de','StandardboostTalismnI',NULL);
INSERT INTO charm_text VALUES(283,'de','StandardbostTalsmnII',NULL);
INSERT INTO charm_text VALUES(218,'de','Klarer-Kopf-Talisman',NULL);
INSERT INTO charm_text VALUES(219,'de','Reiter-Talisman',NULL);
INSERT INTO charm_text VALUES(220,'de','Vermesser-Talisman',NULL);
INSERT INTO charm_text VALUES(221,'de','Kritischer Talisman I',NULL);
INSERT INTO charm_text VALUES(284,'de','KritischerTalisman II',NULL);
INSERT INTO charm_text VALUES(222,'de','Kräftigung-Talisman I',NULL);
INSERT INTO charm_text VALUES(223,'de','KräftigungTalisman II',NULL);
INSERT INTO charm_text VALUES(285,'de','KräftigungTalismnIII',NULL);
INSERT INTO charm_text VALUES(224,'de','Durchdring-Talisman I',NULL);
INSERT INTO charm_text VALUES(286,'de','DurchdringTalismanII',NULL);
INSERT INTO charm_text VALUES(225,'de','Zerstreu-Talisman I',NULL);
INSERT INTO charm_text VALUES(287,'de','Zerstreu-Talisman II',NULL);
INSERT INTO charm_text VALUES(226,'de','Giftschicht-Talisman',NULL);
INSERT INTO charm_text VALUES(227,'de','Lähmschicht-Talisman',NULL);
INSERT INTO charm_text VALUES(228,'de','SchlafschichtTalisman',NULL);
INSERT INTO charm_text VALUES(229,'de','ExplosionschchtTalmn',NULL);
INSERT INTO charm_text VALUES(230,'de','Geomantik-Talisman',NULL);
INSERT INTO charm_text VALUES(231,'de','Sturmwind-Talisman',NULL);
INSERT INTO charm_text VALUES(232,'de','LindwurmtöterTalismn',NULL);
INSERT INTO charm_text VALUES(233,'de','Bollwerk-Talisman',NULL);
INSERT INTO charm_text VALUES(288,'de','Wächter-Talisman I',NULL);
INSERT INTO charm_text VALUES(289,'de','Wächter-Talisman II',NULL);
INSERT INTO charm_text VALUES(290,'de','Wächter-Talisman III',NULL);
INSERT INTO charm_text VALUES(291,'de','Phönix-Talisman I',NULL);
INSERT INTO charm_text VALUES(292,'de','Phönix-Talisman II',NULL);
INSERT INTO charm_text VALUES(302,'de','Phönix-Talisman III',NULL);
INSERT INTO charm_text VALUES(293,'de','Diamantener Talisman',NULL);
INSERT INTO charm_text VALUES(294,'de','Rasiermesser-Talisman',NULL);
INSERT INTO charm_text VALUES(295,'de','Versiegler-Talisman',NULL);
INSERT INTO charm_text VALUES(296,'de','Stehvermögen-Talisman',NULL);
INSERT INTO charm_text VALUES(234,'de','Talisman der Fünften',NULL);
INSERT INTO charm_text VALUES(304,'de','Attack Charm V',NULL);
INSERT INTO charm_text VALUES(305,'de','Windproof Charm V',NULL);
INSERT INTO charm_text VALUES(306,'de','Survival Charm I',NULL);
INSERT INTO charm_text VALUES(307,'de','Survival Charm II',NULL);
INSERT INTO charm_text VALUES(308,'de','Survival Charm III',NULL);
INSERT INTO charm_text VALUES(309,'de','Master''s Charm V',NULL);
INSERT INTO charm_text VALUES(310,'de','Evasion Charm V',NULL);
INSERT INTO charm_text VALUES(311,'de','Handicraft Charm V',NULL);
INSERT INTO charm_text VALUES(312,'de','Earplugs Charm V',NULL);
INSERT INTO charm_text VALUES(313,'de','Exploiter Charm III',NULL);
INSERT INTO charm_text VALUES(314,'de','Grit Charm V',NULL);
INSERT INTO charm_text VALUES(315,'de','Unscathed Charm III',NULL);
INSERT INTO charm_text VALUES(316,'de','Critical Charm III',NULL);
INSERT INTO charm_text VALUES(317,'de','Shaver Charm',NULL);
INSERT INTO charm_text VALUES(1,'en','Poison Charm I',NULL);
INSERT INTO charm_text VALUES(2,'en','Poison Charm II',NULL);
INSERT INTO charm_text VALUES(3,'en','Poison Charm III',NULL);
INSERT INTO charm_text VALUES(4,'en','Attack Charm I',NULL);
INSERT INTO charm_text VALUES(5,'en','Attack Charm II',NULL);
INSERT INTO charm_text VALUES(6,'en','Attack Charm III',NULL);
INSERT INTO charm_text VALUES(235,'en','Attack Charm IV',NULL);
INSERT INTO charm_text VALUES(7,'en','Defense Charm I',NULL);
INSERT INTO charm_text VALUES(8,'en','Defense Charm II',NULL);
INSERT INTO charm_text VALUES(9,'en','Defense Charm III',NULL);
INSERT INTO charm_text VALUES(236,'en','Defense Charm IV',NULL);
INSERT INTO charm_text VALUES(237,'en','Defense Charm V',NULL);
INSERT INTO charm_text VALUES(10,'en','Paralysis Charm I',NULL);
INSERT INTO charm_text VALUES(11,'en','Paralysis Charm II',NULL);
INSERT INTO charm_text VALUES(12,'en','Paralysis Charm III',NULL);
INSERT INTO charm_text VALUES(13,'en','Sleep Charm I',NULL);
INSERT INTO charm_text VALUES(14,'en','Sleep Charm II',NULL);
INSERT INTO charm_text VALUES(15,'en','Sleep Charm III',NULL);
INSERT INTO charm_text VALUES(16,'en','Stun Charm I',NULL);
INSERT INTO charm_text VALUES(17,'en','Stun Charm II',NULL);
INSERT INTO charm_text VALUES(18,'en','Stun Charm III',NULL);
INSERT INTO charm_text VALUES(19,'en','Windproof Charm I',NULL);
INSERT INTO charm_text VALUES(20,'en','Windproof Charm II',NULL);
INSERT INTO charm_text VALUES(21,'en','Windproof Charm III',NULL);
INSERT INTO charm_text VALUES(238,'en','Windproof Charm IV',NULL);
INSERT INTO charm_text VALUES(22,'en','Health Charm I',NULL);
INSERT INTO charm_text VALUES(23,'en','Health Charm II',NULL);
INSERT INTO charm_text VALUES(24,'en','Health Charm III',NULL);
INSERT INTO charm_text VALUES(25,'en','Recovery Charm I',NULL);
INSERT INTO charm_text VALUES(26,'en','Recovery Charm II',NULL);
INSERT INTO charm_text VALUES(27,'en','Recovery Charm III',NULL);
INSERT INTO charm_text VALUES(28,'en','Fire Charm I',NULL);
INSERT INTO charm_text VALUES(29,'en','Fire Charm II',NULL);
INSERT INTO charm_text VALUES(30,'en','Fire Charm III',NULL);
INSERT INTO charm_text VALUES(31,'en','Water Charm I',NULL);
INSERT INTO charm_text VALUES(32,'en','Water Charm II',NULL);
INSERT INTO charm_text VALUES(33,'en','Water Charm III',NULL);
INSERT INTO charm_text VALUES(34,'en','Thunder Charm I',NULL);
INSERT INTO charm_text VALUES(35,'en','Thunder Charm II',NULL);
INSERT INTO charm_text VALUES(36,'en','Thunder Charm III',NULL);
INSERT INTO charm_text VALUES(37,'en','Blaze Charm I',NULL);
INSERT INTO charm_text VALUES(38,'en','Blaze Charm II',NULL);
INSERT INTO charm_text VALUES(39,'en','Blaze Charm III',NULL);
INSERT INTO charm_text VALUES(239,'en','Blaze Charm IV',NULL);
INSERT INTO charm_text VALUES(240,'en','Blaze Charm V',NULL);
INSERT INTO charm_text VALUES(40,'en','Flood Charm I',NULL);
INSERT INTO charm_text VALUES(41,'en','Flood Charm II',NULL);
INSERT INTO charm_text VALUES(42,'en','Flood Charm III',NULL);
INSERT INTO charm_text VALUES(241,'en','Flood Charm IV',NULL);
INSERT INTO charm_text VALUES(242,'en','Flood Charm V',NULL);
INSERT INTO charm_text VALUES(43,'en','Shock Charm I',NULL);
INSERT INTO charm_text VALUES(44,'en','Shock Charm II',NULL);
INSERT INTO charm_text VALUES(45,'en','Shock Charm III',NULL);
INSERT INTO charm_text VALUES(243,'en','Shock Charm IV',NULL);
INSERT INTO charm_text VALUES(244,'en','Shock Charm V',NULL);
INSERT INTO charm_text VALUES(46,'en','Venom Charm I',NULL);
INSERT INTO charm_text VALUES(47,'en','Venom Charm II',NULL);
INSERT INTO charm_text VALUES(48,'en','Venom Charm III',NULL);
INSERT INTO charm_text VALUES(245,'en','Venom Charm IV',NULL);
INSERT INTO charm_text VALUES(49,'en','Immobilize Charm I',NULL);
INSERT INTO charm_text VALUES(50,'en','Immobilize Charm II',NULL);
INSERT INTO charm_text VALUES(51,'en','Immobilize Charm III',NULL);
INSERT INTO charm_text VALUES(246,'en','Immobilize Charm IV',NULL);
INSERT INTO charm_text VALUES(52,'en','Tranq Charm I',NULL);
INSERT INTO charm_text VALUES(53,'en','Tranq Charm II',NULL);
INSERT INTO charm_text VALUES(54,'en','Tranq Charm III',NULL);
INSERT INTO charm_text VALUES(247,'en','Tranq Charm IV',NULL);
INSERT INTO charm_text VALUES(55,'en','KO Charm I',NULL);
INSERT INTO charm_text VALUES(56,'en','KO Charm II',NULL);
INSERT INTO charm_text VALUES(57,'en','KO Charm III',NULL);
INSERT INTO charm_text VALUES(58,'en','Enervate Charm I',NULL);
INSERT INTO charm_text VALUES(59,'en','Enervate Charm II',NULL);
INSERT INTO charm_text VALUES(60,'en','Enervate Charm III',NULL);
INSERT INTO charm_text VALUES(61,'en','Artillery Charm I',NULL);
INSERT INTO charm_text VALUES(62,'en','Artillery Charm II',NULL);
INSERT INTO charm_text VALUES(63,'en','Artillery Charm III',NULL);
INSERT INTO charm_text VALUES(64,'en','Hungerless Charm I',NULL);
INSERT INTO charm_text VALUES(65,'en','Hungerless Charm II',NULL);
INSERT INTO charm_text VALUES(66,'en','Hungerless Charm III',NULL);
INSERT INTO charm_text VALUES(67,'en','Ironside Charm I',NULL);
INSERT INTO charm_text VALUES(68,'en','Ironside Charm II',NULL);
INSERT INTO charm_text VALUES(69,'en','Ironside Charm III',NULL);
INSERT INTO charm_text VALUES(248,'en','Ironside Charm IV',NULL);
INSERT INTO charm_text VALUES(249,'en','Ironside Charm V',NULL);
INSERT INTO charm_text VALUES(70,'en','Friendship Charm I',NULL);
INSERT INTO charm_text VALUES(71,'en','Friendship Charm II',NULL);
INSERT INTO charm_text VALUES(72,'en','Friendship Charm III',NULL);
INSERT INTO charm_text VALUES(250,'en','Friendship Charm IV',NULL);
INSERT INTO charm_text VALUES(251,'en','Friendship Charm V',NULL);
INSERT INTO charm_text VALUES(73,'en','Extension Charm I',NULL);
INSERT INTO charm_text VALUES(74,'en','Extension Charm II',NULL);
INSERT INTO charm_text VALUES(75,'en','Extension Charm III',NULL);
INSERT INTO charm_text VALUES(76,'en','Glutton''s Charm I',NULL);
INSERT INTO charm_text VALUES(77,'en','Glutton''s Charm II',NULL);
INSERT INTO charm_text VALUES(78,'en','Glutton''s Charm III',NULL);
INSERT INTO charm_text VALUES(79,'en','Blessing Charm I',NULL);
INSERT INTO charm_text VALUES(80,'en','Blessing Charm II',NULL);
INSERT INTO charm_text VALUES(81,'en','Blessing Charm III',NULL);
INSERT INTO charm_text VALUES(82,'en','Rally Charm I',NULL);
INSERT INTO charm_text VALUES(83,'en','Rally Charm II',NULL);
INSERT INTO charm_text VALUES(84,'en','Rally Charm III',NULL);
INSERT INTO charm_text VALUES(252,'en','Rally Charm IV',NULL);
INSERT INTO charm_text VALUES(253,'en','Rally Charm V',NULL);
INSERT INTO charm_text VALUES(85,'en','Botany Charm I',NULL);
INSERT INTO charm_text VALUES(86,'en','Botany Charm II',NULL);
INSERT INTO charm_text VALUES(87,'en','Botany Charm III',NULL);
INSERT INTO charm_text VALUES(254,'en','Botany Charm IV',NULL);
INSERT INTO charm_text VALUES(88,'en','Geology Charm I',NULL);
INSERT INTO charm_text VALUES(89,'en','Geology Charm II',NULL);
INSERT INTO charm_text VALUES(90,'en','Geology Charm III',NULL);
INSERT INTO charm_text VALUES(91,'en','Slinger Charm I',NULL);
INSERT INTO charm_text VALUES(92,'en','Slinger Charm II',NULL);
INSERT INTO charm_text VALUES(93,'en','Slinger Charm III',NULL);
INSERT INTO charm_text VALUES(94,'en','Stealth Charm I',NULL);
INSERT INTO charm_text VALUES(95,'en','Stealth Charm II',NULL);
INSERT INTO charm_text VALUES(96,'en','Stealth Charm III',NULL);
INSERT INTO charm_text VALUES(97,'en','Smoke Charm I',NULL);
INSERT INTO charm_text VALUES(98,'en','Smoke Charm II',NULL);
INSERT INTO charm_text VALUES(99,'en','Smoke Charm III',NULL);
INSERT INTO charm_text VALUES(100,'en','Mirewalker Charm I',NULL);
INSERT INTO charm_text VALUES(101,'en','Mirewalker Charm II',NULL);
INSERT INTO charm_text VALUES(102,'en','Mirewalker Charm III',NULL);
INSERT INTO charm_text VALUES(103,'en','Insect Charm I',NULL);
INSERT INTO charm_text VALUES(104,'en','Insect Charm II',NULL);
INSERT INTO charm_text VALUES(105,'en','Insect Charm III',NULL);
INSERT INTO charm_text VALUES(106,'en','Intimidator Charm I',NULL);
INSERT INTO charm_text VALUES(107,'en','Intimidator Charm II',NULL);
INSERT INTO charm_text VALUES(108,'en','Intimidator Charm III',NULL);
INSERT INTO charm_text VALUES(109,'en','Heavy Artillery Charm I',NULL);
INSERT INTO charm_text VALUES(110,'en','Heavy Artillery Charm II',NULL);
INSERT INTO charm_text VALUES(111,'en','Light Eater''s Charm',NULL);
INSERT INTO charm_text VALUES(112,'en','Tracker Charm',NULL);
INSERT INTO charm_text VALUES(113,'en','Fortification Charm',NULL);
INSERT INTO charm_text VALUES(114,'en','Performer''s Charm',NULL);
INSERT INTO charm_text VALUES(255,'en','Performer''s Charm II',NULL);
INSERT INTO charm_text VALUES(115,'en','Capacity Charm',NULL);
INSERT INTO charm_text VALUES(116,'en','Bleed Charm I',NULL);
INSERT INTO charm_text VALUES(117,'en','Bleed Charm II',NULL);
INSERT INTO charm_text VALUES(118,'en','Bleed Charm III',NULL);
INSERT INTO charm_text VALUES(119,'en','Speed Heal Charm I',NULL);
INSERT INTO charm_text VALUES(120,'en','Speed Heal Charm II',NULL);
INSERT INTO charm_text VALUES(121,'en','Speed Heal Charm III',NULL);
INSERT INTO charm_text VALUES(122,'en','Ice Charm I',NULL);
INSERT INTO charm_text VALUES(123,'en','Ice Charm II',NULL);
INSERT INTO charm_text VALUES(124,'en','Ice Charm III',NULL);
INSERT INTO charm_text VALUES(125,'en','Blight Charm I',NULL);
INSERT INTO charm_text VALUES(126,'en','Blight Charm II',NULL);
INSERT INTO charm_text VALUES(127,'en','Blight Charm III',NULL);
INSERT INTO charm_text VALUES(128,'en','Frost Charm I',NULL);
INSERT INTO charm_text VALUES(129,'en','Frost Charm II',NULL);
INSERT INTO charm_text VALUES(130,'en','Frost Charm III',NULL);
INSERT INTO charm_text VALUES(256,'en','Frost Charm IV',NULL);
INSERT INTO charm_text VALUES(257,'en','Frost Charm V',NULL);
INSERT INTO charm_text VALUES(131,'en','Master''s Charm I',NULL);
INSERT INTO charm_text VALUES(132,'en','Master''s Charm II',NULL);
INSERT INTO charm_text VALUES(133,'en','Master''s Charm III',NULL);
INSERT INTO charm_text VALUES(258,'en','Master''s Charm IV',NULL);
INSERT INTO charm_text VALUES(134,'en','Evasion Charm I',NULL);
INSERT INTO charm_text VALUES(135,'en','Evasion Charm II',NULL);
INSERT INTO charm_text VALUES(136,'en','Evasion Charm III',NULL);
INSERT INTO charm_text VALUES(259,'en','Evasion Charm IV',NULL);
INSERT INTO charm_text VALUES(137,'en','Sheath Charm I',NULL);
INSERT INTO charm_text VALUES(138,'en','Sheath Charm II',NULL);
INSERT INTO charm_text VALUES(139,'en','Sheath Charm III',NULL);
INSERT INTO charm_text VALUES(140,'en','Whetstone Charm I',NULL);
INSERT INTO charm_text VALUES(141,'en','Whetstone Charm II',NULL);
INSERT INTO charm_text VALUES(142,'en','Whetstone Charm III',NULL);
INSERT INTO charm_text VALUES(143,'en','Blast Charm I',NULL);
INSERT INTO charm_text VALUES(144,'en','Blast Charm II',NULL);
INSERT INTO charm_text VALUES(145,'en','Blast Charm III',NULL);
INSERT INTO charm_text VALUES(146,'en','Dragon Charm I',NULL);
INSERT INTO charm_text VALUES(147,'en','Dragon Charm II',NULL);
INSERT INTO charm_text VALUES(148,'en','Dragon Charm III',NULL);
INSERT INTO charm_text VALUES(149,'en','Wyrmsbane Charm I',NULL);
INSERT INTO charm_text VALUES(150,'en','Wyrmsbane Charm II',NULL);
INSERT INTO charm_text VALUES(151,'en','Wyrmsbane Charm III',NULL);
INSERT INTO charm_text VALUES(260,'en','Wyrmsbane Charm IV',NULL);
INSERT INTO charm_text VALUES(261,'en','Wyrmsbane Charm V',NULL);
INSERT INTO charm_text VALUES(152,'en','Demolition Charm I',NULL);
INSERT INTO charm_text VALUES(153,'en','Demolition Charm II',NULL);
INSERT INTO charm_text VALUES(154,'en','Demolition Charm III',NULL);
INSERT INTO charm_text VALUES(262,'en','Demolition Charm IV',NULL);
INSERT INTO charm_text VALUES(155,'en','Draw Charm I',NULL);
INSERT INTO charm_text VALUES(156,'en','Draw Charm II',NULL);
INSERT INTO charm_text VALUES(301,'en','Draw Charm III',NULL);
INSERT INTO charm_text VALUES(157,'en','Special Shot Charm I',NULL);
INSERT INTO charm_text VALUES(158,'en','Special Shot Charm II',NULL);
INSERT INTO charm_text VALUES(159,'en','Marathon Charm I',NULL);
INSERT INTO charm_text VALUES(160,'en','Marathon Charm II',NULL);
INSERT INTO charm_text VALUES(263,'en','Marathon Charm III',NULL);
INSERT INTO charm_text VALUES(161,'en','Fitness Charm I',NULL);
INSERT INTO charm_text VALUES(162,'en','Fitness Charm II',NULL);
INSERT INTO charm_text VALUES(163,'en','Fitness Charm III',NULL);
INSERT INTO charm_text VALUES(264,'en','Fitness Charm IV',NULL);
INSERT INTO charm_text VALUES(303,'en','Fitness Charm V',NULL);
INSERT INTO charm_text VALUES(164,'en','Surge Charm I',NULL);
INSERT INTO charm_text VALUES(165,'en','Surge Charm II',NULL);
INSERT INTO charm_text VALUES(265,'en','Surge Charm III',NULL);
INSERT INTO charm_text VALUES(166,'en','Leaping Charm I',NULL);
INSERT INTO charm_text VALUES(167,'en','Leaping Charm II',NULL);
INSERT INTO charm_text VALUES(266,'en','Leaping Charm III',NULL);
INSERT INTO charm_text VALUES(168,'en','Bombardier Charm I',NULL);
INSERT INTO charm_text VALUES(169,'en','Bombardier Charm II',NULL);
INSERT INTO charm_text VALUES(170,'en','Bombardier Charm III',NULL);
INSERT INTO charm_text VALUES(171,'en','Mushroom Charm I',NULL);
INSERT INTO charm_text VALUES(172,'en','Mushroom Charm II',NULL);
INSERT INTO charm_text VALUES(267,'en','Mushroom Charm III',NULL);
INSERT INTO charm_text VALUES(173,'en','Awakening Charm I',NULL);
INSERT INTO charm_text VALUES(174,'en','Awakening Charm II',NULL);
INSERT INTO charm_text VALUES(268,'en','Awakening Charm III',NULL);
INSERT INTO charm_text VALUES(175,'en','Handicraft Charm I',NULL);
INSERT INTO charm_text VALUES(176,'en','Handicraft Charm II',NULL);
INSERT INTO charm_text VALUES(177,'en','Handicraft Charm III',NULL);
INSERT INTO charm_text VALUES(269,'en','Handicraft Charm IV',NULL);
INSERT INTO charm_text VALUES(178,'en','Mud Puppy Charm',NULL);
INSERT INTO charm_text VALUES(179,'en','Trickshot Charm',NULL);
INSERT INTO charm_text VALUES(180,'en','Hunter''s Life Charm',NULL);
INSERT INTO charm_text VALUES(181,'en','Procurer''s Charm',NULL);
INSERT INTO charm_text VALUES(182,'en','Gatherer''s Charm',NULL);
INSERT INTO charm_text VALUES(183,'en','Guard Charm I',NULL);
INSERT INTO charm_text VALUES(184,'en','Guard Charm II',NULL);
INSERT INTO charm_text VALUES(185,'en','Guard Charm III',NULL);
INSERT INTO charm_text VALUES(186,'en','Earplugs Charm I',NULL);
INSERT INTO charm_text VALUES(187,'en','Earplugs Charm II',NULL);
INSERT INTO charm_text VALUES(188,'en','Earplugs Charm III',NULL);
INSERT INTO charm_text VALUES(270,'en','Earplugs Charm IV',NULL);
INSERT INTO charm_text VALUES(189,'en','Tremor Charm I',NULL);
INSERT INTO charm_text VALUES(190,'en','Tremor Charm II',NULL);
INSERT INTO charm_text VALUES(271,'en','Tremor Charm III',NULL);
INSERT INTO charm_text VALUES(191,'en','Exploiter Charm I',NULL);
INSERT INTO charm_text VALUES(192,'en','Exploiter Charm II',NULL);
INSERT INTO charm_text VALUES(193,'en','Focus Charm I',NULL);
INSERT INTO charm_text VALUES(194,'en','Focus Charm II',NULL);
INSERT INTO charm_text VALUES(272,'en','Focus Charm III',NULL);
INSERT INTO charm_text VALUES(195,'en','Breaker Charm I',NULL);
INSERT INTO charm_text VALUES(196,'en','Breaker Charm II',NULL);
INSERT INTO charm_text VALUES(273,'en','Breaker Charm III',NULL);
INSERT INTO charm_text VALUES(197,'en','Fury Charm I',NULL);
INSERT INTO charm_text VALUES(198,'en','Fury Charm II',NULL);
INSERT INTO charm_text VALUES(274,'en','Fury Charm III',NULL);
INSERT INTO charm_text VALUES(275,'en','Fury Charm IV',NULL);
INSERT INTO charm_text VALUES(297,'en','Fury Charm V',NULL);
INSERT INTO charm_text VALUES(199,'en','Grit Charm I',NULL);
INSERT INTO charm_text VALUES(200,'en','Grit Charm II',NULL);
INSERT INTO charm_text VALUES(276,'en','Grit Charm III',NULL);
INSERT INTO charm_text VALUES(277,'en','Grit Charm IV',NULL);
INSERT INTO charm_text VALUES(201,'en','Maintenance Charm I',NULL);
INSERT INTO charm_text VALUES(202,'en','Maintenance Charm II',NULL);
INSERT INTO charm_text VALUES(203,'en','Maintenance Charm III',NULL);
INSERT INTO charm_text VALUES(204,'en','Power Charm I',NULL);
INSERT INTO charm_text VALUES(205,'en','Power Charm II',NULL);
INSERT INTO charm_text VALUES(278,'en','Power Charm III',NULL);
INSERT INTO charm_text VALUES(279,'en','Power Charm IV',NULL);
INSERT INTO charm_text VALUES(298,'en','Power Charm V',NULL);
INSERT INTO charm_text VALUES(206,'en','Challenger Charm I',NULL);
INSERT INTO charm_text VALUES(207,'en','Challenger Charm II',NULL);
INSERT INTO charm_text VALUES(280,'en','Challenger Charm III',NULL);
INSERT INTO charm_text VALUES(281,'en','Challenger Charm IV',NULL);
INSERT INTO charm_text VALUES(300,'en','Challenger Charm V',NULL);
INSERT INTO charm_text VALUES(208,'en','Unscathed Charm I',NULL);
INSERT INTO charm_text VALUES(209,'en','Unscathed Charm II',NULL);
INSERT INTO charm_text VALUES(210,'en','Mighty Charm I',NULL);
INSERT INTO charm_text VALUES(211,'en','Mighty Charm II',NULL);
INSERT INTO charm_text VALUES(299,'en','Mighty Charm III',NULL);
INSERT INTO charm_text VALUES(212,'en','Impact Charm I',NULL);
INSERT INTO charm_text VALUES(213,'en','Impact Charm II',NULL);
INSERT INTO charm_text VALUES(282,'en','Impact Charm III',NULL);
INSERT INTO charm_text VALUES(214,'en','Miasma Charm I',NULL);
INSERT INTO charm_text VALUES(215,'en','Miasma Charm II',NULL);
INSERT INTO charm_text VALUES(216,'en','Miasma Charm III',NULL);
INSERT INTO charm_text VALUES(217,'en','Normal Shots Charm',NULL);
INSERT INTO charm_text VALUES(283,'en','Normal Shots Charm II',NULL);
INSERT INTO charm_text VALUES(218,'en','Clearmind Charm',NULL);
INSERT INTO charm_text VALUES(219,'en','Rider''s Charm',NULL);
INSERT INTO charm_text VALUES(220,'en','Surveyor''s Charm',NULL);
INSERT INTO charm_text VALUES(221,'en','Critical Charm I',NULL);
INSERT INTO charm_text VALUES(284,'en','Critical Charm II',NULL);
INSERT INTO charm_text VALUES(222,'en','Invigorate Charm I',NULL);
INSERT INTO charm_text VALUES(223,'en','Invigorate Charm II',NULL);
INSERT INTO charm_text VALUES(285,'en','Invigorate Charm III',NULL);
INSERT INTO charm_text VALUES(224,'en','Penetration Charm',NULL);
INSERT INTO charm_text VALUES(286,'en','Penetration Charm II',NULL);
INSERT INTO charm_text VALUES(225,'en','Dispersal Charm',NULL);
INSERT INTO charm_text VALUES(287,'en','Dispersal Charm II',NULL);
INSERT INTO charm_text VALUES(226,'en','Poison Coating Charm',NULL);
INSERT INTO charm_text VALUES(227,'en','Para Coating Charm',NULL);
INSERT INTO charm_text VALUES(228,'en','Sleep Coating Charm',NULL);
INSERT INTO charm_text VALUES(229,'en','Blast Coating Charm',NULL);
INSERT INTO charm_text VALUES(230,'en','Geomancy Charm',NULL);
INSERT INTO charm_text VALUES(231,'en','Gale Charm',NULL);
INSERT INTO charm_text VALUES(232,'en','Wyrmslayer Charm',NULL);
INSERT INTO charm_text VALUES(233,'en','Bulwark Charm',NULL);
INSERT INTO charm_text VALUES(288,'en','Guardian Charm I',NULL);
INSERT INTO charm_text VALUES(289,'en','Guardian Charm II',NULL);
INSERT INTO charm_text VALUES(290,'en','Guardian Charm III',NULL);
INSERT INTO charm_text VALUES(291,'en','Phoenix Charm I',NULL);
INSERT INTO charm_text VALUES(292,'en','Phoenix Charm II',NULL);
INSERT INTO charm_text VALUES(302,'en','Phoenix Charm III',NULL);
INSERT INTO charm_text VALUES(293,'en','Adamantine Charm',NULL);
INSERT INTO charm_text VALUES(294,'en','Razor Sharp Charm',NULL);
INSERT INTO charm_text VALUES(295,'en','Sealer''s Charm',NULL);
INSERT INTO charm_text VALUES(296,'en','Gutsy Charm',NULL);
INSERT INTO charm_text VALUES(234,'en','Fair Wind Charm',NULL);
INSERT INTO charm_text VALUES(304,'en','Attack Charm V',NULL);
INSERT INTO charm_text VALUES(305,'en','Windproof Charm V',NULL);
INSERT INTO charm_text VALUES(306,'en','Survival Charm I',NULL);
INSERT INTO charm_text VALUES(307,'en','Survival Charm II',NULL);
INSERT INTO charm_text VALUES(308,'en','Survival Charm III',NULL);
INSERT INTO charm_text VALUES(309,'en','Master''s Charm V',NULL);
INSERT INTO charm_text VALUES(310,'en','Evasion Charm V',NULL);
INSERT INTO charm_text VALUES(311,'en','Handicraft Charm V',NULL);
INSERT INTO charm_text VALUES(312,'en','Earplugs Charm V',NULL);
INSERT INTO charm_text VALUES(313,'en','Exploiter Charm III',NULL);
INSERT INTO charm_text VALUES(314,'en','Grit Charm V',NULL);
INSERT INTO charm_text VALUES(315,'en','Unscathed Charm III',NULL);
INSERT INTO charm_text VALUES(316,'en','Critical Charm III',NULL);
INSERT INTO charm_text VALUES(317,'en','Shaver Charm',NULL);

COMMIT;