BEGIN;

INSERT INTO kinsect_text VALUES(1,'de','Keulendrohn I');
INSERT INTO kinsect_text VALUES(2,'de','Keulendrohn II');
INSERT INTO kinsect_text VALUES(3,'de','Keulendrohn III');
INSERT INTO kinsect_text VALUES(4,'de','Zangenkäfer I');
INSERT INTO kinsect_text VALUES(5,'de','Zangenkäfer II');
INSERT INTO kinsect_text VALUES(6,'de','Zangenkäfer III');
INSERT INTO kinsect_text VALUES(7,'de','Königszangenkäfer I');
INSERT INTO kinsect_text VALUES(8,'de','Königszangenkäfer II');
INSERT INTO kinsect_text VALUES(9,'de','Königszangenkäfer III');
INSERT INTO kinsect_text VALUES(10,'de','Kaiserinnenflügel I');
INSERT INTO kinsect_text VALUES(11,'de','Kaiserinnenflügel II');
INSERT INTO kinsect_text VALUES(12,'de','Kaiserinnenflügel III');
INSERT INTO kinsect_text VALUES(13,'de','Rigianbeter I');
INSERT INTO kinsect_text VALUES(14,'de','Rigianbeter II');
INSERT INTO kinsect_text VALUES(15,'de','Rigianbeter III');
INSERT INTO kinsect_text VALUES(16,'de','Dauerflieger I');
INSERT INTO kinsect_text VALUES(17,'de','Dauerflieger II');
INSERT INTO kinsect_text VALUES(18,'de','Dauerflieger III');
INSERT INTO kinsect_text VALUES(19,'de','Mauschelbrix I');
INSERT INTO kinsect_text VALUES(20,'de','Mauschelbrix II');
INSERT INTO kinsect_text VALUES(21,'de','Mauschelbrix III');
INSERT INTO kinsect_text VALUES(22,'de','Windschneider I');
INSERT INTO kinsect_text VALUES(23,'de','Windschneider II');
INSERT INTO kinsect_text VALUES(24,'de','Windschneider III');
INSERT INTO kinsect_text VALUES(25,'de','Großkathar I');
INSERT INTO kinsect_text VALUES(26,'de','Großkathar II');
INSERT INTO kinsect_text VALUES(27,'de','Großkathar III');
INSERT INTO kinsect_text VALUES(28,'de','Pseudokath I');
INSERT INTO kinsect_text VALUES(29,'de','Pseudokath II');
INSERT INTO kinsect_text VALUES(30,'de','Pseudokath III');
INSERT INTO kinsect_text VALUES(31,'de','Schadensdrohn I');
INSERT INTO kinsect_text VALUES(32,'de','Schadensdrohn II');
INSERT INTO kinsect_text VALUES(33,'de','Schadensdrohn III');
INSERT INTO kinsect_text VALUES(34,'de','Feindkäfer I');
INSERT INTO kinsect_text VALUES(35,'de','Feindkäfer II');
INSERT INTO kinsect_text VALUES(36,'de','Feindkäfer III');
INSERT INTO kinsect_text VALUES(37,'de','Gemetzelkäfer I');
INSERT INTO kinsect_text VALUES(38,'de','Gemetzelkäfer II');
INSERT INTO kinsect_text VALUES(39,'de','Gemetzelkäfer III');
INSERT INTO kinsect_text VALUES(40,'de','Schönheitskäfer I');
INSERT INTO kinsect_text VALUES(41,'de','Schönheitskäfer II');
INSERT INTO kinsect_text VALUES(42,'de','Schönheitskäfer III');
INSERT INTO kinsect_text VALUES(43,'de','Damenschild I');
INSERT INTO kinsect_text VALUES(44,'de','Damenschild II');
INSERT INTO kinsect_text VALUES(45,'de','Damenschild III');
INSERT INTO kinsect_text VALUES(46,'de','Damenpavese I');
INSERT INTO kinsect_text VALUES(47,'de','Damenpavese II');
INSERT INTO kinsect_text VALUES(48,'de','Damenpavese III');
INSERT INTO kinsect_text VALUES(49,'de','Marienmagd I');
INSERT INTO kinsect_text VALUES(50,'de','Marienmagd II');
INSERT INTO kinsect_text VALUES(51,'de','Marienmagd III');
INSERT INTO kinsect_text VALUES(52,'de','Schmetterbelle I');
INSERT INTO kinsect_text VALUES(53,'de','Schmetterbelle II');
INSERT INTO kinsect_text VALUES(54,'de','Schmetterbelle III');
INSERT INTO kinsect_text VALUES(55,'de','Schleierflug I');
INSERT INTO kinsect_text VALUES(56,'de','Schleierflug II');
INSERT INTO kinsect_text VALUES(57,'de','Schleierflug III');
INSERT INTO kinsect_text VALUES(58,'de','Flüsterfalter I');
INSERT INTO kinsect_text VALUES(59,'de','Flüsterfalter II');
INSERT INTO kinsect_text VALUES(60,'de','Flüsterfalter III');
INSERT INTO kinsect_text VALUES(61,'de','Drachenseele');
INSERT INTO kinsect_text VALUES(62,'de','Wahre Drachenseele');
INSERT INTO kinsect_text VALUES(63,'de','Nexus Dragon Soul');
INSERT INTO kinsect_text VALUES(64,'de','Vezirstag I Velox');
INSERT INTO kinsect_text VALUES(65,'de','Vezirstag II Velox');
INSERT INTO kinsect_text VALUES(66,'de','Vezirstag III Velox');
INSERT INTO kinsect_text VALUES(67,'de','Vezirstag I Forz');
INSERT INTO kinsect_text VALUES(68,'de','Vezirstag II Forz');
INSERT INTO kinsect_text VALUES(69,'de','Vezirstag III Forz');
INSERT INTO kinsect_text VALUES(70,'de','Bilbobrix I Velox');
INSERT INTO kinsect_text VALUES(71,'de','Bilbobrix II Velox');
INSERT INTO kinsect_text VALUES(72,'de','Bilbobrix III Velox');
INSERT INTO kinsect_text VALUES(73,'de','Bilbobrix I Forz');
INSERT INTO kinsect_text VALUES(74,'de','Bilbobrix II Forz');
INSERT INTO kinsect_text VALUES(75,'de','Bilbobrix III Forz');
INSERT INTO kinsect_text VALUES(76,'de','Foliacath I Medis');
INSERT INTO kinsect_text VALUES(77,'de','Foliacath II Medis');
INSERT INTO kinsect_text VALUES(78,'de','Foliacath III Medis');
INSERT INTO kinsect_text VALUES(79,'de','Foliacath I Forz');
INSERT INTO kinsect_text VALUES(80,'de','Foliacath II Forz');
INSERT INTO kinsect_text VALUES(81,'de','Foliacath III Forz');
INSERT INTO kinsect_text VALUES(82,'de','Elscarad I');
INSERT INTO kinsect_text VALUES(83,'de','Elscarad II');
INSERT INTO kinsect_text VALUES(84,'de','Elscarad III');
INSERT INTO kinsect_text VALUES(85,'de','Gleambeetle I Velox');
INSERT INTO kinsect_text VALUES(86,'de','Gleambeetle II Velox');
INSERT INTO kinsect_text VALUES(87,'de','Gleambeetle III Velox');
INSERT INTO kinsect_text VALUES(88,'de','Gleambeetle I Medis');
INSERT INTO kinsect_text VALUES(89,'de','Gleambeetle II Medis');
INSERT INTO kinsect_text VALUES(90,'de','Gleambeetle III Medis');
INSERT INTO kinsect_text VALUES(91,'de','Ladytower I Forz');
INSERT INTO kinsect_text VALUES(92,'de','Ladytower II Forz');
INSERT INTO kinsect_text VALUES(93,'de','Ladytower III Forz');
INSERT INTO kinsect_text VALUES(94,'de','Ladytower I Velox');
INSERT INTO kinsect_text VALUES(95,'de','Ladytower II Velox');
INSERT INTO kinsect_text VALUES(96,'de','Ladytower III Velox');
INSERT INTO kinsect_text VALUES(97,'de','Valorwing I Forz');
INSERT INTO kinsect_text VALUES(98,'de','Valorwing II Forz');
INSERT INTO kinsect_text VALUES(99,'de','Valorwing III Forz');
INSERT INTO kinsect_text VALUES(100,'de','Valorwing I Medis');
INSERT INTO kinsect_text VALUES(101,'de','Valorwing II Medis');
INSERT INTO kinsect_text VALUES(102,'de','Valorwing III Medis');
INSERT INTO kinsect_text VALUES(103,'de','Arginesse I');
INSERT INTO kinsect_text VALUES(104,'de','Arginesse II');
INSERT INTO kinsect_text VALUES(105,'de','Arginesse III');
INSERT INTO kinsect_text VALUES(1,'en','Culldrone I');
INSERT INTO kinsect_text VALUES(2,'en','Culldrone II');
INSERT INTO kinsect_text VALUES(3,'en','Culldrone III');
INSERT INTO kinsect_text VALUES(4,'en','Alucanid I');
INSERT INTO kinsect_text VALUES(5,'en','Alucanid II');
INSERT INTO kinsect_text VALUES(6,'en','Alucanid III');
INSERT INTO kinsect_text VALUES(7,'en','Monarch Alucanid I');
INSERT INTO kinsect_text VALUES(8,'en','Monarch Alucanid II');
INSERT INTO kinsect_text VALUES(9,'en','Monarch Alucanid III');
INSERT INTO kinsect_text VALUES(10,'en','Empresswing I');
INSERT INTO kinsect_text VALUES(11,'en','Empresswing II');
INSERT INTO kinsect_text VALUES(12,'en','Empresswing III');
INSERT INTO kinsect_text VALUES(13,'en','Rigiprayne I');
INSERT INTO kinsect_text VALUES(14,'en','Rigiprayne II');
INSERT INTO kinsect_text VALUES(15,'en','Rigiprayne III');
INSERT INTO kinsect_text VALUES(16,'en','Cancadaman I');
INSERT INTO kinsect_text VALUES(17,'en','Cancadaman II');
INSERT INTO kinsect_text VALUES(18,'en','Cancadaman III');
INSERT INTO kinsect_text VALUES(19,'en','Fiddlebrix I');
INSERT INTO kinsect_text VALUES(20,'en','Fiddlebrix II');
INSERT INTO kinsect_text VALUES(21,'en','Fiddlebrix III');
INSERT INTO kinsect_text VALUES(22,'en','Windchopper I');
INSERT INTO kinsect_text VALUES(23,'en','Windchopper II');
INSERT INTO kinsect_text VALUES(24,'en','Windchopper III');
INSERT INTO kinsect_text VALUES(25,'en','Grancathar I');
INSERT INTO kinsect_text VALUES(26,'en','Grancathar II');
INSERT INTO kinsect_text VALUES(27,'en','Grancathar III');
INSERT INTO kinsect_text VALUES(28,'en','Pseudocath I');
INSERT INTO kinsect_text VALUES(29,'en','Pseudocath II');
INSERT INTO kinsect_text VALUES(30,'en','Pseudocath III');
INSERT INTO kinsect_text VALUES(31,'en','Mauldrone I');
INSERT INTO kinsect_text VALUES(32,'en','Mauldrone II');
INSERT INTO kinsect_text VALUES(33,'en','Mauldrone III');
INSERT INTO kinsect_text VALUES(34,'en','Foebeetle I');
INSERT INTO kinsect_text VALUES(35,'en','Foebeetle II');
INSERT INTO kinsect_text VALUES(36,'en','Foebeetle III');
INSERT INTO kinsect_text VALUES(37,'en','Carnage Beetle I');
INSERT INTO kinsect_text VALUES(38,'en','Carnage Beetle II');
INSERT INTO kinsect_text VALUES(39,'en','Carnage Beetle III');
INSERT INTO kinsect_text VALUES(40,'en','Bonnetfille I');
INSERT INTO kinsect_text VALUES(41,'en','Bonnetfille II');
INSERT INTO kinsect_text VALUES(42,'en','Bonnetfille III');
INSERT INTO kinsect_text VALUES(43,'en','Ladytarge I');
INSERT INTO kinsect_text VALUES(44,'en','Ladytarge II');
INSERT INTO kinsect_text VALUES(45,'en','Ladytarge III');
INSERT INTO kinsect_text VALUES(46,'en','Ladypavise I');
INSERT INTO kinsect_text VALUES(47,'en','Ladypavise II');
INSERT INTO kinsect_text VALUES(48,'en','Ladypavise III');
INSERT INTO kinsect_text VALUES(49,'en','Arkmaiden I');
INSERT INTO kinsect_text VALUES(50,'en','Arkmaiden II');
INSERT INTO kinsect_text VALUES(51,'en','Arkmaiden III');
INSERT INTO kinsect_text VALUES(52,'en','Gullshad I');
INSERT INTO kinsect_text VALUES(53,'en','Gullshad II');
INSERT INTO kinsect_text VALUES(54,'en','Gullshad III');
INSERT INTO kinsect_text VALUES(55,'en','Bullshroud I');
INSERT INTO kinsect_text VALUES(56,'en','Bullshroud II');
INSERT INTO kinsect_text VALUES(57,'en','Bullshroud III');
INSERT INTO kinsect_text VALUES(58,'en','Whispervesp I');
INSERT INTO kinsect_text VALUES(59,'en','Whispervesp II');
INSERT INTO kinsect_text VALUES(60,'en','Whispervesp III');
INSERT INTO kinsect_text VALUES(61,'en','Dragon Soul');
INSERT INTO kinsect_text VALUES(62,'en','True Dragon Soul');
INSERT INTO kinsect_text VALUES(63,'en','Nexus Dragon Soul');
INSERT INTO kinsect_text VALUES(64,'en','Vezirstag I Velox');
INSERT INTO kinsect_text VALUES(65,'en','Vezirstag II Velox');
INSERT INTO kinsect_text VALUES(66,'en','Vezirstag III Velox');
INSERT INTO kinsect_text VALUES(67,'en','Vezirstag I Forz');
INSERT INTO kinsect_text VALUES(68,'en','Vezirstag II Forz');
INSERT INTO kinsect_text VALUES(69,'en','Vezirstag III Forz');
INSERT INTO kinsect_text VALUES(70,'en','Bilbobrix I Velox');
INSERT INTO kinsect_text VALUES(71,'en','Bilbobrix II Velox');
INSERT INTO kinsect_text VALUES(72,'en','Bilbobrix III Velox');
INSERT INTO kinsect_text VALUES(73,'en','Bilbobrix I Forz');
INSERT INTO kinsect_text VALUES(74,'en','Bilbobrix II Forz');
INSERT INTO kinsect_text VALUES(75,'en','Bilbobrix III Forz');
INSERT INTO kinsect_text VALUES(76,'en','Foliacath I Medis');
INSERT INTO kinsect_text VALUES(77,'en','Foliacath II Medis');
INSERT INTO kinsect_text VALUES(78,'en','Foliacath III Medis');
INSERT INTO kinsect_text VALUES(79,'en','Foliacath I Forz');
INSERT INTO kinsect_text VALUES(80,'en','Foliacath II Forz');
INSERT INTO kinsect_text VALUES(81,'en','Foliacath III Forz');
INSERT INTO kinsect_text VALUES(82,'en','Elscarad I');
INSERT INTO kinsect_text VALUES(83,'en','Elscarad II');
INSERT INTO kinsect_text VALUES(84,'en','Elscarad III');
INSERT INTO kinsect_text VALUES(85,'en','Gleambeetle I Velox');
INSERT INTO kinsect_text VALUES(86,'en','Gleambeetle II Velox');
INSERT INTO kinsect_text VALUES(87,'en','Gleambeetle III Velox');
INSERT INTO kinsect_text VALUES(88,'en','Gleambeetle I Medis');
INSERT INTO kinsect_text VALUES(89,'en','Gleambeetle II Medis');
INSERT INTO kinsect_text VALUES(90,'en','Gleambeetle III Medis');
INSERT INTO kinsect_text VALUES(91,'en','Ladytower I Forz');
INSERT INTO kinsect_text VALUES(92,'en','Ladytower II Forz');
INSERT INTO kinsect_text VALUES(93,'en','Ladytower III Forz');
INSERT INTO kinsect_text VALUES(94,'en','Ladytower I Velox');
INSERT INTO kinsect_text VALUES(95,'en','Ladytower II Velox');
INSERT INTO kinsect_text VALUES(96,'en','Ladytower III Velox');
INSERT INTO kinsect_text VALUES(97,'en','Valorwing I Forz');
INSERT INTO kinsect_text VALUES(98,'en','Valorwing II Forz');
INSERT INTO kinsect_text VALUES(99,'en','Valorwing III Forz');
INSERT INTO kinsect_text VALUES(100,'en','Valorwing I Medis');
INSERT INTO kinsect_text VALUES(101,'en','Valorwing II Medis');
INSERT INTO kinsect_text VALUES(102,'en','Valorwing III Medis');
INSERT INTO kinsect_text VALUES(103,'en','Arginesse I');
INSERT INTO kinsect_text VALUES(104,'en','Arginesse II');
INSERT INTO kinsect_text VALUES(105,'en','Arginesse III');

COMMIT;